module.exports = {
  themes: [
    "campagne",
    "famille",
    "terre",
    "riviere",
    "tradition",
    "honneur",
    "saisons",
    "petit village",
    "recolte",
    "nostalgie",
    "chemin de terre",
    "feu de camp",
    "heritage",
    "liberte"
  ],
  openers: [
    "Sur La Route De Terre Le Soleil Se Leve Doucement",
    "Ma Vieille Maison Se Dresse Au Bout Du Chemin",
    "Les Champs De Ble Ondulent Sous Le Vent Du Soir",
    "Je Reviens Au Pays Ou Mon Coeur A Grandi",
    "Le Vieux Pont De Bois Traverse La Riviere Calme",
    "Dans La Lumiere Doree De Ce Matin D'automne",
    "Mon Pere M'a Appris A Marcher Sur Cette Terre",
    "Les Etoiles Brillent Sur Le Toit De La Grange",
    "Une Guitare Chante Au Bord Du Feu Ce Soir",
    "Le Vent Porte L'odeur Des Foins Fraichement Coupes",
    "Ma Mere Chantait Sous Le Porche Chaque Matin",
    "Les Collines Vertes S'etendent Jusqu'a L'horizon",
    "Je Marche Seul Sur Ce Sentier De Poussiere",
    "Le Train S'eloigne De Ma Petite Ville Natale",
    "Sous Le Vieux Chene On Se Retrouvait Toujours",
    "La Pluie Douce Tombe Sur Les Toits D'ardoise",
    "Ce Soir Les Grillons Chantent Leur Chanson D'ete",
    "Mon Grand-pere Racontait L'histoire De Cette Terre",
    "Le Soleil Couchant Peint Le Ciel De Rouge Et D'or",
    "Au Croisement Des Chemins J'ai Choisi Le Mien",
    "La Cloche De L'eglise Sonne Pour Nous Rappeler",
    "Je Me Souviens Des Etes Passes Au Bord De L'eau",
    "Le Tracteur Roule Lentement Dans Le Champ De Mais",
    "Une Vieille Chanson Revient Comme Un Souvenir",
    "Les Saisons Tournent Et Le Temps File Toujours",
    "Derriere La Colline Le Village S'endort En Paix",
    "Mes Bottes Sont Usees Par Les Kilometres De Terre",
    "Le Matin Se Leve Sur La Vallee Tranquille",
    "On Dansait Sous Les Etoiles Dans La Cour De La Ferme",
    "Le Ruisseau Coule Comme Le Temps Qui Passe Doucement",
    "J'ai Laisse Mon Coeur Quelque Part Sur Ce Chemin",
    "La Fumee Monte Du Toit De La Vieille Maison",
    "Chaque Pierre De Ce Mur Raconte Une Histoire",
    "Le Dernier Train Du Soir Siffle Dans La Nuit",
    "Mes Mains Portent La Terre De Mes Ancetres",
    "Le Chien Fidele Attend Sur Le Pas De La Porte",
    "Au Lever Du Jour La Brume Enveloppe Les Pres",
    "Cette Route Sinueuse Mene Vers La Maison",
    "Le Foin Seche Au Soleil De Cet Apres-midi D'aout",
    "Un Vieux Violon Joue L'air De Notre Jeunesse",
    "La Poussiere Du Chemin Se Souleve Sous Mes Pas",
    "Nous Avons Plante Cet Arbre Le Jour De Ta Naissance",
    "Le Lac Reflete Les Couleurs De L'automne Qui Vient",
    "Je Prends Ma Guitare Et Je Chante Pour Toi Ce Soir",
    "Les Clotures De Bois Dessinent Le Paysage Endormi",
    "Au Fond De La Vallee Un Petit Feu Brule Encore",
    "Le Temps S'arrete Ici Quand Le Soleil Descend",
    "Ma Terre Me Connait Mieux Que Quiconque Au Monde",
    "Un Arc En Ciel Se Dessine Apres La Tempete",
    "Demain Je Repars Mais Ce Soir Je Reste Ici"
  ],
  verses: [
    "les champs de lavande parfument le soir de juin",
    "mon vieux camion roule sur la route de campagne",
    "la riviere serpente entre les collines de ma jeunesse",
    "je regarde le ciel et je pense a toi ce soir",
    "la terre sous mes pieds est celle de mes peres",
    "le vent du sud apporte des promesses de pluie douce",
    "les tournesols se tournent vers la lumiere du matin",
    "une vieille balancoire grince sous le vieux chene centenaire",
    "le coq chante et le monde reprend sa course tranquille",
    "mes mains calleuses racontent des annees de travail honnete",
    "la grange rouge se dresse fiere contre le ciel bleu",
    "le soir tombe et les lucioles dansent dans le jardin",
    "on partageait le pain autour de la table en bois",
    "le murmure du ruisseau berce mes nuits solitaires ici",
    "chaque saison apporte sa beaute et ses lecons de vie",
    "la poussiere des chemins colle a mes bottes usees",
    "je connais chaque arbre chaque pierre de cette vallee",
    "le feu craque dans la cheminee par les soirs de gel",
    "ma mere gardait les fleurs comme on garde un tresor",
    "la recolte est bonne et le coeur est content ce soir",
    "les enfants courent pieds nus dans l'herbe du matin frais",
    "le vieux cheval attend patiemment pres de la barriere ouverte",
    "les etoiles guident le voyageur vers sa maison lointaine",
    "on ne quitte jamais vraiment la terre qui nous a vus naitre",
    "la cloche du soir appelle les ames vers le repos",
    "le temps use les pierres mais pas les souvenirs anciens",
    "je chante pour ceux qui labourent encore sous le soleil brulant",
    "la route est longue mais le coeur sait ou aller",
    "les oiseaux reviennent chaque printemps comme une vieille promesse tenue",
    "sous le ciel etoile on oublie les soucis du jour",
    "la pluie lave la poussiere et reveille la terre endormie",
    "mon frere travaille la terre comme le faisait notre pere",
    "le dimanche matin sentait le cafe et le pain frais",
    "les clotures marquent les frontieres mais pas celles du coeur",
    "un vieux banc sous le tilleul garde nos secrets anciens",
    "la moisson dore les champs comme un ocean de lumiere",
    "je suis ne entre ces collines et j'y mourrai en paix",
    "le sifflement du train rappelle ceux qui sont partis loin",
    "les racines de cet arbre sont aussi profondes que les miennes",
    "le brouillard du matin cache la vallee comme un mystere",
    "on apprend la patience en regardant pousser les bles dores",
    "la vieille horloge bat le rythme de nos jours simples",
    "le pont de pierre enjambe le temps et les rivieres",
    "mes bottes portent la boue de cent chemins parcourus ensemble",
    "le silence de la campagne vaut tous les discours du monde",
    "une photo jaunie rappelle les etes de notre enfance lointaine",
    "la chaleur de midi fait danser l'air au dessus des champs",
    "les murs de cette maison ont entendu nos rires et larmes",
    "le jardin de ma mere fleurit encore apres toutes ces annees",
    "la lune eclaire le chemin vers la maison de mon enfance",
    "on se rassemblait au son du violon les soirs de fete",
    "le vent courbe les herbes hautes comme une vague sur terre",
    "je porte en moi le poids doux de cet heritage ancien",
    "la source coule froide et pure depuis des generations entieres",
    "les nuages de septembre annoncent la fin de la belle saison",
    "un chien aboie au loin dans la nuit claire d'automne",
    "le verger croule sous les pommes rouges de cet octobre",
    "chaque lever de soleil est une promesse que je garde en moi",
    "la sueur de mon front nourrit cette terre genereuse et belle",
    "le soir venu on comptait les etoiles depuis le porche ancien",
    "les orniers du chemin dessinent la carte de nos habitudes",
    "mon coeur bat au rythme des saisons qui passent doucement",
    "la neige couvre les toits et le monde devient silence",
    "le printemps ramene les couleurs sur les branches nues et grises",
    "les rides de mon pere racontent des hivers longs et durs",
    "on ne mesure pas la richesse a la taille du domaine",
    "le vent siffle entre les planches de la vieille grange rouge",
    "chaque grain de ble est une priere plantee dans la terre",
    "la lune se mire dans le lac comme un oeil argente",
    "les chemins de traverse menent aux plus beaux endroits caches",
    "je n'ai besoin de rien que de cette vue au petit matin",
    "le bruit des sabots sur le chemin annonce le retour espere",
    "les nuits sont froides mais le foyer garde sa chaleur vive",
    "la terre ne ment jamais a celui qui la respecte humblement",
    "un vieux chapeau de paille pend au clou de la porte",
    "les hirondelles partent mais elles reviennent toujours au printemps prochain",
    "le puits au fond du jardin garde l'eau la plus pure",
    "on mesure le temps ici aux recoltes et aux lunes pleines",
    "les peupliers bordent la route comme des sentinelles fideles et droites",
    "la brise du soir seche la sueur de cette longue journee",
    "mon fils apprend a marcher sur la meme terre que moi",
    "le cri du hibou traverse la nuit comme une melodie ancienne",
    "les vignes grimpent sur les murs de la vieille ferme endormie",
    "le bonheur est simple quand on sait regarder autour de soi",
    "la riviere emporte mes soucis vers la mer lointaine et bleue",
    "les granges sont pleines et les coeurs aussi ce soir beni",
    "un vieil air de musique flotte dans la brise du couchant",
    "le chemin du retour semble toujours plus court que l'aller",
    "les mains de ma mere sentaient la farine et la lavande",
    "le tonnerre gronde au loin sur les collines de l'ouest sauvage",
    "on danse la valse sous les guirlandes de la fete annuelle",
    "la foi de ceux qui travaillent la terre est indestructible",
    "le ruban de la route se deroule vers l'horizon lointain",
    "les murs de pierre seche tiennent debout depuis des siecles entiers",
    "chaque coucher de soleil me rappelle que la beaute est gratuite",
    "le lait frais du matin a le gout de la terre",
    "les enfants du village grandissent comme les arbres du verger",
    "la poussiere retombe et le calme revient sur les champs vides",
    "je ferme les yeux et je sens le parfum du foin",
    "les ombres s'allongent sur le pre quand le jour decline doucement",
    "le vieux moulin tourne encore au fil de l'eau patiente",
    "on ne peut pas couper les racines sans tuer l'arbre entier",
    "la chaleur du poele rassemble la famille quand l'hiver vient",
    "les traces de pas dans la neige racontent le matin d'hiver",
    "le givre dessine des fleurs sur la vitre de ma fenetre",
    "un rouge-gorge chante sur la branche nue de l'hiver froid",
    "la promesse du printemps se cache sous la neige epaisse encore",
    "les barrieres blanches entourent le pre ou paissent les chevaux libres",
    "le clocher du village se dresse comme un repere dans la brume",
    "la fumee du feu de bois monte droite dans le ciel gris",
    "je marche a travers champs pour retrouver mon calme interieur perdu",
    "les sillons bien droits temoignent du travail accompli avec soin toujours",
    "le grenier cache les tresors des generations passees avant nous ici",
    "une pomme tombee de l'arbre roule jusqu'a mes pieds fatigues",
    "la foi en cette terre me porte quand tout semble fragile",
    "les vendanges reunissent les voisins comme au temps de nos grands-parents",
    "le soleil perce les nuages apres trois jours de pluie froide",
    "on ecrit l'histoire avec la charrue et la sueur du front",
    "les corbeaux survolent le champ comme des ombres sur la terre",
    "la derniere lumiere du jour caresse la cime des arbres anciens",
    "mon coeur est attache a cette terre par des liens invisibles",
    "les sentiers de montagne menent plus pres du ciel bleu immense",
    "le feu de camp craque et les histoires commencent doucement ce soir",
    "la voix de la terre murmure a ceux qui savent ecouter",
    "les foins coupent l'ete en deux comme une page qu'on tourne",
    "le vieux pommier donne encore des fruits chaque automne fidele",
    "les nuits d'ete sont courtes mais les souvenirs sont longs ici",
    "la charrue ouvre la terre comme on ouvre un livre ancien",
    "les pierres du chemin roulent sous mes pas et mes souvenirs",
    "un arc en ciel promet des jours meilleurs apres la tempete",
    "les bleuets poussent entre les bles comme des eclats de ciel",
    "le courage des paysans est ecrit dans la terre qu'ils travaillent",
    "la brume se leve et devoile le paysage endormi doucement",
    "les anneaux du vieux chene comptent plus d'annees que le village",
    "le silence est si profond qu'on entend battre son propre coeur",
    "les saisons dessinent un cercle qui ne finit jamais vraiment",
    "la pluie tambourine sur le toit de tole de la grange",
    "un cheval galope dans le pre et sa criniere vole au vent",
    "les chemins de halage longent la riviere comme un souvenir fidele",
    "la terre est patiente elle attend celui qui revient toujours",
    "les soirs de moisson on chante sous les premieres etoiles du ciel",
    "le parfum du tilleul en fleur envahit la cour de la ferme",
    "chaque cloture reparee est un acte de foi en l'avenir proche",
    "la lune pleine eclaire les champs comme en plein jour argente",
    "les generations passent mais la terre demeure sous nos pieds constants",
    "le vent d'automne emporte les feuilles et les derniers jours de chaleur",
    "mon coeur se serre quand je vois la maison de loin encore",
    "les eaux calmes de la riviere refletent un ciel de novembre",
    "on apprend a vivre en ecoutant le rythme de la nature",
    "la terre craquelle sous le soleil de juillet brulant et sec",
    "les noyers alignes bordent l'allee qui mene vers chez nous",
    "le repos du dimanche a le gout d'une grace meritee enfin",
    "les ombres du soir dansent sur les murs de la cuisine chaude",
    "la vieille porte grince mais elle s'ouvre toujours pour accueillir",
    "le ble murit lentement sous le soleil patient et genereux",
    "les yeux fermes je revois les etes de mon enfance doree",
    "la terre humide du matin colle a mes semelles de cuir",
    "un faucon plane au dessus des champs comme un gardien silencieux",
    "les jours rallongent et l'espoir renait dans le coeur des fermiers",
    "la grange pleine est la recompense de l'annee de labeur entier",
    "le chant du merle annonce le reveil de la campagne endormie",
    "on a grandi ensemble a l'ombre de ces murs de pierre",
    "les forets de chenes bordent les pres comme des murs naturels",
    "la route de terre mene toujours quelque part si on la suit",
    "les mains jointes nous remercions pour cette terre qui nous nourrit",
    "le gel du matin fait briller l'herbe comme des diamants blancs",
    "les oies sauvages passent en formation vers des cieux plus doux",
    "la corde de la cloche use les mains de celui qui sonne",
    "le foin entasse dans la grange sent l'ete emprisonne pour l'hiver",
    "les annees passent et les arbres que j'ai plantes grandissent bien",
    "la brume du soir enveloppe le troupeau qui rentre a la ferme",
    "on porte nos fardeaux comme on porte la terre sur nos epaules",
    "le paysage change avec les saisons mais l'amour reste constant ici",
    "les mares gelees refletent le ciel gris de decembre froid",
    "la hache fend le bois et le bruit resonne dans la vallee",
    "un vieux calendrier marque les jours des semailles et des moissons",
    "les grenouilles chantent au bord de la mare sous la lune pleine",
    "la rose sauvage pousse le long du chemin oublie par le monde",
    "les etoiles filantes de juillet exaucent les voeux des enfants endormis",
    "le tonneau de vin repose dans la cave fraiche et sombre",
    "on mesure la vie aux sourires partages plus qu'aux biens amasses",
    "la barriere ouverte invite le voyageur a entrer se reposer enfin",
    "les coquelicots rouges eclaboussent le vert des champs de leur feu",
    "le vieux puits chante quand on remonte le seau rempli d'eau",
    "les traces du renard dans la neige racontent la nuit passee",
    "la source ne tarit jamais meme dans les etes les plus secs",
    "les martinets tournent autour du clocher dans le ciel d'ete bleu",
    "le bois de chauffage s'empile contre le mur de la maison",
    "on a danse la bourree sous les lampions de la fete",
    "la recolte des cerises tache les doigts des enfants joyeux",
    "les lucioles dessinent des constellations dans la nuit d'ete chaude",
    "le pain sort du four avec l'odeur du bonheur simple et vrai",
    "les cigales chantent leur chanson sans fin sous le soleil du midi",
    "la vieille fontaine coule au centre du village comme un coeur battant",
    "les ombres des nuages glissent sur les collines comme des pensees",
    "mon grand-pere regardait le ciel pour predire le temps qu'il ferait",
    "la terre est froide mais le soleil reviendra bientot nous rechauffer",
    "les filets de peche sechent au bord de la riviere tranquille",
    "on a bati cette maison avec la pierre de nos collines",
    "la meule du moulin ecrase le grain en farine blanche fine",
    "les abeilles bourdonnent dans le verger comme une priere continuelle",
    "le soir on s'assoit dehors et le monde semble enfin en paix",
    "la lessive blanche seche au vent sur le fil tendu dehors",
    "les cerfs brament dans la foret quand l'automne commence a tomber",
    "la vieille forge rougeoie encore au coeur du village endormi",
    "on apprend l'humilite quand la grele detruit un ete de travail",
    "les chemins creux gardent la memoire des charrettes qui les ont creuses",
    "la derniere danse de la soiree restera gravee dans mon coeur",
    "les chataignes grillent sur le feu un soir de novembre sombre",
    "le givre du matin fond sous le premier rayon de soleil",
    "la fidelite a la terre est la plus belle des vertus simples",
    "un coq perche sur la barriere chante la gloire du jour nouveau",
    "les herbes folles envahissent le chemin que personne n'emprunte plus jamais",
    "la vigne s'accroche au mur comme le souvenir a ma memoire",
    "on partait a la peche avant le lever du soleil rose",
    "la cloche fele sonne encore pour appeler les fideles du village",
    "les champs sont vides mais la promesse de la prochaine saison vit",
    "le vent du nord annonce un hiver qui sera long et rude",
    "la grange danse sous la tempete mais elle tient bon toujours",
    "un chevreuil traverse le pre dans la lumiere pale du petit matin",
    "les mots de mon pere resonnent encore comme le son d'une cloche",
    "la terre nous enseigne que rien de beau ne pousse sans patience",
    "les sabots du cheval marquent le rythme de la vie au champ",
    "la rosee du matin perle sur les toiles d'araignee du jardin",
    "les cailles chantent dans les chaumes apres la moisson du mois d'aout",
    "le vieux tracteur demarre au quart de tour malgre les annees passees",
    "les paniers d'osier debordent de fruits cueillis au petit matin frais",
    "la terre noire des labours promet une recolte genereuse cette annee",
    "les anes braient dans le pre quand le soir commence a tomber",
    "le pressoir grince et le jus des pommes coule dans le baquet",
    "les carrioles chargees de foin roulent doucement sur la route de terre",
    "la soupe mijote sur le feu et remplit la maison de son parfum",
    "le berger compte ses betes avant la tombee de la nuit froide",
    "les oies traversent la cour en file indienne comme chaque matin doux",
    "la haie d'aubepine fleurit en mai et parfume tout le chemin creux",
    "les meules de foin dans le champ ressemblent a des geants endormis",
    "le coq se pavane devant la basse-cour comme un roi sans couronne",
    "les ornieres du chemin se remplissent d'eau apres la pluie de mars",
    "la remorque vide rebondit sur les cailloux du chemin de ferme",
    "les poules picorent dans la poussiere sous le soleil de midi brulant",
    "le vieux noyer donne encore des noix pour la fete de la moisson",
    "les murs de torchis gardent la fraicheur pendant les jours d'ete chauds",
    "la fourche plonge dans le foin et ressort chargee de soleil sec",
    "les canards barbotent dans la mare sous le saule qui pleure doucement",
    "la chouette ulule depuis le grenier de la vieille ferme isolee",
    "les tuiles rouges du toit brillent apres l'averse d'un apres-midi lourd",
    "la bache claque au vent sur le tas de bois de chauffage",
    "les corneilles se posent sur les fils electriques comme des notes de musique",
    "le vieux puits a margelle attend qu'on vienne puiser l'eau fraiche encore",
    "la terre respire sous la neige et prepare en secret le printemps prochain",
    "les peupliers argentees frissonnent dans le vent du soir comme des sentinelles",
    "le vieux banc de pierre devant l'eglise garde la memoire des conversations",
    "les empreintes des bottes dans la boue dessinent le chemin du travail quotidien",
    "la lanterne accrochee au porche eclaire les derniers pas du soir vers la maison",
    "les chardons poussent le long de la route comme des etoiles sauvages violettes",
    "le camion charge de pommes de terre cahote sur la route de gravier",
    "la soupe aux legumes du jardin embaume la cuisine chaque soir d'automne",
    "les genisses suivent leur mere dans le pre comme un cortege patient et doux",
    "le vieux calendrier des postes marque les jours de marche et de foire",
    "la grele a epargne nos vignes cette annee et nous remercions le ciel",
    "les meules de pierre du moulin tournent avec la patience des siecles anciens",
    "le chien de berger rassemble le troupeau d'un regard et d'un aboiement bref",
    "la treille couverte de raisin dore ombrage la table du dejeuner d'ete",
    "les champignons poussent en cercle dans le pre apres la pluie d'octobre",
    "le vieux fermier connait le temps qu'il fera rien qu'en regardant le ciel",
    "la chouette effraie a fait son nid dans le clocher depuis dix ans",
    "les dernieres roses de novembre tremblent sous le givre du petit matin",
    "le ruisseau gele craque sous le poids d'un chevreuil qui traverse sans bruit",
    "la paille entassee dans la grange sent le soleil de l'ete emprisonne",
    "les coquelicots dansent dans le champ de ble comme des flammes de joie",
    "le facteur passe une fois par jour et c'est un evenement attendu",
    "la confiture de prunes mijote sur le fourneau et la maison embaume",
    "les pierres du lavoir gardent les traces des battoirs d'un autre temps",
    "le ciel de mai promet les cerises et les longues soirees dehors",
    "la brouette du jardinier grince sur le chemin comme une vieille chanson",
    "les noix tombent de l'arbre et les enfants se precipitent pour les ramasser",
    "le vent d'est annonce la pluie et les paysans rentrent les outils",
    "la maison de pierre resiste aux vents comme elle resiste au temps qui passe",
    "les chauves-souris volent autour de la grange quand le crepuscule descend",
    "le cidre nouveau petille dans le verre comme les rires de la fete",
    "la charrue rouille dans la remise attend le retour du laboureur patient",
    "les maraichers alignent leurs legumes sur l'etal du marche du samedi",
    "le cri du coq traverse la brume du matin comme une trompette claire",
    "la haie de buis taillée borde le chemin qui mene au lavoir ancien",
    "les martinets rasent les champs a la tombee du jour dans le ciel rose",
    "le vieux pommier tordu donne encore les meilleures pommes du verger entier",
    "la cheminee fume et le soir descend sur le hameau comme un drap doux",
    "les citrouilles alignees sur le muret attendent la soupe de l'hiver prochain",
    "le berger compte ses moutons a la lumiere de la lanterne dans le soir",
    "la vendange commence et les paniers se remplissent de grappes dorees au soleil",
    "les outils ranges dans l'appentis brillent d'un eclat de fierete et de soin",
    "le pain cuit dans le four a bois et la croute craque doucement",
    "la riviere deborde au printemps et les pres deviennent des miroirs d'eau",
    "les poiriers en fleurs forment une allee blanche comme un mariage de nature",
    "le sillon droit temoigne de la main sure de celui qui conduit la charrue",
    "la lune de moisson eclaire les champs comme un lampadaire celeste ce soir",
    "les carrioles de foin passent sur le pont de bois avec un bruit sourd",
    "le gel tardif menace les bourgeons et les paysans veillent toute la nuit",
    "la fontaine du village coule depuis des siecles sans jamais se lasser",
    "les groseilles murissent sur la haie et les enfants s'en barbouillent les joues",
    "le tracteur remonte la colline en soufflant comme un vieil homme courageux",
    "la grange a foin sent le miel et la poussiere de l'ete fini",
    "les moutons tondus courent dans le pre comme des enfants liberes de l'ecole",
    "le couchant rouge promet du beau temps pour la moisson de demain matin",
    "la terre noire des labours d'automne attend la semence du printemps prochain",
    "les petits fruits rouges de l'eglantier brillent dans la haie de decembre",
    "le vieux mur de pierres seches se dresse fier malgre les tempetes passees",
    "la graineterie du village sent les semences et les projets de la saison",
    "les brebis allaitent leurs agneaux dans la bergerie tiede et calme ce soir",
    "le pressoir en bois tourne et le jus de pomme coule dans la cuve",
    "la route de campagne se deroule comme un ruban sous le ciel immense",
    "les perdrix s'envolent du chaume en un bruit d'ailes qui surprend le marcheur",
    "le potager du cure donne les plus beaux legumes de tout le canton",
    "la pluie fine de mars reveille les graines endormies sous la terre noire",
    "les claies de sechage portent les herbes qui soigneront les maux de l'hiver",
    "le feu de sarments craque et les braises rougeoient dans la nuit froide",
    "la remorque vide cahote sur le chemin au retour des champs moissonnes",
    "les noisettes tombent dans l'herbe et les ecureuils font leurs provisions d'hiver",
    "le clocher du village pointe vers le ciel comme un doigt qui prie",
    "la mare aux canards reflete les nuages qui passent comme des reves blancs",
    "les faucilles accrochees au mur de la grange racontent des moissons d'antan",
    "le miel coule de la cuillere comme la lumiere d'un apres-midi d'ete",
    "la cabane au fond du jardin garde les secrets des enfants qui jouent",
    "les cordes de bois empilees promettent des soirees chaudes au coin du feu",
    "le cri des oies sauvages annonce l'hiver qui descend des montagnes proches",
    "la terre gelee craque sous les pas du fermier qui sort a l'aube",
    "les tuileries abandonnees gardent l'echo du labeur des generations passees ici",
    "le marche du dimanche rassemble les voisins comme une fete de famille",
    "la vieille jument connait le chemin de retour meme les yeux fermes",
    "les bottes de foin dans le champ sont des cabanes pour les enfants",
    "le coteau expose au sud donne le meilleur vin de la region",
    "la corde du puits grince et l'eau fraiche remonte des profondeurs sombres",
    "les etoiles du berger brillent plus fort ici que dans aucune ville",
    "le travail des mains porte ses fruits quand la terre est genereuse",
    "la vache meugle dans l'etable et le soir s'emplit de sons familiers",
    "les forets de hetres prennent des couleurs de feu quand octobre arrive",
    "le vieux calendrier lunaire guide les semailles comme il le fait depuis toujours",
    "la fumee du barbecue monte droite dans le ciel du dimanche apres-midi",
    "les framboises du jardin tachent les doigts d'un rouge que rien n'efface",
    "le sentier de randonnee traverse trois vallees avant d'atteindre le sommet",
    "la glycine en fleur couvre le mur de la maison d'un manteau mauve",
    "les pommes de terre nouvelles sortent de terre comme des pepites d'or brun",
    "le lavoir couvert garde la fraicheur meme au plus chaud de l'ete",
    "les epis de mais sechent sous l'auvent avant d'etre egreges pour l'hiver",
    "la lune eclaire le chemin de terre et les ombres des arbres dansent",
    "les alouettes montent dans le ciel et chantent au-dessus des champs en eveil",
    "le vieux porche de la ferme accueille les visiteurs comme des membres de la famille",
    "la terre est notre premiere mere et notre dernier berceau dans ce monde",
    "les saisons nous enseignent que toute fin est un nouveau commencement ici",
    "le laboureur connait chaque sillon comme il connait les lignes de sa main"
  ],
  bridges: [
    "et je reste la a regarder le soleil descendre lentement",
    "les annees passent mais cet endroit ne change jamais vraiment",
    "on dit que la terre appelle ceux qui l'aiment sincerement",
    "entre le ciel et la terre mon coeur a trouve sa place",
    "si je ferme les yeux je revois chaque instant passe ici",
    "la vie m'a mene loin mais mon coeur est reste la-bas",
    "quand le vent souffle je sens la presence de ceux qui sont partis",
    "cette terre est plus qu'un lieu c'est une partie de mon ame",
    "le temps efface les traces mais pas les liens du coeur fidele",
    "on revient toujours la ou on a appris a aimer la vie",
    "je ne demande rien de plus que ce ciel et cette terre",
    "les saisons m'ont appris que tout revient si on sait attendre",
    "parfois la distance rend plus fort l'amour de notre terre natale",
    "le silence de la campagne dit plus que tous les mots ecrits",
    "je suis fait de la meme argile que ces collines anciennes",
    "un jour je reviendrai m'asseoir sous cet arbre une derniere fois",
    "la vie simple est la seule richesse que je veux garder",
    "entre ces murs j'ai appris tout ce que je sais de vrai",
    "le coeur a ses racines comme les arbres de ce verger",
    "chaque retour ici me guerit des blessures de la route longue",
    "la terre pardonne a ceux qui reviennent avec humilite sincere",
    "on ne peut pas emporter le paysage mais il vit en nous",
    "les generations se suivent et la meme chanson continue toujours",
    "quand la ville me pese je ferme les yeux et je reviens",
    "ce n'est pas la nostalgie c'est l'amour qui ne meurt jamais",
    "la riviere coule vers la mer mais la source reste ici",
    "les racines sont invisibles mais ce sont elles qui nous tiennent debout",
    "j'ai cherche le bonheur partout il etait ici depuis toujours",
    "la terre ne demande rien sinon qu'on la respecte et l'aime",
    "les etoiles veillent sur ceux qui dorment sous ce toit ancien",
    "le temps passe mais la beaute de ce lieu reste eternelle",
    "on porte en soi le pays meme quand on vit tres loin",
    "la simplicite de cette vie est un cadeau que rien ne remplace",
    "chaque pas sur ce chemin me rapproche de qui je suis",
    "le monde court mais ici le temps marche au pas des saisons"
  ],
  choruses: [
    "je reviens toujours a cette terre qui m'a vu naitre",
    "le ciel de mon pays est le plus beau du monde",
    "cette terre coule dans mes veines comme une riviere ancienne",
    "on rentre a la maison quand le coeur en a besoin",
    "les racines sont profondes et le coeur ne les oublie jamais",
    "sous ce ciel etoile je suis enfin chez moi ce soir",
    "la campagne chante et mon ame repond a son appel doux",
    "rien ne vaut la terre ou l'on a grandi ensemble",
    "mon coeur bat au rythme de cette terre que j'aime tant",
    "les collines de mon enfance m'appellent encore chaque jour nouveau",
    "je suis un enfant de la terre et du vent libre",
    "les chemins de poussiere menent tous vers la meme maison",
    "cette vallee est ma priere et mon chant le plus vrai",
    "on danse on rit on pleure sur cette terre fidele toujours",
    "le feu brule dans la cheminee et le coeur se rechauffe",
    "la terre est genereuse pour ceux qui l'aiment avec patience",
    "je chante pour les champs pour la pluie et le soleil",
    "les saisons passent et notre amour reste aussi fort qu'avant",
    "sous le meme ciel on partage le meme reve de paix",
    "la route me ramene toujours ici comme une vieille habitude",
    "je porte cette terre dans mon coeur partout ou je vais",
    "les etoiles du soir brillent pour ceux qui croient encore",
    "la riviere chante notre histoire depuis la nuit des temps lointains",
    "ce soir le vent porte ma chanson jusqu'a la colline verte",
    "on a bati notre vie avec la pierre et le courage",
    "la lumiere du matin guerit les blessures de la nuit sombre",
    "cette terre est mon refuge et ma chanson la plus douce",
    "les mains dans la terre le coeur dans le ciel immense",
    "on revient toujours la ou la terre connait notre prenom",
    "le soleil se couche et la paix descend sur les champs",
    "je suis la ou le vent connait mon nom depuis toujours",
    "la terre est notre mere et nous sommes ses enfants fideles",
    "les saisons sont la musique et la terre est notre chanson",
    "on ne quitte jamais le pays quand le pays vit en soi",
    "le ciel s'ouvre et la lumiere baigne les collines d'or pur",
    "cette maison cette terre ce ciel sont tout ce que j'ai",
    "la recolte est la preuve que la patience porte ses fruits",
    "je leve mon verre a la terre a la vie a l'amour",
    "les chemins de terre menent au coeur de qui je suis",
    "la campagne m'appelle et je reponds avec toute mon ame",
    "le bonheur pousse ici comme le ble dans les champs fertiles",
    "on chante pour la terre qui nous donne tout sans compter",
    "les nuits etoilees me rappellent pourquoi je suis reste ici",
    "la pluie et le soleil font grandir ce que nous semons",
    "mon coeur est un champ de ble sous le soleil d'ete",
    "les oiseaux chantent et le monde est enfin a sa place",
    "je reviendrai toujours a cette terre qui connait mes pas",
    "la vie est belle quand on la vit au rythme des saisons",
    "cette chanson est pour toi ma terre mon pays mon coeur",
    "les chemins de mon enfance me guident encore dans la nuit",
    "la moisson est ma fete et le soleil est mon ami fidele",
    "je porte la terre de mes peres dans chaque pas que je fais",
    "les rivieres chantent et les collines repondent avec la voix du vent",
    "on a bati notre maison avec la sueur et la foi du coeur",
    "la terre est notre heritage et le ciel est notre priere commune",
    "je chante pour les champs dores et les nuits etoilees d'ici",
    "les generations se suivent et la terre reste fidele sous nos pieds",
    "mon coeur est enracine dans cette vallee comme le chene centenaire",
    "la campagne est ma musique et chaque saison est un couplet nouveau",
    "on rentre chez nous quand les lucioles eclairent le chemin de terre",
    "le soleil de juin brille sur nos reves et nos esperances vives",
    "les mains dans la terre les yeux vers le ciel on avance ensemble",
    "cette route de poussiere mene au seul endroit ou je veux vivre",
    "la riviere ne ment jamais elle dit la verite de cette terre",
    "je leve mon chapeau au ciel et je remercie cette journee benie",
    "les foins coupes embaument le soir de leur parfum d'or chaud",
    "on porte nos peines et nos joies comme on porte les seaux d'eau",
    "la terre est notre chanson et la pluie en est le refrain",
    "les etoiles du soir veillent sur ceux qui aiment cette terre",
    "je suis le fils de cette campagne et je le serai toujours",
    "les ponts que nous batissons traversent le temps et les tempetes aussi",
    "la moisson est notre fierte et le grain est notre or pur",
    "on aime cette terre comme on aime sa mere avec tout le coeur",
    "le vent porte nos chansons au-dela des collines et des vallees",
    "les racines de notre vie plongent profond dans cette terre genereuse",
    "je chante sous le ciel immense et ma voix se mele au vent",
    "la terre nous apprend que la patience est la mere de toute beaute",
    "on vit ici on rit ici et on restera jusqu'au dernier souffle",
    "les saisons tournent et chaque tour nous rapproche de qui nous sommes",
    "la terre et le ciel se rejoignent a l'horizon de mon coeur fidele"
  ],
  vocabulary: {
    nouns: [
      "terre", "chemin", "champ", "riviere", "colline",
      "grange", "moisson", "ble", "chene", "vallee",
      "ferme", "recolte", "saison", "poussiere", "racine",
      "clocher", "barriere", "foin", "verger", "sillon",
      "paturage", "moulin", "tonneau", "charrue", "prairie",
      "ruisseau", "foyer", "troupeau", "sentier", "cloture",
      "semaille", "vendange", "abeille", "hirondelle", "grenier",
      "porche", "puits", "meule", "boue", "givre",
      "brume", "rosee", "cloche", "forge", "tilleul",
      "noyer", "vigne", "etable", "paille", "hache",
      "maison", "porche", "berceau", "heritage", "cloture",
      "laboureur", "moisson", "campagne", "hameau", "village",
      "abreuvoir", "pressoir", "lavoir", "ecurie", "bergerie",
      "alpage", "terroir", "horizon", "paturage", "pre",
      "orge", "avoine", "mais", "seigle", "tournesol",
      "cerise", "pomme", "peche", "vache", "cheval"
    ],
    verbs: [
      "labourer", "semer", "recolter", "grandir", "fleurir",
      "moissonner", "planter", "nourrir", "batir", "cultiver",
      "marcher", "revenir", "danser", "chanter", "prier",
      "secher", "germer", "murir", "faucher", "vendanger",
      "atteler", "chevaucher", "traire", "petrir", "enfouir",
      "enraciner", "bourdonner", "fendre", "creuser", "gronder",
      "bruler", "rechauffer", "eclore", "ployer", "ondoyer",
      "cueillir", "ramasser", "entrelacer", "biner", "herser",
      "sillonner", "ruisseler", "eclabousser", "bourgeoner", "pousser",
      "galoper", "trotter", "hennir", "becqueter", "butiner",
      "defricher", "essarter", "irriguer", "dompter", "dresser",
      "fouler", "arpenter", "parcourir", "explorer", "traverser",
      "endurer", "perseverer", "resister", "lutter", "combattre",
      "rassembler", "reunir", "celebrer", "festoyer", "trinquer",
      "emigrer", "revenir", "s'installer", "battre", "forger",
      "tisser", "raccommoder", "reparer", "consolider", "proteger"
    ],
    adjectives: [
      "fertile", "dore", "ancien", "rustique", "paisible",
      "fidele", "sauvage", "humble", "robuste", "sincere",
      "genereux", "solitaire", "patient", "tenace", "profond",
      "centenaire", "boise", "endormi", "brulant", "frais",
      "poussiereux", "ombrage", "verdoyant", "tortueux", "noueux",
      "rude", "chaleureux", "intact", "fleuri", "fecond",
      "enracine", "terreux", "beni", "laborieux", "abondant",
      "pur", "limpide", "craquele", "use", "argente",
      "embaume", "mur", "lumineux", "austere", "campagnard",
      "immuable", "solide", "eternel", "vaillant", "fier",
      "pastoral", "bucolique", "champetre", "agreste", "bocager",
      "saisonnier", "printanier", "estival", "automnal", "hivernal",
      "nourricier", "protecteur", "tutelaire", "ancestral", "seculaire",
      "terreux", "boueux", "aride", "irrigue", "arrose",
      "dodu", "trapu", "massif", "noueux", "tordu",
      "accueillant", "hospitalier", "bienveillant", "paternel", "maternel"
    ]
  }
};
