module.exports = {
  themes: [
    "euphorie",
    "danse",
    "nuit electrique",
    "energie",
    "foule",
    "basse",
    "drop",
    "festival",
    "rave",
    "lumieres",
    "vibration",
    "extase",
    "liberte nocturne",
    "pulsation"
  ],
  openers: [
    "Les Lumieres S'allument Et La Nuit Prend Vie Sous Nos Pieds",
    "Le Beat Resonne Et La Foule Ne Fait Plus Qu'un Seul Corps",
    "Ce Soir On Danse Jusqu'a Ce Que Le Soleil Se Leve",
    "La Basse Vibre Dans Nos Poitrines Comme Un Second Coeur Battant",
    "Les Mains En L'air On Touche Le Ciel De Cette Nuit",
    "Le DJ Lance Le Son Et Le Monde Explose De Joie",
    "La Nuit Electrique Nous Appelle Et On Repond Par La Danse",
    "Les Stroboscopes Decoupent Le Temps En Mille Eclats De Lumiere",
    "On Se Perd Dans La Musique Et On Se Trouve Enfin",
    "Le Sol Tremble Sous La Puissance Du Son Qui Monte Fort",
    "Ce Soir Les Frontieres N'existent Plus Sous Les Lasers Du Ciel",
    "La Foule Ondule Comme Un Ocean Sous Les Vagues De Basses",
    "Les Enceintes Crachent Le Feu Et Nos Corps S'enflamment De Joie",
    "Un Nouveau Monde S'ouvre Quand La Musique Prend Le Controle Total",
    "Le Compte A Rebours Commence Et Le Drop Va Tout Changer",
    "Sous Les Etoiles Du Festival La Magie Opere Sur Nous",
    "Le Rythme Court Dans Nos Veines Comme De L'electricite Pure",
    "La Nuit N'a Pas De Limites Quand Le Son Nous Porte Haut",
    "Les Bras Leves On Celebre La Vie Sous Les Lumieres Vives",
    "Le Monde Tourne Au Rythme De Cette Basse Qui Ne Cesse Pas",
    "Ce Soir On Est Invincible Sous Le Toit Du Ciel Etoile",
    "La Piste De Danse Est Notre Temple Et Le Son Notre Priere",
    "Les Lasers Percent La Nuit Comme Des Lames De Lumiere Pure",
    "Le Volume Monte Et Les Soucis Disparaissent Dans Le Neant Sonore",
    "On Vit Pour Ces Moments Ou Le Beat Fait Battre Nos Coeurs",
    "La Foule Chante D'une Seule Voix Sous Le Ciel Qui Vibre",
    "Les Frequences Basses Font Trembler Le Sol Comme Un Seisme Musical",
    "Ce Soir Tout Est Possible Tant Que La Musique Ne S'arrete Pas",
    "Le Tempo Accelere Et Nos Corps Suivent Sans Reflechir Jamais",
    "Les Confettis Tombent Du Ciel Comme Une Pluie De Lumiere Doree",
    "La Nuit Commence A Peine Et L'energie Est Deja Au Maximum",
    "On Lache Tout Sur La Piste Et Le Monde S'efface Autour",
    "Les Basses Profondes Font Vibrer Jusqu'a L'ame De La Foule Entiere",
    "Le Beat Tombe Et Mille Voix S'elevent Dans Un Cri De Joie",
    "Sous Les Spots Colores On Devient La Musique Qui Joue Fort",
    "La Nuit Est Un Voyage Et Le Son Est Notre Vehicule Sacre",
    "Les Frequences Nous Traversent Et On Ne Fait Plus Qu'un Avec Le Son",
    "Ce Soir Les Etoiles Dansent Avec Nous Sur Ce Beat Infini",
    "Le Festival S'eveille Et Des Milliers De Coeurs Battent Ensemble Fort",
    "La Pulsation Du Son Est Le Sang De Cette Nuit Vivante",
    "On Court Vers La Scene Et Le Son Nous Accueille A Bras Ouverts",
    "Les Synthetiseurs Peignent Le Ciel De Couleurs Que Seule La Nuit Connait",
    "Le Drop Approche Et L'anticipation Fait Trembler La Foule Entiere",
    "Ce Soir On Ecrit L'histoire Sur Le Dancefloor De Nos Reves",
    "La Nuit Pulse Comme Un Coeur Geant Sous Les Lumieres Du Festival",
    "Les Ondes Sonores Nous Enveloppent Comme Un Manteau D'energie Pure",
    "Le Ciel S'illumine De Lasers Et La Terre Vibre De Basses",
    "On Danse Comme Si Demain N'existait Pas Sous Ce Ciel En Feu",
    "Le Monde Entier Est La Sous Les Enceintes Ce Soir De Fete",
    "La Musique Monte Et Nos Ames S'envolent Vers Les Etoiles Lointaines"
  ],
  verses: [
    "les basses font trembler le sol comme un tonnerre sous nos pieds",
    "on se perd dans la foule et on devient la musique vivante",
    "les stroboscopes flashent et le temps se fige un instant magique",
    "le beat pulse dans ma poitrine comme un coeur electronique puissant",
    "les mains en l'air on touche le ciel electrique de la nuit",
    "la sueur coule et l'euphorie monte comme une vague immense",
    "les lasers dessinent des cathedrales de lumiere dans l'obscurite totale",
    "le drop tombe et le monde explose en mille morceaux de joie",
    "on danse les yeux fermes et le son guide chaque mouvement libre",
    "la foule vibre comme un seul organisme sous le ciel ouvert",
    "les frequences traversent mon corps comme un courant electrique pur",
    "ce soir il n'y a pas de regles que la musique et le mouvement",
    "le sol vibre et mes pieds ne touchent plus la terre ferme",
    "les enceintes rugissent et la nuit prend une nouvelle dimension sonore",
    "on leve les bras et on s'abandonne au rythme qui nous porte",
    "la piste de danse est un ocean de corps en mouvement constant",
    "les synthetiseurs hurlent et le ciel se teinte de couleurs folles",
    "chaque beat est une vague qui emporte mes soucis tres loin d'ici",
    "les confettis tombent comme des etoiles sur nos tetes qui bougent",
    "le volume monte et le monde reel s'efface dans le son pur",
    "on court vers le drop comme on court vers la liberte absolue",
    "les lumieres tournent et le monde tourne avec elles dans la folie",
    "la basse est si profonde qu'elle fait vibrer jusqu'a mes os fragiles",
    "les cris de la foule se melent au son dans un chaos beau",
    "on respire la musique comme on respire l'air de la nuit chaude",
    "le kick frappe et mon coeur repond a chaque coup puissant",
    "les neons colorent nos visages de bleu de rouge et de violet",
    "on danse ensemble et les differences s'effacent dans le son commun",
    "la montee du son est une promesse que le drop va tenir",
    "les pieds ne s'arretent pas tant que le beat joue dans l'air",
    "le festival est un monde parallele ou seule la musique commande",
    "les ondes sonores sont des vagues qui balaient tout sur leur passage",
    "on ferme les yeux et le son peint des images dans nos tetes",
    "la nuit est un terrain de jeu et le son notre jouet prefere",
    "les arpegges montent en spirale vers un ciel de lumiere pure",
    "chaque seconde sur ce dancefloor est une eternite de bonheur intense",
    "les basses grondent comme un orage qui libere toute sa puissance",
    "on ne sent plus la fatigue quand le beat nous tient en eveil",
    "le son rebondit sur les murs et revient plus fort qu'avant encore",
    "les corps se croisent et les energies fusionnent sur la piste pleine",
    "la musique est notre langue commune et le rythme notre dialecte prefere",
    "le countdown commence et l'anticipation electrise chaque cellule de mon corps",
    "les spots balaient la foule comme des phares dans une nuit de tempete",
    "on saute en rythme et le sol tremble sous nos milliers de pieds",
    "le sub-bass fait vibrer l'air comme une membrane invisible et puissante",
    "les cris de joie montent vers le ciel quand le beat reprend",
    "on est ensemble dans cette bulle de son et de lumiere vive",
    "le rythme est un fleuve et on se laisse porter par le courant",
    "les frequences aigues percent la nuit comme des eclairs de cristal pur",
    "la musique monte en pression comme un volcan pret a exploser fort",
    "on danse sur les ruines de nos soucis ecrases par le beat",
    "le dj est le capitaine et nous sommes l'ocean qui suit ses mains",
    "les flammes des pyrotechnies eclairent mille visages heureux dans la foule",
    "la nuit avance et l'energie ne faiblit pas sur ce dancefloor sacre",
    "chaque note est une explosion de couleur dans le noir total",
    "on se noie dans le son et on renait avec chaque nouveau drop",
    "les vibrations parcourent mon corps comme un frisson permanent de joie pure",
    "le beat est notre pouls collectif et la piste notre coeur geant",
    "les bras se levent comme une foret de mains vers le ciel",
    "on crie ensemble et le son de nos voix rejoint la musique",
    "la brume de la machine enveloppe la foule d'un voile mysterieux",
    "le son est si pur qu'il semble venir d'un autre univers lointain",
    "on vit dans l'instant present et le present est fait de basses",
    "les lumieres pulsent au rythme de nos coeurs qui battent ensemble",
    "chaque drop est une renaissance un nouveau souffle de vie intense",
    "la foule respire au meme rythme que la musique qui joue fort",
    "le sol mouille de sueur reflete les lasers comme un miroir magique",
    "on se sent vivant quand le beat fait trembler notre cage thoracique",
    "les enceintes sont nos guides dans cette cathedrale sonore de la nuit",
    "la pression monte et on sait que le drop approche comme un orage",
    "on danse avec des inconnus qui deviennent des freres sous le son",
    "le rythme efface les frontieres entre les corps les ames les langues",
    "les nappes de synthese s'etendent comme des nuages de velours electrique",
    "chaque respiration est synchronisee avec le tempo de la machine sonore",
    "on lache prise et la gravite n'a plus de sens sur ce dancefloor",
    "les basses nous ancrent au sol pendant que l'ame s'envole dans le ciel",
    "le son est une drogue legale et cette nuit on en abuse",
    "les etoiles au dessus du festival sont des spots naturels du ciel",
    "on est des milliers a respirer la meme euphorie sous les enceintes",
    "la nuit est courte mais chaque seconde vaut une heure de vie entiere",
    "les vibrations du caisson de basses font ondoyer l'air autour de nous",
    "on danse comme si la musique allait s'arreter pour toujours demain matin",
    "le beat minimal laisse de l'espace pour que nos ames respirent libres",
    "les nappes de reverb enveloppent la foule d'un halo sonore lumineux",
    "chaque transition du dj est un voyage vers une nouvelle dimension inconnue",
    "on ferme les yeux et les frequences peignent des couleurs invisibles autour",
    "la piste de danse est un creuset ou tout se fond dans l'instant",
    "le breakdown suspend le temps et mille coeurs attendent le retour des basses",
    "on vit la musique avec chaque cellule de notre corps vibrante et libre",
    "les basses reviennent et c'est comme si le monde recommencait a tourner",
    "les mains se levent dans la fumee comme des prieres vers le son",
    "le kick et le clap sont les battements du coeur de cette nuit",
    "on hurle de joie quand le build-up atteint son apogee final",
    "la foule est une mer houleuse que le dj surf avec son art",
    "les frequences resonnent dans la cage thoracique comme un second rythme cardiaque",
    "on se laisse tomber dans le beat comme on tombe dans un reve",
    "les lumieres s'eteignent un instant et la basse revient comme un tsunami",
    "chaque festival est un pelerinage vers le temple du son eternal",
    "on transpire on sourit on crie et la musique absorbe tout notre etre",
    "la nuit electrique grave des souvenirs dans nos corps fatigues mais heureux",
    "le dernier morceau joue et on sait qu'on reviendra danser ici encore",
    "les echos du set resonnent dans nos tetes longtemps apres la fin",
    "on rentre chez nous le coeur plein de beats et d'etoiles dans les yeux",
    "la musique s'arrete mais la vibration continue dans nos os endormis",
    "les premieres lueurs de l'aube eclairent des visages heureux et epuises",
    "on emporte la nuit en nous comme un tresor sonore precieux",
    "le silence apres le dernier beat est assourdissant et magnifique aussi",
    "on se promet de revenir danser sous ces lumieres un jour prochain",
    "les souvenirs de cette nuit brilleront longtemps comme des lasers dans la memoire",
    "le beat s'est arrete mais nos coeurs continuent de battre au meme tempo",
    "on quitte le festival les pieds douloureux mais l'ame en apesanteur totale",
    "la rosee du matin couvre le champ du festival d'un voile argente",
    "les tentes s'eveillent au soleil et les beats resonnent encore dans nos tetes",
    "on se regarde et on sait qu'on a partage quelque chose d'unique ensemble",
    "la musique electronique nous a unis comme rien d'autre ne le pouvait",
    "les debris de confettis sur le sol sont les traces de notre bonheur",
    "on repart avec une energie nouvelle chargee par les ondes de la nuit",
    "le soleil se leve sur un monde nouveau cree par le son d'hier soir",
    "les basses resonnent encore dans la terre du champ maintenant silencieux",
    "on porte les bracelets du festival comme des medailles de nos nuits dansantes",
    "la prochaine rave approche et deja les battements accelerent dans ma poitrine",
    "les souvenirs de la nuit sont graves au rythme de cent quarante beats",
    "on ferme les yeux et on revit chaque drop chaque montee chaque instant",
    "la musique nous a transformes et on ne sera plus jamais pareil",
    "le beat est notre religion et le dancefloor notre lieu sacre eternel",
    "les frequences ont lave nos ames de tout le poids du quotidien gris",
    "on attend la prochaine nuit electrique comme on attend la pluie en ete",
    "les lumieres du festival s'eteignent mais celles dans nos coeurs brillent encore",
    "le monde ordinaire semble plat apres avoir danse sous les etoiles sonores",
    "on se retrouvera sous les enceintes quand le prochain beat tombera lourd",
    "la nuit nous a donne des ailes que le jour ne peut couper",
    "le rythme est inscrit dans notre adn depuis cette nuit de folie",
    "on vit entre deux festivals comme en apnee entre deux respirations profondes",
    "les basses sont notre oxygene et le dancefloor notre atmosphere vitale",
    "chaque nuit de rave est un chapitre de notre histoire collective ecrite en beats",
    "on ne compte plus les nuits passees a danser sous les etoiles vives",
    "le son est notre guide dans le labyrinthe lumineux de la nuit longue",
    "les ondes nous portent au dessus du monde reel vers l'extase pure",
    "la foule est notre famille et le beat notre langue maternelle commune",
    "on se retrouve au premier accord comme si on ne s'etait jamais quittes",
    "les frequences sont des fils invisibles qui relient nos coeurs dans la nuit",
    "le dancefloor est un radeau et le son est notre ocean infini",
    "on vit pour ces nuits ou le beat efface tout ce qui fait mal",
    "les enceintes sont nos phares dans la tempete de la nuit electrique",
    "le prochain drop approche et deja mon corps se prepare a exploser de joie",
    "les projecteurs tournent et peignent la foule de couleurs impossibles",
    "on se perd dans le rythme et on oublie d'ou on vient ce soir",
    "le sol mouille de sueur est un miroir qui reflete les lasers bleus",
    "les murs vibrent et les decibels font craquer l'air autour de nous",
    "on se retrouve dans le chaos sonore comme des etoiles dans le ciel",
    "la ligne de basse creuse un tunnel dans lequel on plonge tete premiere",
    "les hi-hats crepitent comme de la pluie sur un toit de metal vibre",
    "on avance vers la scene comme des pelerins vers leur terre promise sacree",
    "le buildup monte en spirale et nos coeurs suivent son ascension folle",
    "les corps se pressent et la chaleur humaine rivalise avec les spots brulants",
    "le dj tourne un bouton et le monde bascule dans une autre dimension",
    "on crie a l'unisson et le son de nos voix fait trembler les murs",
    "les nappes de synthese enveloppent la foule comme un nuage electrique doux",
    "le tempo change et nos corps s'adaptent instantanement au nouveau rythme du set",
    "les basses rebondissent sur les murs et reviennent nous frapper en plein coeur",
    "on danse avec l'ombre de nos voisins inconnus devenus freres pour la nuit",
    "la fumee des machines monte vers les lasers et cree un voile magique",
    "le kick est si puissant qu'il fait vibrer les os de ma poitrine",
    "on leve les poings vers le ciel et le ciel nous repond en lumiere",
    "les arpegges electroniques dessinent des escaliers vers un paradis fait de sons purs",
    "la foule scande le refrain et le dj sourit derriere sa console lumineuse",
    "le silence avant le drop est le moment le plus intense de la nuit",
    "on se balance au rythme du pad qui pulse comme un coeur geant vivant",
    "les lumieres s'eteignent d'un coup et le noir est electrique de tension pure",
    "la basse revient comme un tsunami et emporte tout sur son passage massif",
    "on danse les pieds dans la boue du festival et le coeur dans les etoiles",
    "les decibels nous enveloppent comme une armure de son contre le monde exterieur",
    "le snare claque comme un fouet et remet nos corps en mouvement instantanement",
    "on respire entre deux drops comme un plongeur entre deux immersions profondes",
    "les frequences sub nous massent les poumons de l'interieur comme un battement geant",
    "le dj enchaine les morceaux et chaque transition est un miracle musical parfait",
    "on se sent connecte a la terre par les vibrations qui montent du sol",
    "les confettis dores volent dans les faisceaux de lumiere comme des etoiles filantes",
    "la musique ralentit un instant et le monde retient sa respiration ensemble",
    "on danse avec la gravite et la gravite finit par abandonner la partie",
    "les spots balaient la foule et chaque visage eclaire est un tableau vivant",
    "le rythme tribal du kick nous ramene a quelque chose de primitif et vrai",
    "on ferme les yeux et le dancefloor devient un univers sans limites connues",
    "les aigus percent le mur de son comme des aiguilles de cristal brillant",
    "la foule ondule et on fait partie d'un seul et meme corps dansant",
    "le set touche a sa fin et chaque seconde devient plus precieuse que l'or",
    "on danse avec les fantomes de toutes les nuits passees sur ce dancefloor sacre",
    "les basses font vibrer l'eau dans les verres poses sur le bar du fond",
    "le rythme accelere et nos pieds suivent sans qu'on leur donne l'ordre de bouger",
    "on se regarde dans la foule et un sourire remplace mille conversations possibles",
    "les enceintes crachent des ondes qui nettoient nos esprits de toute la semaine",
    "le dernier break avant le drop final est un precipice de silence absolu",
    "on se tient par les epaules et on saute ensemble quand le beat revient",
    "les lumieres stroboscopiques decoupent nos mouvements en images fixes dans le temps fige",
    "la vibration du caisson nous fait sentir le son avec tout notre corps",
    "on danse jusqu'a l'aube et les premiers rayons eclairent nos visages heureux fatigues",
    "les woofers grondent comme des betes sauvages enchaines sous la scene du festival",
    "le rythme four on the floor est un mantra que nos pieds repetent toujours",
    "on hurle le nom du dj et notre voix se perd dans le son immense",
    "les nappes de delay creent des echos qui se repandent dans la nuit etoilee",
    "la piste de danse est un volcan en eruption et nous sommes sa lave",
    "on court entre les scenes du festival comme des enfants dans un parc magique",
    "les platines tournent et le monde tourne avec elles dans une spirale sonore",
    "le fade out du dernier morceau est un adieu qui dechire le coeur content",
    "on emporte le rythme dans nos pas en quittant le dancefloor au petit matin",
    "les enceintes refroidissent mais nos corps gardent la chaleur du beat jusqu'au lendemain",
    "le sol du festival porte les traces de milliers de pas qui ont danse",
    "on se promet que la prochaine nuit sera encore plus belle et plus folle",
    "les souvenirs de cette rave sont graves dans nos muscles qui se souviennent",
    "le silence du retour est une toile blanche apres le feu d'artifice sonore",
    "on marche dans la nuit et les basses resonnent encore dans nos tympans sourds",
    "les etoiles du matin palissent devant les lumieres que nous avons dansees ensemble",
    "le son nous a eleves au dessus de nous-memes pendant quelques heures magiques",
    "on range les souvenirs de cette nuit dans le coffre de notre memoire vive",
    "les champs du festival au matin ressemblent a un reve dont on se reveille",
    "le dernier laser s'eteint et le ciel reprend ses droits sur la nuit finie",
    "on quitte le temple du son les oreilles bourdonnantes et l'ame en paix profonde",
    "les basses continuent de vibrer dans la terre longtemps apres la fin du set",
    "on se disperse dans la nuit comme des etincelles apres un feu de joie",
    "le rythme est inscrit dans nos cellules et il ne partira jamais de nous",
    "les lumieres de la ville au retour semblent ternes apres celles du festival",
    "on porte la musique en nous comme un soleil interieur qui ne se couche pas",
    "le prochain beat sera le premier d'une nouvelle nuit que nous attendons deja",
    "les ondes sonores nous ont connectes et ce lien persiste dans le silence matin",
    "on rentre chez nous changes transformes par la puissance du son de cette nuit",
    "les murs de notre chambre resonnent encore du souvenir des basses profondes ecoutees",
    "le beat est un battement de coeur collectif qui refuse de mourir au matin",
    "on vit pour ces instants ou le son efface la frontiere entre soi et les autres",
    "les enceintes sont les orgues d'une cathedrale moderne ou l'on vient prier en dansant",
    "le drop est une chute libre dans un ocean de bonheur pur et brut",
    "on danse comme des flammes et le vent du son nous fait vaciller ensemble",
    "les lasers verts percent la fumee comme des epees de lumiere dans la bataille",
    "le tempo ralentit et nos coeurs s'accordent au nouveau rythme plus doux et profond",
    "les mains se touchent dans la foule et une electricite passe entre les doigts",
    "on saute si haut que pendant un instant on vole au dessus du dancefloor",
    "les vibrations remontent par les pieds traversent le corps et sortent par les mains",
    "le son est une riviere et nous sommes les poissons qui nagent dans le courant",
    "les lumieres tournent de plus en plus vite et le monde devient un kaleidoscope",
    "on crie notre bonheur et le son de nos voix se fond dans le beat",
    "le festival est un monde ou les regles du quotidien ne s'appliquent plus jamais",
    "les basses font trembler les confettis en l'air comme des flocons de neige lumineux",
    "on danse avec la nuit elle-meme et la nuit nous serre dans ses bras",
    "les echos du dernier morceau se propagent comme des cercles dans un lac sonore",
    "le beat est mort vive le beat la musique ne finit jamais vraiment ici",
    "on ferme les yeux une derniere fois et on revit toute la nuit dansee",
    "les frequences nous ont laves purifies et rendus meilleurs qu'avant cette nuit sacree",
    "le dancefloor est vide maintenant mais les fantomes de nos danses y vivent encore",
    "on emporte un morceau de cette nuit dans chaque pas que l'on fera demain",
    "les lumieres du matin remplacent les lasers et le monde reel revient lentement vers nous",
    "le dernier accord electronique vibre dans l'air comme un adieu lumineux et doux",
    "les lasers tracent des lignes de feu a travers la fumee epaisse du club",
    "on court vers le son comme des papillons vers la lumiere la plus vive",
    "la nuit electrique pulse dans chaque cellule de mon corps en mouvement libre",
    "le kick resonne et mon coeur repond comme un echo fidele et puissant",
    "les frequences basses creusent des tunnels dans l'air de la nuit profonde",
    "on se retrouve dans le son quand le monde exterieur perd tout son sens",
    "le dancefloor est un volcan et le drop est son eruption de joie",
    "les stroboscopes decoupent la nuit en tranches de lumiere blanche aveuglante",
    "on leve les mains vers le ciel et le son nous souleve du sol",
    "la musique est un fleuve et on nage dans son courant fort et chaud",
    "le beat tombe et mille corps rebondissent comme un seul organisme vivant",
    "les enceintes crachent des ondes qui font onduler l'air de la salle",
    "on se perd dans les frequences comme dans un labyrinthe de son infini",
    "le sub-bass gronde sous nos pieds comme un monstre qui se reveille enfin",
    "les nappes de synthese flottent au dessus de la foule en transe pure",
    "on danse jusqu'a l'epuisement et la musique nous releve toujours apres chaque chute",
    "le rythme est un ocean et chaque beat est une vague qui nous porte",
    "les confettis tourbillonnent dans les faisceaux de lasers multicolores au dessus de nous",
    "on ferme les yeux et les basses dessinent des paysages sonores magnifiques",
    "la piste vibre et chaque pas resonne comme un tambour electrique sacre",
    "le build-up monte en spirale et tout le monde retient son souffle ensemble",
    "les spots balaient la foule comme des phares dans une nuit de tempete sonore",
    "on crie de joie quand le beat revient apres un silence electrique court",
    "la basse fait trembler les murs et les murs font trembler nos ames libres",
    "le son est un missile qui traverse la foule de part en part ce soir",
    "les neons peignent nos visages de couleurs impossibles et merveilleuses a voir",
    "on vit dans le moment present et le present vibre de basses profondes",
    "le kick est un marteau qui frappe le sol au rythme de nos coeurs",
    "les arpegges montent comme des fusees vers un ciel de lumiere pure cristalline",
    "on se retrouve sous les enceintes comme sous un ciel d'etoiles qui chantent",
    "la foule est un ocean de bras leves vers le son qui descend fort",
    "le break suspend le temps et le drop le fait repartir plus fort qu'avant",
    "les vibrations parcourent la foule comme une vague electrique sans fin ni debut",
    "on danse avec les ombres que les stroboscopes dessinent partout sur les murs",
    "le son est si pur qu'il lave nos ames de toute la douleur accumulee",
    "les basses profondes resonnent comme le battement du coeur geant de la terre",
    "on lache prise et la gravite perd son emprise sur nos corps dansants",
    "le dj tourne les platines et le monde tourne avec elles dans la nuit",
    "les lumieres s'eteignent et la basse remplit le vide de sa puissance brute",
    "on respire au rythme du beat et on vit au tempo du son electrique",
    "la nuit est un poeme ecrit en frequences et en lumieres colorees vives",
    "le countdown electrise l'air et chaque seconde pese une tonne d'anticipation pure",
    "les ondes sonores sculptent l'espace comme un ciseau dans le marbre de la nuit",
    "on se fond dans la foule et on devient le beat qui pulse fort",
    "la basse est une riviere souterraine qui coule sous le dancefloor tremblant",
    "le filtre s'ouvre et le son explose comme un soleil qui nait dans le noir",
    "les mains frappent l'air au rythme du clap comme des ailes en vol libre",
    "on danse dans la brume et les lasers percent le voile autour de nous",
    "le tempo accelere et nos coeurs suivent sans jamais perdre le rythme sacre",
    "les frequences aigues brillent comme des etoiles dans le ciel sonore de la nuit",
    "on est des atomes de joie qui vibrent a la meme frequence cosmique",
    "la piste de danse est un creuset ou les energies fusionnent en une seule",
    "le beat minimal laisse l'espace pour que nos pensees s'envolent vers le haut",
    "les pyrotechnies explosent et la foule repond par un cri collectif de bonheur",
    "on porte le son en nous comme un tresor cache dans la poitrine chaude",
    "la nuit est un terrain de jeu et le beat est notre jouet prefere",
    "le drop est une cascade de son qui tombe sur nos tetes heureuses",
    "les enceintes sont des volcans qui crachent du son au lieu de lave brulante",
    "on court dans les couloirs de son sans jamais trouver la sortie du reve",
    "le rythme est une drogue et on est tous sous son emprise ce soir",
    "les nappes de reverb enveloppent la foule d'un manteau de douceur sonore",
    "on saute et le sol repond en envoyant les basses dans nos os tremblants",
    "la montee du son est un escalier vers le ciel electrique et lumineux",
    "le beat est un metronome qui marque le temps de notre bonheur collectif",
    "les lasers tracent notre chemin dans le labyrinthe de la nuit sans fin",
    "on se laisse porter par le courant du son sans resistance ni peur aucune",
    "la foule pulse comme un coeur geant et le dj est son stimulateur divin",
    "le sub-bass est un ocean profond sous la surface agitee de la musique",
    "les lumieres dansent avec nous et creent des ombres vivantes sur chaque mur",
    "on vit pour le moment ou le beat et le coeur battent a l'unisson",
    "la nuit electrique tatoue des souvenirs dans nos muscles qui se souviennent toujours",
    "le son rebondit sur les murs et revient charge de plus d'energie encore",
    "les frequences basses font vibrer l'air comme une membrane invisible et omnipresente",
    "on est des guerriers du dancefloor armes de notre energie infatigable ce soir",
    "la transition entre deux morceaux est un portail entre deux mondes sonores differents",
    "le kick est le pouls de la nuit et nous sommes ses globules rouges",
    "les stroboscopes flashent et le monde se deplace en images fixes qui dansent",
    "on danse comme des flammes qui vacillent sur les braises de la nuit chaude",
    "la basse est un tremblement de terre qui secoue chaque fibre du dancefloor",
    "le build-up est une montagne que le drop reduit en poussiere de joie",
    "les ondes nous traversent et on devient transparent face au son tout puissant",
    "on se noie dans les decibels et on renait a chaque nouveau beat joue",
    "la nuit avance et l'euphorie ne faiblit pas dans nos veines electriques",
    "le beat est notre boussole dans le labyrinthe lumineux de la fete nocturne",
    "les confettis brillent comme des diamants dans les faisceaux des projecteurs tournants",
    "on est des milliers a partager le meme battement de coeur ce soir la",
    "la pulsation du kick est le tambour de guerre de notre tribu nocturne",
    "le son est une maree qui monte et emporte tout sur son passage large",
    "les enceintes grondent comme des orages electriques qui annoncent l'arrivee du drop",
    "on vit le son avec chaque fibre de notre etre en eveil complet total",
    "la foule respire ensemble et le beat est leur souffle collectif synchronise",
    "le drop nous projette dans un univers parallele fait de basses et de lumiere",
    "les lasers dessinent des constellations sur le plafond du club dans l'obscurite",
    "on danse avec l'abandon de ceux qui vivent le moment comme le dernier",
    "la musique monte en pression et nos corps sont des soupapes de joie brute",
    "le rythme est un train express et on est tous a bord ensemble ce soir",
    "les frequences resonnent dans nos os comme des vibrations venues du centre de la terre",
    "on est des etoiles filantes sur le dancefloor infini de l'univers sonore",
    "la basse est notre ancre et le drop est notre envol vers les nuages",
    "le beat est un battement d'ailes qui nous eleve au dessus de tout le monde",
    "les lumieres pulsent et nos pupilles dansent au rythme hypnotique de chaque flash vif",
    "on court vers le son comme on court vers la promesse d'un monde meilleur",
    "la nuit est un canvas et le dj peint avec des sons et des lumieres",
    "le kick frappe la terre et la terre repond par une vibration profonde et douce",
    "les nappes de synthese coulent comme du miel electrique sur la foule en transe",
    "on est des particules de bonheur en orbite autour du dancefloor magnetique",
    "la piste est un sanctuaire et le son est notre meditation la plus profonde",
    "le drop est un saut dans le vide et la basse rattrape toujours nos corps",
    "les enceintes sont nos guides dans cette cathedrale de son et de lumiere pure",
    "on danse les pieds dans la brume et la tete perdue dans les etoiles",
    "la musique est un pont invisible entre nos solitudes et nos joies immenses",
    "le beat ne ment jamais il dit ce que nos coeurs veulent entendre toujours",
    "les stroboscopes figent des instants de bonheur parfait dans nos memoires vivantes",
    "on est la foule on est le son on est l'instant present qui vibre fort",
    "la basse gronde et la foule repond par un mouvement instinctif et primitif",
    "le son est notre carburant et le dancefloor est notre autoroute vers l'extase",
    "les lasers sont des epees de lumiere qui fendent l'obscurite de la salle entiere",
    "on vit pour ces nuits ou le temps perd toute signification connue",
    "la montee du son est une priere et le drop est la revelation divine",
    "le kick est un coeur qui bat pour chacun d'entre nous ici ce soir",
    "les frequences basses sont des racines sonores qui nous ancrent au dancefloor sacre",
    "on se perd dans la musique et on se retrouve dans le mouvement libre",
    "la nuit electrique nous transforme en versions plus lumineuses de nous-memes ici",
    "le beat est un fil invisible qui relie nos coeurs dans l'obscurite vibrante",
    "les enceintes rugissent et nos ames repondent par un cri de joie collective",
    "on danse pour exister on danse pour resister on danse pour aimer la vie",
    "la basse est une pulsation cosmique qui nous connecte a l'infini du son pur",
    "le son est un voyage dont on ne voudra jamais revenir chez soi",
    "les confettis sont des etoiles filantes qui tombent sur le dancefloor sacre",
    "on est des danseurs cosmiques sur la plus belle piste de l'univers entier",
    "la nuit pulse comme un coeur vivant et nous sommes le sang qui coule",
    "le drop est une porte grande ouverte sur un monde de pure extase totale",
    "les frequences nous lavent de la poussiere du monde ordinaire et gris",
    "on danse dans les bras de la musique et elle ne nous laisse pas tomber",
    "la piste de danse est notre vaisseau spatial et le son notre combustible sacre",
    "le beat est une horloge cosmique qui marque le temps de notre bonheur vivant",
    "les lasers sont nos chemins de lumiere dans la foret dense de la nuit",
    "on est des voyageurs du son en route vers une destination encore inconnue",
    "la basse est une force primitive qui plie le monde a sa volonte sauvage",
    "le son est un ocean sans rivage et on plonge avec joie dans ses vagues",
    "les enceintes sont des phares geants et nous sommes des navires dans la tempete",
    "on vit au rythme des bpm et on respire au tempo de la vie nocturne",
    "la nuit est un concert permanent pour ceux qui ecoutent avec le coeur ouvert",
    "le drop fait jaillir des geysers de joie dans la foule en transe complete",
    "les nappes de synthese sont des voiles de soie sonore qui flottent dans l'air",
    "on danse avec l'univers et les planetes comptent nos pas dans le vide cosmique",
    "la musique est la seule magie qui ne demande que de croire en elle",
    "le beat est un sculpteur qui faconne notre bonheur sur l'enclume de la nuit",
    "les stroboscopes sont les yeux clignotants d'un univers qui nous observe danser ensemble",
    "on est des flammes bleues qui dansent dans le vent electrique de cette nuit",
    "la foule est une constellation et chaque danseur est une etoile qui pulse fort",
    "le son monte si haut qu'il touche le plafond du ciel et le fait vibrer",
    "les basses sont des vagues cosmiques qui nous portent vers des mondes inconnus",
    "on danse sur les ondes sonores comme des surfeurs sur un ocean de beats",
    "la nuit est un reve eveille dont le beat est la bande son eternelle",
    "le drop est un seisme sonore qui reveille nos ames les plus endormies",
    "les lumieres du festival sont un ciel artificiel que nous avons cree ensemble",
    "on respire le son comme on respire l'air pur des sommets les plus hauts",
    "la piste est un miroir cosmique qui reflete notre joie dans mille lumieres",
    "le kick est le tonnerre electronique et le drop est la foudre qui danse",
    "les frequences sont des fils d'or qui tissent la toile magique de la nuit",
    "on danse dans le son comme des plongeurs nagent dans l'ocean profond et bleu",
    "la basse est un geant bienveillant qui berce la foule dans ses bras sonores",
    "le beat est un coeur universel qui bat pour tous ceux qui dansent ce soir",
    "les enceintes sont des fontaines de son qui desalterent nos ames assoiffees de beats",
    "on est des cosmonautes du son en apesanteur au dessus du dancefloor sacre",
    "la nuit electrique nous habille de lumiere pure et de frequences qui guerissent tout",
    "le drop nous catapulte comme des etoiles vers les confins du bonheur pur et vrai",
    "les ondes sonores sont des mains invisibles qui bercent nos coeurs en rythme parfait",
    "on danse les bras grands ouverts et le son nous embrasse comme un ami fidele",
    "la foule vibre et le dancefloor se transforme en un organisme vivant qui respire",
    "le son est un cadeau que la nuit nous offre a chaque beat qui tombe",
    "les lasers ecrivent notre histoire collective en lignes de lumiere sur le ciel sombre",
    "on se consume dans le feu du beat et on renait dans la grace du drop",
    "la musique est notre bouclier invisible contre toutes les ombres du monde de jour",
    "le rythme est un langage universel que tout le monde parle sur le dancefloor"
  ],
  bridges: [
    "et quand le beat s'arrete on retient notre souffle ensemble",
    "la musique nous a lies plus fort que les mots ne pourraient",
    "on a danse toute la nuit et le soleil ne nous arretera pas",
    "entre le silence et le drop le monde suspend son vol un instant",
    "on est venus pour oublier et la musique nous a exauces totalement",
    "sous les lasers on a trouve une famille qu'on ne soupconnait pas",
    "le beat revient et nos coeurs reprennent vie comme par magie instantanee",
    "on ne savait pas qu'on avait besoin de ca avant de l'entendre",
    "les frequences nous guerissent des blessures que le jour nous inflige",
    "cette nuit restera gravee comme la premiere fois qu'on a danse ensemble",
    "le son nous traverse et on comprend enfin ce que veut dire vivre",
    "on a laisse nos armures au vestiaire et on a danse libres",
    "le beat est le seul langage qui ne ment jamais a personne",
    "entre deux drops on se regarde et on sait qu'on est vivants ici",
    "la musique a le pouvoir de reunir ce que le monde separe chaque jour",
    "on danse pour ceux qui ne sont pas la ce soir dans la foule",
    "le drop nous a liberes de tout ce qui pesait sur nos epaules",
    "on a touche quelque chose de sacre sur ce dancefloor ce soir",
    "les lumieres s'eteignent mais la musique continue dans nos coeurs enflammes",
    "le son est un pont entre nos solitudes qui deviennent force ensemble",
    "on a perdu la notion du temps et gagne celle de l'instant pur",
    "le beat nous a portes la ou les mots ne vont jamais seuls",
    "chaque nuit comme celle-ci nous rappelle pourquoi on vit avec passion",
    "la foule respire comme un seul etre et le beat est son pouls",
    "on ne danse pas pour fuir on danse pour se retrouver enfin",
    "le silence entre les morceaux est aussi puissant que les basses les plus lourdes",
    "on a partage plus que de la musique on a partage nos ames",
    "le beat efface les larmes et les remplace par des cris de joie",
    "cette nuit on a prouve que la musique peut changer le monde entier",
    "les vibrations nous ont connectes a quelque chose de plus grand que nous",
    "on sort de cette nuit differents transformes par la puissance du son",
    "le dancefloor est le seul endroit ou je me sens complet et libre",
    "la musique a parle quand les mots ne suffisaient plus pour nous dire",
    "on a danse nos peines et elles se sont envolees dans le son",
    "le dernier beat resonne et on sait qu'on a vecu pleinement ce soir"
  ],
  choruses: [
    "on danse jusqu'au bout de la nuit sans jamais s'arreter",
    "le beat nous porte et on s'envole au dessus du monde entier",
    "la musique coule dans nos veines comme du feu liquide pur",
    "ce soir on est libres et le son est notre liberte totale",
    "les mains en l'air on touche le ciel de cette nuit magique",
    "le drop tombe et on renait dans l'explosion du son immense",
    "on est la foule on est le beat on est la nuit vivante",
    "la basse fait trembler la terre et nos coeurs suivent le rythme",
    "on danse ensemble et le monde n'a jamais ete aussi beau",
    "la nuit electrique coule dans nos veines comme une riviere de feu",
    "le son est notre priere et le dancefloor notre cathedrale sacree",
    "on leve les bras et on crie notre joie vers le ciel",
    "les lasers percent la nuit et nos ames percent les nuages sombres",
    "le beat ne ment jamais et ce soir il dit la verite",
    "on vit pour ces nuits ou la musique fait vibrer le monde",
    "la foule est un ocean et le beat est notre maree montante",
    "on se perd dans le son et on se trouve dans la danse",
    "ce soir rien ne peut nous arreter le beat est trop fort",
    "les enceintes rugissent et nos coeurs repondent avec la meme force",
    "on danse comme si la nuit n'avait pas de fin possible",
    "le rythme nous unit et les lumieres nous guident dans le noir",
    "la musique est notre oxygen et le beat notre battement de coeur",
    "on est vivants on est presents on est la musique elle-meme",
    "le drop nous propulse dans un monde ou tout est possible",
    "la nuit est a nous et le beat est notre roi souverain",
    "on danse pour oublier on danse pour se souvenir de vivre",
    "les frequences nous traversent et on devient lumiere dans le noir",
    "ce soir on ecrit notre histoire en beats et en lumieres vives",
    "la foule pulse comme un coeur geant sous le ciel etoile grand",
    "on est tous ensemble dans ce moment que rien ne peut briser",
    "le son monte et nos ames suivent vers l'infini de la nuit",
    "la basse est notre ancre et le ciel est notre destination finale",
    "on danse avec l'univers et les etoiles sont nos spots lumineux",
    "le beat est notre langue et cette nuit on parle couramment",
    "les vibrations nous connectent a tout ce qui est vivant autour",
    "on lache tout et le son nous rattrape toujours au bon moment",
    "la nuit est un poeme ecrit en beats et en decibels",
    "on est des guerriers du dancefloor et la musique est notre armure",
    "le rythme coule comme un fleuve et on nage dans son courant",
    "ce soir le monde est un dancefloor et tout le monde danse",
    "les basses sont nos racines et les aigus sont nos ailes deployees",
    "on danse sur les cendres de nos doutes et de nos peurs",
    "la musique guerit les blessures que le silence laisse ouvertes chaque jour",
    "on est ensemble dans le beat et c'est tout ce qui compte",
    "le son est un miracle et cette nuit on croit aux miracles",
    "la foule chante et le monde tremble sous nos pieds dansants",
    "on vit la nuit comme un reve dont on ne veut pas se reveiller",
    "les lumieres dansent avec nous et le ciel applaudit notre folie",
    "le beat final resonne et nos coeurs le gardent pour toujours",
    "on reviendra danser ici quand la nuit nous appellera de nouveau",
    "le son nous enveloppe et on devient la musique qui joue ce soir",
    "on est des etincelles dans le feu du beat qui brule sans fin",
    "la nuit est notre temple et le dancefloor est notre autel sacre",
    "le drop nous libere de la gravite et on flotte dans le son pur",
    "on danse comme des etoiles qui tournent dans le ciel electrique",
    "la basse est notre coeur et le beat est notre sang qui coule",
    "le son est une vague et on surfe jusqu'au bout de la nuit",
    "on est la nuit on est le son on est le feu qui danse",
    "les frequences nous elevent au dessus du monde et on ne redescend pas",
    "la musique est notre oxygene et le dancefloor est notre univers entier",
    "le beat est un miracle qui se repete a chaque seconde de la nuit",
    "on danse ensemble et les frontieres entre nous disparaissent dans le son",
    "la nuit electrique coule en nous et on brille de mille frequences",
    "le drop est notre renaissance et le beat est notre eternite",
    "on est les enfants du son et la musique est notre mere eternelle",
    "la basse gronde et nos ames repondent par un cri de joie pure",
    "le dancefloor est notre monde et le son est notre loi sacree",
    "on danse pour vivre et on vit pour danser sous les lasers",
    "la musique nous connecte a l'infini et le beat est le fil sacre",
    "le son est notre revolution et le dancefloor est notre champ de bataille",
    "on est des guerriers de la nuit armes de beats et de lumieres",
    "la nuit pulse en nous et nous pulsons en elle sans jamais faiblir",
    "le beat est notre promesse que demain sera aussi beau que cette nuit",
    "on danse jusqu'a ce que le soleil se leve sur nos visages heureux",
    "la musique est le feu qui brule en nous et illumine la nuit sombre",
    "le son est notre liberte et le dancefloor est notre terre promise",
    "on est vivants dans le beat et le beat est vivant en nous",
    "la nuit est un cadeau et le son est le papier qui l'enveloppe",
    "on danse et le monde danse avec nous sous un ciel de beats infinis"
  ],
  vocabulary: {
    nouns: [
      "beat", "basse", "drop", "foule", "laser",
      "stroboscope", "enceinte", "frequence", "vibration", "pulsion",
      "dancefloor", "festival", "rave", "synthetiseur", "neon",
      "decibel", "tempo", "onde", "eclat", "euphorie",
      "energie", "extase", "transe", "rythme", "confetti",
      "kick", "clap", "buildup", "breakdown", "sequence",
      "arpege", "filtre", "reverb", "woofer", "platine",
      "mix", "set", "spot", "fumee", "brume",
      "pyrotechnie", "scene", "ampli", "caisson", "nappe",
      "oscillation", "impulsion", "decharge", "deflagration", "tsunami",
      "pulsation", "vibration", "secousse", "transe", "hypnose",
      "vertige", "spirale", "tourbillon", "vortex", "cyclone",
      "tonnerre", "foudre", "eclair", "choc", "impact",
      "detonation", "explosion", "eruption", "raz-de-maree", "avalanche",
      "comete", "meteore", "supernova", "satellite", "orbite",
      "circuit", "courant", "voltage", "plasma", "noyau"
    ],
    verbs: [
      "danser", "vibrer", "pulser", "exploser", "electriser",
      "trembler", "bondir", "crier", "hurler", "sauter",
      "transpirer", "tournoyer", "onduler", "gronder", "rugir",
      "flasher", "briller", "eclater", "monter", "descendre",
      "accelerer", "ralentir", "synchroniser", "fusionner", "propulser",
      "lacher", "s'envoler", "plonger", "rebondir", "resonner",
      "decoller", "percuter", "vrombir", "marteler", "scander",
      "scanner", "balayer", "irradier", "deferler", "submerger",
      "amplifier", "moduler", "filtrer", "saturer", "distordre",
      "enflammer", "embraser", "galvaniser", "transcender", "detonner",
      "catapulter", "propulser", "projeter", "ejecter", "declencher",
      "atomiser", "desintegrer", "volatiliser", "pulveriser", "calciner",
      "magnetiser", "aimanter", "hypnotiser", "ensorceler", "fasciner",
      "vrombir", "crepiter", "siffler", "bourdonner", "tonner",
      "fuser", "jaillir", "eructer", "deferler", "inonder",
      "decupler", "demultiplier", "intensifier", "maximaliser", "optimiser"
    ],
    adjectives: [
      "electrique", "puissant", "massif", "hypnotique", "euphorique",
      "pulsant", "vibrant", "nocturne", "cosmique", "stellaire",
      "frenetique", "extatique", "stroboscopique", "sourd", "profond",
      "sature", "distordu", "lumineux", "fluorescent", "incandescent",
      "tonnant", "explosif", "foudroyant", "titanesque", "volcanique",
      "magnetique", "ultrasonique", "subsonique", "tellurique", "sismique",
      "infernal", "dementiel", "vertigineux", "hallucinant", "transcendant",
      "atomique", "nucleaire", "orbital", "interstellaire", "galactique",
      "mecanique", "synthetique", "analogique", "numerique", "futuriste",
      "sauvage", "brut", "tribal", "primaire", "visceral",
      "supersonique", "hypersonique", "stratospherique", "ionique", "photonique",
      "binaire", "algorithmique", "cybernetique", "holographique", "virtuel",
      "astral", "lunaire", "solaire", "nebuleux", "quantique",
      "thermonucleaire", "radioactif", "corrosif", "abrasif", "abyssal",
      "dementiel", "psychedelique", "hallucinatoire", "endiable", "effrenee",
      "percutant", "tonitruant", "assourdissant", "cataclysmique", "ravageur"
    ]
  }
};
