module.exports = {
  themes: [
    "voyage", "nature", "tradition", "contes", "racines",
    "saisons", "rivieres", "montagnes", "communaute", "feu de camp",
    "ancetres", "sagesse", "moisson", "berger", "chemin"
  ],
  openers: [
    "Sur Les Chemins De Nos Ancetres Je Marche Encore",
    "La Riviere Chante Doucement Dans La Vallee Endormie",
    "Au Coin Du Feu Les Vieilles Histoires Reprennent Vie",
    "Le Vent Porte Les Chansons De Ceux Qui Sont Partis",
    "Dans Les Champs Dores La Moisson Appelle Nos Bras",
    "Les Montagnes Gardent Le Secret Des Anciens Temps",
    "Sous Le Grand Chene On Se Rassemble Pour Chanter",
    "La Terre Nous Parle Si On Sait Bien Ecouter",
    "Au Premier Jour Du Printemps Les Oiseaux Reviennent",
    "Le Berger Descend De La Colline Avec Son Troupeau",
    "Les Etoiles Guident Le Voyageur Dans La Nuit Claire",
    "On Dit Que La Foret Murmure Le Nom Des Disparus",
    "Le Vieux Moulin Tourne Encore Au Bord Du Ruisseau",
    "Quand La Neige Fond Les Sentiers Se Reveillent Enfin",
    "Les Chansons De Ma Grand Mere Resonnent Dans Mon Coeur",
    "Au Village On Danse Sous La Lumiere Des Lanternes",
    "Le Fleuve Suit Son Cours Vers Des Terres Inconnues",
    "Dans Le Silence De L Aube La Nature S Eveille",
    "Les Racines De Cet Arbre Plongent Dans Notre Histoire",
    "Sur Le Pont De Pierre Les Pas Des Anciens Resonnent",
    "La Lune Eclaire Le Chemin Des Pelerins Fatigues",
    "Nos Peres Ont Bati Ces Murs De Leurs Propres Mains",
    "Le Ble Se Courbe Sous Le Vent De La Plaine Immense",
    "Au Creux De La Vallee Un Hameau Vit En Paix",
    "Les Saisons Passent Mais Les Chansons Restent Toujours",
    "Chaque Pierre De Ce Mur Raconte Une Histoire Ancienne",
    "Le Forgeron Bat Le Fer Au Rythme De Son Coeur",
    "Par Les Sentiers De Montagne Les Bergers S En Vont",
    "La Rosee Du Matin Brille Sur Les Pres Verts",
    "Quand Le Soleil Se Couche Les Contes Commencent Enfin",
    "Les Voix Du Passe Chantent Dans Le Vent Du Soir",
    "Au Marche Du Village Les Rires Emplissent La Place",
    "La Source Jaillit Du Rocher Comme Une Promesse Pure",
    "Dans La Grange On Entend Encore Les Vieux Violons",
    "Le Chemin Serpente A Travers Les Collines Verdoyantes",
    "Nos Grands Parents Savaient Lire Le Ciel Et La Terre",
    "Le Feu Craque Et Les Ombres Dansent Sur Les Murs",
    "Au Bord Du Lac Les Peupliers Se Balancent Doucement",
    "La Moisson Est Belle Quand On Travaille Ensemble",
    "Les Cloches Du Village Annoncent Le Retour Du Jour",
    "Sous Le Ciel Etoile Le Monde Semble Plus Simple",
    "Le Ruisseau Emporte Les Feuilles Mortes Vers La Mer",
    "Quand L Automne Arrive Les Vignes Se Parent D Or",
    "Le Pain Qui Sort Du Four Embaume Toute La Maison",
    "Les Enfants Courent Pieds Nus Dans Les Champs De Ble",
    "Au Sommet De La Colline On Voit Le Monde Entier",
    "La Pluie Douce Nourrit La Terre De Nos Aieux",
    "Le Tisserand File Les Histoires Avec La Laine",
    "Chaque Aube Nouvelle Est Un Cadeau De La Terre",
    "Les Chemins De Traverse Menent Aux Plus Beaux Endroits"
  ],
  verses: [
    "le vent souffle a travers les branches du vieux chene",
    "je marche sur les traces de ceux qui m ont precede",
    "la terre sous mes pieds garde la memoire des anciens",
    "les oiseaux chantent l arrivee du printemps dans la vallee",
    "le ruisseau serpente entre les pierres couvertes de mousse",
    "dans la foret profonde les ombres dansent avec la lumiere",
    "le feu de camp rechauffe nos ames par les nuits froides",
    "les etoiles dessinent la carte des voyageurs perdus",
    "la moisson est le fruit du labeur de nos mains",
    "chaque saison apporte sa chanson et son lot de promesses",
    "le berger connait le nom de chaque sommet alentour",
    "les racines de nos traditions plongent dans un sol fertile",
    "le vent du nord apporte des nouvelles de pays lointains",
    "sous la lune les loups chantent leur solitude infinie",
    "la riviere porte les reves des enfants vers la mer",
    "dans le grenier on trouve les tresors des temps passes",
    "le violon pleure les joies et les peines des humbles",
    "les mains calleuses du fermier racontent des annees de travail",
    "la brume matinale enveloppe le village comme un voile doux",
    "chaque pas sur le sentier est une priere muette",
    "les murs de pierre temoignent de la force de nos peres",
    "le soleil se leve sur les champs laboures avec soin",
    "la chanson du boulanger accompagne le lever du jour",
    "les enfants apprennent les contes au coin du feu sacre",
    "le vent fait chanter les herbes hautes de la prairie",
    "la neige recouvre les traces mais pas les souvenirs",
    "le pont de bois relie deux rives et deux destins",
    "dans le jardin les fleurs sauvages poussent en liberte",
    "le clocher sonne l heure ou les travailleurs se reposent",
    "les chemins de terre menent aux portes de la sagesse",
    "la laine du mouton file entre les doigts de la vieille",
    "le ble mur ondule comme une mer sous le soleil",
    "chaque arbre de cette foret a une histoire a conter",
    "les hirondelles reviennent annoncer la fin de l hiver long",
    "la source claire abreuve les betes et les ames assoiffees",
    "le vent transporte le parfum des foins fraichement coupes",
    "dans la cave les tonneaux gardent le vin des bonnes annees",
    "la grand mere tisse des echarpes et des souvenirs tendres",
    "le sentier de montagne grimpe vers un ciel plus proche",
    "les pommes tombent de l arbre quand l automne les appelle",
    "le silence de la campagne est une musique en soi",
    "les pas du cheval resonnent sur le chemin de terre",
    "la lune guide le pecheur sur les eaux calmes du lac",
    "les mains du potier donnent forme a la terre docile",
    "le vent d est apporte la pluie sur nos terres seches",
    "dans le pre les vaches paissent sous un ciel immense",
    "la flamme de la bougie danse au rythme du vent",
    "le vieux sage parle et le village entier ecoute",
    "les pierres du chemin portent la marque de mille pas",
    "la foret murmure des secrets que seul le coeur entend",
    "le matin se leve et la brume se dissipe lentement",
    "les mains jointes autour du feu on partage le pain",
    "la riviere ne s arrete jamais meme quand le monde dort",
    "le chariot grince sur le chemin des vendanges d automne",
    "les feuilles mortes tapissent la terre comme un tapis roux",
    "la chouette veille sur la nuit et ses mysteres profonds",
    "le forgeron plie le metal comme on plie son destin",
    "les enfants chantent en rond sous le tilleul centenaire",
    "la pluie tambourine sur le toit de la vieille grange",
    "le ruisseau raconte l histoire de la montagne a la plaine",
    "les anciens savaient lire les signes dans le vol des oiseaux",
    "la recolte est bonne quand le coeur est genereux",
    "le sillon trace droit est la promesse d un ete fertile",
    "les etoiles brillent plus fort loin des lumieres des villes",
    "la barque glisse sur le lac dans le silence du soir",
    "le vent souffle la poussiere des chemins oublies depuis longtemps",
    "les mains du tisserand creent la beaute fil apres fil",
    "la colline verte domine la vallee et ses tresors caches",
    "le coq chante et le jour commence sa danse eternelle",
    "les saisons tournent comme la roue du vieux moulin fidele",
    "la chanson du berceau endort les enfants du monde entier",
    "le vent du soir apporte les chants lointains des montagnards",
    "les vignes grimpent le long du mur de pierre seche",
    "la neige fond et les premiers bourgeons apparaissent timidement",
    "le pas du bucheron resonne dans la foret silencieuse",
    "les mains de ma mere sentaient la farine et la lavande",
    "la lune rousse annonce les semailles et les jours longs",
    "le tonnerre gronde au loin sur les cretes des montagnes",
    "les abeilles butinent les fleurs du verger en plein soleil",
    "la nuit tombe et le village se recueille en silence",
    "le chemin du retour est toujours plus court que l aller",
    "les champs de lavande embaument la colline au mois de juin",
    "la vieille horloge marque le temps qui passe sans fin",
    "le vent fait tourner les ailes du moulin inlassablement",
    "les contes de fees sont nes dans ces vallees profondes",
    "la terre promise est sous nos pieds si on sait voir",
    "le chant du merle annonce que le jour va bientot naitre",
    "les filets du pecheur sechent au soleil du port tranquille",
    "la rosee perle sur les petales de la rose sauvage",
    "le fermier seme avec espoir dans le champ de printemps",
    "les nuages dessinent des visages au dessus des montagnes",
    "la foret en automne se pare de mille couleurs chaudes",
    "le pain partagee unit les coeurs autour de la table",
    "les chemins s effacent mais la direction reste dans le coeur",
    "la pluie douce fait pousser les fleurs et les reves",
    "le silence du matin porte la promesse d un jour nouveau",
    "les rides du vieux sage sont des rivieres de sagesse",
    "la lune se mire dans l eau calme du lac endormi",
    "le vent chante une melodie que les arbres accompagnent",
    "les mains du jardinier caressent la terre comme un enfant",
    "la grange est pleine et le coeur est reconnaissant ce soir",
    "le cheval galope dans la prairie sous un ciel sans nuages",
    "les cloches du soir appellent les fideles a la priere",
    "la fontaine du village murmure des histoires oubliees depuis longtemps",
    "le lierre grimpe sur les murs de la vieille eglise",
    "les champs de ble se balancent comme une mer doree",
    "la nuit etoilee invite les reveurs a lever les yeux",
    "le bois craque dans la cheminee les soirs de decembre",
    "les cerises rougissent sous le soleil du premier ete",
    "la colombe blanche porte un message de paix et d espoir",
    "le vieux pont enjambe le torrent depuis des siecles entiers",
    "les pas des danseurs marquent le rythme de la fete",
    "la terre gelee attend patiemment le retour du soleil chaud",
    "le miel des abeilles est le tresor cache de la montagne",
    "les ombres s allongent quand le soleil descend sur la plaine",
    "la fumee du foyer monte droit dans l air immobile",
    "le chant des cigales remplit les apres midi d ete",
    "les murs du cimetiere gardent la memoire de nos proches",
    "la pluie lave la poussiere des chemins de nos ancetres",
    "le fleuve grossi par les pluies deborde dans les pres",
    "les premieres gelees annoncent le temps du repos meerite",
    "la laine cardee sera le manteau de l hiver prochain",
    "le tambour bat et le village danse jusqu au petit matin",
    "les chataignes grillent sur la braise du feu d automne",
    "la brume se leve sur les paturages de la vallee verte",
    "le silence de la neige apaise les coeurs fatigues",
    "les graines semees au printemps portent les fruits de l automne",
    "la chanson du vent raconte l histoire de mille voyages",
    "le pain dore sort du four et embaume la cuisine",
    "les traces dans la neige revelent le passage du renard",
    "la lumiere du matin filtre a travers les rideaux de lin",
    "le potager nourrit la famille de ses legumes colores",
    "les grenouilles chantent dans la mare au crepuscule doux",
    "la faux du moissonneur brille sous le soleil de juillet",
    "le chemin du pelerinage mene au coeur de soi meme",
    "les murs de la ferme sont blanchis par le temps passe",
    "la brise du soir seche les larmes des jours difficiles",
    "le lac reflete les montagnes dans son miroir tranquille",
    "les vendanges reunissent le village dans la joie partagee",
    "la nuit porte conseil a ceux qui savent attendre",
    "le givre dessine des fleurs sur les carreaux de la fenetre",
    "les sentiers oublies menent aux claireres les plus belles",
    "la terre noire du jardin promet une belle recolte",
    "le son de la cloche se perd dans la vallee brumeuse",
    "les papillons dansent autour des fleurs de la haie vive",
    "la sagesse des anciens coule dans nos veines encore",
    "le toit de chaume protege du froid et de la pluie",
    "les chants des moissonneurs resonnent dans la campagne entiere",
    "la source chante en descendant le flanc de la montagne",
    "le temps passe mais les traditions demeurent dans nos coeurs",
    "les nuages blancs voyagent portant la pluie vers les champs",
    "la veille au coin du feu rassemble les generations ensemble",
    "le ruisseau gele craque sous les pas des promeneurs",
    "les champs en jachere se reposent avant le prochain cycle",
    "la fumee blanche monte des cheminees du hameau tranquille",
    "le panier d osier deborde de fruits cueillis au verger",
    "les peupliers bordent le canal et dansent avec le vent",
    "la terre humide sent bon apres la pluie de printemps",
    "le faucheur avance au rythme regulier de sa lame aiguisee",
    "les ecureuils cachent leurs provisions pour les mois a venir",
    "la nuit de la saint jean les feux illuminent les collines",
    "le vieux puits au fond du jardin garde son eau fraiche",
    "les martinets tournent dans le ciel au dessus du clocher",
    "la lavande seche parfume les armoires de la maison ancienne",
    "le soleil d hiver rechauffe a peine les murs de pierre",
    "les chemins croises sont les carrefours de tous les destins",
    "la charrette pleine de foin traverse le pont de bois",
    "le laboureur retourne la terre brune du champ au matin",
    "les chauves souris dessinent des cercles dans le ciel obscur",
    "la recolte des olives marque la fin de la saison chaude",
    "le figuier du jardin offre ses fruits aux passants",
    "les saisons dansent en rond comme une ronde enfantine",
    "la lumiere d or du couchant embrase la plaine entiere",
    "le chien de berger veille sur son troupeau fidlement",
    "les greniers regorgent de ble pour nourrir le village l hiver",
    "la branche de pommier ploie sous le poids des fruits murs",
    "le vent de mars secoue les arbres et reveille la terre",
    "les premieres violettes annoncent le renouveau du monde endormi",
    "la lune pleine eclaire les champs comme en plein jour",
    "le bucheron fend le bois pour les longues nuits d hiver",
    "les sentiers de douaniers longent la cote sauvage et belle",
    "la marche en foret guerit les blessures de l ame triste",
    "le vent transporte les graines vers des terres nouvelles et fertiles",
    "les cigognes sur le toit annoncent le bonheur a venir",
    "la terre argileuse garde les empreintes de nos ancetres courageux",
    "le soir tombe tot en hiver et les contes commencent",
    "les jardins secrets cachent les fleurs les plus precieuses du monde",
    "la voix du conteur fait revivre les heros des temps anciens",
    "le moulin a eau grince et moud le grain patiemment",
    "les libellules survolent la mare dans la chaleur de juillet",
    "la haie d aubepine fleurit et parfume le chemin creux",
    "le cri du faucon perce le silence de la falaise haute",
    "les mains jointes on prie pour une recolte genereuse et belle",
    "la danse des flammes hypnotise les yeux des enfants emerveilles",
    "le givre du matin scintille sur les brins d herbe fins",
    "les pierres seches du muret protegent le jardin du vent fort",
    "la nuit claire d ete est pleine de murmures et de parfums",
    "le torrent devale la pente avec la force des montagnes",
    "les lucioles eclairent les sentiers des amoureux dans la nuit",
    "la mare aux canards reflete les nuages du ciel changeant",
    "le vieux noyer donne ses fruits a qui sait attendre",
    "les ombres du soir s etirent sur les champs endormis paisiblement",
    "la route est longue mais les compagnons rendent le chemin doux",
    "le coeur du village bat au rythme des quatre saisons",
    "les mains tendues accueillent l etranger comme un frere bienvenu",
    "la terre nous enseigne la patience et la perseverance chaque jour",
    "le cycle des saisons est la promesse que tout recommence toujours",
    "les racines des vieux arbres tiennent la colline ensemble",
    "la pluie fine tisse un voile entre le ciel et la terre",
    "le monde est vaste mais la maison reste le port d attache",
    "les histoires des anciens sont le fil qui nous relie au passe",
    "la foret generee offre ses champignons a l automne humide",
    "le reflet de la montagne tremble dans le lac agite",
    "les nuits d ete sont courtes et pleines de chants joyeux",
    "la derniere feuille tombe et l arbre attend le renouveau",
    "le pas lent du paysan mesure la terre avec amour",
    "les cerfs traversent la clairiere dans la lumiere du petit matin",
    "la fumee du foyer s eleve droit dans l air calme du soir",
    "le ruban de la route serpente entre les collines boisees",
    "les noix tombent de l arbre et roulent dans l herbe humide",
    "la vieille balance du marche pese les fruits de la saison",
    "le mur de pierres seches tient bon depuis des generations entieres",
    "les grenouilles annoncent la pluie avec leur concert du crepuscule",
    "la barque du pecheur attend sagement sur la berge moussue",
    "le gel matinal craque sous les sabots du cheval fidele",
    "les corneilles se posent sur le labour frais du matin",
    "la soupe chaude fume dans le bol de terre cuite simple",
    "le bois sec craque et les etincelles montent vers les etoiles",
    "les iris sauvages bordent le canal au mois de mai fleuri",
    "la brouette grince sur le chemin du potager au petit jour",
    "le chat du grenier guette les souris parmi les bottes de foin",
    "les piverts martlent le tronc du vieux hetre au bord du pre",
    "la cloche de la vache tinte dans le brouillard du vallon",
    "le soleil couchant peint les nuages de rose et de pourpre",
    "les chemins creux s enfoncent entre les haies d aubepine fleurie",
    "la mure sauvage tache les doigts des enfants gourmands d ete",
    "le faisan s envole dans un battement d ailes bruyant et rapide",
    "les anes braient au fond du pre sous les peupliers argentees",
    "la vigne vierge rougit le mur de la ferme abandonnee",
    "le sentier de halage longe la riviere jusqu au prochain village",
    "les champs de colza illuminent la campagne de leur jaune vif",
    "la citerne recueille l eau de pluie pour les jours de secheresse",
    "le houx aux baies rouges decore la porte a noel joyeux",
    "les grillons chantent leur serenade dans les herbes du talus",
    "la meule de foin trone au milieu du champ fraichement fauche",
    "le canard sauvage se pose sur l etang dans un glissement doux",
    "les geraniums rouges fleurissent aux fenetres des maisons de pierre",
    "la brume du matin se leve et revele un paysage intact",
    "le vol des oies sauvages dessine un triangle dans le ciel gris",
    "les fraises des bois parfument le panier d osier du promeneur heureux",
    "le vieux banc sous le tilleul attend les amoureux du soir",
    "les pommiers en fleurs parfument toute la vallee au printemps doux",
    "la route de terre serpente entre les champs de tournesols dores",
    "le fermier rentre ses betes avant que la tempete ne gronde",
    "les fougeres cachent les traces du chevreuil dans la foret humide",
    "la cloche de l eglise sonne midi sur le village endormi",
    "le vieux pressoir ecrase les pommes pour le cidre de l automne",
    "les martinets filent dans le ciel du soir avec des cris joyeux",
    "la lessive blanche seche au vent sur le fil du jardin",
    "le sentier de douanier longe les falaises battues par les vagues",
    "les champignons poussent en cercle sous les chenes centenaires",
    "la barque du passeur traverse la riviere dans le matin brumeux",
    "le forgeron souffle sur les braises et le metal rougit au feu",
    "les enfants ramassent les chataignes dans les feuilles mortes d automne",
    "la source murmure entre les racines du vieux saule pleureur",
    "le berger joue de la flute assis sur un rocher gris",
    "les nuages effilochees courent au dessus de la lande sauvage",
    "la vieille porte de bois grince et ouvre sur le jardin secret",
    "le vent d automne arrache les dernieres feuilles de l orme ancien",
    "les truites sautent dans le torrent au pied de la cascade claire",
    "la pierre du lavoir garde la fraicheur meme au coeur de l ete",
    "le coq de la girouette indique la direction du vent qui change",
    "les prunelles sauvages murissent dans la haie au bord du chemin creux",
    "la lune se leve sur le village et les chats sortent chasser",
    "le sabotier taille le bois de hetre avec des gestes precis",
    "les grues cendrees passent dans le ciel et annoncent le grand froid",
    "la neige recouvre la campagne d un silence blanc et pur",
    "le puits du village garde son eau claire meme pendant la secheresse",
    "les jonquilles percent la terre gelee aux premiers jours du printemps",
    "la lessive battue au lavoir resonne dans le hameau tranquille",
    "le charretier siffle en conduisant son attelage sur le chemin boueux",
    "les cerises noires du verger tachent les mains des enfants rieurs",
    "la fumee du soir monte des cheminees dans l air calme et froid",
    "le ruisseau gonfle par la fonte des neiges devale la montagne",
    "les orchidees sauvages fleurissent dans les pres non fauches du plateau",
    "la grand mere conte les histoires du temps ou les loups rodaient",
    "le vent fait chanter les girouettes de tous les toits du village",
    "les pommes de terre sortent de la terre noire au bout de la fourche",
    "la brouette grinche sur le chemin du verger au petit matin gris",
    "le herison traverse le jardin dans la lumiere douce du crepuscule",
    "les bles d hiver verdissent les champs sous le soleil pale de mars",
    "la fontaine coule sans relache depuis le temps des premiers bergers",
    "le laboureur guide son soc droit dans la terre brune et grasse",
    "les choucas tournoient au dessus des ruines du vieux chateau fort",
    "la pluie d orage lave le ciel et l arc-en-ciel apparait enfin",
    "le miel ambree coule du rayon que l apiculteur vient de recolter",
    "les noyers centenaires bordent le chemin qui mene a la chapelle",
    "la riviere deborde au printemps et fertilise les prairies basses",
    "le vent du sud apporte la chaleur et les parfums de la garrigue",
    "les coquelicots rouges tachent le champ de ble comme des gouttes",
    "la meule du moulin tourne en grinchant et le grain devient farine",
    "le renard roux traverse le pre dans la brume du petit matin",
    "les eglantines en fleurs embaument les haies du chemin creux",
    "la pluie fine nourrit les racines et les reves des semeurs",
    "le cheval tire la charrue dans le champ au lever du soleil",
    "les grenouilles coassent la nuit tombee dans la mare du jardin",
    "la cabane du berger se dresse seule contre le vent de la montagne",
    "le rouet tourne et la laine devient fil entre les doigts agiles",
    "les sentiers de crete offrent une vue sur toute la vallee verte",
    "la souche du chene abattu porte encore les marques de la cognee",
    "le passeur connait chaque rocher sous la surface de la riviere",
    "les glands du chene nourissent les sangliers dans la foret profonde",
    "la clairiere baignee de soleil est le jardin secret de la foret",
    "le vent courbe les herbes et les joncs au bord du lac calme",
    "les mures tardives parfument les doigts des cueilleurs du dimanche",
    "la croix du carrefour marque le chemin des anciens pelerins",
    "le vent porte le son des cloches bien au dela du village",
    "les peupliers alignes le long du canal sont les gardiens de l eau",
    "la terre rouge du midi colore les mains du vigneron courageux",
    "le coq chante trois fois et le village se reveille doucement",
    "les sauterelles chantent dans les bles sous le soleil de plomb",
    "la vieille fontaine du lavoir abreuve les betes au retour du pre",
    "le vannier tresse l osier humide avec une patience de saint homme",
    "les etoiles filantes traversent le ciel d aout au dessus des meules",
    "la moisson finie les gerbes se dressent dans le champ rase sec",
    "le vent de la mer monte jusqu a la lande et la fait chanter",
    "les noisettes tombent des branches quand l ecureuil secoue la cime",
    "la marche longue dans la montagne purifie l ame et l esprit",
    "le talus fleuri abrite les nids des merles et des fauvettes",
    "les ombres des nuages courent sur les collines comme des chevaux libres",
    "la terre mouille colle aux bottes et alourdit les pas du marcheur",
    "le verger croule sous les fruits et la joie de la recolte",
    "les chouettes appellent la nuit depuis le clocher de la vieille eglise",
    "la rosee perle sur les fils de la toile d araignee fine",
    "le givre dessine des feuilles blanches sur les vitres du matin",
    "les canards colvert glissent sur l etang dans la lumiere d or",
    "la grange ouverte laisse entrer le vent et le parfum du foin",
    "le bucheron empile les buches pour chauffer tout l hiver long",
    "les premiers crocus percent la neige comme des flammes violettes",
    "la pleine lune eclaire les meules de foin dans le champ argente",
    "le vieux chat du grenier ronronne sur le sac de grain tiede",
    "les sillons droits du champ fraichement laboure brillent sous la pluie",
    "la vallee s eveille sous un voile de brume fine et blanche",
    "le son de la cornemuse porte loin dans les vallons boisees",
    "les raisins murissent sur les ceps et la vendange approche enfin",
    "la route pavee de pierres rondes mene au moulin abandonee",
    "le pic vert martele le tronc creux de l aulne au bord de l eau",
    "les genets en fleurs habillent les collines d un manteau d or",
    "la nuit d hiver est longue mais le feu veille dans la maison chaude",
    "le chant du rossignol perce le silence de la nuit de juin"
  ],
  bridges: [
    "et la terre tournera encore quand nous ne serons plus la",
    "mais les racines tiennent bon malgre les tempetes du temps",
    "car chaque generation porte le flambeau un peu plus loin",
    "et dans le silence on entend battre le coeur du monde",
    "mais le chemin continue au dela de la ligne d horizon",
    "car les anciens savaient que la terre ne ment jamais",
    "et nous chanterons encore quand les etoiles s eteindront enfin",
    "mais l hiver finit toujours par ceder la place au printemps",
    "car la memoire des hommes est plus forte que le temps",
    "et la riviere emporte nos peines vers un ocean lointain",
    "mais les chansons restent gravees dans le coeur des enfants",
    "car le feu ne meurt jamais tant qu on le nourrit bien",
    "et demain sera un autre jour plein de promesses neuves",
    "mais la nuit est douce pour ceux qui savent rever",
    "car les saisons reviennent toujours malgre les annees qui passent",
    "et le vent portera nos voix bien au dela des montagnes",
    "mais le silence est parfois la plus belle des reponses",
    "car on ne perd jamais ce qu on a seme avec amour",
    "et la lumiere revient meme apres la nuit la plus longue",
    "mais les pierres gardent les secrets de ceux qui les ont posees",
    "car la terre nourrit ceux qui la respectent avec humilite",
    "et les voix du passe chantent encore dans nos coeurs",
    "mais le voyage compte plus que la destination lointaine",
    "car les mains qui travaillent la terre faconnent le monde",
    "et la foret repousse apres chaque tempete devastatrice",
    "mais les etoiles guident ceux qui ont perdu leur chemin",
    "car le pain partage a le gout de la fraternite vraie",
    "et chaque aube nouvelle efface les ombres de la veille",
    "mais la sagesse se transmet de bouche a oreille doucement",
    "car les rivires coulent sans jamais regarder en arriere",
    "et le monde tourne au rythme des saisons immuables",
    "mais le coeur humain est plus vaste que toutes les plaines",
    "car chaque arbre abattu laisse une place pour un autre",
    "et nous sommes les gardiens de cette terre ancestrale",
    "mais la beaute se cache parfois dans les choses simples"
  ],
  choruses: [
    "nous marchons ensemble sur les chemins de nos peres",
    "la terre est notre mere et le ciel notre toit",
    "chantons la vie qui coule comme la riviere fidele",
    "les saisons passent mais notre chanson demeure eternelle",
    "ensemble autour du feu nous sommes plus forts que tout",
    "la montagne nous appelle et nous repondons avec joie",
    "les racines de nos coeurs plongent dans la terre ancienne",
    "le vent emporte nos chants vers les quatre coins du monde",
    "nous sommes les enfants de la terre et du soleil",
    "la moisson est belle quand on la fait ensemble ici",
    "chantons pour ceux qui viennent et ceux qui sont partis",
    "la nature est notre guide sur les sentiers de la vie",
    "les etoiles veillent sur nous comme des ancetres bienveillants",
    "le feu de nos coeurs ne s eteindra jamais ce soir",
    "marchons chantant vers l aube d un jour meilleur pour tous",
    "la terre sous nos pieds vibre au rythme de nos pas",
    "les chansons de nos peres resonnent dans chaque vallee",
    "le fleuve de la vie nous porte vers des rives nouvelles",
    "ensemble on batit des ponts entre hier et demain",
    "la lumiere du matin chasse les ombres de la nuit",
    "nous semons les graines d un avenir plein d esperance",
    "le chant du coq nous rappelle que tout peut recommencer",
    "les mains unies forment une chaine plus forte que le fer",
    "la terre tourne et nous dansons au rythme des saisons",
    "les voix du village montent vers le ciel etoile ce soir",
    "nous portons en nous la force des anciennes generations",
    "chantons la pluie qui nourrit les champs et les ames",
    "le chemin est long mais la compagnie rend tout plus beau",
    "les fleurs du printemps annoncent la renaissance de nos espoirs",
    "ensemble on partage le pain et les histoires du coeur",
    "la lune nous eclaire et la terre nous porte toujours",
    "nous sommes le grain seme par la main de nos aieux",
    "chantons pour la terre qui nous nourrit chaque saison",
    "le vent de liberte souffle sur les collines verdoyantes",
    "les rivieres chantent la meme chanson depuis la nuit des temps",
    "notre chanson est le fil qui tisse notre communaute",
    "la beaute du monde est un cadeau a partager entre tous",
    "ensemble sous les etoiles nous retrouvons notre vraie nature",
    "les pas des danseurs font trembler la terre avec bonheur",
    "nous gardons la flamme allumee pour les generations futures",
    "chantons la joie simple de vivre au rythme de la terre",
    "le soleil se leve et nos coeurs se levent avec lui",
    "la tradition est le pont entre le passe et l avenir",
    "les mains dans la terre nous trouvons la paix veritable",
    "ensemble nous ecrivons l histoire de notre village bien aime",
    "le chant des oiseaux est la symphonie de notre campagne",
    "nous sommes les gardiens des sentiers et des forets profondes",
    "la vie est un voyage et chaque pas est une chanson",
    "les saisons dansent et nous dansons avec elles ce soir",
    "chantons pour le monde tel qu il est beau et fragile",
    "nous marchons sur les traces de nos ancetres dans la lumiere",
    "la terre nous porte et nous portons ses chansons dans nos coeurs",
    "chantons ensemble car la nuit est courte et la vie est belle",
    "les montagnes veillent sur nous comme des geants bienveillants et vieux",
    "nous semons l espoir dans chaque sillon que nos mains ont creuse",
    "la riviere chante et nous chantons avec elle depuis toujours",
    "ensemble nous gardons la flamme des traditions qui nous unissent fort",
    "le vent porte nos voix jusqu aux confins du monde endormi",
    "nous sommes le grain qui germe et nourrit les generations futures",
    "chantons la beaute des saisons qui tournent comme une ronde eternelle",
    "la foret nous protege et nous protegeons ses secrets anciens",
    "ensemble autour de la table nous partageons le pain et les histoires",
    "le chemin est notre maison et le ciel notre seul toit",
    "nous chantons pour les fleurs les arbres et les ruisseaux fideles",
    "la terre tourne et nos pas suivent le rythme des saisons neuves",
    "ensemble nous tissons le fil qui relie le passe au present",
    "les etoiles nous guident et nos chansons guident ceux qui viendront",
    "chantons pour la pluie qui nourrit et le soleil qui rechauffe",
    "nous sommes les voix de la terre et le chant de la riviere",
    "la moisson est notre joie et le partage est notre richesse",
    "ensemble nous batissons des ponts de chansons entre les villages",
    "le feu de camp eclaire nos visages et rechauffe nos ames",
    "nous marchons ensemble et le chemin devient plus beau sous nos pas",
    "chantons la nuit qui tombe et le jour qui se leve toujours",
    "la terre est genereuse pour ceux qui la respectent avec amour",
    "ensemble nous sommes la chanson que le vent emporte au loin",
    "les saisons sont nos compagnes et la nature notre seule richesse",
    "nous gardons la memoire de ceux qui ont marche avant nous",
    "chantons car nos voix unies sont plus fortes que le silence froid",
    "la terre est notre chanson et nous sommes sa plus belle melodie"
  ],
  vocabulary: {
    nouns: [
      "chemin", "riviere", "montagne", "foret", "champ",
      "village", "colline", "vallee", "moisson", "saison",
      "ancetre", "racine", "pierre", "grange", "feu",
      "vent", "terre", "ciel", "etoile", "lune",
      "arbre", "fleur", "oiseau", "berger", "moulin",
      "source", "pont", "sentier", "ruisseau", "prairie",
      "aube", "crepuscule", "brume", "givre", "rosee",
      "recolte", "semaille", "charrue", "tonneau", "graine",
      "troupeau", "vignoble", "verger", "haie", "sillon",
      "conte", "legende", "chanson", "danse", "sagesse",
      "pelerin", "voyageur", "nomade", "errant", "barde",
      "luth", "violon", "flute", "harpe", "tambourin",
      "lanterne", "torche", "bougie", "lampe", "chandelle",
      "tisserand", "potier", "charpentier", "meunier", "aubergiste",
      "auberge", "taverne", "hameaux", "hospice", "refuge",
      "parchemin", "encre", "plume", "manuscrit", "chronique",
      "toison", "laine", "lin", "soie", "cuir"
    ],
    verbs: [
      "marcher", "chanter", "semer", "recolter", "danser",
      "voyager", "tisser", "batir", "cultiver", "partager",
      "murmurer", "fleurir", "bruler", "souffler", "couler",
      "grimper", "descendre", "veiller", "nourrir", "faucher",
      "labourer", "cueillir", "moudre", "forger", "filer",
      "rever", "ecouter", "contempler", "rassembler", "guider",
      "planter", "germer", "eclore", "bruire", "ondoyer",
      "serpenter", "scintiller", "embaumer", "resonner", "bercer",
      "accueillir", "transmettre", "enraciner", "bourdonner", "moissonner",
      "paitre", "vendanger", "glaner", "errer", "cheminer",
      "vagabonder", "peleriner", "arpenter", "parcourir", "sillonner",
      "conter", "narrer", "reciter", "declamer", "psalmodier",
      "tresser", "entrelacer", "nouer", "filer", "tisser",
      "aiguiser", "polir", "sculpter", "tailler", "graver",
      "bivouaquer", "camper", "s'abriter", "giter", "loger",
      "enfouir", "denicher", "debusquer", "decouvrir", "explorer"
    ],
    adjectives: [
      "ancien", "fertile", "verdoyant", "dore", "paisible",
      "humble", "robuste", "fidele", "sauvage", "genereux",
      "brumeux", "ensoleille", "fleuri", "centenaire", "rustique",
      "sacre", "profond", "tranquille", "lointain", "ancestral",
      "tendre", "chaleureux", "eternel", "simple", "pur",
      "solitaire", "immense", "silencieux", "patient", "courageux",
      "bienveillant", "lumineux", "modeste", "fecond", "harmoieux",
      "serein", "vivace", "fragile", "precieux", "accueillant",
      "champetre", "bucolique", "pastoral", "nocturne", "matinal",
      "hivernal", "printanier", "estival", "automnal", "intemporel",
      "legendaire", "mythique", "fabuleux", "epique", "heroique",
      "nomade", "itinerant", "vagabond", "errant", "ambulant",
      "bruissant", "chantant", "murmurant", "susurrant", "bourdonnant",
      "embaume", "parfume", "odorant", "aromatique", "capiteux",
      "tortueux", "sinueux", "serpentin", "ondulant", "vallonne",
      "immemorial", "millenaire", "patriarcal", "venerable", "auguste"
    ]
  }
};
