/**
 * Gospel Genre — French Phrase Bank
 * Themes: faith, glory, heaven, grace, spirit, salvation, praise, blessing, light, divine
 */
module.exports = {
  themes: [
    "foi", "gloire", "ciel", "grace", "esprit",
    "salut", "louange", "benediction", "lumiere", "divin",
    "priere", "ame", "redemption", "eternite", "sacre"
  ],
  openers: [
    "La Lumiere De Dieu Eclaire Notre Chemin Ce Soir",
    "On Eleve Nos Voix Vers Le Ciel Dans La Gloire",
    "La Grace Divine Descend Sur Nous Comme Une Pluie D'or",
    "Ce Soir On Chante La Louange Du Seigneur Tres-Haut",
    "L'esprit Saint Souffle Sur Nos Ames Avec Amour Et Paix",
    "On Marche Dans La Lumiere De La Grace Eternelle Ce Soir",
    "Le Ciel S'ouvre Et La Gloire De Dieu Brille Sur Nous",
    "Nos Prieres Montent Comme L'encens Vers Le Trone Celeste",
    "La Foi Nous Porte Au-dessus Des Tempetes De La Vie",
    "Ce Soir On Celebre La Bonte Du Seigneur Notre Dieu",
    "La Benediction De Dieu Couvre Nos Vies De Sa Lumiere",
    "On Ouvre Nos Coeurs Et La Grace Coule Comme Un Fleuve",
    "Le Seigneur Est Notre Berger Et On Ne Manque De Rien",
    "Ce Soir Nos Ames S'elevent Dans La Presence Du Tres-Haut",
    "La Gloire De L'eternel Remplit Ce Lieu De Sa Lumiere",
    "On Leve Les Mains Vers Le Ciel Et Les Anges Chantent",
    "La Grace Infinie Du Seigneur Renouvelle Nos Forces Ce Soir",
    "Ce Soir On Est Les Enfants De La Lumiere Eternelle",
    "L'amour De Dieu Est Un Ocean Sans Fond Ni Rivage",
    "On Chante Avec Les Anges Et Le Ciel Nous Repond",
    "La Foi Est Notre Ancre Dans La Tempete De Ce Monde",
    "Ce Soir La Redemption Coule Comme Une Riviere De Vie",
    "Le Seigneur Nous A Delivres Et On Chante Sa Victoire",
    "La Lumiere Du Paradis Brille Dans Nos Coeurs Ce Soir",
    "On Marche Par La Foi Et Non Par La Vue Seule",
    "Ce Soir On Temoigne De La Grandeur De Notre Dieu",
    "La Paix De Dieu Qui Surpasse Toute Intelligence Nous Garde",
    "On Est Sauvés Par La Grace Et Portes Par La Promesse",
    "Le Saint-Esprit Nous Guide Sur Le Chemin De La Verite",
    "Ce Soir On Rend Gloire Au Roi Des Rois Eternel",
    "La Benediction Du Seigneur Nous Suit Tous Les Jours Ici",
    "On Danse De Joie Dans La Presence De Notre Pere Celeste",
    "La Grace Nous A Trouves La Ou La Nuit Etait Profonde",
    "Ce Soir Nos Voix S'unissent Pour Louer Le Nom Sacre",
    "Le Ciel Est Plus Pres Quand On Chante Ensemble Ce Soir",
    "On Leve Nos Mains Et La Gloire Descend Sur Ce Lieu",
    "La Lumiere De L'espoir Brille Dans La Nuit La Plus Sombre",
    "Ce Soir On Goute La Bonte De L'eternel Notre Dieu",
    "Le Seigneur Est Notre Force Et Notre Chant De Victoire",
    "On Marche Ensemble Dans Le Jardin De La Grace Divine",
    "La Priere Ouvre Les Portes Du Ciel Pour Nos Ames",
    "Ce Soir On Depose Nos Fardeaux Aux Pieds Du Seigneur",
    "La Gloire De Dieu Resplendit Dans Chaque Battement De Coeur",
    "On Est Les Vaisseaux De La Lumiere Dans Ce Monde Sombre",
    "Le Sang Precieux A Lave Nos Peches Et Nos Douleurs",
    "Ce Soir La Grace Nous Porte Sur Des Ailes De Colombes",
    "La Foi Deplace Les Montagnes Et Nos Prieres Percent Le Ciel",
    "On Celebre La Victoire De La Croix Avec Nos Chants",
    "Le Seigneur Est Bon Et Sa Misericorde Dure A Toujours",
    "Ce Soir On Entre Dans Le Saint Des Saints Avec Louange"
  ],
  verses: [
    "la grace de dieu coule dans nos veines comme un fleuve de vie",
    "on leve nos mains vers le ciel et les anges chantent avec nous",
    "la lumiere de l'eternel eclaire nos pas dans la nuit sombre",
    "nos prieres montent comme la fumee de l'encens sacre vers le ciel",
    "le seigneur est notre rocher et notre forteresse dans la tempete",
    "on marche par la foi sur les eaux troubles de ce monde",
    "la gloire de dieu remplit nos coeurs d'une joie indescriptible",
    "l'esprit saint souffle sur nos vies et tout devient nouveau ce soir",
    "on chante la louange et les murs de jericho s'ecroulent devant nous",
    "la benediction du seigneur nous enrichit sans ajouter aucun chagrin",
    "nos ames s'elevent comme des aigles au-dessus des montagnes de l'ombre",
    "le sang precieux a lave nos peches et nous sommes libres enfin",
    "on danse de joie car le seigneur a tourne notre deuil en fete",
    "la paix de dieu descend comme la rosee sur nos ames assoiffees",
    "le chemin etroit mene au paradis et on marche ensemble dessus",
    "nos voix s'unissent dans un chant de louange qui monte au ciel",
    "la grace est un cadeau que nos mains ne meritent pas de tenir",
    "on se tient debout car le seigneur combat pour nous chaque jour",
    "la lumiere du monde brille dans nos coeurs comme un phare divin",
    "l'amour de dieu est plus vaste que tous les oceans du monde",
    "on porte la croix avec joie car elle mene a la victoire",
    "la redemption est un chant de liberte dans la nuit de l'esclavage",
    "nos larmes deviennent des semences de joie dans le jardin du seigneur",
    "le seigneur essuie chaque larme et guerit chaque blessure de l'ame",
    "on est les enfants de la promesse et heritiers de la gloire",
    "la foi est une lampe qui brille dans les tenebres du doute",
    "l'eternel est notre berger et il nous conduit pres des eaux calmes",
    "on chante dans la vallee car le seigneur marche avec nous toujours",
    "la grace nous a rattrapes au bord du precipice de la chute",
    "nos prieres percent les nuages et atteignent le trone de la grace",
    "le seigneur transforme nos deserts en jardins fleuris et abondants ce soir",
    "on eleve un cri de louange qui fait trembler les tenebres autour",
    "la misericorde de dieu se renouvelle chaque matin comme l'aurore doree",
    "l'esprit divin nous remplit de force pour affronter chaque jour nouveau",
    "on marche dans la lumiere et les ombres fuient devant nos pas",
    "le ciel est notre patrie et la terre n'est qu'un passage bref",
    "la joie du seigneur est notre force dans les epreuves du monde",
    "nos chaines sont brisees car le fils nous a liberes pour toujours",
    "on ouvre nos bibles et la parole vivante eclaire notre chemin sombre",
    "la gloire de dieu brille dans les moments les plus sombres aussi",
    "le seigneur est proche de ceux qui ont le coeur brise ce soir",
    "on se refugie sous les ailes du tres-haut dans chaque tempete",
    "la grace transforme les cenacles de cendres en couronnes de beaute divine",
    "nos voix s'elevent comme un tonnerre de louange devant le trone sacre",
    "l'eternel combat nos batailles et nous donne la victoire a chaque fois",
    "on chante un cantique nouveau car le seigneur fait des merveilles ici",
    "la benediction coule comme le miel et la grace comme l'huile sainte",
    "le seigneur est notre lumiere et notre salut de qui aurions-nous peur",
    "on danse devant l'arche de la presence comme david dansait jadis",
    "la grace est une riviere qui ne tarit jamais et coule sans fin",
    "nos ames trouvent le repos dans les bras du pere celeste ce soir",
    "le sang de l'agneau nous a rachetes du peche et de la mort",
    "on est les pierres vivantes du temple que le seigneur construit",
    "la lumiere de la verite chasse les mensonges de nos coeurs perdus",
    "l'amour du calvaire est plus fort que toutes les forces du mal",
    "on marche sur les traces du maitre et il eclaire nos pas",
    "la priere est le souffle de notre ame et la grace son repos",
    "le seigneur nous a appeles par notre nom et nous sommes a lui",
    "on leve nos yeux vers les montagnes d'ou vient notre secours divin",
    "la foi grandit comme un grain de moutarde qui devient un grand arbre",
    "nos louanges sont des offrandes parfumees devant le trone de la grace",
    "le seigneur fait toutes choses nouvelles et nos vies en temoignent",
    "on chante dans les chaines et les portes de la prison s'ouvrent",
    "la grace divine est le pont entre nos peches et le paradis",
    "l'esprit du seigneur est sur nous et il nous a consacres ce soir",
    "on est les flambeaux de la foi dans un monde plonge dans le noir",
    "la gloire du matin eclaire nos nuits les plus sombres et froides",
    "le seigneur nous donne la paix que le monde ne connait pas",
    "on marche avec confiance car les promesses de dieu sont fideles toujours",
    "la redemption est un lever de soleil apres la nuit du peche",
    "nos coeurs debordent de gratitude pour la grace recue chaque matin",
    "le ciel chante avec nous quand on loue le nom du tres-haut",
    "on eleve nos mains vides et le seigneur les remplit de grace",
    "la benediction de dieu est comme une pluie bienfaisante sur nos vies",
    "l'eternel est notre refuge et notre forteresse en tout temps difficile",
    "on se tient sur la parole qui ne passera jamais en vain",
    "la grace nous a liberes et la verite nous a rendus libres",
    "le seigneur est le potier et nous sommes l'argile dans ses mains",
    "on chante alleluia car la victoire est a notre dieu pour toujours",
    "la lumiere de l'esperance brille dans nos yeux malgre les epreuves",
    "nos ames sont lavees par la grace et vetues de sa justice",
    "le seigneur restaure nos annees perdues avec sa bonte infinie",
    "on danse sous la pluie de la grace qui tombe du ciel ouvert",
    "la foi nous donne des ailes pour survoler les tempetes de la vie",
    "l'amour du seigneur est un feu qui purifie nos coeurs impurs",
    "on porte les fruits de l'esprit et le monde reconnait notre lumiere",
    "la priere du juste a une grande efficacite quand elle est sincere",
    "le seigneur nous couvre de sa main et nous protege du mal ce soir",
    "on est les serviteurs fideles qui attendent le retour du roi",
    "la grace est le manteau qui couvre nos fragilites et nos peches",
    "nos voix resonnent dans les cieux et les anges se joignent a nous",
    "le sang precieux a scelle l'alliance eternelle entre dieu et nous",
    "on marche dans la victoire car le seigneur a deja vaincu pour nous",
    "la gloire du seigneur se revele dans notre faiblesse rendue parfaite",
    "l'esprit divin souffle un vent nouveau sur nos vies assechees par le monde",
    "on est les brebis du bon berger et sa voix nous guide chaque jour",
    "la benediction du seigneur est le tresor que nous portons dans des vases",
    "le ciel se rejouit quand un seul pecheur se repent devant dieu",
    "on chante la bonte de l'eternel de generation en generation sans cesse",
    "la grace transforme nos epreuves en temoignages de la fidelite de dieu",
    "le seigneur fait jaillir l'eau vive dans le desert de nos vies",
    "on se prosterne devant sa majeste et nos coeurs debordent de louange",
    "la lumiere de la grace perce les nuages les plus sombres du desespoir",
    "nos prieres sont les cles qui ouvrent les portes du ciel ce soir",
    "le seigneur nous releve quand nous tombons et nous porte dans ses bras",
    "on est les temoins de sa grace infinie dans ce monde perdu",
    "la redemption nous a liberes des chaines du passe et du peche",
    "l'amour de dieu nous poursuit tous les jours de notre vie entiere",
    "on leve un chant de victoire car le seigneur a fait de grandes choses",
    "la foi est le bouclier qui eteint les fleches enflammees du mal",
    "le seigneur est fidele et ses promesses se realisent en leur temps",
    "on marche ensemble sur le chemin de la saintete et de la grace",
    "la grace est le parfum du ciel qui embaume nos vies terrestres",
    "nos ames sont des temples ou habite l'esprit du dieu vivant",
    "le ciel est notre destination et la foi notre boussole eternelle",
    "on chante avec les rachetés le cantique de l'agneau dans la gloire",
    "la benediction se repand comme l'huile sur la tete et la barbe",
    "l'eternel est notre soleil et notre bouclier dans les combats spirituels",
    "on se refugie dans le secret du tres-haut et sous son ombre",
    "la grace du seigneur suffit car sa puissance s'accomplit dans la faiblesse",
    "le sang de jesus parle mieux que celui d'abel devant le pere",
    "on est les pierres rejetees devenues la pierre angulaire du temple",
    "la lumiere de la resurrection eclaire nos tombeaux et nos nuits sombres",
    "nos louanges font tomber les murailles qui nous separent de la promesse",
    "le seigneur ouvre les yeux des aveugles et les oreilles des sourds",
    "on porte la bonne nouvelle aux pauvres et la liberte aux captifs",
    "la priere fervente du juste a une grande puissance dans ses effets",
    "l'amour divin ne perit jamais il est patient et plein de bonte",
    "on danse avec liberte car le joug est brise et les chaines tombent",
    "la gloire se revele et nos visages brillent comme celui de moise",
    "le seigneur nous a choisis avant la fondation du monde par grace",
    "on est les ambassadeurs du ciel sur la terre dans ce monde",
    "la foi voit l'invisible croit l'incroyable et recoit l'impossible chaque jour",
    "nos coeurs sont enracines dans l'amour et la grace du tres-haut",
    "le ciel applaudit quand les enfants de dieu se levent dans la foi",
    "on chante la fidelite de dieu qui traverse les generations sans fin",
    "la grace a ecrit nos noms dans le livre de vie eternelle",
    "l'esprit de dieu habite en nous et nous sommes ses temples vivants",
    "on est les rachetés de l'eternel et on le proclame a haute voix",
    "la benediction du seigneur repose sur ceux qui marchent dans ses voies",
    "le sang precieux est la cle qui ouvre les portes du paradis",
    "on marche de gloire en gloire car l'esprit nous transforme chaque jour",
    "la redemption est la plus belle histoire d'amour jamais racontee au monde",
    "nos ames assoiffees trouvent la source de vie dans la presence divine",
    "le seigneur fait lever son soleil sur les justes et les injustes",
    "on eleve un altar de louange avec les pierres de notre temoignage",
    "la grace est la melodie du ciel qui resonne dans nos coeurs",
    "l'amour du pere celeste nous enveloppe comme un manteau de lumiere",
    "on est les sentinelles qui veillent dans la nuit en attendant l'aurore",
    "la priere est notre souffle et la louange notre chant de guerre",
    "le seigneur renouvelle nos forces comme celles de l'aigle qui s'eleve",
    "on danse dans la joie car le tombeau est vide et la mort vaincue",
    "la gloire de dieu couvre la terre comme les eaux couvrent la mer",
    "nos voix proclament la victoire de la croix sur les tenebres du monde",
    "le ciel et la terre passeront mais sa parole demeure a jamais",
    "on est les branches attachees au cep et nous portons du fruit",
    "la grace nous a adoptes dans la famille royale du roi celeste",
    "l'eternel nous a grave dans la paume de ses mains par amour",
    "on chante dans les vallees et sur les montagnes avec la meme foi",
    "la benediction de dieu est un heritage eternel pour nos enfants aussi",
    "le seigneur transforme nos larmes en perles de joie et de louange",
    "on marche vers la cite celeste avec des chants de victoire eternelle",
    "la lumiere de sa face brille sur nous et nous donne la paix",
    "nos prieres sont des ponts de foi entre la terre et le ciel",
    "le sang de l'alliance nouvelle coule comme une riviere de grace pure",
    "on est les elus de dieu saints et bien-aimes appeles a la gloire",
    "la grace est l'ancre de notre ame sure et ferme en tout temps",
    "l'esprit nous conduit dans toute la verite et nous revele les mysteres",
    "on leve un etendard de foi dans les nations et les peuples",
    "la redemption est un chant eternel que les rachetés chanteront pour toujours",
    "le seigneur est notre justice notre saintete et notre redemption en christ",
    "on danse sur les tombes de nos ennemis car dieu nous donne la victoire",
    "la priere perseverante brise les forteresses et renverse les principautes du mal",
    "nos ames sont gardees par la puissance de dieu pour le salut final",
    "le ciel se rapproche avec chaque louange que nos levres prononcent ensemble",
    "on est les porteurs de la flamme divine dans un monde de tenebres",
    "la grace du seigneur est nouvelle chaque matin et grande est sa fidelite",
    "l'amour de dieu a ete repandu dans nos coeurs par l'esprit saint",
    "on chante les merveilles de celui qui nous a appeles des tenebres",
    "la gloire de dieu habite dans la louange de son peuple rassemble",
    "le seigneur est notre portion et notre heritage dans cette vie et au-dela",
    "on est les mains et les pieds de jesus dans ce monde brise",
    "la foi est la substance des choses esperees et la preuve de l'invisible",
    "nos louanges ouvrent les cieux et font descendre la presence de dieu",
    "le sang precieux nous reconcilie avec le pere et nous donne la paix",
    "on marche comme des enfants de lumiere dans un monde plonge dans la nuit",
    "la benediction du seigneur enrichit et n'ajoute avec elle aucune peine",
    "l'eternel est notre chant et notre force dans les jours de detresse",
    "on se tient fermes dans la grace car rien ne peut nous separer",
    "la redemption a brise le pouvoir du peche et de la mort eternelle",
    "le seigneur habite les louanges de son peuple et sa gloire nous couvre",
    "on est les sacrificateurs royaux appeles a proclamer les vertus de dieu",
    "la lumiere de l'evangile brille dans les tenebres et elles ne l'eteignent pas",
    "nos coeurs sont des autels ou brule le feu de la louange sacree",
    "le ciel est notre maison et le seigneur nous prepare une place la-haut",
    "on eleve le nom au-dessus de tout nom avec nos voix unies",
    "la grace est le fleuve qui traverse nos vies et porte du fruit",
    "l'esprit de dieu nous revele les profondeurs de l'amour du pere celeste",
    "on danse dans le fleuve de la grace qui coule du trone celeste",
    "la priere est la respiration de l'ame et la louange son battement",
    "le seigneur fait toute chose belle en son temps et par sa grace",
    "on chante la victoire car celui qui est en nous est plus grand",
    "la gloire du seigneur se leve sur nous et sa splendeur nous eclaire",
    "on est les instruments de sa paix dans un monde dechire par la haine",
    "la priere du matin ouvre les portes que les hommes ont fermees devant nous",
    "le seigneur transforme nos nuits en aurores et nos pleurs en chants de joie",
    "on porte la lumiere de l'evangile dans les ruelles les plus sombres",
    "la grace est un bouclier invisible qui nous protege des fleches du mal",
    "nos louanges sont des epees spirituelles qui tranchent les liens de l'ennemi",
    "le seigneur fait couler des sources d'eau vive dans nos deserts interieurs",
    "on est les messagers de la bonne nouvelle pour les coeurs brises du monde",
    "la redemption est un pont de lumiere entre nos peches et le pardon divin",
    "nos ames chanteront sa gloire jusqu'a ce que le dernier jour se leve",
    "le sang de l'alliance coule comme une riviere de grace dans nos vies",
    "on se tient sur les promesses du seigneur comme sur un roc inebranlable",
    "la paix de dieu est une forteresse ou nos ames trouvent refuge toujours",
    "nos voix unies dans la louange font trembler les fondations de l'enfer",
    "le seigneur peint l'arc-en-ciel de sa promesse dans le ciel de nos vies",
    "on danse avec la joie du salut comme des enfants dans les bras du pere",
    "la grace est une pluie qui tombe sur les justes et les injustes aussi",
    "nos prieres sont des graines de foi semees dans le jardin de l'eternite",
    "le seigneur nous conduit sur des sentiers de justice pour l'amour de son nom",
    "on est les colonnes vivantes du temple que dieu construit dans ce monde",
    "la lumiere de sa parole dissipe les tenebres de nos pensees troublees",
    "nos coeurs sont des instruments accorde pour jouer la symphonie de sa grace",
    "le seigneur recolte la moisson de nos prieres semees dans les larmes",
    "on leve l'etendard de la foi au milieu des batailles de ce monde",
    "la grace nous habille de robes blanches lavees dans le sang de l'agneau",
    "nos pas sont guides par la colonne de feu de sa presence divine",
    "le seigneur fait sonner la trompette de la victoire dans nos oreilles",
    "on est les gardiens de la flamme sacree qui brule sur l'autel du coeur",
    "la benediction du seigneur est une huile parfumee qui coule sur nos tetes",
    "nos ames assoiffees boivent a la source de vie qui ne tarit jamais",
    "le seigneur ouvre les fenetres du ciel et repand ses bienfaits sur nous",
    "on chante les promesses de dieu comme des ancres pour nos ames troublees",
    "la grace est un manteau de pourpre qui couvre nos haillons de peche",
    "nos louanges font descendre le feu du ciel sur l'autel de nos coeurs",
    "le seigneur nous donne des ailes d'aigle pour survoler les vallees sombres",
    "on est les brebis de son paturage et les enfants de sa maison",
    "la lumiere de la resurrection eclaire chaque tombe et chaque nuit de doute",
    "nos mains levees sont des branches d'olivier qui offrent la paix au monde",
    "le seigneur fait jaillir des chants de louange des pierres les plus dures",
    "on marche sur les eaux de la foi car le seigneur tient nos mains",
    "la grace est le levain qui fait lever la pate de nos vies",
    "nos coeurs sont des greniers remplis des tresors de sa bonte infinie",
    "le seigneur trace un chemin dans la mer de nos impossibilites humaines",
    "on est les flambeaux de sa gloire dans un monde plonge dans la nuit",
    "la redemption est le chant du matin apres la plus longue nuit d'hiver",
    "nos ames trouvent le repos eternel dans les bras du berger fidele",
    "le seigneur est le rocher des ages et nos vies sont baties sur lui",
    "la main de dieu trace des chemins dans les deserts de nos existences",
    "on se tient a la lisiere du miracle et la foi nous fait avancer",
    "la promesse du seigneur est une ancre jetee dans l'ocean de l'eternite",
    "nos ames sont des harpes dont dieu tire les plus belles melodies",
    "le sang de la croix a ecrit notre nom dans le livre de vie",
    "on marche sur les traces du maitre avec des sandales de paix aux pieds",
    "la grace est une rosee matinale qui couvre nos ames de fraicheur divine",
    "nos voix proclament la verite dans un monde qui a oublie le chemin",
    "le seigneur plante des jardins de joie dans les terres ravagees par le chagrin",
    "on est les sentinelles de l'aube qui attendent la lumiere du roi celeste",
    "la benediction du seigneur est un soleil qui ne se couche jamais sur nous",
    "nos prieres percent le voile entre le visible et l'invisible chaque nuit",
    "le seigneur deverse sa gloire comme la pluie sur les champs de nos coeurs",
    "on porte le flambeau de la foi a travers les tenebres de ce monde",
    "la grace efface les dettes de nos peches et restaure la joie du salut",
    "nos louanges sont des escaliers qui montent vers le trone de la grace eternelle",
    "le seigneur fait pousser des fleurs dans les crevasses de nos vies brisees",
    "on chante sa gloire car sa bonte est plus haute que les montagnes",
    "la lumiere de l'esprit eclaire les recoins les plus sombres de nos coeurs",
    "nos ames sont des vases d'argile remplis du tresor de sa presence",
    "le seigneur conduit nos pas sur les hauteurs quand le monde nous tire vers le bas",
    "on danse sur les ruines de nos anciennes prisons car les chaines sont brisees",
    "la grace est le souffle de vie qui ressuscite nos reves enfouis sous la terre",
    "nos coeurs sont des autels allumes par le feu sacre de sa presence",
    "le seigneur repand son huile sur nos tetes et nos coupes debordent de joie",
    "on est les pierres d'angle que le maitre batisseur pose avec precision divine",
    "la priere est une echelle qui relie la terre au ciel sans interruption",
    "nos voix unies sont un tonnerre de louange qui fait trembler le royaume des ombres",
    "le seigneur fait briller sa face sur nous et nous sommes transformes par sa gloire",
    "on marche dans la vallee de l'ombre et le berger nous guide avec douceur",
    "la grace est un fleuve qui deborde de ses rives et inonde nos vies",
    "nos ames chantent un cantique nouveau car le seigneur fait des merveilles chaque jour",
    "le sang de l'alliance est le sceau de notre heritage eternel dans les cieux",
    "on leve nos bannières de victoire car le combat est deja gagne par la croix",
    "la benediction divine couvre nos familles comme une tente dans le desert aride",
    "nos prieres sont des cles d'or qui ouvrent les tresors caches du royaume",
    "le seigneur fait germer l'esperance dans la terre aride de nos epreuves",
    "on est les porteurs de son message et la terre attend notre temoignage",
    "la grace nous soutient quand nos jambes flechissent sous le poids du chemin",
    "nos louanges sont parfumees comme l'encens qui monte devant le trone eternel",
    "le seigneur guerit les coeurs brises et panse les blessures de l'ame blessée",
    "on chante dans la fournaise car celui qui marche avec nous ne brule pas",
    "la lumiere de la parole est une lampe a nos pieds dans la nuit",
    "nos ames sont enracinees dans l'amour du pere comme le cedre dans le sol",
    "le seigneur fait pleuvoir la manne sur nos deserts quand la faim menace",
    "on danse avec la joie du pardon car nos peches sont effaces pour toujours",
    "la grace est le vent qui pousse nos voiles vers le port eternel",
    "nos coeurs sont des jardins ou l'esprit saint fait pousser les fruits du ciel",
    "le seigneur nous revet de la cuirasse de justice et du casque du salut",
    "on est les heritiers de la promesse faite a nos peres dans la foi",
    "la priere fervente ouvre les portes de bronze et brise les verrous de fer",
    "nos voix s'elevent comme des colombes vers le ciel de sa misericorde infinie",
    "le seigneur sculpte nos vies avec le ciseau de sa sagesse parfaite",
    "on marche ensemble car la route du ciel se parcourt en communion fraternelle",
    "la grace est la melodie que les anges chantent au-dessus de nos tetes",
    "nos ames sont des temples vivants ou reside la gloire du dieu tres-haut",
    "le seigneur est notre bouclier et rien ne peut nous atteindre sous son ombre",
    "on leve un chant de gratitude car sa fidelite se renouvelle chaque matin",
    "la benediction de dieu est un arbre de vie plante au bord des eaux",
    "nos prieres sont des fleches de lumiere lancees vers le coeur du pere celeste",
    "le seigneur fait danser les montagnes et les collines chantent devant sa face",
    "on est les ambassadeurs de la reconciliation dans un monde divise par la haine",
    "la grace nous transforme de gloire en gloire a l'image du fils bien-aime",
    "nos louanges creent un chemin dans le desert ou fleurissent les roses de saron",
    "le seigneur repond a nos cris avec la tendresse d'un pere qui aime ses enfants",
    "on chante car les murs de nos prisons s'ecroulent au son de la louange",
    "la lumiere du christ est un phare dans la tempete de ce monde agite",
    "nos ames trouvent le repos dans la certitude de ses promesses immuables",
    "le seigneur fait couler le lait et le miel dans la terre de nos destins",
    "on danse car le voile est dechire et la presence remplit le lieu saint",
    "la grace est le fondement sur lequel nos vies sont baties pour l'eternite",
    "nos coeurs sont des trompettes qui sonnent la victoire du roi des rois eternel",
    "le seigneur est notre heritage et notre part dans le pays des vivants",
    "on est les sarments attaches au cep veritable et nous portons du fruit abondant",
    "la priere est le pont qui enjambe l'abime entre nos faiblesses et sa puissance",
    "nos voix proclament que le tombeau est vide et que la mort est vaincue",
    "le seigneur ecrit nos noms sur la paume de sa main avec amour eternel",
    "on marche par la foi et chaque pas est une declaration de confiance en lui",
    "la grace est une source intarissable qui jaillit du rocher fendu pour nous",
    "nos ames sont des aigles qui montent vers les hauteurs portees par son souffle",
    "le seigneur fait de nos vallees des portes d'esperance et de nos larmes des perles",
    "on leve nos mains et la presence divine descend comme une colombe de paix",
    "la benediction couvre nos enfants et nos petits-enfants de generation en generation",
    "nos louanges sont des armes de lumiere dans le combat spirituel de chaque jour",
    "le seigneur renouvelle nos forces et nous courons sans nous lasser vers la victoire",
    "on est les temoins de sa resurrection et nos vies portent la marque de sa grace",
    "la lumiere de la grace transforme nos cicatrices en etoiles qui brillent pour sa gloire",
    "nos prieres sont des semences de foi qui porteront du fruit en leur saison",
    "le seigneur fait chanter les etoiles du matin et les fils de dieu crient de joie",
    "on danse avec les rachetés car le prix a ete paye sur la croix",
    "la grace est le parfum du ciel qui emplit nos sanctuaires de sa douceur",
    "nos coeurs sont des calices remplis du vin nouveau de sa presence divine",
    "le seigneur plante ses pieds sur la montagne et la terre tremble de joie",
    "on chante la fidelite de celui qui ne change pas malgre les saisons",
    "la priere est notre respiration spirituelle et la louange notre nourriture quotidienne",
    "nos ames sont des champs de ble dore par le soleil de sa grace",
    "le seigneur fait lever l'aurore de sa justice sur les nations dans l'obscurite",
    "on est les enfants du jour et la nuit n'a plus de pouvoir sur nous",
    "la grace est un ocean sans rivage ou nos peches sont engloutis pour toujours",
    "nos voix s'unissent en un seul chant qui traverse les frontieres et les cultures",
    "le seigneur place un chant de delivrance dans la bouche de ceux qui pleurent",
    "on marche dans la lumiere car les tenebres n'ont plus d'emprise sur nos vies",
    "la benediction de dieu est un fleuve de vie qui traverse nos generations",
    "nos louanges ouvrent les portes de bronze et brisent les verrous de fer devant nous",
    "le seigneur nous donne la victoire par notre seigneur et notre joie est complete",
    "on est les vaisseaux de sa misericorde appeles a repandre sa grace sur la terre",
    "la lumiere de sa face dissipe nos peurs comme le soleil dissipe la brume",
    "nos prieres sont des ponts de diamant entre notre faiblesse et sa toute-puissance",
    "le seigneur combat devant nous et derriere nous et la victoire est certaine",
    "on danse avec la liberte des enfants de dieu dans la joie du salut",
    "la grace est un jardin eternel ou fleurissent la paix la joie et l'amour",
    "nos coeurs sont des lyres accordees pour chanter les louanges du roi eternel",
    "le seigneur nous couvre de ses plumes et sous ses ailes nous trouvons refuge",
    "on chante car les chaines du peche sont tombees et la liberte regne en nous",
    "la priere du soir est une offrande parfumee devant le trone de la grace",
    "nos ames sont des torches allumees par le feu du saint-esprit qui brule",
    "le seigneur fait de nos deserts des jardins et de nos ruines des palais",
    "on est les sacrificateurs de la louange qui entrent dans le lieu tres saint",
    "la grace est le fil d'or qui tisse la tapisserie de nos destins eternels",
    "nos voix proclament sa souverainete sur les nations et les peuples de la terre",
    "le seigneur est notre part et notre calice et le sort qui nous est echu",
    "on leve un cri de joie car la promesse s'accomplit sous nos yeux emus",
    "la benediction du seigneur est un tresor cache dans le champ de notre foi",
    "nos louanges sont des vagues qui deferlent sur les rivages du ciel eternel",
    "le seigneur ecrit notre histoire avec l'encre de sa grace sur les pages du temps",
    "on marche avec assurance car la victoire de la croix est notre fondement",
    "la lumiere divine transperce nos tenebres et nos ombres deviennent des temoignages",
    "nos prieres sont des pierres precieuses posees sur le fondement de la foi",
    "le seigneur est le gardien de nos ames et le protecteur de nos jours",
    "on est les porteurs de l'arche de sa presence dans un monde qui a soif",
    "la grace du seigneur est notre chant du matin et notre berceuse du soir",
    "nos coeurs battent au rythme de sa grace comme un tambour de louange",
    "le seigneur fait briller sa lumiere dans nos tenebres et nous marchons sans crainte",
    "on danse avec les anges car le ciel et la terre celebrent sa gloire",
    "la redemption est le plus beau chapitre de l'histoire que dieu ecrit avec nous",
    "nos ames sont des fontaines de louange qui jaillissent de la source eternelle",
    "le seigneur tient nos vies dans sa main et personne ne peut nous arracher",
    "on chante la grace qui nous a trouves quand nous etions perdus dans la nuit",
    "la priere est l'aube de chaque jour et la louange est son crepuscule dore",
    "nos voix sont des instruments de paix dans un monde de bruit et de fureur",
    "le seigneur est notre lumiere et notre salut qui craindrons-nous dans cette vie",
    "on est les enfants de la promesse nes de l'esprit et appeles a la gloire",
    "la grace est notre heritage et la foi notre passeport vers le royaume celeste",
    "nos louanges font descendre la gloire et nos prieres font monter les miracles",
    "le seigneur deverse sa joie sur nos ames comme une cascade de lumiere pure",
    "on marche par la foi dans la certitude que ses promesses sont fideles toujours"
  ],
  bridges: [
    "on ferme les yeux et la presence de dieu nous enveloppe doucement",
    "dans le silence sacre nos ames trouvent le repos du seigneur",
    "le temps s'arrete dans la presence et la grace coule sur nous",
    "on respire la paix divine et nos coeurs trouvent enfin le repos",
    "la lumiere de dieu descend doucement et nos ames sont remplies",
    "on se tient dans le lieu tres saint et la gloire nous couvre",
    "le souffle de l'esprit caresse nos visages et nos larmes coulent",
    "nos mains levees sont des antennes qui captent la grace du ciel",
    "la presence de dieu est si dense qu'on peut presque la toucher",
    "on s'incline devant sa majeste et nos bouches restent sans mots",
    "le voile se dechire et la gloire du tres-haut nous inonde",
    "nos ames sont comme des cerfs qui soupirent apres les eaux vives",
    "la paix qui surpasse toute intelligence garde nos coeurs et nos pensees",
    "on laisse la grace faire son oeuvre dans le silence de nos ames",
    "le seigneur murmure a nos coeurs et nous reconnaissons sa voix douce",
    "nos prieres deviennent des larmes et nos larmes deviennent des louanges pures",
    "la gloire remplit le temple et on ne peut rester debout devant lui",
    "on depose nos couronnes aux pieds du roi des rois eternel",
    "le silence est rempli de sa presence et nos ames sont en paix",
    "nos coeurs battent au rythme de la grace qui coule du trone",
    "la lumiere divine perce les tenebres de nos doutes et nos peurs",
    "on est a genoux devant sa bonte et les mots nous manquent",
    "l'esprit intercede pour nous avec des gemissements inexprimables et profonds",
    "le seigneur essuie nos larmes et place un chant nouveau dans nos bouches",
    "nos ames trouvent leur repos dans les bras du pere celeste aimant",
    "la grace est un ocean et nous nageons dans sa profondeur infinie",
    "on leve les yeux et le ciel s'ouvre devant nos regards emus",
    "le temps s'arrete dans l'eternite de cet instant de communion sacree",
    "nos voix se taisent et laissent parler la presence du saint-esprit",
    "la paix de dieu coule comme un fleuve dans nos coeurs brises",
    "on respire la saintete de ce lieu et nos ames sont transformees",
    "le seigneur nous tient dans le creux de sa main avec tendresse",
    "nos larmes arrosent les semences de foi plantees dans nos coeurs",
    "la gloire descend comme une colombe et se pose sur nos epaules",
    "on est dans le lieu secret du tres-haut et sa presence nous suffit"
  ],
  choruses: [
    "on chante la gloire on chante la grace du seigneur tres-haut",
    "la lumiere de dieu eclaire nos pas et nos coeurs chaque jour",
    "on leve nos mains et la grace descend comme une pluie du ciel",
    "le seigneur est bon et sa misericorde dure a toujours pour nous",
    "on danse dans la joie de la redemption et de la grace pure",
    "la gloire du seigneur remplit nos coeurs et nos bouches de louange",
    "on chante alleluia car le roi des rois regne pour toujours",
    "la grace nous a sauvés et l'amour nous porte chaque jour",
    "on est les enfants de la lumiere et on brille pour sa gloire",
    "le seigneur combat pour nous et nous n'avons qu'a rester fermes",
    "on eleve le nom au-dessus de tout nom avec nos louanges",
    "la benediction du seigneur couvre nos vies comme un manteau de grace",
    "on marche dans la victoire car le seigneur a deja vaincu tout",
    "la grace est suffisante et sa puissance s'accomplit dans notre faiblesse",
    "on chante on danse on loue le seigneur de tout notre coeur",
    "le ciel et la terre proclament la gloire de notre dieu eternel",
    "on est libres on est sauvés par le sang de l'agneau precieux",
    "la lumiere brille dans les tenebres et les tenebres ne l'eteignent pas",
    "on leve un cri de victoire car le tombeau est vide ce matin",
    "le seigneur est notre berger et on ne manque de rien jamais",
    "on chante la fidelite de dieu d'age en age sans jamais cesser",
    "la grace coule comme un fleuve et nos ames sont desalterees enfin",
    "on est les rachetés de l'eternel et on le proclame avec joie",
    "le sang de jesus nous purifie de tout peche et toute souillure",
    "on danse devant le seigneur avec toute notre force et notre joie",
    "la gloire de dieu se leve sur nous comme le soleil du matin",
    "on marche on court on vole avec la force du saint-esprit en nous",
    "la benediction de dieu ne se mesure pas et deborde de nos vies",
    "on est les temoins de sa grace dans un monde qui a besoin",
    "le seigneur fait toutes choses nouvelles et nos vies en sont la preuve",
    "on chante la victoire de la croix qui a vaincu la mort",
    "la lumiere de l'esperance brille dans nos coeurs et eclaire le monde",
    "on leve les mains on baisse la tete et on adore notre roi",
    "le seigneur est notre rocher notre forteresse et notre delivrance ce soir",
    "on danse dans la grace on chante dans la gloire pour toujours",
    "la grace la grace la grace du seigneur nous suffit chaque jour",
    "on est portes par ses promesses et gardes par sa fidelite eternelle",
    "le ciel s'ouvre quand on loue et la gloire descend sur nous",
    "on chante avec les anges saint saint saint est le seigneur",
    "la redemption est notre chant et la grace notre melodie eternelle",
    "on marche dans la lumiere comme il est lui-meme dans la lumiere",
    "le seigneur nous aime d'un amour eternel et sa grace ne faillit pas",
    "on est les pierres vivantes et le seigneur batit son temple en nous",
    "la benediction coule la grace abonde et l'amour de dieu nous entoure",
    "on leve nos voix comme un seul coeur devant le trone de grace",
    "le sang precieux a parle et nous sommes rachetes pour toujours",
    "on danse on loue on crie victoire au nom de jesus notre roi",
    "la gloire du seigneur est notre heritage et notre part pour l'eternite",
    "on chante on pleure on rit dans la presence du dieu vivant",
    "le seigneur est fidele et ses promesses sont oui et amen pour nous",
    "on chante la victoire car les tenebres ne prevaudront jamais contre nous",
    "la grace est notre chant de guerre et la foi notre bouclier sacre",
    "on leve nos voix et les murs de nos prisons s'effondrent devant nous",
    "le seigneur est notre refuge et notre force un secours toujours present",
    "on danse dans la grace car le joug est brise et la liberte coule",
    "la lumiere du seigneur eclaire notre chemin et nos ames sont en paix",
    "on est les enfants du roi et notre heritage est la gloire celeste",
    "la benediction de dieu depasse nos prieres et nos reves les plus grands",
    "on chante la bonte du seigneur car elle dure de generation en generation",
    "le sang de jesus est notre victoire et la croix est notre trophee",
    "on marche dans la foi car le seigneur tient nos mains dans les siennes",
    "la grace nous entoure comme les eaux couvrent la mer sans limites",
    "on leve un chant d'adoration car le roi des cieux habite nos louanges",
    "le seigneur est notre bouclier notre epee et notre couronne de gloire",
    "on danse car les chaines sont tombees et la joie remplit nos coeurs",
    "la priere est notre arme et la louange est notre chant de victoire",
    "on est les flammes vivantes de sa presence dans un monde qui a froid",
    "le seigneur fait toutes choses belles et sa grace ne connait pas de fin",
    "on chante car le matin se leve apres la nuit la plus longue",
    "la gloire descend sur nous comme la rosee du matin sur les collines",
    "on leve nos mains vers le ciel et la pluie de grace tombe",
    "le seigneur est notre rocher et sur ce roc nous sommes inebranlables",
    "on est les heritiers de la promesse et la couronne nous attend la-haut",
    "la grace est notre histoire et la louange est notre avenir eternel",
    "on marche on court on vole dans la puissance du saint-esprit en nous",
    "le seigneur nous porte sur des ailes d'aigle au-dessus de chaque tempete",
    "on chante la redemption car le prix a ete paye et nous sommes libres",
    "la benediction du seigneur est sans mesure et sans condition pour ses enfants",
    "on est debout dans la grace et rien ne pourra nous faire tomber jamais",
    "la gloire de dieu est notre couronne et la grace notre vetement royal"
  ],
  vocabulary: {
    nouns: [
      "grace", "gloire", "lumiere", "priere", "louange",
      "benediction", "redemption", "salut", "foi", "esperance",
      "ame", "esprit", "ciel", "trone", "croix",
      "sang", "agneau", "berger", "temple", "autel",
      "encens", "parole", "promesse", "alliance", "heritage",
      "victoire", "delivrance", "liberte", "paix", "joie",
      "misericorde", "bonte", "fidelite", "saintete", "justice",
      "verite", "sagesse", "onction", "onction", "fleuve",
      "source", "semence", "moisson", "fruit", "vigne",
      "couronne", "sceptre", "etendard", "bouclier", "armure",
      "ange", "archange", "seraphim", "cherubin", "messager",
      "cantique", "hymne", "psaume", "chorale", "choeur",
      "aureole", "nimbe", "halo", "aura", "rayonnement",
      "onction", "bapteme", "communion", "eucharistie", "sacrement",
      "paradis", "eden", "jardin", "vigne", "olivier",
      "colombe", "aigle", "lion", "agneau", "brebis",
      "forteresse", "refuge", "abri", "sanctuaire", "tabernacle"
    ],
    verbs: [
      "louer", "adorer", "glorifier", "celebrer", "exalter",
      "elever", "proclamer", "temoigner", "benir", "consacrer",
      "prier", "interceder", "implorer", "supplier", "invoquer",
      "delivrer", "sauver", "racheter", "restaurer", "guerir",
      "pardonner", "purifier", "sanctifier", "oindre", "reveler",
      "eclairer", "guider", "proteger", "couvrir", "envelopper",
      "fortifier", "renouveler", "transformer", "ressusciter", "relever",
      "combler", "repandre", "deverser", "inonder", "remplir",
      "chanter", "danser", "crier", "acclamer", "magnifier",
      "marcher", "courir", "voler", "monter", "s'elever",
      "briller", "resplendir", "irradier", "rayonner", "flamboyer",
      "trembler", "fremir", "vibrer", "tressaillir", "frissonner",
      "embrasser", "accueillir", "recevoir", "adopter", "heberger",
      "nourrir", "abreuver", "rassasier", "sustenter", "combler",
      "affermir", "consolider", "cimenter", "ancrer", "enraciner",
      "proclamer", "declarer", "annoncer", "prophetiser", "reveler"
    ],
    adjectives: [
      "divin", "sacre", "saint", "celeste", "eternel",
      "glorieux", "beni", "consacre", "sanctifie", "oint",
      "fidele", "misericordieux", "bienveillant", "gracieux", "juste",
      "pur", "immacule", "radieux", "lumineux", "resplendissant",
      "puissant", "souverain", "majestueux", "omnipotent", "invincible",
      "infini", "incommensurable", "insondable", "ineffable", "indicible",
      "redempteur", "liberateur", "restaurateur", "consolateur", "protecteur",
      "triomphant", "victorieux", "vainqueur", "glorifie", "exalte",
      "paisible", "serein", "tranquille", "bienheureux", "comble",
      "fervent", "ardent", "devot", "pieux", "reconnaissant",
      "celeste", "angelique", "seraphique", "paradisiaque", "edenique",
      "transcendant", "sublime", "merveilleux", "prodigieux", "miraculeux",
      "inalterable", "incorruptible", "imperissable", "indestructible", "immuable",
      "clement", "compatissant", "indulgent", "magnamine", "charitable",
      "humble", "modeste", "simple", "depouille", "austere",
      "rayonnant", "eclatant", "flamboyant", "embrase", "incandescent"
    ]
  }
};
