module.exports = {
  themes: [
    "rue",
    "succes",
    "lutte",
    "quartier",
    "pouvoir",
    "respect",
    "ambition",
    "fierte",
    "argent",
    "survie",
    "hustle",
    "flow",
    "authenticite",
    "legende"
  ],
  openers: [
    "Je Viens De La Ou Personne Ne Croyait En Nous",
    "Les Rues M'ont Forge Et Le Beton M'a Eleve",
    "Ils Parlent De Moi Mais Ils Ne Savent Rien",
    "Je Suis Debout Malgre Tout Ce Qu'ils Ont Dit",
    "Le Micro Est Mon Arme Et Les Mots Mon Bouclier",
    "J'ai Grandi Dans L'ombre Maintenant Je Brille Fort",
    "Chaque Cicatrice Raconte Une Bataille Que J'ai Gagnee",
    "La Nuit Tombe Sur Le Quartier Mais Je Reste Eveille",
    "Personne Ne M'a Donne Ce Que J'ai Construit Seul",
    "Je Sors Du Beton Comme Une Fleur De L'asphalte",
    "Mon Flow Coule Comme Un Fleuve Sans Barrage",
    "Ils Voulaient Me Voir Tomber Mais Je Me Suis Releve",
    "Du Bas De L'immeuble Jusqu'au Sommet De La Ville",
    "Je Porte Le Poids Du Quartier Sur Mes Epaules",
    "Les Lumieres De La Ville Eclairent Mon Chemin",
    "J'ai Transforme La Douleur En Or Pur Ce Soir",
    "Le Bitume Est Mon Royaume Et La Nuit Mon Alliee",
    "Chaque Jour Est Un Combat Que Je Refuse De Perdre",
    "Je Marche La Tete Haute Dans Les Rues Qui M'ont Vu Grandir",
    "Mon Histoire Commence La Ou Les Autres Ont Abandonne",
    "Les Blocs De Beton Sont Ma Scene Et Mon Decor",
    "J'ecris Mon Destin Avec L'encre De Mes Erreurs",
    "Rien Ne M'arrete Quand Le Beat Tombe Comme Ca",
    "Je Suis La Voix De Ceux Qu'on N'ecoute Jamais",
    "Le Succes N'a Pas De Raccourci Je Le Sais Bien",
    "Depuis Le Hall D'immeuble Jusqu'aux Scenes Du Monde",
    "Mes Rimes Touchent Plus Fort Que N'importe Quelle Arme",
    "Je Ne Demande Pas La Permission De Briller",
    "Le Quartier M'a Tout Appris Y Compris La Survie",
    "Ils Ont Ferme Les Portes Mais J'ai Pris Les Fenetres",
    "Chaque Mot Que Je Pose Est Une Balle De Verite",
    "Je Suis Ne Dans La Galere Mais Je Vise Les Etoiles",
    "La Rue M'a Forge L'acier De Mon Caractere",
    "Mon Nom Resonne Dans Chaque Mur De La Cite",
    "J'ai Fait De Mes Cauchemars Un Empire De Beats",
    "Le Monde Me Regarde Et Je Ne Baisse Pas Les Yeux",
    "Chaque Rime Est Un Pas De Plus Vers Le Sommet",
    "Je Suis Le Fils Du Beton Et De La Nuit",
    "Les Vrais Savent D'ou Je Viens Et Ou Je Vais",
    "Mon Parcours Est Ecrit Dans La Sueur Et Le Sang",
    "Depuis La Cage D'escalier J'ai Vu Le Monde Changer",
    "Je Transforme Le Plomb De La Rue En Or Musical",
    "Chaque Defaite M'a Rendu Plus Fort Pour La Suite",
    "Le Beat Pulse Dans Mes Veines Comme Du Feu Liquide",
    "Je Suis La Preuve Que Le Quartier Produit Des Rois",
    "Mes Mots Sont Des Diamants Tailles Dans Le Beton",
    "La Rue Ne Pardonne Pas Mais Elle M'a Tout Donne",
    "Je Suis Passe De L'ombre A La Lumiere Sans Pitie",
    "Chaque Verse Que Je Crache Porte Le Poids Du Reel",
    "Le Silence De La Nuit M'inspire Plus Que Le Bruit"
  ],
  verses: [
    "je compte les billets mais je n'oublie pas d'ou je viens",
    "le beton sous mes pieds c'est ma terre natale a moi",
    "ils parlent dans mon dos mais jamais face a moi",
    "chaque jour je me bats pour ceux que j'ai laisses derriere",
    "la rue m'a appris que la confiance se merite ici",
    "je pose mes rimes comme des briques pour construire mon empire",
    "les faux freres disparaissent quand la galere s'installe",
    "mon flow est une lame qui tranche a travers le silence",
    "j'ai grandi entre les murs gris et les reves dores",
    "personne ne m'a tendu la main j'ai grimpe tout seul",
    "les sirenes de la nuit sont la bande son de ma vie",
    "je transforme chaque obstacle en marche vers le haut",
    "le quartier dort mais mon stylo reste eveille",
    "je me souviens des jours ou le frigo etait vide",
    "la reussite a un gout different quand tu pars de rien",
    "mes mots sont graves dans le marbre de la realite",
    "je ne fais pas de musique je fais des temoignages",
    "chaque soir je regarde les etoiles depuis le bloc",
    "les promesses de la rue s'evaporent comme la fumee",
    "j'ai le coeur dur mais les yeux grands ouverts sur le monde",
    "ils veulent mon respect mais ils n'ont rien fait pour le meriter",
    "la nuit me connait mieux que le jour ne me verra",
    "je marche sur le fil entre le reve et la galere",
    "mon micro est le seul ami qui ne m'a jamais trahi",
    "les murs du quartier sont tatoues de nos histoires",
    "je suis parti de zero maintenant ils comptent mes zeros",
    "chaque rime est un cri que le monde refuse d'entendre",
    "le bitume colle a mes semelles comme mon passe",
    "j'ai appris a voler avant d'apprendre a marcher droit",
    "les tours en bas c'est la que j'ai appris la vie",
    "je ne mendie pas le succes je le prends de force",
    "mon ombre est la seule qui me suit sans me juger",
    "la faim dans le ventre nourrit le feu dans le coeur",
    "je pese mes mots comme un joaillier pese ses diamants",
    "ils ont ri quand j'ai commence maintenant ils copient mon style",
    "le temps est un luxe que la rue ne m'a pas offert",
    "je grave mon nom dans l'histoire avec un stylo",
    "les murs ont des oreilles et moi j'ai des choses a dire",
    "chaque pas dans la nuit est un pas de plus vers la lumiere",
    "mon coeur est blinde mais mes rimes percents les armures",
    "la galere forge le caractere mieux que l'ecole le fera",
    "je viens de la ou les ascenseurs ne marchent jamais",
    "mes cicatrices sont les preuves que j'ai survecu ici",
    "le respect se gagne sur le terrain pas dans les mots",
    "je suis le phenix qui renait des cendres du ghetto",
    "les reves n'ont pas de frontiere meme dans le beton",
    "j'ai tourne le dos a la facilite pour choisir l'honneur",
    "mon parcours est un labyrinthe dont je connais la sortie",
    "chaque echec m'a enseigne une lecon que l'ecole ne donnait pas",
    "le micro tremble quand je m'approche avec mes verites",
    "je porte les cicatrices de la ville sur ma peau",
    "la nuit tombe et les masques tombent avec elle aussi",
    "j'ai construit ma couronne avec les pierres qu'ils m'ont lancees",
    "les vrais reconnaissent les vrais dans l'obscurite totale",
    "je ne recule jamais meme face au mur le plus haut",
    "mon histoire est ecrite avec l'encre de la souffrance",
    "les reverberes sont les seules etoiles de mon quartier",
    "je suis le produit du beton de la sueur et des larmes",
    "chaque barre que je crache est une victoire sur le destin",
    "le monde m'a donne des murs j'en ai fait des ponts",
    "les faux sourires ne trompent plus mes yeux aguerris",
    "je marche droit malgre les courbes de la route",
    "mon flow est un tsunami qui balaie tout sur son passage",
    "la verite me brule les levres mais je la crache quand meme",
    "j'ai mesure la distance entre le reve et le sol",
    "les tours d'en bas sont les gratte-ciels de nos espoirs",
    "je ne suis pas un produit du systeme je suis son erreur",
    "chaque nuit passee dehors m'a rapproche de mon but final",
    "le silence du quartier cache plus de drames que de paix",
    "je suis la flamme qui refuse de s'eteindre dans le vent",
    "mes rimes sont des lames qui decoupent les faux semblants",
    "la reussite est un plat qui se mange seul parfois",
    "j'ai transforme la colere en combustible pour mon art",
    "les murs de ma cite sont les pages de mon livre",
    "je suis le roi d'un royaume que personne ne voulait",
    "chaque souffle est une priere pour ceux restes en bas",
    "le beton ne pleure pas mais moi je me souviens",
    "j'ai grandi trop vite dans un monde trop lent",
    "les billets passent mais le respect lui reste pour toujours",
    "je ne suis pas parfait mais je suis authentique au moins",
    "mon stylo saigne la verite sur des feuilles blanches",
    "la rue est une ecole dont on ne sort jamais diplome",
    "je suis le resultat de mille nuits sans sommeil",
    "chaque defaite a plante une graine de victoire en moi",
    "les mots sont mes soldats et le beat est mon champ",
    "j'ai appris le prix de la loyaute dans la douleur",
    "le monde tourne mais le quartier reste ma boussole",
    "je suis ne avec rien et je mourrai avec tout",
    "les fenetres eclairees des tours sont nos constellations",
    "chaque reve ecrase par la realite revient plus fort",
    "le bitume garde la memoire de tous nos pas perdus",
    "je ne cherche pas la gloire je cherche la verite",
    "mes mots portent le poids de ceux qui n'ont pas de voix",
    "la nuit est mon studio et la lune mon projecteur",
    "j'ai paye le prix fort pour chaque once de respect",
    "le succes ne change pas l'homme il revele sa nature",
    "je suis le loup qui a survecu a tous les hivers",
    "chaque matin dans le miroir je vois un survivant",
    "les portes fermees m'ont appris a construire des echelles",
    "le froid du beton m'a forge un coeur d'acier trempe",
    "je ne lache rien meme quand tout le monde me lache",
    "mon ame est un champ de bataille ou je gagne chaque jour",
    "les cris de la cite resonnent dans chaque mesure",
    "j'ai ecrit ma legende avec le sang de mes erreurs",
    "le respect ne s'achete pas il se conquiert au quotidien",
    "je suis debout quand le monde voudrait me voir a genoux",
    "chaque barre est un coup de poing dans le silence",
    "les murs de beton sont les temoins de mon ascension",
    "j'ai trop vu pour faire semblant que tout va bien",
    "le micro est mon arme et la scene mon tribunal",
    "je suis le messager de ceux que la societe a oublies",
    "chaque nuit je me bats contre mes propres demons",
    "les rues sales m'ont appris la beaute de la lutte",
    "j'ai grandi a l'ombre des tours qui touchaient le ciel",
    "le silence de la cite cache des cris que personne n'entend",
    "je suis la voix du beton qui refuse de se taire",
    "mes rimes sont des flammes qui brulent les mensonges",
    "chaque jour sans victoire est un jour de plus de preparation",
    "la nuit est mon alliee et le beat mon bouclier",
    "j'ai survecu a tout ce qui devait me detruire",
    "le quartier est un ring et la vie est le combat",
    "je ne fais confiance qu'a ceux qui ont connu la galere",
    "mes yeux ont vu trop de choses pour pleurer encore",
    "la verite est crue mais c'est la seule monnaie que j'accepte",
    "j'ai le flow des ruelles et l'ambition des avenues",
    "chaque mot que je pose est une brique de mon edifice",
    "le monde me doit rien mais je vais tout lui prendre",
    "je suis le diamant brut que la pression a faconne",
    "les lampadaires sont mes projecteurs quand je rappe la nuit",
    "j'ai appris a lire le monde avant de lire les livres",
    "le beton ne ment pas il garde toutes nos traces",
    "je suis le produit d'une generation qu'on a sous-estimee",
    "chaque respiration est un acte de resistance ici",
    "les reves des tours montent plus haut que les ascenseurs",
    "j'ai forge ma couronne dans le feu de l'adversite",
    "le temps est mon ennemi mais la patience est mon arme",
    "je ne plie pas face a la tempete je deviens la tempete",
    "mes mots sont des pierres lancees contre les murs du systeme",
    "chaque soir dans le quartier une nouvelle histoire commence",
    "la rue est dure mais elle ne m'a jamais menti au moins",
    "j'ai mis mon ame dans ce micro pour ne plus la perdre",
    "le beat resonne dans les couloirs comme un coeur de beton",
    "je suis le fils de la nuit et l'ennemi du silence",
    "les murs tagges racontent mieux l'histoire que les manuels",
    "j'ai transforme les insultes en motivation pour demain",
    "chaque pas sur le bitume est un pas de plus vers moi",
    "le respect dans la rue n'a pas de prix ni de monnaie",
    "je suis la en chair et en os pas juste des paroles",
    "mes ombres me suivent mais je marche vers la lumiere",
    "la galere c'est l'universite de la vie reelle",
    "j'ai les poches vides mais l'esprit plein de projets",
    "le monde d'en haut ne voit pas le monde d'en bas",
    "je suis un guerrier du quotidien arme de mes rimes",
    "chaque larme versee dans l'ombre nourrit ma force interieure",
    "les jours se suivent mais ne se ressemblent jamais ici",
    "j'ai le feu sacre qui brule dans les veines du quartier",
    "le beton est froid mais mes mots rechauffent les ames",
    "je suis le survivant d'une guerre que personne ne declare",
    "mes yeux sont des cameras qui filment la realite crue",
    "chaque rime est une cicatrice transformee en diamant",
    "la nuit porte les secrets que le jour ne veut pas voir",
    "j'ai construit mon trone avec les decombres de mes echecs",
    "le flow ne s'achete pas il se vit dans chaque cellule",
    "je suis le bruit que fait le silence quand il se rebelle",
    "les tours sont nos montagnes et les parkings nos vallees",
    "j'ai marche dans la boue pour meriter les etoiles",
    "chaque battement de mon coeur pulse au rythme du quartier",
    "la verite sort de ma bouche comme la lave d'un volcan",
    "je ne mendie pas les applaudissements je les arrache",
    "mes mots traversent les murs comme des fantomes de verite",
    "le ciel est le meme pour tous mais la vue differe",
    "j'ai vecu chaque mot que je pose sur ce beat",
    "chaque jour est un round de plus dans le combat",
    "les lumieres de la ville ne brillent pas pour tout le monde",
    "je suis le produit final d'une equation impossible",
    "le beton est ma toile et les mots sont ma peinture",
    "j'ai fait de chaque non un tremplin vers le oui",
    "mes reves sont des plans de bataille traces dans la nuit",
    "la rue t'oublie vite si tu ne laisses pas ta marque",
    "je suis le gardien des histoires que personne ne raconte",
    "chaque verse est un chapitre de l'epopee du beton",
    "le monde me testait mais je n'ai jamais craque non",
    "j'ai les mains calleuses de ceux qui batissent leur propre chemin",
    "les etoiles du quartier brillent differemment des autres",
    "je suis la preuve vivante que le beton peut fleurir",
    "chaque nuit blanche m'a rapproche de mon reve eveille",
    "le micro ne ment jamais il amplifie la verite",
    "j'ai le regard de ceux qui ont traverse la tempete",
    "mes pas resonnent dans les halls comme des tambours de guerre",
    "la fierte ne se vend pas elle se porte sur le visage",
    "je suis le phoenix du bitume qui renait chaque matin",
    "chaque souffle de vent dans la cite porte nos prieres",
    "le succes est un marathon et je ne m'essouffle jamais",
    "j'ai grave mon histoire dans le beton arme de la cite",
    "les nuits du quartier ont forge l'acier de mon regard",
    "je suis ne pour regner sur les beats de la nuit",
    "chaque coin de rue est un chapitre de mon existence",
    "le monde peut trembler je reste ancre dans mes racines",
    "j'ai fait de la douleur un carburant pour mon ascension",
    "mes mots percent les murs comme des balles de verite pure",
    "la pluie sur le beton lave les traces mais pas les souvenirs",
    "j'ai le flow qui coule comme le sang dans les veines du quartier",
    "les murs gris sont ma toile et chaque rime est un coup de pinceau",
    "je suis le produit de nuits blanches et de matins sans pitie",
    "chaque billet que je gagne porte le poids de mille sacrifices",
    "la cite dort mais les reves de ses enfants restent eveilles",
    "j'ai mis ma douleur en musique et elle est devenue de l'or",
    "le beton sous mes pieds tremble quand je lache mes rimes dessus",
    "les faux amis disparaissent comme la brume au lever du soleil",
    "j'ai la faim des loups qui chassent meme par les nuits les plus froides",
    "le quartier m'a donne des ailes faites de beton et de reves",
    "mes cicatrices sont des medailles que la vie m'a donnees",
    "la nuit est ma confidente et le micro mon journal intime",
    "j'ai construit mon empire avec des briques que personne ne voulait",
    "les couloirs de l'immeuble resonnent de mes premiers essais de rime",
    "le monde m'a dit non alors j'ai cree mon propre oui",
    "je suis le gardien des secrets que le beton n'a jamais reveles",
    "chaque defaite m'a donne une raison de me relever plus fort",
    "les tours grises sont les piliers de mon temple interieur sacre",
    "j'ai le regard de ceux qui ont traverse le desert sans eau",
    "le bitume garde les empreintes de ceux qui ont ose marcher",
    "mes rimes sont des ponts entre le monde d'en bas et les etoiles",
    "la faim dans le ventre est le meilleur moteur qui existe",
    "j'ai transforme le plomb de mes echecs en or de victoires",
    "le quartier est un livre et chaque mur est une page ecrite",
    "les nuits de galere ont forge une armure autour de mon coeur",
    "j'ai la voix de ceux qui mangent le beton pour petit dejeuner",
    "le respect ne tombe pas du ciel il se ramasse dans la boue",
    "mes mots sont des graines plantees dans le sol dur du ghetto",
    "la lumiere du lampadaire est la seule etoile de ma rue sombre",
    "j'ai la patience des pierres et la force des rivieres souterraines",
    "le temps m'a appris que le succes est un marathon sans fin",
    "les rues etroites m'ont enseigne a penser plus large que les tours",
    "j'ai mis toute ma vie dans ce flow sans rien garder",
    "le beton ne pardonne pas mais il respecte ceux qui tiennent debout",
    "mes yeux ont vu le pire et mes mots montrent le meilleur",
    "la cite est un volcan dont les rimes sont la lave brulante",
    "j'ai grandi entre les murs mais mon esprit n'a pas de limites",
    "le silence du quartier a minuit est plus lourd que le beton",
    "mes pas sur le trottoir sont des beats que la rue reconnait",
    "la galere est un professeur severe mais ses lecons sont eternelles",
    "j'ai le sang du quartier et les reves d'un monde meilleur",
    "le micro est le seul temoin de mes nuits les plus sombres",
    "les fenetres eclairees sont les yeux d'un immeuble qui ne dort jamais",
    "j'ai forge mes mots dans le feu de mille nuits d'insomnie",
    "le beton a des oreilles et il ecoute mes confessions nocturnes",
    "mes rimes sont des flambeaux qui eclairent les couloirs obscurs",
    "la rue est un miroir qui montre ce que les autres cachent",
    "j'ai la precision des horlogers quand je pose mes mots sur le beat",
    "le quartier est un ring ou chaque jour est un nouveau round",
    "les murs tagges sont les journaux de notre generation oubliee",
    "j'ai transforme la colere du ventre vide en vers pleins de sens",
    "le temps passe mais le quartier garde ses blessures comme des tresors",
    "mes mots sont le ciment qui repare les fissures du beton",
    "la nuit dans la cite a plus d'histoires que mille bibliotheques",
    "j'ai le coeur trempe dans l'acier des nuits passees a ecrire",
    "le succes sent bon mais il a le gout sale de la sueur",
    "les escaliers de l'immeuble sont les marches de ma legende personnelle",
    "j'ai la memoire du beton qui n'oublie jamais une trace de pas",
    "le flow est mon passeport pour quitter le quartier sans le trahir",
    "mes yeux ont photographie chaque fissure de ces murs gris tristes",
    "la pluie dans le quartier tombe differemment elle pese plus lourd ici",
    "j'ai le souffle des marathoniens qui courent meme sans ligne d'arrivee",
    "le beton est mon berceau et le micro est mon destin sacre",
    "les nuits de garde dans le hall m'ont appris la patience vraie",
    "j'ai transforme les cris du quartier en hymnes de liberation",
    "le respect se porte sur le visage pas dans les poches percees",
    "mes rimes sont des bullets qui traversent les gilets de l'ignorance",
    "la cite est un ecosysteme ou seuls les plus forts survivent",
    "j'ai le regard aiguise de ceux qui ne dorment que d'un oeil",
    "le beat resonne dans les caves comme un coeur enterre vivant",
    "les murs de ma chambre ont entendu plus de rimes que de prieres",
    "j'ai la force des racines qui fissurent le beton pour respirer",
    "le quartier m'a donne un accent et un regard que rien n'efface",
    "mes cicatrices sont la preuve que j'ai vecu plus fort que les autres",
    "la nuit est un studio a ciel ouvert pour ceux qui ecoutent",
    "j'ai le feu des braises qui ne s'eteignent jamais completement",
    "le beton se souvient de chaque larme qu'on a versee sur lui",
    "les tours sont des temoins silencieux de notre histoire jamais ecrite",
    "j'ai transforme le bruit des sirenes en melodie pour mes couplets",
    "le micro tremble pas par peur mais par la puissance de mes mots",
    "mes mains calleuses temoignent d'un travail que personne ne voyait avant",
    "la rue est ma mere et le beton est mon pere adoptif",
    "j'ai le rythme des nuits sans sommeil grave dans les os",
    "le quartier ne m'a pas choisi c'est moi qui l'ai adopte",
    "les ombres de la cite sont des fantomes de ceux partis trop tot",
    "j'ai le vocabulaire de la rue et la syntaxe des survivants",
    "le flow circule dans mes veines comme l'eau dans les canalisations",
    "mes rimes sont des poings fermes contre les portes fermees du systeme",
    "la galere m'a appris a compter les centimes et les rimes",
    "j'ai le pas lourd de ceux qui portent le monde sur le dos",
    "le beton est un tamis qui separe les faibles des guerriers",
    "les reverberes clignotent comme des signaux en morse du quartier vivant",
    "j'ai transforme chaque insulte en combustible pour la machine a rimes",
    "le silence de la cite cache des volcans prets a exploser demain",
    "mes yeux ont scanne chaque recoin de ces rues sans pitie",
    "la nuit tombe et les masques avec elle dans les caniveaux gris",
    "j'ai le coeur blinde comme les portes des caves de l'immeuble",
    "le quartier m'a tatoue son histoire sur la peau de mon ame",
    "les pas dans le hall resonnent comme des battements de tambour sacre",
    "j'ai grandi trop vite mais je n'ai pas vieilli pour autant",
    "le beton ne pleure pas mais ses fissures parlent de douleur",
    "mes rimes sont des missiles guides par la precision de mon vecu",
    "la cite est un terrain mine et je danse entre les bombes",
    "j'ai le sang froid de ceux qui ont regarde le vide en face",
    "le micro est ma bequille quand le monde me met a genoux",
    "les toits de la cite sont les seuls sommets que je connais",
    "j'ai la memoire longue de ceux qui n'oublient jamais une trahison",
    "le beton est mon encrier et le trottoir est mon parchemin",
    "mes mots tombent comme des marteaux sur l'enclume de la realite",
    "la rue m'a donne un diplome que l'ecole ne delivre jamais",
    "j'ai forge mon caractere dans les flammes de l'adversite quotidienne",
    "le quartier est un orchestre et chaque bruit est un instrument",
    "les fissures dans les murs sont les rides de notre quartier age",
    "j'ai la tenacite des herbes qui poussent entre les dalles grises",
    "le flow est mon bouclier et la rime est mon epee tranchante",
    "mes nuits dans le quartier m'ont donne plus de sagesse que les livres",
    "la pluie nocturne sur le beton chante une melodie que je connais",
    "j'ai le pas des survivants qui marchent meme quand la route s'arrete",
    "le respect dans le quartier vaut plus que l'or dans les coffres",
    "les murs de la cite ont plus de verite que les journaux du matin",
    "j'ai transforme mon histoire en lecon pour ceux qui montent apres moi",
    "le beton est mon miroir il me renvoie toujours la verite crue",
    "mes rimes creusent des tunnels sous les murs de l'indifference du monde",
    "la cite est une jungle et je suis le lion qui ne recule pas",
    "j'ai les poings serres de ceux qui se battent pour chaque centimetre",
    "le micro amplifie ce que le silence du quartier a etoffe en moi",
    "les traces de pas sur le beton sont la carte de nos combats",
    "j'ai la vision des aigles qui voient tout depuis le toit de la tour",
    "le quartier est un creuset ou le feu de la vie nous fond",
    "mes mots sont des torches qui brulent dans la nuit de l'oubli",
    "la galere est un ocean et mes rimes sont le radeau solide",
    "j'ai le souffle des coureurs de fond qui ne s'arretent jamais",
    "le beton est un tombeau pour les reves des faibles seulement",
    "les escaliers de la tour sont l'echelle de ma legende en construction",
    "j'ai la fierte gravee dans le regard que personne ne peut baisser",
    "le flow est une riviere souterraine qui remonte quand le beat appelle",
    "mes cicatrices brillent dans le noir comme des etoiles sur le beton",
    "la nuit du quartier est un livre ouvert pour ceux qui savent lire",
    "j'ai le coeur des soldats qui se battent sans attendre de medaille",
    "le beton m'a tout pris et m'a tout rendu au centuple",
    "les murs gris sont mes pages blanches et mes rimes les encres",
    "j'ai transforme les pierres qu'ils m'ont jetees en fondations de mon empire",
    "le quartier vit dans mes veines comme un battement qui ne faiblit pas",
    "mes pas sur le bitume ecrivent l'histoire que personne ne racontera",
    "la rue est un professeur qui ne donne jamais de vacances a personne"
  ],
  bridges: [
    "on a traverse l'enfer pour meriter notre paradis",
    "le quartier ne dort jamais et moi non plus",
    "entre la lumiere et l'ombre j'ai choisi ma voie",
    "les vrais savent ce que ca coute de rester debout",
    "je n'ai pas choisi cette vie mais je l'ai dominee",
    "le beton a des fissures et c'est la que la lumiere entre",
    "chaque cicatrice me rappelle pourquoi je ne lache rien",
    "le monde nous regarde et on ne baisse pas les yeux",
    "entre le reve et la realite il y a le travail",
    "la rue t'apprend des lecons que l'ecole ne donne pas",
    "on a grandi trop vite dans un monde trop cruel",
    "le respect ne se demande pas il s'impose par les actes",
    "entre les tours de beton le ciel reste le meme",
    "la verite fait mal mais le mensonge fait pire",
    "on a construit des empires avec des miettes de pain",
    "le silence de la nuit cache les cris du quartier",
    "entre la chute et le vol il n'y a qu'un battement d'ailes",
    "les murs ont des yeux et les halls ont des oreilles",
    "on ne nait pas roi on le devient par la lutte",
    "le feu interieur brule plus fort que le froid dehors",
    "entre le premier pas et le sommet il y a mille nuits",
    "la fierte est le seul bijou que la rue ne vole pas",
    "on a ecrit l'histoire avec des stylos trempes dans le reel",
    "le beat resume tout ce que les mots ne disent pas",
    "entre le beton et les etoiles il y a mon ambition",
    "la nuit est longue mais l'aube finit toujours par venir",
    "on ne mesure pas un homme a sa chute mais a sa remontee",
    "le quartier m'a tout pris mais il m'a tout rendu aussi",
    "entre hier et demain il y a le combat d'aujourd'hui",
    "la force vient de la ou on ne l'attend pas",
    "on avance dans le noir en suivant le son du beat",
    "le respect est la monnaie de ceux qui n'ont rien d'autre",
    "entre les lignes de mes rimes se cache ma verite",
    "la rue est un miroir qui ne ment jamais a personne",
    "on est les architectes de notre propre legende urbaine"
  ],
  choruses: [
    "je viens du beton mais je vise les etoiles",
    "le quartier dans le coeur et le monde dans les mains",
    "on monte on monte on ne redescendra jamais",
    "je suis le roi de mon destin le maitre de mon ame",
    "les rues m'ont forge je suis plus dur que l'acier",
    "rien ne m'arrete quand le beat pulse dans mes veines",
    "du bas de l'immeuble jusqu'au toit du monde",
    "je brille dans le noir comme un diamant du beton",
    "le respect avant l'argent la famille avant le reste",
    "je ne recule jamais face a rien ni face a personne",
    "on a grandi ensemble et on va regner ensemble",
    "mon flow est une arme que rien ne peut arreter",
    "le quartier est fier et moi je porte son drapeau",
    "je suis la voix des tours et l'echo du beton",
    "on avance sans relache jusqu'a ce qu'on touche le ciel",
    "le beton m'a fait naitre le micro m'a fait vivre",
    "je transforme la boue en or avec mes mots",
    "on ne lache rien on ne recule devant rien",
    "je suis debout et je resterai debout quoi qu'il arrive",
    "le monde est a nous si on ose le prendre",
    "mes mots sont des armes et le beat est mon bouclier",
    "je represente la rue et la rue est en moi",
    "on a traverse le feu maintenant on est incassables",
    "le succes a un gout de victoire sur le destin",
    "je suis le produit du ghetto et la fierte du quartier",
    "on ecrit l'histoire avec nos mains pleines de beton",
    "le micro tremble quand je lache ma verite dessus",
    "je porte la cite sur mon dos comme un atlas",
    "on a la rage de vaincre dans le sang depuis toujours",
    "le beton est notre berceau et le ciel notre destination",
    "je ne suis pas la pour plaire je suis la pour regner",
    "les vrais reconnaissent les vrais c'est la loi du quartier",
    "on avance toujours meme quand le chemin est sombre",
    "le flow coule dans mes veines plus fort que le sang",
    "je suis indestructible forge par les epreuves de la rue",
    "on a la dalle et rien ne peut nous rassasier",
    "le quartier m'a tout donne je lui dois tout en retour",
    "je brule les etapes comme je brule les beats",
    "on ne mendie pas notre place on la prend de force",
    "le monde nous sous-estime et c'est notre plus grande force",
    "je suis le tonnerre qui gronde avant la tempete du changement",
    "les murs de beton tremblent quand je prends le micro",
    "on est la generation qui refuse de se taire",
    "le beat pulse comme le coeur du quartier la nuit",
    "je transforme les cailloux du beton en pierres precieuses",
    "on est nes dans la galere on mourra dans la gloire",
    "le respect se voit dans les yeux pas dans les mots",
    "je suis le gardien du temple sacre de la rime",
    "on a la force de ceux qui n'avaient rien a perdre",
    "le quartier vit a travers moi et je vis pour lui",
    "je suis le beton arme que rien ne peut fissurer jamais",
    "on regne sur les beats comme des rois sur leur trone d'acier",
    "le flow est une tempete et je suis son oeil implacable",
    "je porte le quartier comme un tatouage sur le coeur sacre",
    "on est la voix du beton qui resonne dans tout le pays",
    "le micro est mon sceptre et la scene est mon royaume",
    "je suis le feu qui brule dans les veines de la cite",
    "on avance comme une armee que rien ne peut arreter jamais",
    "le beton forge les diamants et je suis la preuve vivante",
    "je suis le survivant le guerrier le roi du bitume noir",
    "on lache les rimes comme des bombes sur le silence du monde",
    "le quartier est immortel et je suis sa voix eternelle",
    "je ne plie pas je ne romps pas je suis le beton pur",
    "on est les architectes de notre gloire batie sur le neant",
    "le flow tranche comme une lame aiguisee par mille nuits froides",
    "je suis la legende que le beton a enfantee pour le monde",
    "on marche sur les cendres et on construit des palais dessus",
    "le beat est notre hymne et la rime notre priere collective",
    "je suis le phoenix du quartier qui renait plus fort chaque fois",
    "on est les loups du beton et la nuit est notre territoire",
    "le respect coule dans mes veines comme le flow dans mes rimes",
    "je suis debout sur les ruines et je regarde le monde d'en haut",
    "on transforme le beton en or et les rimes en diamants purs",
    "le quartier nous a fait naitre et on va le faire briller",
    "je suis la rumeur qui court dans les halls de chaque tour",
    "on porte la couronne du beton sans jamais la laisser tomber",
    "le flow est notre arme secrete et le beat notre bouclier forge",
    "je suis le fils prodigue du quartier revenu pour regner enfin",
    "on est la generation qui transforme le plomb en or musical"
  ],
  vocabulary: {
    nouns: [
      "beton",
      "quartier",
      "cite",
      "block",
      "asphalte",
      "bitume",
      "micro",
      "rime",
      "flow",
      "barre",
      "verse",
      "beat",
      "galere",
      "lutte",
      "combat",
      "cicatrice",
      "couronne",
      "trone",
      "empire",
      "diamant",
      "acier",
      "flamme",
      "guerrier",
      "soldat",
      "roi",
      "billet",
      "liasse",
      "butin",
      "reussite",
      "sommet",
      "tour",
      "immeuble",
      "hall",
      "escalier",
      "reverbere",
      "trottoir",
      "pave",
      "frontiere",
      "territoire",
      "legende",
      "fierte",
      "honneur",
      "parole",
      "serment",
      "frere",
      "sang",
      "sueur",
      "cendres",
      "phoenix",
      "arsenal",
      "gloire",
      "heritage",
      "dynastie",
      "blindage",
      "fortune",
      "tresor",
      "tranchee",
      "ghetto",
      "facade",
      "dalle",
      "cage",
      "tunnel",
      "ombre",
      "lumiere",
      "cible",
      "bouclier",
      "arme",
      "calibre",
      "coffre",
      "monnaie",
      "dette",
      "victoire",
      "defaite",
      "chute",
      "envol",
      "instinct",
      "reflet",
      "ambition",
      "destin",
      "strategie"
    ],
    verbs: [
      "regner",
      "survivre",
      "combattre",
      "percer",
      "cracher",
      "graver",
      "forger",
      "batir",
      "conquerir",
      "ecraser",
      "dominer",
      "representer",
      "imposer",
      "affronter",
      "resister",
      "grimper",
      "frapper",
      "trancher",
      "briser",
      "rugir",
      "tonner",
      "avancer",
      "renaitre",
      "incendier",
      "pulveriser",
      "arracher",
      "defier",
      "poser",
      "rapper",
      "creer",
      "calculer",
      "viser",
      "cibler",
      "charger",
      "lacher",
      "enflammer",
      "terrasser",
      "balayer",
      "envahir",
      "soulever",
      "planter",
      "ancrer",
      "electriser",
      "decoder",
      "maitriser",
      "enchainer",
      "debloquer",
      "sculpter",
      "tracer",
      "emerger",
      "piloter",
      "manoeuvrer",
      "negocier",
      "capitaliser",
      "propulser",
      "defoncer",
      "dynamiter",
      "saccager",
      "catapulter",
      "pulser",
      "magnetiser",
      "intimider",
      "subjuguer",
      "neutraliser",
      "eclipser",
      "supplanter",
      "surpasser",
      "transcender",
      "revolutionner",
      "galvaniser",
      "mobiliser",
      "calibrer",
      "verrouiller",
      "deverrouiller",
      "empiler",
      "accumuler",
      "reinvestir",
      "manifester",
      "revendiquer"
    ],
    adjectives: [
      "dur",
      "brut",
      "cru",
      "reel",
      "authentique",
      "feroce",
      "indestructible",
      "incassable",
      "blinde",
      "affame",
      "tenace",
      "intouchable",
      "invincible",
      "implacable",
      "redoutable",
      "impitoyable",
      "solide",
      "massif",
      "tranchant",
      "acere",
      "sombre",
      "nocturne",
      "urbain",
      "beton",
      "souterrain",
      "royal",
      "supreme",
      "ultime",
      "legendaire",
      "mythique",
      "mortel",
      "fatal",
      "glacial",
      "bouillant",
      "explosif",
      "electrique",
      "magnetique",
      "toxique",
      "visceral",
      "intime",
      "lourd",
      "profond",
      "intense",
      "furieux",
      "fier",
      "loyal",
      "forge",
      "trempe",
      "aguerri",
      "indomptable",
      "infaillible",
      "imparable",
      "irreductible",
      "intraitable",
      "inalterable",
      "inflexible",
      "inoxydable",
      "effronte",
      "audacieux",
      "calculateur",
      "strategique",
      "lucide",
      "pragmatique",
      "souverain",
      "imperieux",
      "tyrannique",
      "dominateur",
      "triomphant",
      "adamantin",
      "titanesque",
      "herculeen",
      "ravageur",
      "devastateur",
      "venimeux",
      "corrosif",
      "abrasif",
      "cinglant",
      "percutant",
      "foudroyant"
    ]
  }
};
