module.exports = {
  themes: [
    "melancolie",
    "nostalgie",
    "solitude",
    "introspection",
    "automne",
    "reves",
    "cinema",
    "cafes",
    "pluie",
    "vintage",
    "errance",
    "crepuscule",
    "polaroid",
    "silence"
  ],
  openers: [
    "La Pluie Tombe Sur Les Vitres De Ce Cafe Presque Vide",
    "Je Regarde Le Monde A Travers Un Vieux Film En Super Huit",
    "Les Feuilles D'automne Tombent Comme Des Pages D'un Livre Oublie",
    "Un Vieux Disque Tourne Et Le Temps Se Suspend Enfin Ici",
    "Je M'assieds Seul Au Comptoir D'un Bar Que Personne Ne Connait",
    "Les Rues Sont Vides Et Le Ciel Est D'un Gris Parfait",
    "Mon Reflet Dans La Vitre Me Regarde Avec Des Yeux Fatigues",
    "Une Chanson Oubliee Revient Me Hanter Dans Ce Cafe Silencieux",
    "Le Crepuscule Peint La Ville De Couleurs Que Personne Ne Voit",
    "Je Marche Sans But Dans Les Rues De Cette Ville Endormie",
    "Un Polaroid Jauni Raconte Un Ete Que J'ai Presque Oublie Maintenant",
    "Le Brouillard Enveloppe Les Immeubles Comme Un Reve Qui Se Dissipe",
    "Les Neons Du Cinema Eclairent Mon Visage Solitaire Ce Soir",
    "Un Livre Ouvert Sur La Table Attend Que Je Revienne Lire",
    "Le Dernier Metro Passe Et La Ville M'appartient Toute Entiere",
    "Je Cherche Un Sens Dans Les Reflets De Cette Flaque Grise",
    "Les Toits De Zinc Brillent Sous La Pluie Fine D'octobre Froid",
    "Un Chat Traverse La Rue Deserte Comme Un Fantome Silencieux",
    "Le Vent Souffle Les Pages D'un Journal Que Personne N'a Lu",
    "Je Bois Mon Cafe Noir En Regardant Le Monde Passer Dehors",
    "Les Lampadaires S'allument Un Par Un Dans La Rue Mouillee Ce Soir",
    "Un Vieux Manege Tourne Seul Dans Le Parc Ferme Pour L'hiver",
    "Le Son De La Pluie Est La Plus Belle Musique Ce Soir",
    "Je Fume Une Cigarette Sous L'auvent D'un Magasin Ferme Depuis Longtemps",
    "Les Escaliers De Service Menent Vers Un Toit Ou Le Ciel Attend",
    "Un Carnet De Notes Deborde De Mots Que Je N'ai Jamais Dits",
    "La Melodie D'un Piano Sort D'une Fenetre Entrouverte Ce Soir Humide",
    "Les Vieilles Photos En Noir Et Blanc Ne Mentent Jamais Vraiment",
    "Le Tramway Passe Dans La Brume Comme Un Souvenir En Mouvement",
    "Je M'endors Au Son De La Ville Qui Murmure Ses Secrets",
    "Un Parapluie Retourne Par Le Vent Git Sur Le Trottoir Mouille",
    "Les Murs De Cette Chambre Connaissent Tous Mes Monologues Nocturnes",
    "Le Vinyle Craque Et La Nostalgie Envahit Chaque Coin De La Piece",
    "Je Compte Les Gouttes De Pluie Sur La Vitre De Ma Fenetre",
    "Un Vieux Velo Rouille S'appuie Contre Le Mur Du Passage Couvert",
    "Les Pigeons Sur Le Rebord De La Fenetre Sont Mes Seuls Voisins",
    "Le Ciel De Novembre A La Couleur De Mes Pensees Ce Soir",
    "Un Carton A Dessin Deborde De Croquis De Visages Inconnus Croises",
    "La Librairie Du Coin Ferme Et Les Livres Dorment Jusqu'a Demain",
    "Je Regarde Les Trains Partir Depuis Le Quai De Mes Hesitations",
    "Les Volets Se Ferment Et La Nuit M'accueille Dans Son Silence Doux",
    "Un Film En Noir Et Blanc Joue Pour Moi Seul Ce Soir",
    "Les Nuages Defilent Comme Les Pensees Dans Ma Tete Agitee Ce Jour",
    "Le Cafe Se Vide Et Je Reste Le Dernier A Ma Table",
    "Un Graffiti Sur Le Mur Dit Ce Que Je N'ose Pas Penser",
    "Les Marches Du Pont Menent Vers Un Endroit Que Je Ne Connais Pas",
    "Le Silence De Trois Heures Du Matin Est Assourdissant Et Beau",
    "Je Dessine Des Cercles Dans La Buee De La Vitre Froide",
    "Un Accordeon Joue Au Loin Et La Rue Devient Un Film D'auteur",
    "Les Lumieres De La Ville Tremblent Comme Des Larmes Suspendues Au Ciel"
  ],
  verses: [
    "la pluie dessine des lignes sur la vitre de mon cafe prefere",
    "je tourne les pages d'un livre que je ne finirai jamais ici",
    "les rues mouillees refletent un ciel qui ne sait pas pleurer",
    "un vieux poste de radio gresille une chanson d'un autre temps",
    "je me perds dans les ruelles comme on se perd dans ses pensees",
    "les feuilles mortes craquent sous mes pas comme des souvenirs fragiles",
    "le vent souffle dans les rues vides et emporte mes mots inutiles",
    "un neon clignote au dessus d'un bar ou personne ne va plus",
    "je compte les secondes entre les gouttes de pluie sur le zinc",
    "les toits de la ville dessinent une ligne brisee contre le ciel",
    "un chat noir me regarde depuis l'autre cote de la rue sombre",
    "les murs de cette chambre gardent l'echo de mes nuits sans sommeil",
    "je bois du the dans une tasse ebreche que j'aime quand meme",
    "la buee sur la vitre efface le monde et je me sens mieux",
    "un vieux film joue en boucle dans ma tete chaque nuit grise",
    "les lampadaires sont les seules etoiles de cette ville sans ciel ouvert",
    "je griffonne des mots dans les marges d'un roman inacheve encore",
    "le metro passe sous mes pieds et le sol tremble doucement a peine",
    "les reflets dans les flaques sont plus beaux que la realite grise",
    "un accordeon pleure au coin de la rue et je m'arrete pour ecouter",
    "les vieilles affiches se decollent des murs comme ma peau du temps",
    "je regarde les gens passer et j'invente des vies pour chacun d'eux",
    "la melancolie est un manteau que je porte avec une certaine elegance",
    "un escalier en colimacon monte vers un ciel que je ne verrai jamais",
    "les fils electriques dessinent des portees musicales entre les immeubles gris endormis",
    "je cherche un visage dans la foule mais tous me sont etrangers",
    "le bruit de mes pas resonne dans le couloir vide du soir",
    "une lettre non envoyee jaunit dans le tiroir de mon vieux bureau",
    "les nuages passent comme des pensees que je n'arrive pas a retenir",
    "un miroir fele me renvoie une image que je ne reconnais plus bien",
    "la fumee de ma cigarette dessine des questions sans reponse dans l'air",
    "les pages de mon carnet sont blanches comme les jours qui restent encore",
    "un parc ferme de l'autre cote de la grille me fait envie",
    "le temps s'ecoule comme le cafe froid que j'ai oublie de boire",
    "les trains partent sans moi et je reste sur le quai vide",
    "un vieux piano desaccorde joue la bande son de mes regrets lointains",
    "les rideaux bougent avec le courant d'air et je crois voir quelqu'un",
    "je m'assois sur un banc mouille et la ville tourne autour de moi",
    "les horloges de la gare indiquent des heures qui ne sont pas les miennes",
    "un rayon de soleil perce les nuages comme une pensee positive rare",
    "les murs tagges racontent les histoires de ceux qui passent sans s'arreter",
    "je feuillette un album photo et chaque image est un petit deuil",
    "la solitude est une piece vide ou mes pensees resonnent trop fort",
    "un avion trace une ligne blanche dans le ciel gris de novembre",
    "les boites aux lettres sont vides comme les promesses qu'on m'a faites",
    "le crepuscule est l'heure ou la ville hesite entre le jour et la nuit",
    "un vieux pont rouille enjambe une riviere ou flottent les feuilles mortes",
    "je regarde la lune par la lucarne de mon appartement sous les toits",
    "les rues se vident et le silence s'installe comme un vieil ami fidele",
    "un manege arrete dans le parc a l'air d'un souvenir fige la",
    "les gouttes de pluie sont les larmes d'un ciel qui me comprend",
    "je marche pieds nus sur le parquet froid de mes insomnies longues",
    "les mots que je cherche se cachent derriere le brouillard de mes pensees",
    "un reverbere eclaire un cercle de lumiere ou la pluie danse seule",
    "les tasses s'empilent dans l'evier comme les jours se suivent sans fin",
    "je mets un disque et l'aiguille gratte le silence de ma solitude",
    "les escaliers de la cite menent nulle part et partout a la fois",
    "un panneau affiche un film que j'ai vu seul un soir de novembre triste",
    "les pigeons picorent les miettes de mes reves tombes sur le trottoir",
    "je colle mon front a la vitre et le monde parait irreel dehors",
    "la melancolie a le gout du cafe que j'ai laisse refroidir encore",
    "un carillon sonne quelque part et le temps reprend son cours lent",
    "les ombres sur le mur jouent une piece que je ne comprends pas",
    "je plie et deplie une carte sans savoir ou je veux aller vraiment",
    "les couvertures du lit gardent la forme de mes nuits agitees d'hier",
    "un vieux telephone sonne dans un film et je sursaute quand meme",
    "les vitres embuees du bus cachent une ville que je connais par coeur",
    "je regarde mes mains et je me demande ce qu'elles ont construit",
    "les toiles d'araignee dans le coin du plafond sont de l'art brut",
    "un carre de ciel bleu entre les immeubles me suffit certains jours",
    "les trottoirs mouilles sont des miroirs ou la ville se regarde vivre",
    "je traine dans les librairies d'occasion comme on traine ses souvenirs",
    "le vent tourne les pages du journal oublie sur le banc mouille",
    "un feu de signalisation clignote pour personne au milieu de la nuit",
    "les bruits de la ville sont une symphonie que personne ne dirige",
    "je dessine ton visage sur la buee et tu disparais quand meme",
    "les stores venitiens decoupent la lumiere en tranches fines et regulieres",
    "un carnet de croquis deborde de visages que j'ai croises sans parler",
    "les murs de brique rouge portent la patine du temps qui passe",
    "je me noie dans un verre d'eau et c'est presque poetique ici",
    "les voix du cafe se melent en un murmure qui me berce doucement",
    "un vieux cinema de quartier ferme ses portes pour la derniere fois",
    "les lignes de ma main dessinent des chemins que je n'ai pas pris",
    "le bruit de la pluie sur le velux est ma berceuse preferee",
    "les enseignes lumineuses epellent des mots qui n'ont plus de sens la nuit",
    "je collectionne les tickets de metro comme des preuves de mes errances",
    "un arbre solitaire dans la cour de l'immeuble perd ses dernieres feuilles",
    "les reflets des lumieres dans le canal tremblent comme mes certitudes fragiles",
    "je me regarde dans la vitrine et un etranger me rend mon regard",
    "les escaliers de secours zigzaguent sur la facade comme mes pensees du soir",
    "un croissant de lune pend au dessus de la ville comme un sourire triste",
    "les murs suintent l'humidite et les souvenirs dans ce vieil appartement",
    "je ramasse une feuille morte et je la garde comme un marque-page delicat",
    "les grilles du parc se ferment et je reste de l'autre cote pensif",
    "un thermos de cafe tiede est mon seul compagnon sur ce banc froid",
    "les antennes sur les toits captent des ondes que personne n'ecoute plus",
    "je regarde les lumieres s'allumer dans les fenetres comme des vies qui s'eveillent",
    "un manteau trop grand pour moi est ma protection contre le monde exterieur",
    "les cernes sous mes yeux sont les traces de mes nuits philosophiques longues",
    "le vent souleve la poussiere et les souvenirs dans cette rue pavee",
    "les bouquinistes du quai rangent leurs boites et la culture se ferme",
    "un velo abandonne dans la cour attend un proprietaire qui ne viendra plus",
    "les papiers peints decolles racontent les gouts de ceux qui vivaient la",
    "je trace des mots dans la poussiere de la table du cafe vide",
    "les cloches sonnent et le dimanche a le gout de l'ennui dore",
    "un rideau de pluie tombe entre le monde et moi comme un voile",
    "les ampoules nues pendent du plafond comme des idees inachevees et nues",
    "je m'endors avec le bruit de la ville et me reveille avec son silence",
    "les moulures du plafond dessinent des labyrinthes ou mes yeux se perdent",
    "un vieux reveil mecanique bat le temps comme un coeur fatigue encore",
    "les ombres des passants glissent sur le mur de ma chambre sombre",
    "je plie un avion en papier et le lance vers la fenetre ouverte",
    "les rues pavees brillent sous la pluie comme un film de nouvelle vague",
    "un verre de vin a moitie vide attend sur le rebord de la fenetre",
    "les fumees des cheminees montent droites dans le ciel froid de decembre",
    "je me souviens de tout et c'est ca qui rend les jours lourds",
    "les portes cocheres cachent des cours interieures ou le temps s'est arrete",
    "un sac plastique vole au vent comme un fantome ordinaire de la rue",
    "les pages du calendrier tombent et chaque jour ressemble au precedent gris",
    "je regarde par la fenetre et la rue est un film que je regarde",
    "les marches usees de l'escalier comptent les pas de tous ceux qui sont montes",
    "un post-it sur le frigo dit quelque chose que j'ai oublie depuis",
    "les murs blancs de cette chambre sont une toile vierge pour mes pensees",
    "le silence de la nuit est si dense qu'on pourrait le toucher ici",
    "un rayon de lumiere traverse les volets et dessine une ligne doree",
    "les rues se croisent et je choisis toujours le chemin le plus long",
    "le brouillard engloutit les immeubles un par un comme un reve qui s'efface",
    "les boutons du vieux poste de radio cliquent comme des souvenirs qu'on egrene",
    "je vis entre parentheses dans une phrase que personne ne lit jamais",
    "les photos accrochees au mur sont des fenetres sur des jours meilleurs passes",
    "un crayon use jusqu'a la mine est la mesure de mes pensees ecrites",
    "les reflets de la ville dans la riviere sont plus doux que la realite",
    "je marche sous la pluie sans parapluie et je me sens vivant enfin",
    "les rues de nuit sont des couloirs ou mes pas font echo seuls",
    "un chat dort sur le radiateur comme si le monde n'existait pas",
    "les grues sur le chantier dessinent des croix dans le ciel de novembre",
    "je regarde le plafond et les fissures ressemblent a une carte au tresor",
    "les stores fermes filtrent une lumiere qui ressemble a mes emotions tamisees",
    "un ticket de cinema dans ma poche me rappelle un soir de douceur",
    "les bancs publics portent les initiales de ceux qui ont aime ici avant",
    "le craquement du parquet est la seule conversation que j'ai eue aujourd'hui",
    "les fils du telephone pendent comme des notes sur une portee oubliee",
    "un cafe serre dans une tasse blanche est tout un poeme pour moi",
    "les gouttieres debordent et la pluie fait son propre chemin sur les murs",
    "je me couche habille et la nuit m'avale comme un vieux roman noir",
    "les ombres des branches sur le mur dansent un ballet sans musique",
    "un vieux journal date de la semaine derniere est ma seule compagnie",
    "les bruits de pas au dessus resonnent comme une vie qui continue sans moi",
    "je regarde les etoiles par la fenetre mais les nuages les cachent",
    "les nuits blanches ont une saveur que les nuits de sommeil n'ont pas",
    "un miroir couvert de buee me rend une image floue de moi-meme",
    "les touches du piano sont froides sous mes doigts de quatre heures du matin",
    "je vis au dernier etage et mes pensees montent encore plus haut la nuit",
    "les cafes fermes de nuit ont l'air de theatres apres la derniere piece",
    "un parapluie noir retourne par le vent est une sculpture de hasard",
    "les platanes perdent leurs feuilles et la rue change de visage lentement",
    "je compte les jours sur le mur comme un prisonnier de mes habitudes",
    "la lumiere de la lune filtre a travers les rideaux de tulle blanc",
    "un stylo a bille vide est la metaphore de ce que je ressens",
    "les murs de la cage d'escalier gardent l'echo de conversations nocturnes",
    "je regarde les avions passer et j'imagine les vies qu'ils transportent ailleurs",
    "un paquet de sucre renverse sur la table dessine des constellations blanches",
    "les bruits de la tuyauterie sont les entrailles de cet immeuble qui vit",
    "je lis les petites annonces pour trouver un sens a cette journee vide",
    "un chat de gouttiere me suit dans la rue comme un compagnon choisi",
    "les affiches de concerts passes jaunissent sur le mur de ma chambre grise",
    "je regarde le plafond et les ombres y projettent un cinema gratuit la nuit",
    "un parapluie oublie dans le metro attend un proprietaire qui ne viendra plus jamais",
    "les marches du metro sentent l'humanite et le metal mouille du matin triste",
    "je fais tourner ma cuillere dans le cafe comme une aiguille de montre lente",
    "les lignes du cahier sont des barreaux sur lesquels mes mots s'appuient fatigues",
    "un graffiti a demi efface dit quelque chose que je ne peux plus lire",
    "les mouettes crient au dessus du canal comme des ames en peine perdues",
    "je regarde la pluie couler sur le pare-brise d'une voiture garee depuis longtemps",
    "un vieux magazine dans la salle d'attente parle d'un monde qui n'existe plus",
    "les lumieres du distributeur automatique eclairent le trottoir d'un halo bleu froid",
    "je ramasse un galet sur le quai et je le garde dans ma poche",
    "les fils electriques vibrent dans le vent comme les cordes d'une guitare invisible",
    "un pigeon boiteux traverse la place avec plus de dignite que moi ce matin",
    "les rideaux de fer des boutiques fermees sont les paupieres de la rue endormie",
    "je regarde mon telephone mais personne n'a appele depuis trois jours de silence",
    "un panneau publicitaire promet le bonheur et la promesse sonne creux dans la nuit",
    "les gouttes de condensation sur la vitre du bus sont des larmes du verre",
    "je marche contre le vent et le vent gagne toujours a la fin",
    "un ticket de caisse froisse dans ma poche est tout ce qui reste d'hier",
    "les pedalos amarres sur le lac attendent un ete qui tarde a venir",
    "je dessine des spirales sur un coin de nappe en papier au restaurant vide",
    "un sac plastique accroche a un arbre flotte comme un drapeau de rien du tout",
    "les premieres gouttes de pluie font des cercles dans la flaque comme des disques",
    "je regarde les gens a travers la vitrine et je suis le poisson ici",
    "un ancien cinema transforme en supermarche garde quelque chose de triste dans ses murs",
    "les fils a linge tendus entre les immeubles portent les couleurs du quotidien gris",
    "je me perds dans le metro et chaque couloir mene a un autre couloir",
    "un vieux banc dans le parc porte les marques de tous ceux qui ont attend",
    "les flaques d'eau refletent un monde inverse qui me semble plus vrai parfois",
    "je regarde le bateau mouche passer sous le pont comme un reve qui glisse",
    "un croissant a moitie mange dans l'assiette est tout un roman de solitude",
    "les gouttes de pluie sur le zinc du comptoir font de la musique pointilliste",
    "je fais le tour du pate de maisons et je reviens au point de depart",
    "un vieux transistor dans la vitrine de la brocante joue encore pour personne",
    "les escaliers mecaniques du metro bougent sans passagers dans la nuit desertee",
    "je regarde la fumee de mon souffle dans l'air froid comme une priere visible",
    "un calendrier de l'annee derniere est toujours accroche au mur de la cuisine",
    "les chaises empilees sur les tables du cafe ferme sont un monument a l'attente",
    "je tourne en rond dans ma tete comme un manege qui ne s'arrete pas",
    "un reflet de neon rose dans une flaque est la seule beaute de ce soir",
    "les vieux immeubles haussmanniens regardent la rue avec leurs yeux de pierre grise",
    "je cherche mes clefs dans mes poches comme je cherche un sens a tout cela",
    "un pigeon roucoule sur le rebord et sa voix est plus douce que le silence",
    "les fils de la pluie cousent le ciel a la terre comme un rideau",
    "je regarde les lumieres s'eteindre fenetre apres fenetre et la nuit s'installe ici",
    "un thermos vide au fond de mon sac a le gout des matins froids",
    "les papillons de nuit tournent autour du lampadaire comme moi autour de mes pensees",
    "je prends des photos de murs fissures parce qu'ils me ressemblent un peu",
    "un livre de poche abandonne sur un banc attend un lecteur de passage",
    "les marches de pierre usees temoignent de milliers de pas qui ne reviendront pas",
    "je marche dans les flaques expres parce que le bruit me fait du bien",
    "un paquet de cigarettes vide sur le trottoir est la ponctuation d'une conversation finie",
    "les volets clos d'un appartement me font imaginer une vie que je ne vis pas",
    "je regarde le ciel entre deux immeubles et c'est comme une riviere de gris",
    "un carillon eolien sur un balcon chante une chanson que le vent compose",
    "les taches de cafe sur mon cahier sont des empreintes de mes matins pensifs",
    "je m'assieds dans l'escalier de service et le beton est froid mais honnete",
    "un chat dort sur le comptoir du cafe comme s'il etait le proprietaire endormi",
    "les stores a demi baisses filtrent une lumiere qui ressemble a ma moitie d'espoir",
    "je regarde la pendule et l'aiguille avance plus lentement quand on la regarde fixement",
    "un vieux plan de metro deplie dans ma poche est ma carte au tresor grise",
    "les murs du tunnel resonnent de mes pas et je suis une percussion solitaire",
    "je fais des ricochets avec des cailloux plats sur le canal immobile du soir",
    "un autocollant decolle sur un poteau dit paix et je souris tristement en passant",
    "les vitres du bus embuees cachent un monde que je devine sans le voir",
    "je regarde les canards sur le canal et leur calme me rend presque jaloux",
    "un panneau sens interdit est un poeme court que la ville a ecrit rouge",
    "les pas des passants sur le pave mouille font un rythme que j'ecoute assis",
    "je ramasse une plume de pigeon et je la glisse entre deux pages blanches",
    "un reverbere casse eclaire quand meme un bout de trottoir dans la nuit grise",
    "les feuilles collees au trottoir mouille sont les traces d'un automne qui ne finit pas",
    "je regarde mes chaussures usees et elles racontent tous les chemins que j'ai pris",
    "un carre de lumiere tombe d'une fenetre sur le trottoir comme un tapis doux",
    "les antennes paraboliques sur les toits sont des oreilles qui ecoutent le ciel muet",
    "je ferme la porte de mon studio et le bruit du monde s'arrete enfin",
    "un miroir brise dans la ruelle reflete le ciel en sept morceaux de gris",
    "les tags sur les murs sont les poemes de ceux qui n'ont pas de cahier",
    "je regarde le dernier rayon de soleil disparaitre derriere les toits de zinc",
    "un verre de vin oublie sur la terrasse se remplit de pluie lentement",
    "les vieux escaliers de bois craquent sous mes pieds comme des confidences du passe",
    "je dessine un coeur sur la buee et il disparait avant que je puisse le garder",
    "un chat traverse la cour interieure et le silence revient apres son passage furtif",
    "les lampes de poche des passants sont des lucioles urbaines dans la nuit profonde",
    "un bout de craie sur le trottoir dessine un monde meilleur que le vrai",
    "un thermos de cafe tiede attend sur le rebord de la fenetre givre",
    "les grues du chantier dessinent des croix geometriques dans le ciel de plomb",
    "je regarde le givre dessiner des fougeres sur la vitre de ma chambre",
    "un vieux transistor capte des stations fantomes dans la nuit brumeuse d'hiver",
    "les cernes sous mes yeux sont des vallees creusees par l'insomnie chronique",
    "le bruit du refrigerateur est la seule compagnie dans cet appartement vide",
    "un carnet moleskin noirci de mots illisibles traine au fond de ma poche",
    "les toits d'ardoise mouilles brillent comme des ecailles de poisson sous la pluie",
    "je regarde les avions traverser le ciel et j'imagine leurs destinations lointaines",
    "un morceau de papier peint decolle revele la couleur d'une vie precedente",
    "les marches du metro usees par des millions de pas gardent chaque histoire",
    "je bois un espresso debout au comptoir en regardant la rue se vider",
    "un vieux polaroid dans mon portefeuille montre un visage que j'ai oublie de regretter",
    "les fils du tramway dessinent des portees musicales au-dessus de la rue grise",
    "le bruit de la machine a ecrire resonne dans un appartement vide du quatrieme",
    "un paquet de cigarettes froisse dans ma poche me rappelle des promesses non tenues",
    "les mouettes crient au-dessus du canal comme des voix qui appellent au loin",
    "je traine mes pas sur le pont et chaque planche grince sous le poids",
    "un cinema d'art et d'essai projette un film pour trois spectateurs silencieux",
    "les flaques d'eau refletent un ciel inverse plus beau que l'original morne",
    "je plie un billet de metro comme un origami et je le pose la",
    "un saxophone joue au loin et la nuit devient un film en noir",
    "les paves mouilles luisent sous les phares comme des yeux qui veillent",
    "je griffonne sur la nappe en papier du bistrot des mots sans suite",
    "un chat tigre se faufile entre les poubelles comme un poeme furtif",
    "les enseignes eteintes de nuit ressemblent a des bouches fermees sur des secrets",
    "le bruit du vent dans la cage d'escalier est un orgue invisible la nuit",
    "un parapluie oublie dans le porte-parapluie attend son proprietaire depuis des mois",
    "les platanes perdent leur ecorce et montrent une peau neuve et pale dessous",
    "je regarde le plafond si longtemps que les fissures deviennent des routes nouvelles",
    "un vieux chapeau melon sur l'etagere me rappelle une epoque que je n'ai pas vecue",
    "les gouttieres debordent et l'eau coule le long du mur comme des larmes lentes",
    "je tourne en rond dans cette chambre comme un vinyle sur sa platine",
    "un calendrier vide traine sur la table depuis le debut de l'annee passee",
    "les pigeons roucoulent sur le rebord et leur chant est presque musical ce matin",
    "le bruit des talons sur le trottoir s'eloigne et le silence revient lentement",
    "un rayon de soleil oblique traverse la poussiere comme un projecteur de cinema",
    "les stores venitiens dessinent des barreaux de lumiere sur le mur blanc nu",
    "je relis une lettre que je n'enverrai jamais et les mots ont change de sens",
    "un bocal de confiture vide sur la table est un monument a l'absence douce",
    "le tapis use montre la trame de ses annees sous mes pieds fatigues",
    "un miroir brise dans la salle de bain multiplie mon visage en fragments",
    "les grilles du jardin public sont fermees et les arbres dorment sans nous",
    "je colle des timbres sur une enveloppe que je n'adresserai a personne ce soir",
    "un feu de signalisation passe du rouge au vert pour une rue deserte",
    "les murs de la chambre de bonne ont absorbe trop de solitudes anciennes",
    "le plancher craque sous mes pas comme s'il racontait ses propres souvenirs",
    "un globe terrestre poussiereux trone sur le bureau et le monde semble petit",
    "les pages du dictionnaire sont ecornees aux mots que je cherche toujours en vain",
    "je regarde la pluie couler sur la vitre et chaque goutte est une seconde perdue",
    "un paquet de lettres attache par un ruban jaunit dans le tiroir du bas",
    "les ampoules du couloir grillent une par une et je ne les remplace pas",
    "le silence entre deux sirenes de nuit est le vrai son de la ville",
    "un croissant entame refroidit dans l'assiette pendant que je regarde dehors pensif",
    "les rideaux de tulle filtrent la lumiere du matin comme un souvenir tamise",
    "je marche le long du canal et les peniches sont des maisons flottantes",
    "un vieux magazine ouvert a une page au hasard est mon oracle quotidien",
    "les chaises empilees de la terrasse fermee attendent un printemps qui tarde encore",
    "le bruit de la bouilloire est le signal que la journee doit commencer enfin",
    "un cendrier plein sur le rebord de la fenetre recueille les cendres du soir",
    "les fils electriques portent des chaussures suspendues comme des trophees de passage",
    "je descends les escaliers et chaque marche est un pas vers le dehors froid",
    "les vitres du bus embuees cachent les passagers comme des fantomes en transit",
    "le bruit de mes doigts sur le clavier ressemble a une pluie legere",
    "un ticket de caisse froisse dans ma poche est la trace d'un mardi oublie",
    "les poubelles renversees par le vent racontent la nuit comme un journal intime",
    "un vieux telephone a cadran sur la table ne sonne plus jamais pour moi",
    "les tuyaux de l'immeuble grondent la nuit comme un estomac qui a faim",
    "le dernier rayon de soleil peint une ligne doree sur le mur gris nu",
    "un nid d'oiseau abandonne dans la gouttiere est un petit theatre vide la",
    "les affiches superposees sur le mur forment un collage de temps passes ici",
    "je laisse la radio allumee pour ne pas entendre le silence trop fort",
    "les bruits de pas au-dessus de moi dessinent la vie de quelqu'un d'autre",
    "le thermostat bloque a dix-sept degres est ma mesure du confort minimal",
    "un cactus sur le rebord de la fenetre est mon seul engagement durable",
    "les coutures du canape craquent quand je m'assieds comme si le temps pesait",
    "je regarde le soleil se coucher depuis le toit et la ville se tait",
    "les papiers peints a fleurs de cet appartement datent d'un siecle oublie",
    "le son d'un piano quelque part dans l'immeuble traverse les murs comme un songe",
    "un pot de crayons sur le bureau attend que l'inspiration frappe a ma porte",
    "les gouttes de pluie sur la vitre tracent des chemins que je suis du doigt",
    "je m'endors dans le bruit de la pluie et c'est la seule paix possible",
    "un vieux globe lumineux eclaire ma chambre d'une lumiere de lune artificielle",
    "les tuiles du toit d'en face comptent les heures sous le ciel monotone",
    "le cafe moulu dans le filtre attend l'eau chaude comme j'attends une raison",
    "un cadre photo retourne sur le bureau cache un visage que je ne nomme pas",
    "les trottoirs craquelent sous le gel comme ma certitude au petit matin pale",
    "je regarde les etoiles rares entre les immeubles et chacune est un voeu perdu",
    "un manteau accroche derriere la porte est la silhouette d'un absent fidele",
    "les radiateurs tiquent la nuit comme des horloges qui comptent a l'envers lentement",
    "le crepitement du vinyle avant la musique est mon moment prefere du jour",
    "un livre de poche corne traine sur le radiateur depuis des semaines oublie",
    "les reflets des neons dans les yeux des passants sont des etoiles urbaines",
    "je plie et deplie un ticket de cinema comme une pensee obsedante et douce",
    "un moineau se pose sur le balcon et repart sans explication comme les gens",
    "les murs de cette chambre ont la memoire des conversations avec moi-meme seul",
    "le bruit du robinet qui goutte la nuit est un metronome pour mes pensees",
    "les escaliers de secours dessinent des zigzags d'ombre sur la facade endormie",
    "un crayon a papier roule sur le bureau et tombe comme une idee perdue",
    "les nuages de novembre ont la consistance du coton et le poids du plomb",
    "le bruit de la serrure du voisin me rappelle que d'autres vies existent",
    "les pas des joggers dans le parc matinal sont un rythme regulier et vivant",
    "je gratte le givre sur la vitre et decouvre un monde toujours le meme",
    "un sachet de the use repose dans la soucoupe comme un petit vestige brun",
    "les lumieres de la ville vues du toit ressemblent a un circuit imprime geant",
    "le son de la pluie change quand elle frappe le zinc puis le verre",
    "les toiles d'araignee dans le coin de la fenetre captent la lumiere matinale",
    "je marche pieds nus sur le carrelage froid et chaque pas est un eveil",
    "un thermos sans bouchon sur le bureau est le symbole de ma vie entrouverte",
    "les graffitis dans le passage souterrain sont les poemes d'une generation silencieuse",
    "le clapotis de l'eau dans les caniveaux accompagne mes promenades de novembre",
    "les chaises du cafe empilees dehors forment des sculptures involontaires sous la pluie",
    "je feuillette un atlas geographique et chaque carte est un reve en couleur",
    "un sac a dos use dans le placard attend un voyage qui ne viendra pas",
    "les stores se levent dans les bureaux d'en face et les vies recommencent",
    "le vent pousse une cannette vide sur le trottoir et le bruit resonne seul",
    "un piano desaccorde dans le fond du cafe joue des notes approximatives et belles",
    "les marques de tasses sur la table forment des anneaux de solitude blanche",
    "je regarde les feuilles mortes tourbillonner dans un courant d'air du metro souterrain",
    "un carnet de croquis ouvert montre un visage dessine de memoire un soir tard",
    "le bruit du percolateur au comptoir est le premier son humain du matin",
    "un vieux cadre sans photo pendu au mur encadre le vide avec soin",
    "les antennes paraboliques sur les balcons captent des signaux de vies paralleles",
    "je regarde le compteur tourner et le temps s'ecoule avec chaque chiffre noir",
    "un parapluie noir seche dans l'entree et forme une flaque comme un petit lac",
    "le bruit sourd du metro sous les pieds fait vibrer les tasses du cafe",
    "les fenetres eclairees la nuit sont des ecrans de television sans telecommande",
    "je regarde la buee de mon souffle dans l'air froid et je me sens vivant",
    "un vieux stylo plume qui gratte le papier est le seul bruit qui compte",
    "les boites aux lettres rouillees du hall s'ouvrent sur des publicites et du vide",
    "le bruit d'une goutte qui tombe dans l'evier est le pouls de l'appartement",
    "les traces de doigts sur la vitre sont les seules preuves de ma presence",
    "je collectionne les sous-bocks des cafes comme des cartes postales de solitude",
    "un abat-jour penche projette une lumiere oblique sur mes pensees de trois heures",
    "les bruits de la cage d'escalier sont une symphonie de vies superposees ensemble",
    "le son du vent dans la cheminee condamnee est un fantome qui chante seul",
    "un briquet vide dans ma poche est le souvenir d'une flamme eteinte hier",
    "les cables du pont vibrent dans le vent comme les cordes d'une harpe geante",
    "le dernier croissant de la boulangerie a le gout de la fin du jour",
    "les bulles dans mon verre de biere montent comme des pensees vers la surface",
    "je regarde les nuages defiler et chacun ressemble a un pays que j'invente",
    "un vieux pull trop grand est ma couverture quand la nuit est trop froide",
    "le son d'une trompette sort d'une fenetre et la rue devient jazz un instant",
    "un agenda vide pour l'annee prochaine est une promesse que je ne tiendrai pas",
    "les murs de la cave gardent l'humidite et les secrets de l'immeuble endormi",
    "je regarde un escargot traverser le trottoir et j'admire sa determination patiente",
    "les ombres chinoises des branches sur le store sont mon cinema du soir gratuit",
    "le grincement de la balancoire vide dans le parc est une chanson d'absence",
    "les lettres du panneau d'affichage manquent et les mots incomplets font sens quand meme",
    "je regarde le ciel orange au couchant et la ville devient un tableau fauve",
    "un disque raye repete le meme passage et je trouve ca presque philosophique",
    "les bourgeons sur l'arbre de la cour sont les premieres nouvelles du printemps",
    "le bruit de mes pages qui tournent dans le silence est un dialogue intime",
    "un coquillage sur l'etagere me rappelle un ete et le bruit des vagues",
    "les fils a linge entre les immeubles portent le drapeau du quotidien ordinaire",
    "je regarde la condensation couler sur la vitre et chaque goutte ecrit un vers",
    "un prospectus glisse sous la porte est le seul courrier que je recois ici",
    "les fenetres sans rideaux des appartements vides sont des yeux sans paupieres ouverts",
    "un verre d'eau sur la table de nuit est le luxe de ma simplicite",
    "les traces de craie sur le trottoir s'effacent sous la pluie comme mes projets",
    "je regarde mon reflet dans la vitrine du magasin ferme et un etranger me fixe",
    "un vieux cadenas rouille sur la grille du parc garde un jardin abandonne",
    "les boites de conserve empilees dans le placard sont ma collection de jours identiques",
    "le bruit d'un livre qui tombe de l'etagere la nuit me reveille en sursaut",
    "un pot de fleurs seche sur le balcon attend une main qui l'arrose encore",
    "les papillons de nuit autour du lampadaire dessinent des orbites de lumiere",
    "je regarde la pendule et l'aiguille avance comme si elle aussi trainait les pieds",
    "un vieux journal plie en deux sert de cale sous le pied de la table",
    "les fissures dans le plafond forment une carte de pays qui n'existent pas encore",
    "le son des cloches le dimanche matin est la seule horloge que j'accepte ici",
    "un crayon oublie derriere mon oreille me rappelle une pensee perdue en route",
    "les rideaux tires dessinent une frontiere entre moi et le monde exterieur bruyant",
    "je pose mes lunettes sur la table et le monde devient un tableau impressionniste",
    "un vieux poste de radio gresille entre deux stations comme entre deux pensees",
    "les escaliers en colimacon de l'immeuble haussmannien montent vers des vies que j'imagine",
    "le papier kraft d'un paquet defait est la seule carte au tresor que je possede",
    "un neon qui clignote au-dessus du bar ecrit un code morse de solitude",
    "les volets fermes de l'appartement d'en face cachent un mystere que je n'eluciderai jamais",
    "un vieux repondeur telecharge les messages d'une epoque ou les gens laissaient leur voix",
    "les pavés descelles du trottoir forment un puzzle que personne ne resout jamais",
    "je lis les graffitis dans les toilettes du bar comme de la poesie brutale",
    "un ticket de loterie perdant dans ma poche est mon billet pour le reve",
    "les chenes du boulevard perdent leurs glands et les ecureuils font la fete",
    "le bruit du generique de fin au cinema est le silence qui reprend ses droits",
    "un verre de grenadine au comptoir me ramene a une enfance que j'ai quittee",
    "les escalators du centre commercial montent et descendent comme des vies paralleles sans fin",
    "je regarde les moineaux se baigner dans la flaque et j'envie leur insouciance folle",
    "un vieux transistor dans la poche de mon manteau capte des bribes de monde",
    "les gommes a effacer usees sur mon bureau sont les traces de mes doutes",
    "le bruit des cuilleres dans les tasses du matin est un orchestre de petit dejeuner"
  ],
  bridges: [
    "et la pluie continue de tomber comme si elle comprenait ma peine",
    "on dit que le temps guerit tout mais le temps est si lent",
    "quelque part entre l'aube et le crepuscule j'ai perdu le fil",
    "les reves sont les seuls endroits ou les choses ont un sens",
    "je cherche la beaute dans les fissures du monde qui s'effrite",
    "le silence est le seul ami qui ne me doit jamais mentir",
    "entre deux pages blanches il y a tout ce que je n'ai pas dit",
    "la nostalgie est un pays ou l'on vit mieux qu'au present gris",
    "je suis un film dont personne ne connait la fin encore",
    "les mots que j'ecris sont des bouteilles jetees dans un ocean vide",
    "quelque part dans cette ville quelqu'un ressent exactement la meme chose",
    "la melancolie n'est pas une tristesse c'est une facon de voir le monde",
    "je ne sais pas ou je vais mais le chemin est beau quand meme",
    "entre le reve et la realite il y a cette chanson que je chante",
    "on grandit en apprenant a porter le poids de ses propres silences",
    "le monde tourne et moi je reste assis a regarder passer le temps",
    "les plus belles histoires sont celles qu'on ne raconte a personne jamais",
    "je vis dans les marges d'un monde trop etroit pour mes reves",
    "la solitude est une chambre dont j'ai perdu la clef quelque part",
    "parfois je me demande si les nuages ont la meme melancolie que moi",
    "le cafe refroidit et les heures passent sans que je m'en apercoive",
    "je suis l'auteur d'un roman dont je ne connais pas la suite",
    "les rues de la ville sont les veines d'un corps que j'habite seul",
    "entre deux trains il y a un quai ou ma vie attend encore",
    "la beaute se cache dans les choses que personne ne regarde jamais",
    "je vis au ralenti dans un monde qui court trop vite autour",
    "les souvenirs sont des photos qu'on regarde trop souvent jusqu'a les user",
    "quelque part entre hier et demain j'existe dans un present flou incertain",
    "les mots non dits pesent plus lourd que ceux qu'on crie fort",
    "je suis le spectateur de ma propre vie et le film est etrange",
    "la pluie lave les rues mais pas les traces que tu as laissees",
    "le monde est un musee ferme dont je regarde les oeuvres par la vitre",
    "je fais semblant d'aller quelque part mais je tourne en rond dans ma tete",
    "les chansons tristes sont les seules qui disent la verite nue entiere",
    "le temps passe et les choses changent mais ma fenetre donne sur le meme ciel"
  ],
  choruses: [
    "je me perds dans la ville et c'est la que je me trouve",
    "la pluie tombe et le monde est enfin a la bonne temperature",
    "je suis seul mais la solitude est ma plus vieille amie",
    "les rues vides chantent pour moi une chanson que je connais",
    "le ciel gris est le miroir de tout ce que je ressens",
    "je marche et chaque pas est un mot de cette chanson triste",
    "la melancolie est belle quand on sait la regarder en face",
    "les lumieres de la ville sont les etoiles de mon petit univers",
    "je vis entre les lignes d'un poeme que personne ne lira jamais",
    "la nuit tombe et je deviens enfin celui que je suis vraiment",
    "les feuilles tombent et chaque automne me ramene a toi encore",
    "je suis un fantome dans une ville qui ne me voit pas",
    "la musique joue et le monde a enfin un sens pour moi",
    "les mots me manquent mais le silence dit tout ce que je pense",
    "je reve les yeux ouverts et le monde est plus beau ainsi",
    "la vie passe comme un train et je suis reste sur le quai",
    "je porte la nuit en moi comme un manteau de velours sombre",
    "les souvenirs sont des films que je projette sur les murs gris",
    "la solitude a une musique et cette chanson est la mienne propre",
    "je cherche la lumiere dans les reflets d'une ville mouillee de larmes",
    "le monde tourne sans moi et je regarde tourner depuis ma fenetre",
    "les reves sont les seuls voyages que je peux encore me permettre",
    "je vis dans un polaroid un peu jauni par les jours qui passent",
    "la pluie est ma confidente et la nuit est mon journal intime",
    "je suis une note oubliee dans une melodie que tout le monde chante",
    "le cafe se boit seul et c'est bien ainsi parfois la nuit",
    "les pages se tournent et mon histoire s'ecrit sans que je comprenne",
    "je suis le dernier spectateur d'un cinema qui va bientot fermer",
    "la ville dort et ses reves se melent aux miens dans la brume",
    "je regarde le monde a travers un voile de nostalgie douce",
    "les nuits sont longues mais elles ont la beaute des choses lentes",
    "je me tais et le silence raconte mieux que je ne le ferais",
    "la vie est un brouillon que je n'ai pas le temps de mettre au propre",
    "les rues me connaissent mieux que les gens que je croise chaque jour",
    "je suis fait de pluie de cafe et de chansons oubliees ici",
    "le monde est un livre ouvert a une page que je ne comprends pas",
    "la nuit m'appartient et j'en fais un poeme que personne ne lit",
    "je collectionne les instants comme d'autres collectionnent les timbres anciens",
    "les lumieres s'eteignent et je reste seul avec mes pensees fideles",
    "la melancolie est un art et je suis devenu un artiste accompli",
    "je vis au rythme de la pluie et du vent qui me berce",
    "les mots s'accumulent dans ma tete comme la neige sur les toits",
    "je suis un disque raye qui repete le meme moment sans fin",
    "la ville est un poeme ecrit en neons et en pluie fine",
    "je regarde les heures passer et chacune emporte un morceau de moi",
    "les reves sont les seuls endroits ou je ne suis pas seul",
    "le monde est flou et c'est dans le flou que je vois clair",
    "je porte mes nuits blanches comme des medailles de guerre silencieuse",
    "la pluie s'arrete et le silence qui suit est presque assourdissant ici",
    "je suis le personnage secondaire de ma propre vie et ca me va",
    "la ville me berce dans ses bras de beton et de pluie fine",
    "je suis un vers libre dans un poeme que personne ne termine",
    "les trottoirs mouilles sont mon chemin et la pluie est ma boussole",
    "je vis dans l'entre-deux des jours et des nuits sans repit",
    "la melancolie est un fleuve et je me laisse porter sans resister",
    "les fenetres sont des ecrans ou passent des vies que je ne vis pas",
    "je suis le silence entre les mots d'une conversation que j'ai ratee",
    "la nuit me comprend mieux que le jour et ses lumieres crues",
    "les rues vides sont mon royaume et la lune est ma couronne",
    "je vis dans les marges de la page comme un mot non ecrit",
    "le cafe refroidit et le monde tourne sans se soucier de moi",
    "je suis un film muet dans un monde ou tout le monde crie",
    "les ombres sont mes compagnes et la lumiere est une etrangere ici",
    "la solitude est un jardin secret ou poussent mes plus belles pensees",
    "je regarde le monde se defaire et je ramasse les morceaux un par un",
    "les murs de cette ville sont les pages de mon autobiographie grise",
    "je suis une parenthese dans une phrase que le monde a oublie de fermer",
    "la pluie lave tout sauf les souvenirs qui collent a ma peau",
    "les pas que je fais sont des mots dans une chanson sans refrain",
    "je vis a contretemps dans un monde qui bat trop vite pour moi",
    "le ciel gris est mon toit et la pluie est ma couverture",
    "je suis le dernier cafe dans la tasse avant la fermeture du bar",
    "les reves sont les seules lettres que je recois et que je lis",
    "la nostalgie est un parfum que je porte sans jamais le choisir",
    "je marche dans la nuit et chaque lampadaire est un chapitre de plus",
    "le monde est un theatre et je suis assis au dernier rang seul",
    "les heures passent comme des pages blanches dans un carnet que je ne remplis pas",
    "je suis fait de silences et de bruits de pluie sur les toits",
    "la vie est un film d'auteur dont je cherche encore le sens profond",
    "les trottoirs sont mes pages et la pluie est l'encre de mon histoire"
  ],
  vocabulary: {
    nouns: [
      "melancolie", "nostalgie", "crepuscule", "brume", "polaroid",
      "vinyle", "cafe", "tasse", "librairie", "parapluie",
      "tramway", "gare", "quai", "velux", "parquet",
      "vitre", "reflet", "ombre", "carnet", "encre",
      "plafond", "fissure", "rebord", "gouttiere", "lucarne",
      "ampoule", "escalier", "moulure", "comptoir", "zinc",
      "buee", "crachin", "pave", "reverbere", "enseigne",
      "affiche", "bouquiniste", "grille", "volet", "balcon",
      "cheminee", "radiateur", "sonnette", "pallier", "moquette",
      "rideau", "store", "poussiere", "penombre", "silence",
      "aquarelle", "pellicule", "bobine", "cassette", "ecran",
      "projecteur", "diapositif", "cliche", "negatif", "expo",
      "galerie", "atelier", "toile", "chevalet", "pinceau",
      "machine", "portiere", "wagon", "billet", "valise",
      "carrefour", "ruelle", "passage", "impasse", "porche",
      "plafond", "mansarde", "grenier", "alcove", "niche",
      "thermos", "cigarette", "cendrier", "allumette", "briquet"
    ],
    verbs: [
      "errer", "flaner", "rever", "contempler", "mediter",
      "murmurer", "griffonner", "feuilleter", "observer", "soupirer",
      "s'effacer", "s'evanouir", "hesiter", "trainer", "divaguer",
      "se souvenir", "oublier", "attendre", "disparaitre", "surgir",
      "palir", "faner", "jaunir", "craquer", "grincer",
      "suinter", "embuer", "estomper", "diluer", "ternir",
      "frissonner", "trembler", "vaciller", "osciller", "clignoter",
      "resonner", "bruire", "chuchoter", "tinter", "fredonner",
      "collectionner", "accumuler", "empiler", "entasser", "conserver",
      "dechirer", "froisser", "plier", "effleurer", "caresser",
      "s'evaporer", "se dissoudre", "s'etioler", "se faner", "defraichir",
      "rembobiner", "projeter", "developper", "cadrer", "filmer",
      "esquisser", "crayonner", "dessiner", "peindre", "colorier",
      "deambuler", "vagabonder", "musarder", "baguenauder", "paresser",
      "grelotter", "claquer", "gemir", "soupirer", "haleter",
      "s'effriter", "se desagreger", "se deliter", "pericliter", "deperir"
    ],
    adjectives: [
      "melancolique", "nostalgique", "solitaire", "pensif", "reveur",
      "gris", "pale", "fane", "jauni", "delave",
      "brumeux", "voile", "flou", "estompe", "dilue",
      "silencieux", "feutre", "tamise", "assourdi", "muet",
      "fragile", "ebreche", "fele", "raye", "use",
      "oublie", "perdu", "abandonne", "deserte", "vide",
      "tiede", "attiedi", "refroidi", "humide", "mouille",
      "inacheve", "suspendu", "interrompu", "ephemere", "fugace",
      "poetique", "cinematographique", "litteraire", "pictural", "musical",
      "interieur", "intime", "secret", "invisible", "inavoue",
      "monochrome", "sepia", "pastel", "aquarelle", "crayonne",
      "granuleux", "grenu", "rugueux", "lisse", "satine",
      "fripe", "froisse", "chiffonne", "abime", "ecorne",
      "crepusculaire", "automnale", "hivernal", "brumeux", "pluvieux",
      "flottant", "suspendu", "aerien", "ethere", "diaphane",
      "contemplatif", "meditatif", "songeur", "absorbe", "distrait"
    ]
  }
};
