module.exports = {
  themes: [
    "fumee", "minuit", "notes bleues", "swing", "ame",
    "whisky", "club", "saxophone", "velours", "clair de lune",
    "improvisation", "blues", "nuit blanche", "melancolie", "rythme"
  ],
  openers: [
    "La Fumee S Eleve Lentement Dans Le Club De Minuit",
    "Le Saxophone Pleure Doucement Dans La Penombre Du Bar",
    "Sous Les Lumieres Tamisees Les Ombres Dansent Le Swing",
    "Le Piano Murmure Des Secrets A La Nuit Qui Ecoute",
    "Un Verre De Whisky Et La Melodie Prend Son Envol",
    "Les Notes Bleues S Echappent Dans La Fumee Du Soir",
    "Minuit Sonne Et La Ville Devient Un Reve De Velours",
    "Le Batteur Fait Parler Les Balais Sur La Caisse Claire",
    "Dans L Ombre Du Club Les Coeurs Battent En Contretemps",
    "La Contrebasse Vibre Et Le Monde S Arrete Un Instant",
    "Les Neons Clignotent Au Rythme Du Jazz De La Nuit",
    "Le Chanteur Ferme Les Yeux Et Laisse Parler Son Ame",
    "Sous La Pluie Fine Le Trombone Chante Sa Melancolie",
    "La Nuit De Velours Enveloppe Le Quartier Des Musiciens",
    "Le Tempo Ralentit Et Les Coeurs S Ouvrent Doucement Enfin",
    "Un Accord Mineur Et Le Monde Prend Une Teinte Bleue",
    "Les Doigts Glissent Sur Les Touches Du Piano Ancien Fatigue",
    "La Voix Rauque Du Chanteur Emplit La Salle De Fumee",
    "Le Reflet Du Neon Danse Dans Le Verre De Bourbon",
    "Sous Les Etoiles De La Ville Le Jazz Prend Vie",
    "Le Silence Entre Les Notes Est Aussi Beau Que La Musique",
    "La Trompette Bouchee Murmure Comme Un Amant Timide Ce Soir",
    "Les Couples Se Balancent Au Rythme Lent Du Dernier Set",
    "Un Solo De Piano Eclaire La Nuit Comme Un Phare",
    "La Pluie Sur Le Trottoir Fait Un Rythme De Balais",
    "Le Barman Essuie Un Verre En Ecoutant Le Blues Jouer",
    "Les Ombres Se Melent Aux Notes Dans Le Coin Du Bar",
    "La Clarinette Rit Et Pleure Dans La Meme Phrase Douce",
    "Le Vieux Jukebox Joue Une Ballade Que Personne N Oublie",
    "Sous Le Lampadaire Le Saxophoniste Joue Pour Les Passants",
    "Les Notes S Envolent Et Se Perdent Dans La Nuit Tiede",
    "Le Rythme Du Train Fait Swinguer Les Pensees Du Voyageur",
    "La Derniere Danse Du Soir Est Toujours La Plus Belle",
    "Le Pianiste Improvise Et Le Monde Retient Son Souffle",
    "Les Verres Tintent Comme Des Cymbales Dans Le Brouhaha Doux",
    "La Lune Se Pose Sur Le Toit Du Club Enfume",
    "Un Frisson Parcourt La Salle Quand Le Solo Commence Enfin",
    "Le Vent De La Nuit Porte Le Son Du Trombone Loin",
    "Les Doigts Du Bassiste Marchent Sur Les Cordes Avec Grace",
    "La Fumee Dessine Des Arabesques Au Dessus Des Musiciens",
    "Le Tempo Change Et Les Danseurs Suivent Sans Hesiter",
    "Sous Les Projecteurs La Chanteuse Brille Comme Un Diamant Rare",
    "Le Dernier Set Commence Et La Nuit Est Encore Jeune",
    "Les Notes Bleues Coulent Comme Du Miel Dans L Obscurite",
    "Le Batteur Sourit Et Lance Un Rythme Qui Fait Vibrer",
    "La Rue Mouille Reflete Les Lumieres Du Club De Jazz",
    "Un Accord De Septieme Et Le Coeur Se Serre Doucement",
    "Le Saxophone Alto Chante L Histoire De Tous Les Solitaires",
    "Les Bougies Tremblent Au Rythme De La Contrebasse Profonde",
    "La Nuit Est Un Poeme Que Le Jazz Ecrit Pour Nous"
  ],
  verses: [
    "la fumee monte en spirale vers le plafond du vieux club",
    "le saxophone murmure des mots que la bouche ne dit pas",
    "les doigts du pianiste courent sur les touches comme la pluie",
    "dans le verre de whisky le monde parait moins cruel ce soir",
    "la contrebasse pulse comme un coeur dans la penombre chaude",
    "les notes bleues peignent la nuit de teintes melancoliques",
    "le balai sur la caisse claire chuchote des secrets rythmes",
    "sous les lumieres tamisees les visages deviennent des mysteres doux",
    "le solo s envole et emporte les soucis de la journee",
    "la voix de la chanteuse coule comme du velours sombre",
    "les couples enlacees se balancent au rythme du slow profond",
    "le neon rouge clignote au rythme lent du blues nocturne",
    "un accord suspendu laisse le temps en suspension douce",
    "la pluie dehors accompagne le piano comme un duo parfait",
    "le barman verse le bourbon au rythme de la musique",
    "les ombres dansent sur les murs du club enfume ce soir",
    "le trombone glisse entre les notes comme un chat dans la nuit",
    "les yeux fermes le musicien voyage dans un autre monde",
    "la melodie s egare dans les ruelles sombres de la ville",
    "le rythme berce les ames fatiguees par le jour qui passe",
    "un verre se pose sur le comptoir comme une ponctuation douce",
    "la trompette bouchee pleure une larme de cuivre dans l air",
    "les doigts calleux du guitariste font chanter les cordes usees",
    "dans la fumee les souvenirs prennent la forme de melodies",
    "la nuit avance et le jazz devient plus intime et profond",
    "le silence entre deux morceaux est charge d emotion pure",
    "les notes graves de la contrebasse font vibrer le plancher",
    "la chanteuse ferme les yeux et le monde disparait autour",
    "le tempo accelere et les coeurs suivent sans reflechir",
    "un accord mineur fait basculer l ambiance dans le bleu sombre",
    "le vieux club sent le tabac froid et le bois cire",
    "les cymbales chuchotent comme la pluie sur un toit de zinc",
    "le piano solo eclaire la salle comme un rayon de lune",
    "les glacons fondent dans le verre au rythme des mesures lentes",
    "la melodie serpente a travers la fumee bleue du soir",
    "le batteur ferme les yeux et trouve le groove parfait",
    "les notes hautes du soprano percent le brouhaha du bar",
    "dans ce club on oublie le temps et ses contraintes lourdes",
    "la contrebasse et le piano conversent comme deux vieux amis",
    "le scat de la chanteuse imite les oiseaux de la nuit",
    "les lumieres baissent et la musique prend toute la place",
    "un riff de guitare electrise l air du petit bar sombre",
    "la melodie tourne en boucle comme les pensees d un reveur",
    "le whisky rechauffe la gorge et la musique rechauffe l ame",
    "les musiciens echangent des regards complices dans la penombre douce",
    "le tempo swing fait taper du pied meme les plus tristes",
    "la voix cassee du bluesman porte le poids du monde entier",
    "les notes s egrainent comme les heures dans la nuit longue",
    "le reflet des bougies danse dans les yeux des amoureux",
    "la clarinette basse ronronne dans le fond du mix sonore",
    "les applaudissements crepitent comme une pluie sur le trottoir chaud",
    "le son feutre de la sourdine adoucit le cuivre brillant",
    "dans le dernier set les musiciens donnent tout ce qui reste",
    "la fumee bleue enveloppe les musiciens comme un voile tendre",
    "le solo de batterie fait vibrer les murs du petit club",
    "les cordes de la contrebasse gemissent sous les doigts experts",
    "un soupir de saxophone et la nuit reprend son cours",
    "le pianiste plaque un accord et laisse resonner le silence",
    "les talons hauts claquent le rythme sur le parquet du club",
    "la melodie s improvise comme une conversation entre amis proches",
    "le vin rouge dans le verre a la couleur du blues",
    "les notes se chevauchent et creent une tapisserie sonore riche",
    "le rythme latin colore le jazz d une chaleur nouvelle inattendue",
    "la nuit de jazz est une parenthese dans le bruit du monde",
    "le vibraphone scintille comme des etoiles dans la nuit musicale",
    "les balades du petit matin sont les plus sinceres de toutes",
    "le groove de la basse fait onduler les corps fatigues",
    "dans l echo du club les notes trouvent leur chemin vers l ame",
    "la trompette ouverte eclate comme un soleil dans la nuit sombre",
    "les accords de passage ouvrent des portes vers des mondes inconnus",
    "le rubato du piano fait respirer la melodie librement",
    "les musiciens se regardent et le magic commence sans un mot",
    "la derniere note flotte dans l air comme un parfum delicat",
    "le saxophoniste souffle son ame dans le pavilion de cuivre",
    "les tables rondes du club sont des iles dans la nuit",
    "la basse electrique gronde comme un orage lointain mais present",
    "le charme du jazz reside dans ce qu on ne joue pas",
    "les verres vides sur le comptoir racontent la nuit passee",
    "un chorus de plus et la nuit sera complete enfin",
    "la flute traverse le mix comme un oiseau dans la brume",
    "les percussions murmurent et le corps se met a danser seul",
    "le piano rhodes fait miroiter les harmonies dans l air tiede",
    "la voix de la chanteuse monte et le silence se fait",
    "les notes dissonantes ajoutent du sel a la melodie douce",
    "le rythme binaire laisse place au ternaire et tout bascule",
    "dans la penombre du fond le trompettiste attend son tour",
    "la soiree avance et les improvisations deviennent plus audacieuses",
    "le charleston de la batterie fait swinguer le temps lui meme",
    "les harmoniques de la guitare resonnent comme des cloches lointaines",
    "le duo voix et piano est un dialogue entre deux ames",
    "la nuit s etire comme un solo sans fin ni mesure",
    "le barman connait par coeur le repertoire de chaque musicien",
    "les notes graves du baritone font trembler les verres sur le bar",
    "la musique coule et les fronts se decrispent peu a peu",
    "le vieux disque vinyle craque comme le plancher du club",
    "les bras du chef d orchestre dessinent la musique dans l air",
    "le pont du morceau ouvre une fenetre sur un autre monde",
    "la coda approche et les musiciens se retrouvent pour la fin",
    "les notes finales s eteignent comme les braises d une cigarette",
    "le silence apres le dernier accord est sacre et immense",
    "le rythme de la ville se mele au jazz du club",
    "la pluie s arrete et le saxophone continue seul dans la rue",
    "les souvenirs de cette nuit resteront graves dans les coeurs",
    "le piano prepare le terrain pour le solo a venir bientot",
    "la contrebasse marche sur la ligne entre ombre et lumiere",
    "le chorus libre explore des territoires que la partition ignore",
    "les glissandos du trombone font sourire les habitues du premier rang",
    "la musique de nuit a une saveur que le jour ne connait pas",
    "le dernier whisky accompagne la derniere chanson de la soiree",
    "les musiciens rangent leurs instruments et la magie s evapore doucement",
    "un dernier accord de neuvieme et le rideau tombe lentement",
    "la basse walking porte le groupe comme une mere son enfant",
    "le scat improvise fait rire et pleurer en meme temps",
    "les harmonies alterees donnent au morceau une couleur inattendue",
    "le ride de la cymbale scintille comme une riviere au soleil",
    "dans le club a moitie vide la musique sonne plus vraie",
    "la melodie revient au theme et le cercle est complet enfin",
    "le souffle du saxophoniste raconte une vie entiere en une note",
    "les doigts du pianiste trouvent des accords que la theorie ignore",
    "le rythme shuffle fait swinguer les hanches et les epaules",
    "la voix sans micro touche les coeurs plus que les amplis",
    "le jazz du petit matin est un secret entre inities",
    "les yeux mi clos le batteur sent chaque temps dans son corps",
    "la chaleur du club fait perler la sueur sur les fronts",
    "un standard bien joue vaut mieux que mille compositions creuses",
    "le ghroove s installe et plus personne ne veut partir ce soir",
    "la sourdine adoucit la trompette comme le soir adoucit la ville",
    "les notes perlees du piano tombent comme une pluie fine et douce",
    "le saxophone tenor hurle sa joie dans le refrain du morceau",
    "la nuit est un velours que la musique brode de fils d or",
    "le rythme change et les danseurs s adaptent avec grace naturelle",
    "les accords suspendus laissent le temps en apesanteur breve",
    "la derniere danse est toujours un peu plus lente que les autres",
    "le jazz est une conversation ou chacun parle et ecoute aussi",
    "les reverberes dehors eclairent la pluie comme des projecteurs de scene",
    "le duo basse batterie est le fondement sur lequel tout repose",
    "la voix grave du baryton fait vibrer les verres cristal",
    "un chorus de plus un verre de plus la nuit continue",
    "le piano ferme le morceau comme on ferme une lettre d amour",
    "les musiciens saluent et les applaudissements sont le dernier accord",
    "la nuit de jazz se termine mais la melodie reste en nous",
    "le club se vide lentement et le silence reprend ses droits",
    "les notes jouees ce soir ne seront jamais jouees de meme",
    "la magie de l instant est l essence meme du jazz pur",
    "le dernier souffle dans le saxophone clot la nuit musicale",
    "les pas sur le trottoir mouille font un dernier rythme doux",
    "la ville dort mais dans nos tetes le jazz joue encore",
    "le soleil pointe et les notes de la nuit s effacent",
    "la fumee se dissipe mais le souvenir reste intact et chaud",
    "un dernier regard au club et la porte se ferme doucement",
    "les melodies de cette nuit berceront nos reves jusqu au matin",
    "le saxophoniste nettoie son anche et range son instrument avec soin",
    "la nuit parisienne vibre au son des cuivres eclates joyeux",
    "le pianiste enchaine les standards comme on effeuille un bouquet",
    "les danseurs de lindy hop tournoient au milieu de la piste",
    "la voix du crooner fait soupirer les femmes au premier rang",
    "le son warm de l ampli a lampes rechauffe toute la salle",
    "les cocktails colores refletent les lumieres du petit club intime",
    "le batteur enchaine les breaks avec une precision milimetree parfaite",
    "la ligne de basse dessine un chemin sinueux dans la nuit",
    "le public retient son souffle pendant le solo de trompette pur",
    "les doigts agiles du guitariste effleurent les cordes comme une brise",
    "la reverb naturelle de la salle donne aux notes une profondeur unique",
    "le son du hautbois ajoute une touche classique au set de jazz",
    "les couples se serrent sur la piste au rythme de la ballade",
    "la nuit avance et les morceaux deviennent de plus en plus libres",
    "le son mat de la grosse caisse ponctue chaque phrase musicale",
    "les harmoniques du piano resonnent longtemps apres que les doigts se levent",
    "la fumee de cigarette forme un halo autour du spot lumineux",
    "le trompettiste souffle une note haute qui perce le plafond de fumee",
    "les verres de martini tremblent quand la basse descend dans les graves",
    "la voix de la chanteuse glisse entre les notes du piano",
    "le hi hat siffle doucement comme un serpent amical dans la nuit",
    "les standards de cole porter prennent une couleur nouvelle ce soir",
    "la nuit de jazz sent le bois verni et le cuir use",
    "le guitariste joue en picking et chaque note est une perle",
    "les arrangements de cuivre habillent la melodie comme du satin fin",
    "la chanteuse monte d une octave et la salle frissonne en silence",
    "le son sourd du tom basse fait vibrer les entrailles du club",
    "les accords de treizieme ouvrent des horizons harmoniques insoupcones et vastes",
    "le club new orleans resonne de cuivres et de joie de vivre",
    "la trompette wa wa raconte des histoires droles dans le silence",
    "les nappes de rhodes flottent comme des nuages dans l air nocturne",
    "le bassiste slap ajoute du funk au swing traditionnel du groupe",
    "la batterie aux balais fait un son de pluie douce eternelle",
    "le public tape des mains sur le deux et le quatre",
    "les chorus s enchainent et chaque musicien donne le meilleur de soi",
    "la salle est si petite que la musique touche chaque ame",
    "le son du flugelhorn est plus doux que le miel le soir",
    "les touches noires du piano dessinent des gammes pentatoniques bleues",
    "la chanteuse scat fait danser les syllabes comme des papillons nocturnes",
    "le son de l orgue hammond tourne dans le leslie comme un reve",
    "les musiciens transpirent sous les projecteurs mais le groove ne faiblit pas",
    "la contrebasse pizzicato ponctue chaque temps comme un battement de coeur",
    "le son clair du vibraphone egraine des notes de cristal pur",
    "les cuivres en sourdine murmurent comme des voix dans un reve lointain",
    "la basse fretless glisse entre les notes sans aucune frontiere audible",
    "le charleston ferme cree un tissu rythmique serre et precis",
    "la melodie du theme revient apres les solos comme un vieil ami",
    "le barman connait les gouts de chaque habitue du club fidele",
    "les tables au fond sont reservees aux amoureux et aux poetes",
    "le saxophoniste joue les yeux fermes et le monde disparait autour",
    "la contrebasse archet fait pleurer les cordes dans un registre grave",
    "le son du piano prepare est percussif et mysterieux a la fois",
    "les lumieres du club changent de couleur au fil des morceaux",
    "la trompette ouverte eclate comme un feu d artifice sonore",
    "le rythme bossa nova amene le soleil dans ce club de nuit",
    "les musiciens echangent des quatre mesures dans un dialogue electrique",
    "la voix susurree de la chanteuse est plus intime qu une confession",
    "le son du bandoneon ajoute une touche de tango a la soiree",
    "les couples dansent joue contre joue sur le parquet use du club",
    "la melodie en mineur fait couler les larmes des plus endurcis",
    "le batteur joue si doucement qu on entend les coeurs battre autour",
    "les notes du celesta brillent comme des diamants dans l obscurite",
    "la basse electrique ronronne dans le fond du mix avec chaleur",
    "le pianiste cite un theme de monk et les connaisseurs sourient",
    "les arrangements ecrits laissent de la place pour la liberte improvisee",
    "la voix et le saxophone chantent a l unisson puis se separent",
    "le rythme afro cubain fait bouger les hanches de toute la salle",
    "les accords diminues creent une tension que le refrain resout enfin",
    "la nuit s ecoule comme un long solo de saxophone tenor",
    "le son feutre des balais sur la peau de la caisse claire",
    "les musiciens jouent pour eux memes et le public est temoin",
    "la chanteuse chante en portugais et le club devient rio ce soir",
    "le piano stride fait danser la main gauche sur les basses",
    "les notes rapides du bebop defient les lois de la gravite",
    "la contrebasse en doubles cordes remplit l espace de sa puissance",
    "le guitariste manouche fait courir ses doigts a une vitesse folle",
    "les cuivres en section jouent un riff qui colle a la peau",
    "la voix grave de la chanteuse fait trembler les murs du club",
    "le solo de batterie est un monologue passionne qui dit tout",
    "les musiciens terminent ensemble sur une note tenue puis le silence vient",
    "la pluie reprend dehors et accompagne les derniers accords du soir",
    "le jazz modal ouvre des espaces immenses dans la petite salle",
    "les harmonies vocales enveloppent la melodie comme un ecrin precieux",
    "la nuit est longue et le repertoire semble ne jamais s epuiser",
    "le public commande un dernier verre en ecoutant la derniere ballade",
    "les photos au mur montrent les legendes qui ont joue ici avant",
    "la vibration du sol sous les pieds raconte l histoire du groove",
    "le chorus final rassemble tous les musiciens dans un tourbillon sonore",
    "la note finale vibre dans l air et personne n ose applaudir encore",
    "les lumieres se rallument doucement et la realite revient petit a petit",
    "le jazz de ce soir fut une parenthese enchantee hors du temps",
    "les musiciens se serrent la main et promettent de revenir bientot",
    "la porte du club s ouvre sur la nuit fraiche et silencieuse",
    "le trottoir mouille reflete les dernieres lumieres du club qui ferme",
    "les notes de cette soiree resonnent encore dans les ruelles vides",
    "la ville endormie garde en elle le souvenir de la musique jouee",
    "le dernier taxi emporte un musicien et son etui de saxophone use",
    "les reverberes projettent des ombres longues sur le pave humide et brillant",
    "le piano a queue murmure des accords oublies dans la penombre chaude",
    "les bougies fondent et la cire coule au rythme du blues lent",
    "le saxophoniste alto souffle une note longue qui traverse le mur du temps",
    "la pluie dessine des notes de musique sur la vitre du club",
    "le tabouret du bar porte les marques de mille nuits de jazz",
    "les aiguilles de l horloge avancent mais la musique reste suspendue",
    "le trombone a coulisse glisse entre les ombres comme un fantome doux",
    "la derniere gorgee de whisky a le gout de la melancolie",
    "le pianiste joue un diminue et le monde se teinte de bleu",
    "les talons de la chanteuse claquent un rythme sur le sol cire",
    "la fumee s echappe par la porte entrouverte du club assoupi",
    "le batteur effleure les cymbales avec la douceur d une caresse furtive",
    "les conversations se taisent quand le solo de trompette commence enfin",
    "la voix de la chanteuse enroule les mots autour de la melodie",
    "le barman sert un dernier verre et la musique change de ton",
    "les doigts du bassiste marchent sur les cordes comme un funambule",
    "la nuit parisienne sent la pluie le tabac et les notes bleues",
    "le vibraphone egraine des perles de son dans l air enfume tiede",
    "les couples quittent la piste et la musique devient plus intime",
    "le pianiste improvise un prelude que personne n a jamais entendu avant",
    "la contrebasse gronde doucement comme un orage tres lointain dans la nuit",
    "le verre de cognac capte la lumiere tamisee comme une ambre liquide",
    "les musiciens s ecoutent et chaque silence est une note de plus",
    "la voix grave du crooner fait vibrer l air comme un violoncelle",
    "le charme de cette soiree tient dans les espaces entre les notes",
    "les rideaux de velours absorbent les dernieres notes du set de nuit",
    "le saxophone soprano perce le brouhaha comme un rayon de lune clair",
    "la nuit avance a pas feutres et la musique l accompagne doucement",
    "le piano prepare le terrain pour un solo qui n arrivera peut etre pas",
    "les verres alignes sur le comptoir refletent les lumieres du club",
    "la chanteuse respire entre deux phrases et le monde retient son souffle",
    "le batteur joue les balais si doucement qu on entend la pluie dehors",
    "les couples enlacees oscillent comme des algues dans un courant de notes",
    "la trompette murmure ce que le coeur n ose pas dire tout haut",
    "le son du piano electrique flotte comme un nuage dans la salle",
    "les accords de treizieme ouvrent des fenetres sur des paysages sonores",
    "la derniere danse commence et les lumieres baissent encore d un cran",
    "le saxophoniste souffle comme s il voulait vider son ame par le bec",
    "les spectateurs ferment les yeux et voient la musique en couleurs",
    "la guitare acoustique ajoute une chaleur intime au fond du mix sonore",
    "le groove se pose comme un chat qui s installe et ne bouge plus",
    "les notes mineures font tomber les masques dans la penombre complice",
    "la voix de la chanteuse craquele comme un vieux vinyle qui tourne",
    "le piano joue seul un instant et le monde devient un ecrin",
    "les musiciens transpirent l art par chaque pore de leur peau",
    "la nuit est un club dont personne ne veut etre exclu jamais",
    "le son de la clarinette serpente entre les tables comme de la fumee",
    "les basses profondes font vibrer les fondations du vieux batiment",
    "la melodie s eleve en spirale comme la fumee d un cigare fin",
    "le rubato du soliste suspend le temps entre deux battements de coeur",
    "les chaises vides du premier rang attendent les habitues de la nuit",
    "la voix sans vibrato touche le coeur avec une sincerite desarmante",
    "le saxophone baryton ronronne dans le registre grave comme un felin",
    "les accords suspendus laissent la melodie en apesanteur un long moment",
    "la pluie s intensifie dehors et le club devient un refuge sacre",
    "le batteur change de baguettes pour les balais et l ambiance s adoucit",
    "les nappes d orgue flottent dans la salle comme de la brume matinale",
    "la note tenue du saxophoniste dure plus longtemps que le temps lui meme",
    "le barman ferme les yeux un instant et savoure la derniere ballade",
    "les cuivres en sourdine murmurent des prieres profanes dans le noir",
    "la basse fretless dessine des courbes invisibles dans l air de la nuit",
    "le piano joue les touches noires et le blues prend sa plus belle robe",
    "les lumieres du neon dessinent des reflets bleus sur le pare brise",
    "la trompette ouverte hurle une joie presque douloureuse dans le silence",
    "le rythme change de couleur comme le ciel au crepuscule d automne",
    "les notes du celesta tombent comme des gouttes de pluie sur un miroir",
    "la voix de la chanteuse caresse les mots comme des pierres precieuses",
    "le solo de guitare manouche fait courir des frissons sur les bras",
    "les ombres des musiciens se projettent sur le mur comme une fresque",
    "la contrebasse soutient le groupe comme un pilier de chene dans la nuit",
    "le verre de vin rouge tremble quand la basse descend aux graves",
    "les fioritures du piano embellissent la melodie comme de la dentelle fine",
    "la nuit bleue coule entre les notes comme de l encre dans l eau",
    "le saxophoniste alto cite un standard et les connaisseurs hochent la tete",
    "les mains du batteur sont si legeres qu elles semblent ne pas toucher",
    "la chanteuse de jazz est une conteuse qui chante au lieu de parler",
    "le son du cor anglais ajoute une touche pastorale au set du soir",
    "les applaudissements s eteignent et le silence qui suit est musical aussi",
    "la derniere note du piano resonne dans la salle comme un adieu tendre",
    "le jazz de minuit a un parfum que l on ne trouve nulle part",
    "les musiciens de rue jouent sous la pluie et la ville les ecoute",
    "la flute traversiere dessine des arabesques dans l air chaud du club",
    "le son du banjo ajoute une touche de nostalgie au set de jazz",
    "les doigts uses du guitariste connaissent chaque note par la memoire du toucher",
    "la voix rauque du baryton fait vibrer les verres sur les tables",
    "le tempo shuffle berce la salle comme un bateau sur l eau calme",
    "les arrangements de cordes enveloppent le jazz d un manteau de soie douce",
    "la nuit s effrite comme du tabac et les notes sont les miettes",
    "le public ne bouge plus comme si le temps s etait fige ici",
    "les notes du marimba rebondissent dans la salle comme des billes de verre",
    "la chanteuse monte dans les aigus et le plafond semble s elever",
    "le groove du funk jazz fait bouger les pieds sous les tables",
    "les ombres et les lumieres jouent ensemble comme un duo de contrebasse",
    "la nuit est un disque vinyle qui tourne sans fin sur la platine",
    "le saxophoniste range son instrument et le silence est un dernier accord",
    "les rues vides du petit matin portent encore l echo des cuivres",
    "la ville s eveille et les notes de la nuit s endorment enfin",
    "le dernier musicien quitte le club avec la melodie encore dans les doigts",
    "les souvenirs de cette nuit de jazz resteront comme un tatouage invisible",
    "le son de la nuit vibre encore dans les murs du vieux club vide"
  ],
  bridges: [
    "car la nuit est faite pour ceux qui savent ecouter",
    "et le jazz coule dans nos veines comme du whisky chaud",
    "mais la melodie continue meme quand la musique s arrete",
    "car les notes bleues guerissent les blessures que le jour inflige",
    "et dans le silence entre deux notes vit toute la musique",
    "mais le rythme revient toujours comme les marees de la nuit",
    "car le jazz est la voix de ceux qui ne parlent pas",
    "et la fumee emporte nos peines vers le plafond du monde",
    "mais la nuit finit toujours par ceder la place au jour",
    "car le swing fait battre les coeurs a l unisson ce soir",
    "et les notes improvisees sont les plus sinceres de toutes",
    "mais le blues est une lumiere deguisee en ombre douce",
    "car la musique dit ce que les mots ne peuvent pas",
    "et le dernier verre est le meilleur quand la musique joue",
    "mais chaque nuit de jazz est unique et ne revient jamais",
    "car le groove est un langage que tout le monde comprend",
    "et les larmes sur les touches du piano font de belles notes",
    "mais l improvisation est un saut dans le vide magnifique",
    "car le saxophone connait la verite que le coeur cache",
    "et la contrebasse porte le poids du monde avec elegance",
    "mais la derniere chanson est toujours la plus belle du set",
    "car le jazz vit dans l espace entre les notes jouees",
    "et le rythme de la pluie est le meilleur des batteurs",
    "mais la melancolie du jazz est douce comme le velours noir",
    "car les meilleurs solos naissent quand on arrete de reflechir",
    "et la nuit nous donne la permission d etre nous memes",
    "mais le matin efface les reves que le jazz avait dessines",
    "car le club est un refuge pour les ames vagabondes",
    "et les notes de minuit ont une saveur que l aube ne connait pas",
    "mais chaque fin de set est le debut d une autre histoire",
    "car la musique de nuit parle directement a l ame profonde",
    "et le whisky et le jazz sont les deux faces du reconfort",
    "mais les meilleurs moments sont ceux que l on n attendait pas",
    "car le jazz est une priere pour ceux qui ne croient plus",
    "et la nuit appartient a ceux qui osent ecouter le silence"
  ],
  choruses: [
    "les notes bleues eclairent la nuit comme des etoiles de son",
    "le jazz coule dans nos veines et fait danser nos ames",
    "sous les lumieres tamisees nous sommes enfin nous memes ce soir",
    "la musique est le seul langage qui ne ment jamais",
    "le saxophone pleure et nos coeurs pleurent avec lui doucement",
    "dans la fumee du club nous trouvons notre verite cachee",
    "le rythme du jazz est le battement de coeur de la nuit",
    "les notes s envolent et emportent nos soucis avec elles loin",
    "le swing fait danser les ombres sur les murs du bar",
    "nous sommes les enfants de la nuit et du blues profond",
    "la melodie nous berce comme les vagues sur un rivage doux",
    "le piano parle et nous ecoutons avec le coeur ouvert",
    "les notes bleues sont les etoiles du ciel de minuit chaud",
    "le jazz est notre refuge quand le monde tourne trop vite",
    "dans chaque note vit une histoire que seul le coeur comprend",
    "la nuit est notre scene et le jazz notre seule lumiere",
    "le son du saxophone est la couleur du bleu profond nocturne",
    "nous dansons sur les notes comme sur des nuages de velours",
    "le rythme nous porte et nous n avons plus besoin de rien",
    "les notes bleues guerissent les blessures invisibles de nos jours",
    "le jazz est la bande son de nos nuits les plus belles",
    "dans le silence du club la musique parle plus fort",
    "le swing est un sourire que le corps ne peut retenir",
    "nous sommes les reveurs de minuit bercees par le blues doux",
    "la melodie improvise et nos coeurs suivent sans hesiter un instant",
    "le saxophone alto est la voix de notre melancolie douce",
    "les notes coulent comme le whisky chaud dans la nuit froide",
    "le jazz est une lettre d amour ecrite en notes bleues",
    "la contrebasse pulse et nous respirons au rythme de la nuit",
    "dans chaque improvisation vit une liberte que le jour nous refuse",
    "les lumieres tamisees et le jazz font de la nuit un reve",
    "le rythme swing fait oublier que le monde existe dehors",
    "nous sommes la fumee et la musique et la nuit ensemble",
    "le piano murmure ce que les levres n osent pas dire",
    "les notes de minuit sont plus vraies que les mots du jour",
    "le jazz est un voyage sans carte ni destination precise",
    "la voix de la chanteuse est le velours de la nuit bleue",
    "le rythme nous lie les uns aux autres dans la penombre",
    "les notes bleues peignent nos reves sur la toile de la nuit",
    "le club est notre ile et le jazz notre ocean infini",
    "dans chaque silence entre les notes vit un univers entier",
    "le saxophone dessine des courbes dans l air enfume du soir",
    "nous dansons avec nos ombres au rythme du vieux piano",
    "la musique de nuit est un secret que partagent les insomniaques",
    "le jazz est le fil qui relie nos solitudes entre elles",
    "les notes bleues tombent comme une pluie douce sur nos ames",
    "le rythme de la nuit bat dans nos poitrines unies",
    "nous sommes vivants quand la musique joue et le monde s efface",
    "le dernier morceau est une promesse que la nuit reviendra bientot",
    "le jazz est la reponse a une question que personne ne pose",
    "les notes coulent dans la nuit comme un fleuve de velours bleu",
    "le club est notre monde et la musique notre seul oxygene",
    "sous les lumieres nous oublions tout sauf le rythme et le silence",
    "le jazz peint la nuit avec des couleurs que le jour ignore",
    "nous respirons la musique et la musique respire a travers nous",
    "les ombres dansent et la melodie les guide dans le noir chaud",
    "le saxophone est la voix de tous les coeurs solitaires du monde",
    "nous sommes les gardiens d une nuit que le jazz rend eternelle",
    "les notes bleues tombent et font naitre des fleurs dans le silence",
    "le rythme nous enlace et nous dansons sans toucher le sol",
    "le piano murmure des verites que personne n ose dire a voix haute",
    "nous sommes la fumee et la musique entrelacees dans la nuit bleue",
    "les notes improvisees sont des oiseaux de nuit qui volent sans cage",
    "le jazz nous enveloppe comme un manteau de velours et de brume",
    "la melodie coule et nos soucis fondent comme glace dans le whisky",
    "nous dansons entre les notes comme des ombres entre les reverberes",
    "le swing nous porte et nous n avons plus besoin de sol ferme",
    "les notes de minuit guerissent les blessures que le soleil a faites",
    "le jazz est le parfum de la nuit que le jour ne connait pas",
    "nous sommes les enfants du silence et du son dans la penombre",
    "la musique coule et la nuit devient un reve sans reveil",
    "le saxophone pleure des larmes de cuivre et nous pleurons avec lui",
    "sous les spots tamises le monde est plus doux et plus vrai",
    "le jazz est un bateau qui navigue sur un ocean de bleu",
    "nous ecoutons le silence entre les notes et tout est dit enfin",
    "les accords suspendus tiennent nos coeurs en equilibre dans la nuit",
    "le rythme du coeur et le rythme du jazz ne font qu un",
    "nous sommes la derniere note qui vibre quand la chanson est finie",
    "le jazz est la couleur de la nuit la plus profonde et belle",
    "la musique est le seul feu qui rechauffe sans jamais bruler l ame"
  ],
  vocabulary: {
    nouns: [
      "saxophone", "piano", "contrebasse", "trompette", "trombone",
      "fumee", "velours", "whisky", "bourbon", "neon",
      "club", "scene", "penombre", "minuit", "aube",
      "blues", "swing", "groove", "rythme", "melodie",
      "solo", "accord", "note", "silence", "tempo",
      "ballade", "scat", "chorus", "improvisation", "harmonie",
      "barman", "comptoir", "bougie", "verre", "glace",
      "ombre", "lumiere", "reflet", "murmure", "echo",
      "sourdine", "cymbale", "balai", "corde", "touche",
      "trottoir", "lampadaire", "pluie", "brume", "reverie",
      "clarinette", "vibraphone", "bandoneon", "orgue", "harmonica",
      "cabaret", "lounge", "estrade", "rideau", "coulisse",
      "cravate", "fedora", "costume", "monocle", "pochette",
      "cognac", "rhum", "absinthe", "cocktail", "glacon",
      "tabac", "cendre", "braise", "encens", "ambre",
      "ruelle", "impasse", "arcade", "passage", "porche",
      "crescendo", "diminuendo", "staccato", "legato", "rubato"
    ],
    verbs: [
      "swinguer", "improviser", "murmurer", "resonner", "vibrer",
      "glisser", "flotter", "onduler", "scintiller", "caresser",
      "soupirer", "fredonner", "moduler", "syncopper", "pulser",
      "balancer", "envelopper", "bercer", "embrumer", "enfumer",
      "couler", "ruisseler", "miroiter", "papilloter", "bruisser",
      "chuchoter", "susurrer", "planer", "voltiger", "effleurer",
      "languir", "rever", "savourer", "deguster", "contempler",
      "ecouter", "ressentir", "frissoner", "osciller", "tanguer",
      "chalouper", "enlacer", "etreindre", "souffler", "exhaler",
      "bourdonner", "tinter", "gronder", "feutrer", "estomper",
      "swinger", "groover", "phraser", "accentuer", "ponctuer",
      "siroter", "deguster", "savourer", "humer", "respirer",
      "voluter", "spiraler", "serpenter", "sinuer", "louvoyer",
      "teinter", "colorer", "nuancer", "ombrer", "voiler",
      "se dissoudre", "se fondre", "s'evaporer", "se diluer", "se volatiliser",
      "improviser", "broder", "orner", "embellir", "enjoliver"
    ],
    adjectives: [
      "bleu", "nocturne", "enfume", "tamise", "feutre",
      "veloute", "soyeux", "languide", "melancolique", "nostalgique",
      "intime", "profond", "subtil", "sensuel", "enivrant",
      "suave", "delicat", "mysterieux", "onirique", "hypnotique",
      "doux", "grave", "aigu", "sourd", "cristallin",
      "chaleureux", "cuivre", "boise", "ambree", "mordore",
      "crepusculaire", "brumeaux", "vaporeux", "ethere", "diffus",
      "improvise", "spontane", "libre", "fluide", "aerien",
      "rauque", "voile", "tremblant", "fragile", "ephemere",
      "urbain", "souterrain", "interlope", "boheme", "cosmopolite",
      "cuivre", "ambre", "mordore", "fauve", "ocre",
      "nacre", "ivoire", "ebene", "acajou", "palissandre",
      "capricieux", "fantaisiste", "espiegle", "malicieux", "mutin",
      "nonchalant", "desinvolte", "detache", "insouciant", "neglige",
      "canaille", "coquin", "fripon", "polisson", "voyou",
      "brumeux", "pluvieux", "orageux", "couvert", "bas"
    ]
  }
};
