/**
 * K-pop Genre — French Phrase Bank
 * Themes: shine, dream, candy, love, together, dance, colors, sparkle, youth, cute
 */
module.exports = {
  themes: [
    "eclat", "reve", "bonbon", "amour", "ensemble",
    "danse", "couleurs", "etincelle", "jeunesse", "mignon",
    "etoile", "lumiere", "magie", "arc-en-ciel", "fete"
  ],
  openers: [
    "Ce Soir On Brille Sous Les Lumieres De La Scene",
    "Mon Coeur Bat Comme Un Rythme De K-pop",
    "Les Etoiles Dansent Avec Nous Ce Soir",
    "On Est Ensemble Et Rien Ne Peut Nous Arreter",
    "Le Monde Entier Est Notre Scene Ce Soir",
    "Nos Reves Brillent Plus Fort Que Les Etoiles",
    "La Musique Nous Porte Vers Le Ciel Ce Soir",
    "On Danse Comme Si Demain N'existait Pas",
    "Les Couleurs De La Nuit Nous Enveloppent De Magie",
    "Chaque Battement De Coeur Eclaire Notre Chemin",
    "On Est Les Etoiles De Cette Nuit Sans Fin",
    "La Scene Est A Nous Et Le Monde Nous Regarde",
    "Nos Voix S'elevent Plus Haut Que Les Nuages",
    "Ce Soir On Ecrit Notre Histoire En Lettres De Lumiere",
    "Le Rythme Nous Emporte Dans Un Tourbillon De Couleurs",
    "On Brille Si Fort Que Le Soleil Est Jaloux",
    "La Magie De Nos Reves Prend Vie Ce Soir",
    "Ensemble On Peut Toucher Les Etoiles Du Bout Des Doigts",
    "Les Lumieres De La Ville Dansent Pour Nous Ce Soir",
    "Notre Amour Brille Comme Un Arc-en-ciel Infini",
    "On Est Inarretables Quand La Musique Joue Pour Nous",
    "Le Monde Est Plus Beau Quand On Danse Ensemble",
    "Nos Coeurs Battent Au Meme Rythme Ce Soir",
    "La Nuit Est Jeune Et Nos Reves Sont Immenses",
    "On Illumine Le Ciel Avec Nos Voix Ce Soir",
    "Chaque Pas De Danse Nous Rapproche Des Etoiles",
    "Le Bonheur Eclate En Mille Couleurs Autour De Nous",
    "On Est La Lumiere Qui Brille Dans L'obscurite",
    "Nos Reves S'envolent Comme Des Confettis Dores",
    "Ce Soir Le Monde Entier Danse Avec Nous",
    "La Musique Nous Unit Dans Un Eclat De Joie",
    "On Cree La Magie A Chaque Instant Ce Soir",
    "Les Etoiles Tombent Dans Nos Mains Ouvertes Ce Soir",
    "Notre Energie Fait Trembler Les Murs Ce Soir",
    "On Peint Le Ciel Avec Les Couleurs De Nos Reves",
    "Le Rythme De Nos Coeurs Fait Vibrer La Nuit",
    "Ensemble On Est Plus Forts Que Tous Les Orages",
    "La Scene Brille De Mille Feux Quand On Arrive",
    "Nos Pas Dessinent Des Etoiles Sur Le Sol",
    "On Est Les Heros De Cette Histoire Magique",
    "Ce Soir On Danse Jusqu'a Toucher Le Ciel",
    "La Lumiere De Nos Reves Guide Nos Pas Ce Soir",
    "On Fait Briller Chaque Instant Comme Un Diamant",
    "Les Couleurs De Nos Ames Eclairent La Scene Ce Soir",
    "Notre Amitie Brille Plus Fort Que Mille Soleils",
    "On S'envole Ensemble Vers Un Monde De Reves Dores",
    "Le Ciel Entier Chante Avec Nous Ce Soir",
    "Nos Sourires Illuminent La Nuit Comme Des Etoiles",
    "On Est La Generation Qui Brille Sans Jamais S'eteindre",
    "Ce Soir La Magie Est Partout Autour De Nous"
  ],
  verses: [
    "on danse sous les lumieres comme des etoiles filantes",
    "mon coeur bat si fort quand tu me regardes",
    "les couleurs du monde brillent dans tes yeux ce soir",
    "on est ensemble et tout devient plus beau ici",
    "le rythme nous emporte loin de tout ce soir",
    "nos reves sont faits de paillettes et de lumiere",
    "tu fais briller mon monde comme un arc-en-ciel magique",
    "chaque instant avec toi est un cadeau precieux ce soir",
    "on tourne sous les projecteurs comme des diamants en feu",
    "la musique coule dans nos veines ce soir ensemble",
    "tes yeux brillent comme des etoiles dans le ciel noir",
    "on defie la gravite quand on danse ensemble ce soir",
    "le monde est notre scene et on brille fort dessus",
    "nos voix s'harmonisent comme une melodie parfaite ce soir",
    "tu es la lumiere qui guide mes pas dans la nuit",
    "on eclaire la ville avec nos sourires dores ce soir",
    "chaque battement de coeur est un pas de danse magique",
    "le bonheur coule comme une riviere de paillettes ici",
    "on fait trembler le sol avec notre energie ce soir",
    "tes mains dans les miennes et le monde s'arrete un instant",
    "on brille si fort que la nuit devient jour ce soir",
    "les confettis tombent comme une pluie de reves dores",
    "notre energie fait vibrer les murs de la salle entiere",
    "on danse comme si c'etait la derniere nuit du monde",
    "le rose et le bleu se melangent dans le ciel ce soir",
    "ton sourire est la plus belle melodie que je connais",
    "on saute si haut qu'on touche les nuages ce soir",
    "les lumieres clignotent au rythme de nos coeurs unis",
    "on est les rois et les reines de cette nuit magique",
    "chaque note de musique fait danser notre ame ce soir",
    "le monde entier nous regarde briller sur cette scene doree",
    "on court vers nos reves sans jamais regarder en arriere",
    "les etoiles dessinent nos noms dans le ciel ce soir",
    "notre amour est fait de sucre et de lumieres brillantes",
    "on fait la fete comme si demain n'existait pas du tout",
    "tes yeux sont deux galaxies ou je veux me perdre toujours",
    "on tourbillonne dans un univers de couleurs et de joie",
    "le beat fait battre nos coeurs a l'unisson ce soir ensemble",
    "on est inarretables quand la musique prend le dessus ici",
    "les papillons dans mon ventre dansent quand tu es la",
    "on peint le ciel avec nos reves les plus fous ce soir",
    "chaque seconde avec toi vaut plus que tout l'or du monde",
    "on fait briller la nuit avec notre jeunesse eternelle ici",
    "le rythme de nos pas dessine des etoiles sur le sol",
    "on s'envole ensemble vers un monde ou tout est possible",
    "tes paroles sont douces comme du miel sur mes levres ce soir",
    "on danse pieds nus sur les nuages de nos reves dores",
    "les neons eclairent nos visages de mille couleurs vives ce soir",
    "on est la lumiere que le monde attendait depuis toujours",
    "notre histoire s'ecrit en lettres de feu dans le ciel noir",
    "on brille comme des diamants sous les projecteurs ce soir ensemble",
    "le monde est fait de bonbons quand tu es a mes cotes",
    "on fait vibrer la terre avec notre joie immense ce soir",
    "tes rires sont les plus belles notes de ma chanson preferee",
    "on tourne en rond dans un tourbillon de bonheur infini",
    "les etoiles sont jalouses de la lumiere de nos yeux",
    "on danse avec le vent et la lune nous applaudit ce soir",
    "chaque moment ensemble est un tresor que je garde precieusement",
    "on eclaire le chemin avec la flamme de nos reves immenses",
    "le ciel est rose et nos coeurs sont pleins de joie pure",
    "on fait la revolution avec nos pas de danse ce soir",
    "tes mains brillent comme des etoiles quand tu danses avec moi",
    "on est les enfants de la lumiere et de la musique eternelle",
    "les confettis sont nos etoiles et la scene notre galaxie",
    "on repousse les limites du possible avec notre energie ce soir",
    "le monde est un bonbon geant et on croque dedans fort",
    "on fait battre le coeur de la ville ce soir ensemble",
    "tes yeux sont mon ciel et ton sourire est mon soleil dore",
    "on danse si vite que le temps s'arrete autour de nous",
    "les couleurs de l'arc-en-ciel vivent dans notre musique ce soir",
    "on est la jeunesse dorée qui fait trembler le monde entier",
    "chaque pas de danse est une declaration d'amour au monde",
    "on brille dans le noir comme des lucioles un soir d'ete",
    "le beat accelere et nos coeurs suivent le rythme parfaitement",
    "on est les etoiles montantes qui eclairent la nuit entiere",
    "tes mots sont des etincelles qui allument mon coeur ce soir",
    "on fait la fete sous un ciel de confettis colores ensemble",
    "les lumieres de la ville dansent dans tes yeux ce soir",
    "on est ensemble et c'est tout ce qui compte vraiment ici",
    "le rythme de nos ames cree une symphonie de lumiere pure",
    "on court pieds nus vers l'horizon sans jamais s'arreter ce soir",
    "tes reves sont mes reves et on les vit ensemble maintenant",
    "on fait briller chaque seconde comme une pierre precieuse rare",
    "les papillons de nos reves s'envolent vers le ciel dore ce soir",
    "on danse avec les etoiles jusqu'au lever du soleil rouge",
    "le monde est notre terrain de jeu et on s'amuse fort",
    "on eclaire chaque coin sombre avec notre lumiere interieure ce soir",
    "tes bras sont mon refuge et ton coeur est ma maison",
    "on fait trembler les etoiles avec la force de nos voix",
    "les couleurs de nos reves peignent le ciel chaque nuit sombre",
    "on est la melodie que le monde n'oubliera jamais ce soir",
    "chaque note que tu chantes fait danser mon ame entiere",
    "on tourne sous les spots comme des joyaux dans la lumiere",
    "le bonheur est un feu d'artifice dans notre coeur ce soir",
    "on s'eleve au-dessus des nuages avec notre amour immense",
    "tes yeux sont des lanternes qui eclairent ma nuit sombre",
    "on danse avec la pluie et chaque goutte est une note",
    "les reves de notre jeunesse brillent comme des etoiles filantes dorées",
    "on est la flamme qui ne s'eteint jamais dans la nuit",
    "le rythme de notre danse fait tourner la terre ce soir",
    "on fait briller le monde avec chaque pas que l'on fait",
    "tes mains dans les miennes et le monde devient un bonbon",
    "on eclaire la route avec la lumiere de notre amitie forte",
    "les neons de la ville sont notre constellation ce soir ensemble",
    "on danse jusqu'a l'aube avec des etoiles dans les yeux",
    "chaque sourire que tu m'offres est un rayon de soleil pur",
    "on fait la fete avec le monde entier ce soir dore",
    "le ciel est notre toile et nos reves les couleurs dessus",
    "on s'envole si haut que les oiseaux nous envient ce soir",
    "tes rires font eclater des bulles de bonheur autour de nous",
    "on est les architectes d'un monde fait de lumiere et musique",
    "les etoiles applaudissent quand on monte sur la scene ce soir",
    "on danse avec nos ombres et elles brillent aussi fort maintenant",
    "le monde est un karaoke geant et c'est notre tour enfin",
    "on fait vibrer l'air avec la puissance de nos reves immenses",
    "tes yeux sont des feux d'artifice dans la nuit de ma vie",
    "on tourne la page vers un chapitre fait de lumiere pure",
    "les confettis de nos reves tombent comme une pluie d'or fin",
    "on est la generation qui danse sous les etoiles chaque nuit",
    "chaque battement de nos coeurs cree un rythme nouveau et unique",
    "on brille comme mille soleils dans le ciel de cette nuit",
    "le bonheur est notre chanson et on la chante fort ce soir",
    "on fait danser les ombres avec la lumiere de notre joie",
    "tes sourires sont des etoiles que je collectionne dans mon coeur",
    "on eclaire l'obscurite avec chaque note que l'on chante fort",
    "les couleurs de ton ame peignent mon monde de bonheur dore",
    "on danse avec le destin et il nous sourit ce soir",
    "le rythme nous connecte au-dela des mots et du temps",
    "on s'envole vers demain avec des ailes faites de reves dores",
    "tes paroles font eclore des fleurs de lumiere dans mon ame",
    "on fait la revolution du bonheur avec chaque pas de danse",
    "les etoiles de nos yeux eclairent le chemin vers nos reves",
    "on danse avec la vie et elle nous rend tout au centuple",
    "le monde brille plus fort quand on est ensemble ce soir",
    "on est la lumiere au bout du tunnel et on brille fort",
    "chaque instant de bonheur est un diamant dans notre couronne doree",
    "on fait trembler le monde avec la force de notre amour",
    "tes yeux dansent avec les etoiles et je suis hypnotise",
    "on eclaire la nuit avec des milliers de reves colores vifs",
    "les papillons de mon coeur s'envolent quand tu me regardes tendrement",
    "on tourne en boucle dans un monde fait de sucre glace",
    "le ciel s'ouvre pour nous et les anges nous applaudissent ce soir",
    "on fait briller chaque ombre avec la lumiere de nos sourires",
    "tes mains dessinent des etoiles dans l'air quand tu danses",
    "on est les heros d'un conte fait de lumiere et musique",
    "les lumieres de nos reves eclairent chaque pas sur scene",
    "on danse avec le feu et les flammes deviennent des fleurs",
    "le bonheur est un ocean ou on nage ensemble ce soir",
    "on s'eleve au-dessus de tout avec la force de nos voix",
    "tes rires sont la bande-son de ma vie en couleurs vives",
    "on fait la fete dans un monde ou tout est possible enfin",
    "les etoiles sont notre public et elles brillent pour nous seuls",
    "on danse pieds nus dans un champ de lumieres et de reves",
    "le monde est notre bonbon et on le savoure avec joie",
    "on eclaire chaque instant avec la flamme de notre jeunesse",
    "chaque note de ta voix est un rayon de soleil pur",
    "on fait vibrer les etoiles avec chaque battement de nos coeurs",
    "tes yeux sont le ciel ou je veux m'envoler chaque nuit",
    "on tourne la terre avec la force de notre danse ce soir",
    "les confettis de bonheur pleuvent sur nous sans jamais s'arreter",
    "on est la chanson que le monde chante avant de dormir",
    "le rythme de nos pas cree des vagues de lumiere pure",
    "on s'envole ensemble dans un ciel fait de musique et reves",
    "tes sourires sont les etincelles qui allument ma vie entiere",
    "on fait danser le monde entier avec notre energie ce soir",
    "les couleurs de notre amour peignent le ciel de mille teintes",
    "on brille si fort que meme le soleil nous regarde briller",
    "le bonheur explose comme un feu d'artifice dans nos coeurs",
    "on danse avec les nuages et ils deviennent notre scene magique",
    "chaque moment avec toi est une chanson que je veux chanter",
    "on eclaire l'univers avec la puissance de notre lien unique",
    "tes mots sont des bonbons qui fondent sur mon coeur emu",
    "on fait briller la nuit comme si le jour n'existait plus",
    "les etoiles filantes portent nos voeux vers le ciel infini dore",
    "on est la lumiere qui ne s'eteindra jamais dans ce monde",
    "le monde danse avec nous et les murs tremblent de joie",
    "on s'envole si haut que les reves deviennent notre realite",
    "tes yeux brillent comme des diamants dans la nuit de velours",
    "on fait la fete avec chaque battement de nos coeurs unis",
    "les lumieres de nos ames se melangent dans la nuit doree",
    "on fait exploser le ciel avec nos rires et nos cris de joie",
    "tes pas de danse sont des poemes ecrits sur le sol dore",
    "on illumine chaque coin sombre avec notre energie sans limites ce soir",
    "le monde est un bonbon que l'on partage entre amis sous les spots",
    "on chante si fort que les nuages se dispersent autour de nous",
    "tes yeux sont des projecteurs qui eclairent ma scene interieure ce soir",
    "on fait tourner la terre avec chaque mouvement de notre danse vive",
    "les paillettes de nos reves tombent comme une pluie d'etoiles dorees",
    "on est les heros d'un monde fait de musique et de bonbons",
    "chaque note de notre chanson est un fil d'argent vers le ciel",
    "on danse avec les anges et ils applaudissent notre spectacle de lumiere",
    "tes sourires sont des soleils miniatures qui rechauffent mon univers entier",
    "on peint chaque instant avec les couleurs de notre amitie eternelle",
    "le bonheur est un manege ou on tourne ensemble sans jamais descendre",
    "on fait vibrer l'univers avec la force de nos coeurs unis",
    "tes rires sont des feux d'artifice qui eclairent ma nuit la plus sombre",
    "on court vers les etoiles et elles nous tendent les bras ouverts",
    "chaque danse ensemble est un chapitre de notre histoire magique et doree",
    "on est les etincelles qui allument le feu de la joie partout",
    "le ciel chante notre chanson et la terre danse notre rythme ce soir",
    "on fait briller chaque moment comme un cristal sous les projecteurs vifs",
    "tes mots sont des confettis qui colorent mon monde de bonheur pur",
    "on tourne sous les etoiles et chaque tour est un souvenir precieux",
    "les couleurs de nos reves explosent comme des feux d'artifice la nuit",
    "on est la generation qui fait danser les etoiles chaque soir de fete",
    "chaque battement de coeur est une note de notre symphonie de lumiere",
    "on fait trembler les murs avec la puissance de notre joie immense",
    "tes yeux sont des lanternes magiques qui eclairent le chemin vers nos reves",
    "on s'envole ensemble et les nuages deviennent notre piste de danse doree",
    "le monde entier brille quand on danse sous les projecteurs de nos reves",
    "on danse jusqu'a ce que les etoiles se couchent enfin",
    "le ciel est notre piste de danse et les nuages notre public",
    "on eclaire le monde un sourire a la fois ce soir",
    "chaque pas ensemble est un souvenir que je cheris pour toujours",
    "on fait trembler l'univers avec la magie de notre danse",
    "tes rires eclairent mon chemin comme un phare dans la tempete",
    "on brille comme des etoiles jumelles dans le ciel nocturne noir",
    "le bonheur est contagieux quand on danse ensemble sous les spots",
    "on tourne et on vole dans un reve de couleurs infinies",
    "les papillons de lumiere dansent autour de nous ce soir dore",
    "on est la melodie que le vent emporte vers les etoiles",
    "le rythme de nos coeurs est le plus beau son du monde",
    "on fait danser les lumieres avec chaque mouvement de nos corps",
    "tes mains sont des etoiles qui brillent quand elles touchent les miennes",
    "on s'envole vers un monde fait de reves et de bonbons roses",
    "les couleurs de la vie explosent quand on est ensemble ce soir",
    "on eclaire chaque pas de danse avec la flamme de nos ames",
    "chaque note chantee ensemble est un fil d'or entre nos coeurs",
    "on fait briller le monde avec notre amour pur et infini",
    "le ciel est rouge et nos coeurs sont pleins de reves immenses",
    "on danse avec les anges et ils chantent notre chanson ce soir",
    "tes sourires sont des arcs-en-ciel qui colorent mon univers gris",
    "on est les enfants du rythme et de la lumiere eternelle",
    "les etoiles de nos reves brillent dans chaque regard echange ici",
    "on fait vibrer le monde avec la purete de nos voix",
    "le bonheur danse dans nos yeux comme des etincelles de feu",
    "on court vers l'infini avec des reves plein les poches dorées",
    "tes yeux sont mon etoile du nord dans la nuit sombre",
    "on tourne dans un manege de lumiere et de musique sans fin",
    "les confettis de nos joies pleuvent sur chaque instant passe ensemble",
    "on est le feu d'artifice qui eclaire le ciel ce soir",
    "le monde entier est notre chanson et on la chante tres fort",
    "on fait la fete comme des etoiles qui dansent dans le ciel",
    "chaque seconde ensemble est un tresor de lumiere et de joie",
    "on eclaire l'horizon avec nos reves les plus brillants ce soir",
    "tes paroles sont des etoiles qui brillent dans mon ciel interieur",
    "on danse avec la lumiere et les ombres s'effacent autour de nous",
    "le rythme de la nuit coule dans nos veines comme du miel",
    "on s'envole au-dela des etoiles avec la force de notre amour",
    "les lumieres de la scene sont les etoiles de notre univers",
    "on court a travers les rues illuminees par nos reves ce soir",
    "ton regard est une etoile filante qui traverse mon univers entier",
    "on saute dans le vide et les couleurs nous rattrapent toujours",
    "les neons de la ville chantent notre nom a chaque coin",
    "on danse sur les toits et le vent nous applaudit fort",
    "tes levres murmurent une promesse que le vent porte au ciel",
    "on allume la nuit avec la flamme de notre jeunesse rebelle",
    "les flocons de lumiere tombent sur nous comme une benediction doree",
    "on tourne dans un manege fait de rires et de chansons",
    "ton coeur est un tambour qui bat la mesure de ma vie",
    "on fait danser les ombres jusqu a ce qu elles brillent enfin",
    "les papillons de cristal volent autour de nos tetes ce soir",
    "on chante sous la pluie et les gouttes deviennent des notes",
    "tes doigts entrelaces aux miens sont la plus belle harmonie possible",
    "on dessine des coeurs sur les fenetres embuees de la nuit",
    "le monde pourrait s arreter et on continuerait de danser encore",
    "on est le refrain que tout le monde veut chanter ensemble",
    "tes larmes sont des perles qui font briller ta beaute unique",
    "on fait exploser les confettis de nos reves dans le ciel",
    "les miroirs refletent nos sourires multiplies a l infini ce soir",
    "on transforme chaque seconde en une image de bonheur inoubliable",
    "ton nom est une melodie que mon coeur fredonne sans arret",
    "on fait trembler les planchers avec la joie de nos retrouvailles",
    "les guirlandes de lumiere enveloppent nos silhouettes de danse ce soir",
    "on est les artistes d une toile de musique et de rires",
    "tes pas de danse racontent une histoire que les mots ignorent",
    "on allume des lanternes de papier et nos voeux s envolent loin",
    "le soleil se couche mais notre eclat ne faiblit jamais ici",
    "on est le reflet dore de tout ce qui est beau",
    "tes yeux sont des kaleidoscopes ou mille couleurs se melangent",
    "on brise les regles et on cree notre monde enchante ce soir",
    "les bulles de savon portent nos rires vers les nuages blancs",
    "on est le battement qui fait vibrer toute la salle entiere",
    "ton ombre danse avec la mienne meme quand tu es loin",
    "on colore le monde en rose et en or avec nos sourires",
    "les projecteurs s allument et notre aventure commence enfin sur scene",
    "on court vers l avenir les bras ouverts le coeur leger",
    "tes mains applaudissent et le monde entier se met a danser",
    "on est la generation qui transforme les larmes en paillettes fines",
    "les arcs-en-ciel se forment quand nos voix se rencontrent en choeur",
    "on tisse des fils de lumiere entre nos coeurs eloignes",
    "ton rire est un feu d artifice qui eclaire mon ciel gris",
    "on fait la fete meme quand la pluie tombe sur nous",
    "les etoiles dessinent notre constellation unique dans le ciel nocturne",
    "on est le debut d une chanson que le monde fredonnera",
    "tes yeux mi-clos sont un clair de lune sur mon ame",
    "on repousse les nuages gris avec la force de nos sourires",
    "les bonbons de nos reves fondent sur nos langues emerveillees",
    "on transforme la nuit en jour avec la chaleur de nos ames",
    "ton souffle est une brise douce qui fait danser mes cheveux",
    "on est la reponse a toutes les questions de la nuit",
    "les rubans colores de nos danses s entremelent dans l air doux",
    "on fait tourner le globe avec la magie de nos chansons",
    "tes bras sont un cocon de lumiere ou je me blottis",
    "on crie de joie et les murs tremblent de notre bonheur",
    "les etoiles nous envoient des baisers de lumiere et de grace",
    "on est le pont entre le reve et la realite doree",
    "ton coeur est une boussole qui pointe toujours vers le mien",
    "on danse dans les flaques et elles deviennent des miroirs d or",
    "les petales de cerisier tombent autour de nous comme des flocons",
    "on ecrit nos reves sur les murs de la ville endormie",
    "tes mots sont des bonbons sucres qui rechauffent mon coeur triste",
    "on fait monter le volume et la ville vibre avec nous",
    "les lucioles de nos pensees eclairent le sentier des reves",
    "on est le choeur qui chante la bande-son de notre epoque",
    "ton regard est un phare qui me guide a travers la nuit",
    "on lance des etoiles en papier dans le vent du soir",
    "les nuages se transforment en coussins pour nos reves endormis",
    "on est la promesse d un lendemain plus brillant que jamais",
    "tes pieds dessinent des arabesques sur la piste illuminee vive",
    "on fait briller nos cicatrices comme des fils d or precieux",
    "les ballons s envolent vers le ciel emportant nos soucis au loin",
    "on est le sel et le sucre de cette vie en couleurs",
    "ton silence parle plus fort que tous les mots du monde",
    "on transforme chaque adieu en un nouveau debut lumineux ce soir",
    "les miroirs de nos ames refletent un monde fait de bonheur",
    "on danse meme quand la musique s arrete car nos coeurs chantent",
    "tes empreintes sur mon coeur sont des etoiles que rien n efface",
    "on fait de chaque nuit ordinaire un souvenir extraordinaire et vif",
    "les plumes de lumiere tombent du ciel et nous couronnent doucement",
    "on est les notes d une partition que le monde joue en boucle",
    "ton parfum est une trainee de comete dans mon univers sombre",
    "on rassemble les morceaux de nos reves et on les colle ensemble",
    "les perles de rosee brillent comme nos larmes de joie pure",
    "on est le cri de joie qui traverse les frontieres du reve",
    "tes mains ouvertes sont deux soleils qui rechauffent mes jours gris",
    "on marche sur un tapis de lumiere vers notre destin commun",
    "les cristaux de glace fondent quand nos coeurs battent ensemble fort",
    "on est le feu de camp autour duquel le monde se rassemble",
    "ton coeur bat en stereo et je suis la musique qui joue",
    "on fait tourner les etoiles avec nos rires et nos chants",
    "les fils invisibles de nos coeurs tissent une toile incassable",
    "on transforme le gris en rose avec la poudre de nos reves",
    "tes cheveux dansent dans le vent comme des rubans de soie",
    "on allume des feux de joie dans le ciel de nos espoirs",
    "les echos de nos voix resonnent dans les couloirs du temps",
    "on est la vague qui emporte tout sur son passage lumineux",
    "ton sourire efface les ombres et fait naitre des jardins dores",
    "on fait de la scene notre maison et du public notre famille",
    "les flocons de notre amitie s accumulent en montagne de souvenirs",
    "on est le premier et le dernier accord de cette nuit",
    "tes larmes de bonheur font pousser des fleurs dans mon jardin",
    "on danse avec les ombres et on les transforme en lumieres",
    "les trompettes de notre joie sonnent la fanfare d un nouveau jour",
    "on tient le monde dans un battement de coeur et un sourire",
    "ton existence est la preuve que la magie existe pour de vrai",
    "on fait tourner le monde a l envers et tout devient beau",
    "les ailes de nos reves sont faites de notes de musique",
    "on est la reponse que le monde cherche dans la nuit calme",
    "tes pas resonnent dans mon coeur comme une melodie sans fin",
    "on fabrique des souvenirs en or avec chaque seconde ensemble",
    "les cerises de nos joies murissent sous le soleil de nos rires",
    "on est le battement de coeur qui fait vivre cette chanson",
    "ton ame brille a travers tes yeux comme un diamant rare",
    "on fait des ricochets de lumiere sur l ocean de la nuit",
    "les fils de nos destins se croisent et forment un noeud d or",
    "on est la pluie de printemps qui fait renaitre les fleurs",
    "tes mots tracent des chemins de lumiere dans l obscurite douce",
    "on lance nos chapeaux vers le ciel et ils deviennent des etoiles",
    "les melodies de notre coeur voyagent plus loin que la lumiere",
    "on est le dernier rayon de soleil avant la tombee du soir",
    "ton amour est un parapluie qui me protege de toutes les peines",
    "on danse sur les lignes de nos destins entrecroises sous les neons",
    "les cloches de cristal sonnent l arrivee d un bonheur tout neuf",
    "on est la constellation que le monde n avait pas encore vue",
    "tes battements de coeur sont le tempo de ma chanson preferee",
    "on transforme les adieux en promesses de retrouvailles lumineuses proches",
    "les nuages de coton deviennent la scene de notre prochain spectacle",
    "on est le souffle qui fait danser les flammes de l espoir"
  ],
  bridges: [
    "on ferme les yeux et le monde entier brille pour nous",
    "dans le silence entre les notes nos coeurs se retrouvent enfin",
    "le temps s'arrete quand nos regards se croisent sur la scene",
    "on respire la lumiere et on exhale des etincelles d'or pur",
    "ce moment est eternel et rien ne peut nous le voler",
    "les etoiles descendent du ciel pour danser avec nous ce soir",
    "on tient le monde dans nos mains et il brille si fort",
    "le rythme ralentit et nos coeurs battent a l'unisson parfaitement",
    "on est suspendus dans le temps entre deux battements de coeur",
    "la lumiere de nos reves traverse les murs et le ciel",
    "on se regarde et tout devient clair comme un matin de printemps",
    "les mots s'effacent et seule la musique parle a nos ames",
    "on touche le ciel du bout des doigts ensemble ce soir",
    "le monde entier retient son souffle quand on danse ainsi",
    "nos ames se melangent dans une symphonie de lumiere pure dorée",
    "on est au sommet et les etoiles sont a nos pieds",
    "le silence entre les notes est aussi beau que la musique",
    "on ferme les yeux et on voit un ocean de lumieres",
    "ce soir le temps n'existe plus seule la musique compte",
    "on tient la lumiere dans nos coeurs et elle ne s'eteint jamais",
    "les reves et la realite se melangent dans notre danse magique",
    "on respire ensemble et le monde s'arrete un instant pour nous",
    "la scene devient notre ciel et les spots sont nos etoiles",
    "on suspend le temps avec la force de notre lien profond",
    "les larmes de joie brillent comme des diamants sur nos joues roses",
    "on s'arrete un instant pour savourer la beaute de cet instant",
    "le coeur du monde bat avec nous dans ce moment unique",
    "on laisse la musique porter nos ames vers le ciel infini",
    "les lumieres s'eteignent et nos coeurs brillent encore plus fort ensemble",
    "on tient nos reves dans nos mains et ils pulsent de vie",
    "ce pont entre nos ames est fait de musique et de lumiere",
    "on flotte dans un espace ou le temps ne compte plus",
    "les etoiles chuchotent nos noms dans le vent de la nuit",
    "on est a la croisee des reves et de la lumiere pure",
    "le battement de nos coeurs est le metronome de nos reves"
  ],
  choruses: [
    "on brille on brille comme des etoiles dans la nuit ce soir",
    "ensemble on peut tout faire danser voler briller sans s'arreter",
    "les couleurs de nos reves peignent le ciel en rose et or",
    "on danse on danse et le monde tourne avec nous ce soir",
    "nos coeurs battent comme un seul et la nuit nous appartient",
    "on est la lumiere qui eclaire chaque coin de la nuit",
    "ensemble on fait trembler les etoiles avec nos voix ce soir",
    "on brille si fort que le monde ne peut pas nous ignorer",
    "les etoiles sont pour nous et la nuit est notre scene doree",
    "on danse jusqu'au bout du reve sans jamais s'arreter ce soir",
    "nos reves sont faits de lumiere et de paillettes et d'amour",
    "on fait la fete et le monde entier danse avec nous",
    "ensemble on eclaire la nuit avec la force de nos coeurs",
    "on brille on vole on danse on chante pour toujours ensemble",
    "les lumieres sont pour nous et la scene est notre monde dore",
    "on fait trembler le ciel avec chaque pas de danse ce soir",
    "nos voix s'elevent et les etoiles applaudissent notre chanson ce soir",
    "on danse comme des diamants qui brillent sous les projecteurs dores",
    "ensemble on est la plus belle constellation de la nuit entiere",
    "on fait briller le monde avec notre energie sans limites ce soir",
    "les couleurs de nos ames eclairent chaque instant de cette nuit",
    "on est ensemble et c'est la plus belle chanson du monde",
    "nos reves sont la musique et nos coeurs sont les instruments dores",
    "on danse sous les etoiles et elles dansent pour nous aussi",
    "ensemble on est plus forts que tout ce qui veut nous arreter",
    "on brille comme le soleil meme au milieu de la nuit noire",
    "les etoiles chantent avec nous et la nuit est notre scene",
    "on fait la fete dans un monde fait de reves et lumiere",
    "nos coeurs brillent si fort qu'ils eclairent tout l'univers ce soir",
    "on danse et on chante et le monde est a nous ensemble",
    "ensemble on cree la magie qui fait briller chaque instant vecu",
    "on est les etoiles filantes qui traversent le ciel de la nuit",
    "les lumieres de nos reves ne s'eteindront jamais dans nos coeurs",
    "on fait vibrer la terre avec notre danse de joie pure",
    "nos voix sont la lumiere qui guide le monde vers le bonheur",
    "on brille ensemble et rien ne peut eteindre notre flamme vive",
    "les couleurs explosent quand on chante ensemble sous les spots dores",
    "on danse avec le vent et les nuages sont notre tapis rouge",
    "ensemble on est la chanson que le monde n'oubliera jamais ce soir",
    "on fait briller chaque seconde comme un joyau dans la nuit noire",
    "nos reves sont des etoiles et on les allume une par une",
    "on est la musique qui fait danser le monde entier ce soir",
    "les etoiles de nos yeux eclairent le chemin vers nos reves dores",
    "on danse on reve on brille et le monde est a nous",
    "ensemble on est un feu d'artifice de joie et de lumiere pure",
    "on fait trembler les murs avec la puissance de notre lien",
    "nos coeurs sont les etoiles qui eclairent la nuit pour toujours",
    "on brille on danse on chante et rien ne nous arrete jamais",
    "les lumieres de nos ames sont la plus belle constellation du ciel",
    "on est ensemble pour toujours et c'est notre plus beau reve",
    "on fait tourner le monde avec la force de nos reves reunis",
    "les couleurs explosent quand on crie ensemble vers le ciel",
    "on est le refrain qui reste en tete longtemps apres la fin",
    "nos sourires sont les etoiles d une galaxie que l on cree ce soir",
    "on danse on vole on reve et la nuit nous porte haut",
    "ensemble on est la plus belle chanson jamais ecrite au monde",
    "les confettis tombent et nos coeurs s envolent ensemble vers le ciel",
    "on est la lumiere qui ne s eteint pas meme dans la tempete",
    "nos mains levees forment une foret de reves et d espoir dore",
    "on fait briller chaque larme et chaque rire sous les spots ce soir",
    "ensemble on est un arc-en-ciel qui traverse le ciel de nuit",
    "on brille on crie on danse et c est notre moment a nous",
    "les etoiles chantent notre chanson et le monde entier reprend le refrain",
    "on est le battement de coeur qui fait vivre cette nuit magique",
    "nos voix unies sont un torrent de lumiere dans l obscurite",
    "on danse ensemble et chaque pas est une promesse de toujours",
    "les lumieres brillent pour nous et la scene est notre univers dore",
    "on fait trembler le ciel avec la joie de nos coeurs reunis",
    "ensemble on est une constellation qui eclaire le monde entier ce soir",
    "on brille comme des soleils jumeaux dans le ciel de nos reves",
    "les notes de notre chanson sont des etoiles filantes dans la nuit",
    "on danse avec le vent et les nuages applaudissent notre spectacle dore",
    "nos reves sont les ailes qui nous portent au dessus du monde",
    "on est la melodie qui fait sourire meme les jours de pluie",
    "les etoiles tombent dans nos mains et on les lance plus haut",
    "on fait danser le monde et le monde nous remercie avec des sourires",
    "ensemble on cree une tempete de joie que rien ne peut calmer",
    "on est le premier rayon de soleil apres la nuit la plus longue",
    "nos coeurs battent ensemble comme un seul tambour de lumiere et joie",
    "on est la chanson qui reste dans les coeurs quand la nuit finit"
  ],
  vocabulary: {
    nouns: [
      "etoile", "lumiere", "reve", "coeur", "danse",
      "scene", "couleur", "nuit", "ciel", "bonbon",
      "paillette", "diamant", "sourire", "musique", "jeunesse",
      "eclat", "magie", "arc-en-ciel", "confetti", "etincelle",
      "rayon", "fleur", "papillon", "melodie", "tresor",
      "feu", "galaxie", "constellation", "aube", "aurore",
      "bonheur", "joyau", "couronne", "soleil", "lune",
      "voix", "chanson", "battement", "tourbillon", "horizon",
      "amour", "ame", "flamme", "lumignon", "luciole",
      "prisme", "cristal", "bulle", "fete", "harmonie",
      "comete", "nebuleuse", "galaxie", "supernova", "univers",
      "miroir", "reflet", "kaleidoscope", "mosaique", "vitrail",
      "cerise", "fraise", "miel", "caramel", "vanille",
      "ruban", "noeud", "guirlande", "lampion", "fanfare",
      "peluche", "poupee", "jouet", "ballon", "manege",
      "diademe", "tiare", "pendentif", "bracelet", "bague",
      "flocon", "nuage", "brume", "rosee", "cascade"
    ],
    verbs: [
      "briller", "danser", "voler", "chanter", "eclater",
      "tourner", "scintiller", "vibrer", "illuminer", "etinceler",
      "s'envoler", "rayonner", "exploser", "eclore", "palpiter",
      "tourbillonner", "chatoyer", "resplendir", "embraser", "miroiter",
      "bondir", "sauter", "courir", "flotter", "rever",
      "sourire", "rire", "crier", "applaudir", "saisir",
      "toucher", "peindre", "dessiner", "creer", "batir",
      "elever", "unir", "partager", "celebrer", "enchanter",
      "fasciner", "emerveiller", "captiver", "emporter", "transporter",
      "accelerer", "pulser", "fuser", "eclabousser", "irradier",
      "papillonner", "voltiger", "virevolter", "pirouetter", "cabrioler",
      "etinceler", "flamboyer", "chatoyer", "miroiter", "rutiler",
      "gazouiller", "babiller", "pepier", "fredonner", "chantonner",
      "emoustiller", "exciter", "exalter", "enthousiasmer", "galvaniser",
      "couronner", "sacrer", "introniser", "consacrer", "glorifier",
      "eclore", "s'epanouir", "s'ouvrir", "jaillir", "germer"
    ],
    adjectives: [
      "brillant", "lumineux", "dore", "magique", "etincelant",
      "colore", "eclatant", "scintillant", "radieux", "eblouissant",
      "merveilleux", "fantastique", "feerique", "celeste", "divin",
      "infini", "eternel", "immense", "grandiose", "spectaculaire",
      "joyeux", "heureux", "vif", "palpitant", "electrisant",
      "pur", "cristallin", "limpide", "onirique", "enchante",
      "irresistible", "magnifique", "splendide", "somptueux", "majestueux",
      "inoubliable", "unique", "precieux", "rare", "extraordinaire",
      "chatoyant", "iridescent", "fluorescent", "phosphorescent", "incandescent",
      "ardent", "vibrant", "intense", "fulgurant", "resplendissant",
      "sucre", "acidule", "petillant", "mousseux", "effervescent",
      "mignon", "adorable", "craquant", "charmant", "ravissant",
      "fluo", "neon", "pastel", "bonbon", "arc-en-ciel",
      "stellaire", "cosmique", "galactique", "interstellaire", "celeste",
      "exuberant", "debordant", "explosif", "impetueaux", "bouillonnant",
      "glamour", "chic", "sophistique", "raffine", "elegant"
    ]
  }
};
