/**
 * Latin Genre — French Phrase Bank
 * Themes: fire, heart, dance, night, heat, passion, rhythm, fiesta, love, sun
 */
module.exports = {
  themes: [
    "feu", "coeur", "danse", "nuit", "chaleur",
    "passion", "rythme", "fiesta", "amour", "soleil",
    "corps", "desir", "salsa", "tropique", "flamme"
  ],
  openers: [
    "Le Feu De La Nuit Brule Dans Nos Veines Ce Soir",
    "On Danse Sous Le Soleil Jusqu'a La Derniere Flamme",
    "La Passion Coule Comme Un Fleuve De Lave Brulante",
    "Ce Soir On Fait Briller La Nuit Avec Notre Feu",
    "Le Rythme De La Salsa Enflamme Nos Corps Ce Soir",
    "Nos Coeurs Battent Au Rythme Du Soleil Couchant Ce Soir",
    "La Fiesta Commence Et Nos Ames S'embrasent De Desir",
    "On Brule Comme Le Soleil Sur Les Plages Du Sud",
    "Le Desir Monte Comme La Maree Dans La Nuit Chaude",
    "Ce Soir On Danse Avec Le Feu Dans Les Mains",
    "La Nuit Tropicale Embrase Nos Coeurs De Passion Brulante",
    "On Fait Trembler La Terre Avec Nos Pas De Salsa",
    "Le Soleil Se Couche Et Nos Corps S'enflamment De Desir",
    "La Chaleur De La Nuit Fait Fondre Nos Inhibitions Ce Soir",
    "On Danse Comme Des Flammes Sous Le Ciel Etoile Ce Soir",
    "Le Rythme Nous Possede Et Nos Hanches Bougent Seules Ce Soir",
    "La Passion Est Un Volcan Qui Explose Dans Nos Coeurs",
    "Ce Soir Les Etoiles Dansent La Salsa Avec Nous",
    "On Brule D'amour Comme Un Feu Qui Ne S'eteint Jamais",
    "La Fiesta S'enflamme Et Le Monde Entier Danse Avec Nous",
    "Le Feu De Nos Regards Allume La Nuit Chaude Ce Soir",
    "On Danse Peau Contre Peau Sous Le Ciel Du Sud Brulant",
    "La Musique Latine Fait Trembler Les Murs Ce Soir Fort",
    "Ce Soir On Vit Comme Si Le Soleil Ne Se Couchait Jamais",
    "Le Desir Coule Dans Nos Veines Comme Du Vin Brulant",
    "On Fait La Fiesta Sous Les Palmiers De La Nuit Chaude",
    "La Chaleur De Ton Corps Est Mon Oasis Ce Soir",
    "Le Rythme Du Tambour Fait Battre Nos Coeurs Plus Fort",
    "Ce Soir On Embrase Le Monde Avec Notre Danse De Feu",
    "La Passion Monte Et Les Etoiles S'inclinent Devant Nous",
    "On Danse Sur Le Sable Chaud Jusqu'a L'aube Rouge Ce Soir",
    "Le Soleil De Nos Ames Brille Meme Dans La Nuit Noire",
    "La Nuit Est Un Carnaval De Flammes Et De Desir Pur",
    "Ce Soir On Vit La Fievre De La Nuit Tropicale Chaude",
    "Le Feu De La Danse Consume Tout Sauf Notre Amour",
    "On S'enflamme Comme Des Torches Sous Le Ciel Du Carnaval",
    "La Musique Brule Dans L'air Comme Une Promesse D'amour Pur",
    "Ce Soir Les Tropiques Sont Dans Nos Coeurs Brulants D'amour",
    "Le Rythme Du Caraibe Fait Danser Nos Ames Ce Soir",
    "On Danse Avec Le Feu Et Les Flammes Deviennent Des Roses",
    "La Passion Est Notre Langue Et Le Rythme Notre Voix",
    "Ce Soir On Fait L'amour Avec La Musique Latine Brulante",
    "Le Soleil De Minuit Brille Dans Tes Yeux Ce Soir",
    "On Brule La Nuit Avec La Flamme De Notre Desir Ardent",
    "La Fiesta N'a Pas De Fin Quand On Danse Ensemble",
    "Ce Soir Le Monde Entier Brule De Notre Passion Latine",
    "Le Feu De Nos Ames Eclaire Le Chemin De La Nuit",
    "On Danse Comme Des Volcans En Eruption Sous Les Etoiles",
    "La Chaleur De Cette Nuit Restera Gravee Dans Nos Coeurs",
    "Ce Soir On Est Le Feu Qui Embrase Le Monde Entier"
  ],
  verses: [
    "le feu de tes yeux allume la nuit comme un volcan",
    "on danse si pres que nos coeurs ne font plus qu'un",
    "le rythme de la conga fait trembler le sol sous nous",
    "ta peau brule sous mes doigts comme le sable au soleil",
    "la nuit tropicale embrase nos corps de desir et de fievre",
    "on tourne comme des flammes dans le vent chaud du soir",
    "le soleil se couche mais notre feu ne s'eteint jamais",
    "tes hanches bougent comme les vagues de l'ocean sous la lune",
    "la passion coule dans nos veines comme un fleuve de lave",
    "on danse sous les palmiers et le monde disparait autour de nous",
    "le tambour bat comme nos coeurs dans la nuit chaude tropicale",
    "ta voix est un murmure de feu dans mon oreille brulante",
    "la fiesta eclate et nos ames s'envolent avec la musique chaude",
    "on brule sur la piste comme deux etoiles en collision ce soir",
    "le rythme du reggaeton fait vibrer chaque fibre de nos corps",
    "tes levres sont du miel chaud sous le soleil du soir rouge",
    "la chaleur monte entre nous comme la vapeur d'un volcan brulant",
    "on danse peau contre peau et le monde n'existe plus du tout",
    "le feu de la nuit consume tout sauf notre amour brulant",
    "tes yeux sont deux brasiers ou je me perds chaque soir",
    "la musique nous enveloppe comme une brise chaude du tropique lointain",
    "on tourne et on tourne comme des flammes dans le vent chaud",
    "le desir est un ocean de feu dans lequel on plonge ensemble",
    "ta danse est un sortilege qui enchaine mon coeur pour toujours",
    "la nuit nous appartient et le rythme est notre roi ce soir",
    "on fait bruler le sol avec chaque pas de notre danse",
    "le soleil de ton sourire eclaire ma nuit la plus sombre",
    "tes mains sur ma taille et le monde prend feu autour de nous",
    "la passion est un tango qui ne finit jamais entre nous",
    "on danse comme des diables sous la lune rouge du sud chaud",
    "le rythme de la bossa nova berce nos ames enlacees ce soir",
    "ta chaleur est mon soleil dans la nuit froide de l'hiver",
    "la fiesta fait rage et nos corps ne peuvent plus s'arreter",
    "on brule d'un amour si fort que les etoiles fondent autour",
    "le feu de notre danse eclaire tout le quartier ce soir",
    "tes mouvements sont des flammes qui lechent l'air de la nuit",
    "la musique latine coule dans nos os comme du sang chaud",
    "on se consume l'un l'autre comme deux bougies dans le vent",
    "le tambour est le battement de coeur de la nuit tropicale",
    "ta peau a le gout du soleil et du sel de la mer",
    "la chaleur de nos corps cree une brume de desir pur",
    "on danse jusqu'a l'aube et le soleil nous trouve encore debout",
    "le rythme accelere et nos coeurs suivent la cadence du feu",
    "tes yeux sont des torches qui eclairent mon chemin dans la nuit",
    "la passion monte comme le mercure sous le soleil du tropique",
    "on fait l'amour avec la danse sous les etoiles du sud chaud",
    "le feu de tes levres brule sur les miennes toute la nuit",
    "ta voix est une brise chaude qui caresse mon ame brulante",
    "la fiesta n'a pas de fin quand nos corps s'enflamment ainsi",
    "on tourne comme des toupies de feu dans la nuit chaude",
    "le soleil nous regarde danser et il sourit dans le ciel rouge",
    "tes bras sont mon paradis sous le ciel du carnaval tropical",
    "la nuit se consume dans le feu de notre amour ardent",
    "on brule les regles et on danse avec le destin ce soir",
    "le rythme de nos pas dessine des flammes sur le sol chaud",
    "ta danse est un poeme de feu ecrit dans l'air de nuit",
    "la chaleur de cette nuit fond les barrieres entre nos coeurs",
    "on danse avec les ombres et elles prennent feu autour de nous",
    "le desir est un fruit mur qui tombe dans nos mains avides",
    "tes hanches racontent une histoire d'amour en rythme sous la lune",
    "la musique est le feu et nos corps sont les flammes dansantes",
    "on fait la revolution sur la piste avec nos pas de feu",
    "le soleil de minuit brille dans le creux de tes mains",
    "ta peau doree reflète la lumiere de mille bougies ce soir",
    "la passion est un ouragan qui balaie tout sur son passage",
    "on danse comme des volcans en eruption sous le ciel etoile",
    "le rythme du son nous enchaine sur la piste de danse brulante",
    "tes yeux lancent des eclairs qui enflamment mon coeur sauvage ce soir",
    "la fiesta nous emporte dans un tourbillon de couleurs et chaleur",
    "on brule ensemble et nos cendres deviennent des etoiles dans le ciel",
    "le feu de nos ames fait fondre la glace du monde froid",
    "ta chaleur m'enveloppe comme un coucher de soleil sur la plage",
    "la nuit est une flamme et nous sommes les etincelles qui dansent",
    "on tourne sous les guirlandes de feu comme des cometes en feu",
    "le tambour appelle et nos pieds repondent sans hesiter ce soir",
    "tes mouvements sont de la lave qui coule lentement sur mon coeur",
    "la passion nous brule et on aime chaque seconde de ce feu",
    "on danse sur les braises et la douleur devient du plaisir intense",
    "le soleil dort mais notre feu reste eveille toute la nuit longue",
    "ta voix est un incendie qui ravage mon coeur de fond en comble",
    "la chaleur de nos regards fait bouillir l'air entre nos corps",
    "on fait bruler la piste avec notre passion sans aucune retenue",
    "le rythme de la cumbia fait onduler nos corps comme des vagues",
    "tes levres sont des braises qui marquent ma peau pour toujours",
    "la nuit tropicale est notre temple et la danse notre priere",
    "on brule comme le soleil et on eclaire tout le monde autour",
    "le feu de la guitare fait pleurer les etoiles dans le ciel",
    "ta danse est un incendie que personne ne peut eteindre ce soir",
    "la fiesta embrase la rue et les murs transpirent de chaleur",
    "on tourne et le monde fond comme de la cire chaude autour",
    "le desir est un tango eternel entre nos ames enlacees ce soir",
    "tes bras m'enveloppent comme la chaleur du soleil au zenith dore",
    "la musique brulante coule sur notre peau comme du miel chaud",
    "on danse sous un ciel de feu et les etoiles fondent autour",
    "le rythme de nos coeurs est un incendie qui ne s'eteint pas",
    "ta peau est une carte au tresor ou chaque courbe est un mystere",
    "la passion est notre oxygene et on respire le feu du desir",
    "on fait trembler la nuit avec la force de notre amour brulant",
    "le soleil brule dans nos poitrines meme au milieu de la nuit",
    "tes yeux sont le feu qui allume la meche de mon coeur",
    "la chaleur monte en spirale comme la fumee d'un feu sacre",
    "on danse avec la fievre et elle devient notre meilleure amie",
    "le tambour pulse comme un coeur geant sous la lune rouge",
    "ta voix murmure des promesses de feu dans la nuit chaude",
    "la nuit est un brasier et on danse au milieu des flammes",
    "on brule les kilometres entre nos corps avec chaque pas de danse",
    "le rythme du merengue fait tourner nos ames comme des toupies",
    "tes mains sont du feu liquide sur ma peau brulante ce soir",
    "la fiesta rugit comme un lion et nos corps suivent le rythme",
    "on s'enflamme comme des torches et la nuit devient notre scene doree",
    "le feu de notre union fait palir les etoiles du ciel noir",
    "ta danse est une conversation entre le feu et le vent chaud",
    "la passion nous consume et de nos cendres nait un amour neuf",
    "on tourne dans la chaleur de la nuit comme des derviches de feu",
    "le soleil de nos ames ne se couche jamais sur notre amour",
    "tes mouvements sont des vagues de chaleur qui brisent mes defenses",
    "la musique est un rio de feu ou on nage ensemble sans fin",
    "on fait danser les flammes avec chaque mouvement de nos hanches",
    "le desir monte comme la temperature au coeur du tropique brulant",
    "ta chaleur fait eclore des fleurs de feu dans mon coeur froid",
    "la nuit brule et on est le combustible de cette flamme eternelle",
    "on danse avec le soleil meme quand il se cache derriere l'horizon",
    "le rythme de nos corps cree des ondes de chaleur dans l'air",
    "tes levres murmurent des mots de feu qui font fondre ma raison",
    "la fiesta est un volcan et nous sommes la lave qui coule",
    "on brule d'un desir si fort que l'ocean ne peut l'eteindre",
    "le feu de la trompette fait danser les etoiles au-dessus de nous",
    "ta peau est un coucher de soleil que je veux toucher toujours",
    "la passion est un carnaval de feu et de couleurs dans la nuit",
    "on tourne comme la terre autour du soleil de notre amour ardent",
    "le tambour de la nuit bat le tempo de notre desir brulant",
    "tes yeux sont des soleils jumeaux qui rechauffent mon ame glacee",
    "la chaleur de nos danses fait transpirer les murs de la salle",
    "on fait bruler chaque seconde comme une offrande au dieu du rythme",
    "le soleil danse avec la lune et nos corps font de meme",
    "ta voix est un soleil de minuit qui brille dans mon coeur",
    "la nuit tropicale pleure de joie quand on danse sous ses etoiles",
    "on brule les ponts derriere nous et on danse vers l'avenir chaud",
    "le rythme nous possede comme un esprit de feu dans la nuit",
    "tes mains dessinent des flammes sur ma peau tremblante de desir",
    "la fiesta est notre religion et la danse notre priere ardente",
    "on s'enflamme comme un coucher de soleil sur l'ocean du desir",
    "le feu de la clave fait vibrer nos os jusqu'a la moelle",
    "ta danse est un soleil qui se leve dans la nuit noire",
    "la passion est une riviere de lave qui coule vers nos coeurs",
    "on tourne dans un cyclone de desir et de rythme effrene",
    "le soleil brule dans nos pas et la terre frissonne sous nous",
    "tes bras sont deux flammes qui m'encerclent dans la nuit tropicale",
    "la musique est un feu de camp ou nos ames se rechauffent",
    "on danse avec la chaleur de mille soleils dans nos coeurs",
    "le desir est un tambour qui bat sans relache dans nos veines",
    "ta chaleur est la seule chose dont j'ai besoin dans cette nuit",
    "la nuit est une danse de flammes et on en est les etoiles",
    "on brule la piste avec un amour plus fort que le feu",
    "le rythme de la bachata fait pleurer nos corps de bonheur chaud",
    "tes yeux sont le soleil qui ne se couche jamais pour moi",
    "la fiesta enflamme chaque recoin de la ville endormie ce soir",
    "on fait trembler le monde avec le feu de notre passion vive",
    "le feu de nos baisers fait fondre les chaines du temps froid",
    "ta peau est le soleil et mes levres sont l'horizon qui l'embrasse",
    "la passion danse dans nos yeux comme des flammes dans le vent",
    "on tourne sous les etoiles du sud et le ciel rougit de nous",
    "le tambour du desir fait vibrer nos ames enlacees dans la nuit",
    "tes mouvements sont du feu liquide qui coule dans mes veines chaudes",
    "la chaleur de notre amour fait fleurir des roses dans le desert",
    "on danse avec les etoiles et elles deviennent des etincelles de feu",
    "le soleil de nos coeurs fait naitre un nouveau jour chaque nuit",
    "ta voix est une flamme douce qui rechauffe mon ame en hiver",
    "la nuit est notre jardin de feu ou l'amour fleurit sans fin",
    "on brule ensemble comme deux soleils qui fusionnent dans le ciel noir",
    "le rythme de nos ames cree un incendie de beaute pure ce soir",
    "tes levres sont le soleil couchant que je poursuis chaque soir",
    "la fiesta rugit dans nos veines comme un torrent de feu brulant",
    "on fait danser les etoiles avec la chaleur de nos regards croises",
    "le feu de la guitare seche pleure notre histoire d'amour brulante",
    "ta danse est une eruption de beaute sous le ciel du carnaval",
    "la passion est le vent chaud qui souffle sur les braises du coeur",
    "on tourne comme deux cometes de feu dans la nuit sans fin",
    "le soleil de nos reves brille sur nos corps enlaces ce soir",
    "tes mains sont le soleil qui fait fondre la glace de mon coeur",
    "la musique brule dans l'air et nos corps en absorbent la chaleur",
    "on danse sous le volcan et sa lave nous rechauffe le coeur",
    "le desir est un soleil qui ne se couche jamais entre nous",
    "ta chaleur est un paradis tropical ou je veux vivre pour toujours",
    "la nuit est un carnaval et nos ames sont les feux d'artifice",
    "on brule d'envie de danser jusqu'a ce que le soleil se leve",
    "le rythme de la salsa fait chanter nos corps dans la nuit",
    "tes yeux sont deux volcans en eruption qui embrasent mon coeur entier",
    "la fiesta commence quand nos regards se croisent dans la foule dense",
    "on fait bruler la nuit avec des pas de danse enflammes",
    "le feu de ton amour est le seul que je veux sentir",
    "ta peau brune reflete la lumiere des bougies comme de l'or fondu",
    "la passion est un fleuve de lave qui traverse nos coeurs unis",
    "on tourne dans la fievre de la nuit comme des flammes jumelles",
    "le tambour appelle nos ames et elles repondent avec tout leur feu",
    "tes bras sont mon tropique ou le soleil ne se couche jamais",
    "la chaleur de nos peaux melees cree une tempete de desir pur",
    "on danse sur les cendres de nos peurs et un phœnix nait",
    "le soleil pulse dans nos veines et la nuit devient un carnaval",
    "ta voix est un incendie doux qui devore mes doutes dans la nuit",
    "la nuit tropicale nous berce dans un hamac de feu et d'amour",
    "on brule les regles avec la flamme de notre danse sauvage",
    "le rythme de nos souffles cree une brise chaude dans la nuit",
    "tes mouvements sont des eclairs de chaleur dans la nuit noire tropicale",
    "la fiesta est un feu sacre ou nos ames se purifient ensemble",
    "on fait trembler la terre avec chaque pas de notre salsa brulante",
    "le feu de nos ames eclaire le chemin des amants perdus",
    "ta danse est un soleil de minuit qui ne connaît pas la fatigue",
    "la passion nous emporte comme un courant chaud dans l'ocean de la nuit",
    "on tourne dans les bras de la nuit et elle nous rechauffe fort",
    "le desir est une danse eternelle entre le feu et la peau brulante",
    "tes levres sont des braises que le vent de la nuit ravive",
    "la chaleur de nos reves fait fondre les frontieres entre nos mondes",
    "on danse avec le feu sacre des ancetres sous les etoiles du sud",
    "le soleil de notre amour fait fleurir la nuit comme un jardin",
    "ta chaleur est la melodie que mon corps cherchait depuis toujours",
    "le feu de nos baisers fait fondre le temps entre nos levres",
    "on danse sous les palmiers et la lune rougit de nous voir",
    "le rythme de la rumba fait pleurer de joie nos corps fatigues",
    "tes mains tracent des chemins de feu sur la carte de mon corps",
    "la nuit latine nous berce dans un hamac de desir et chaleur",
    "on brule la piste avec des pas de merengue enflammes ce soir",
    "le soleil tropical coule dans nos veines comme un elixir de feu",
    "ta danse est un volcan qui crache des roses au lieu de la lave",
    "la chaleur de nos corps cree un microclimat de passion sous les etoiles",
    "on tourne dans le rythme de la nuit comme deux flammes entrelacees",
    "le tambour appelle notre sang et il repond avec des battements fous",
    "tes yeux sont deux brasiers ou les papillons de nuit viennent bruler",
    "la fiesta gronde dans nos poitrines comme un tonnerre de passion pure",
    "on fait trembler les etoiles avec la fievre de notre danse sauvage",
    "le desir monte en spirale comme la fumee d'un cigare dans la nuit",
    "ta peau a le parfum du jasmin chauffe par le soleil du soir",
    "la nuit nous enveloppe dans un drap de soie et de chaleur brulante",
    "on danse sous un ciel de velours et les etoiles sont nos temoins",
    "le rythme de nos souffles cree une musique plus belle que toute autre",
    "tes levres sont un fruit tropical que je cueille dans la nuit chaude",
    "la passion est une tempete de feu qui balaie nos doutes et peurs",
    "on brule ensemble dans un brasier de musique et de desir effrene",
    "le soleil de ton sourire fait eclore des orchidees dans mon coeur",
    "ta voix est un rhum vieux qui me monte a la tete ce soir",
    "la chaleur de tes mots fait fondre les glaciers de ma solitude",
    "on danse comme des flammes jumelles que le vent ne peut eteindre jamais",
    "le tambour est le coeur de la nuit et nos corps ses battements",
    "tes hanches dessinent des courbes de feu dans l'air chaud de la nuit",
    "la fiesta bat son plein et nos ames s'embrasent de passion pure",
    "on fait l'amour avec chaque pas de danse sous le ciel tropical",
    "le rythme du son cubain fait chanter nos os et nos muscles tendus",
    "ta danse est une priere de feu adressee aux dieux de la nuit",
    "la passion nous consume et de nos cendres renait un amour plus fort",
    "le soleil de notre danse rechauffe les etoiles froides du ciel nocturne",
    "la cumbia nous emporte dans un tourbillon de hanches et de sueur",
    "on danse pieds nus sur le sable brulant et le monde fond",
    "tes yeux sont des braises qui rallument le feu de mon ame",
    "le rythme de la clave bat dans nos poitrines comme un tonnerre",
    "la nuit nous enveloppe dans un drap de soie et de desir",
    "on fait la fete sous les bougainvilliers en fleurs du jardin secret",
    "le tambour appelle nos corps et ils repondent sans hesiter un instant",
    "ta taille ondule comme un palmier sous la brise tropicale du soir",
    "la guitare seche pleure des larmes de feu dans l air chaud",
    "on brule les heures dans un brasier de danse et de baisers",
    "le carnaval explose en mille couleurs de chaleur et de joie",
    "tes pieds dessinent des flammes sur le plancher de la salle chaude",
    "la salsa est un dialogue de feu entre nos corps enlaces",
    "on tourne comme deux cometes dans le ciel tropical de la nuit",
    "le rythme du bongo pulse dans nos veines comme un courant chaud",
    "ta bouche murmure des mots de feu qui brulent mes levres avides",
    "la nuit caribbeenne parfume l air de jasmin et de passion ardente",
    "on danse avec l ocean et les vagues suivent notre cadence folle",
    "le feu de la rumba fait vibrer les os de la terre",
    "tes mains tracent des lignes de chaleur sur ma peau tremblante",
    "la guitare electrique gronde comme un orage au dessus de la mer",
    "on fait l amour avec le rythme et chaque note est un baiser",
    "le soleil de midi coule dans nos gorges comme du rhum dore",
    "ta danse est un hurricane de beaute qui balaie tout devant elle",
    "la percussion fait trembler les murs comme un coeur geant qui bat",
    "on brule d un desir que meme l ocean ne pourrait eteindre",
    "le soir tombe et les flambeaux eclairent nos corps en mouvement",
    "tes cheveux virevoltent comme des serpents de soie dans la nuit chaude",
    "la bachata fait pleurer les guitares et sourire nos levres avides",
    "on danse avec nos ombres et elles rougissent de nos desirs secrets",
    "le rythme du cajun fait onduler les riziers dans le vent chaud",
    "ta sueur brille comme des diamants sous la lumiere des bougies",
    "la passion monte comme la fievre au coeur de la jungle humide",
    "on tourne et les etoiles tracent des cercles de feu au dessus",
    "le son des maracas fait frissonner nos peaux sous le clair de lune",
    "ta voix chante comme un oiseau tropical dans l aube doree du jour",
    "la nuit avance et nos corps ne connaissent pas la fatigue chaude",
    "on fait bruler le dancefloor avec nos pas de mambo effrenes",
    "le soleil se cache mais le feu de nos ventres ne s eteint pas",
    "tes yeux mi-clos sont deux volcans en eruption dans la penombre",
    "la trompette hurle sa passion dans le ciel etoile du tropique",
    "on brule comme deux torches plantees dans le sable de la plage",
    "le rythme des congas fait battre la nuit comme un coeur enorme",
    "ta peau a la douceur du satin et la chaleur du soleil",
    "la nuit nous offre un banquet de feu et de desir sans fin",
    "on danse jusqu a ce que nos pieds marquent le sol de feu",
    "le son du tres cubain fait danser les fantomes de la havane",
    "tes levres ont le gout du fruit de la passion tropicale",
    "la chaleur de tes mains fait eclore des orchidees dans l air",
    "on fait vibrer les cordes de la nuit avec nos corps enlaces",
    "le rythme nous saisit comme un vent chaud venu du large",
    "ta silhouette se decoupe dans la lumiere orange du couchant brulant",
    "la rumba nous possede et nos ames fusionnent dans la danse folle",
    "on tourne sous les lanternes et nos ombres font l amour derriere nous",
    "le feu du tequila brule dans nos gorges et nos regards croises",
    "tes bras m encerclent comme les lianes de la foret tropicale humide",
    "la nuit est un fruit mur que l on mord ensemble a pleines dents",
    "on danse avec le tonnerre et la foudre est notre projecteur ce soir",
    "le rythme du guiro gratte notre peau de frissons electriques ce soir",
    "ta chaleur est la seule saison que je veux connaitre pour toujours",
    "la passion brule les ponts et construit des palais de feu eternels",
    "on fait rugir la piste comme un jaguar dans la jungle sombre",
    "le son de la flute andine fait pleurer les montagnes au loin",
    "tes mouvements sont un incendie que personne ne veut eteindre jamais",
    "la nuit latine a le gout du cafe brulant et du sucre roux",
    "on brule chaque peur dans le brasier de notre danse commune",
    "le rythme du reggaeton fait trembler les vitres de la ville endormie",
    "ta danse est un sortilege de chaleur qui ensorcele tous les regards",
    "la fiesta deborde des murs et inonde les rues de joie chaude",
    "on tourne comme la terre autour d un soleil fait de passion pure",
    "le feu de la trompette mariachi fait pleurer les cactus du desert",
    "tes pieds nus marquent le tempo sur le carrelage chaud du patio",
    "la chaleur de nos regards pourrait faire fondre les glaciers du monde",
    "on danse avec les etoiles du sud et elles rougissent de jalousie",
    "le rythme de nos hanches cree des ondes de chaleur dans l air",
    "ta peau caramel brille sous les lumieres comme du bronze liquide",
    "la nuit est un volcan qui crache des etincelles de desir pur",
    "on fait la fete avec le feu sacre des anciens peuples du sud",
    "le soleil de tes baisers fait naitre des aurores dans mon ame",
    "tes doigts parcourent ma peau comme les flammes sur du bois sec",
    "la passion est une danse que seuls les braves osent tenter ici",
    "on brule les conventions et on danse librement dans la nuit chaude",
    "le rythme du pandeiro fait tourner nos tetes comme un manege de feu",
    "ta respiration est une brise chaude qui fait frissonner mon ame",
    "la nuit tropicale nous berce dans un hamac de musique brulante",
    "on tourne dans les bras du desir comme des papillons pres du feu",
    "le son de la harpe paraguayenne fait vibrer les etoiles du sud",
    "tes hanches racontent en rythme l histoire de tous les amants du monde",
    "la chaleur de cette danse pourrait allumer les lumieres d une ville",
    "on fait bruler nos doutes dans le feu sacre de la salsa",
    "le rythme nous enchaine et les chaines sont faites de velours brulant",
    "ta voix est un rhum vieux qui fait tourner la tete et rever",
    "la nuit sent le jasmin la cannelle et le desir inassouvi",
    "on danse avec la lune rouge et elle nous eclaire de feu",
    "le feu de nos corps cree des mirages dans l air chaud du soir",
    "tes yeux noirs sont deux gouffres de passion ou je tombe sans fin",
    "la musique afro-cubaine fait vibrer nos vertebres une a une ce soir",
    "on brule le temps comme du bois sec dans un feu de joie",
    "le rythme du timbales fait exploser la nuit en mille etincelles",
    "ta danse est un poeme de chair et de feu ecrit a deux",
    "la passion coule entre nous comme un fleuve de lave douce",
    "on fait trembler les collines avec le tonnerre de nos pas de danse",
    "le soleil de ton rire fait eclore des hibiscus dans mon jardin",
    "tes epaules nues brillent sous les guirlandes du bal tropical du soir",
    "la nuit nous consume et nous renaissons a chaque battement de tambour",
    "on danse comme des flammes que le vent du desir attise",
    "le rythme du son montuno fait grimper la fievre dans nos corps",
    "ta main dans la mienne est un pont de feu entre deux mondes",
    "la fiesta gronde comme un volcan pret a exploser de passion folle",
    "on tourne dans le courant chaud de la nuit comme des algues",
    "le feu de nos ames cree une nouvelle constellation dans le ciel noir",
    "tes levres sont une promesse de chaleur que la nuit tient toujours",
    "la danse est notre langage et le feu notre alphabet secret",
    "on brule comme des etoiles filantes dans le ciel du tropique chaud",
    "le rythme du charango fait danser les sommets des andes au loin",
    "ta chaleur est un soleil interieur qui ne connait pas de couchant",
    "la nuit caribbeenne danse avec nous et nous suivons ses pas de feu",
    "on fait l amour avec la musique et chaque note est un frisson",
    "le son des steel drums fait chanter les plages de sable blanc",
    "tes mouvements sont un incendie controle qui rechauffe sans jamais bruler",
    "la passion est un volcan dormant que nos danses reveillent ce soir",
    "on tourne dans la chaleur de nos corps comme des planetes en feu",
    "le rythme du bombo fait battre la terre sous nos pieds nus",
    "ta danse est une offrande au dieu du feu et de l amour",
    "la nuit tombe et nos corps s allument comme des torches vivantes",
    "on danse avec les ombres de la lune et elles prennent feu",
    "le soleil tropical coule comme du miel sur nos corps enlaces",
    "tes yeux sont le soleil de minuit qui eclaire ma nuit sombre",
    "la chaleur de nos pas cree un chemin de braise dans la nuit",
    "on brule de tout notre etre et les cendres sont faites d or pur",
    "le rythme nous emporte vers un paradis fait de feu et de danse",
    "ta peau chaude contre la mienne est le plus beau des brasiers",
    "la fiesta ne mourra jamais tant que nos coeurs battront ensemble"
  ],
  bridges: [
    "le feu ralentit et nos corps se rapprochent dans la nuit",
    "on ferme les yeux et la chaleur nous enveloppe tout doucement",
    "le rythme descend et nos coeurs montent vers le ciel brulant",
    "dans le silence chaud nos peaux murmurent des mots de feu",
    "la nuit retient son souffle et notre passion atteint son sommet",
    "on tient le feu dans nos mains sans jamais se bruler",
    "le soleil et la lune dansent ensemble dans nos yeux ce soir",
    "nos souffles se melangent comme deux flammes qui deviennent une seule",
    "la musique s'arrete mais nos corps continuent de danser doucement",
    "on est suspendus dans la chaleur de cet instant eternel",
    "le tambour ralentit et nos ames trouvent leur rythme secret",
    "la passion se transforme en une braise douce entre nos mains",
    "on respire le feu et il devient une brise chaude en nous",
    "le monde s'efface et il ne reste que la chaleur de toi",
    "nos coeurs battent si fort qu'ils font trembler les etoiles du ciel",
    "la nuit chuchote et nos corps ecoutent dans le silence chaud",
    "on laisse la chaleur nous guider vers un monde sans barrieres",
    "le rythme de nos respirations cree une musique de velours brulant",
    "la passion descend doucement comme le soleil sur l'horizon rouge ce soir",
    "on s'arrete un instant et le feu de nos regards dit tout",
    "le soleil de nos ames se couche pour renaitre plus fort demain",
    "nos mains se trouvent dans la chaleur et tout devient clair enfin",
    "la musique nous berce comme une vague de chaleur sur la plage",
    "on flotte dans un ocean de feu et de tendresse infinie",
    "le desir devient un murmure doux dans la nuit tropicale chaude",
    "on tient la flamme entre nos levres et elle ne brule plus",
    "la nuit s'ouvre comme une fleur de feu devant nos yeux",
    "nos corps parlent un langage de chaleur que les mots ne connaissent pas",
    "le rythme ralentit et la passion devient un fleuve calme et chaud",
    "on ferme les yeux et le feu de nos ames nous guide",
    "la chaleur de cet instant est un tresor que rien ne peut voler",
    "le soleil de nos regards cree un pont de lumiere entre nous",
    "nos souffles se melent dans la nuit comme deux flammes eternelles",
    "on laisse le feu descendre doucement dans les braises de l'amour",
    "la passion retient son souffle et le monde attend notre prochain pas"
  ],
  choruses: [
    "on brule on brule dans la nuit comme deux flammes enlacees",
    "le feu de nos coeurs fait danser le monde entier ce soir",
    "on danse on danse sous le soleil de minuit jusqu'a l'aube rouge",
    "la passion nous consume et on aime bruler ensemble sans fin",
    "nos corps en feu eclairent la nuit comme un volcan ce soir",
    "on tourne on tourne dans le rythme du desir sans s'arreter",
    "le soleil de nos ames ne se couche jamais sur nous",
    "on fait bruler la nuit avec chaque pas de notre danse",
    "la fiesta est dans nos veines et le feu dans nos coeurs",
    "on danse avec les flammes et elles deviennent des fleurs de nuit",
    "le rythme nous possede et nos corps ne peuvent plus s'arreter",
    "on brule d'amour sous les etoiles du sud ce soir chaud",
    "la chaleur de nos pas fait fondre le sol sous nos pieds",
    "on danse on vit on brule et le monde nous regarde bruler",
    "le feu de notre danse eclaire tout l'horizon de la nuit",
    "on tourne dans le feu et le feu tourne en nous ce soir",
    "nos ames en flammes eclairent le chemin de tous les amants",
    "on danse jusqu'au bout du feu sans jamais se bruler ensemble",
    "la passion est notre chanson et le rythme notre battement de coeur",
    "on brule la nuit entiere avec la force de notre amour",
    "le soleil danse dans nos coeurs et la lune dans nos pas",
    "on fait trembler la terre avec le feu de notre danse latine",
    "la fiesta ne finit jamais quand nos coeurs brulent ensemble fort",
    "on tourne on brule on danse et la nuit est notre scene",
    "le rythme du desir fait battre nos coeurs comme des tambours",
    "on danse avec le feu et il ne nous brule pas ce soir",
    "la chaleur de nos ames cree un ete eternel en nous",
    "on brule on danse on vit et rien ne peut nous eteindre",
    "le feu de nos regards allume la nuit comme mille bougies",
    "on tourne dans les bras de la passion sans jamais tomber ce soir",
    "nos coeurs en feu font la fiesta sous les etoiles du sud",
    "on danse comme des flammes et le monde fond autour de nous",
    "la passion est notre feu et la nuit notre piste de danse",
    "on brule ensemble sous le ciel et les etoiles applaudissent notre danse",
    "le rythme de nos coeurs en feu fait vibrer tout l'univers",
    "on danse on brule on aime et la nuit est notre royaume",
    "la chaleur de notre amour fait rougir le ciel tout entier",
    "on fait danser les etoiles avec le feu de notre passion vive",
    "le soleil de nos danses eclaire meme la nuit la plus noire",
    "on tourne dans un ocean de feu et de desir eternel",
    "nos ames brulent comme un carnaval de flammes sous le ciel rouge",
    "on danse avec la chaleur du monde dans nos bras ouverts",
    "la fiesta brule dans nos coeurs et eclaire chaque nuit sombre",
    "on brule d'un feu si beau que les etoiles en pleurent",
    "le rythme de notre amour fait trembler les fondations du monde",
    "on danse on tourne on brule et c'est notre plus beau feu",
    "la passion nous guide comme un soleil dans la nuit sans fin",
    "on fait bruler le monde avec la chaleur de nos coeurs unis",
    "le feu de nos ames est la plus belle lumiere du monde",
    "on danse ensemble dans le feu et c'est notre paradis ce soir",
    "le feu de nos corps eclaire la nuit comme un carnaval eternel",
    "on tourne on brule on danse et le monde fond sous nos pas",
    "la passion est notre drapeau et le rythme notre cri de guerre",
    "nos ames en feu sont le plus beau spectacle de la nuit",
    "on danse avec le destin et il brule de danser avec nous",
    "le soleil de nos coeurs fait rougir les etoiles dans le ciel",
    "la fiesta coule dans nos veines comme un fleuve de feu sacre",
    "on brule on danse on vit et le monde est notre piste",
    "les flammes de notre amour eclairent les quatre coins de la nuit",
    "on fait trembler la terre et le ciel rougit de notre passion",
    "le rythme de nos vies est un incendie que rien n eteint",
    "nos corps en feu dansent la chanson de tous les amants du sud",
    "on tourne dans les bras du soleil meme au coeur de la nuit",
    "la chaleur de nos ames fait fondre les murs entre nos mondes",
    "on brule ensemble et nos cendres deviennent des fleurs de passion",
    "le feu de notre danse fait palir le soleil lui meme",
    "nos hanches bougent et le monde suit le rythme de nos coeurs",
    "on danse jusqu au bout de la nuit et le feu ne meurt pas",
    "la passion est un ocean de feu ou nous nageons ensemble ce soir",
    "on tourne on vit on brule et c est notre plus beau voyage",
    "le rythme du sud coule dans nos corps comme un elixir de feu",
    "nos regards croises allument des incendies que la nuit ne peut eteindre",
    "on danse avec les etoiles du sud et elles deviennent des flammes",
    "la fiesta est notre priere et le feu notre benediction sacree",
    "on brule d amour et le monde entier sent la chaleur de nos coeurs",
    "le soleil de notre passion ne se couchera jamais sur nous deux",
    "nos pas de feu marquent la terre pour les generations a venir",
    "on danse on brule on aime et c est tout ce qui compte",
    "la nuit tropicale chante notre chanson et le monde danse avec nous",
    "on brule ensemble comme un seul soleil dans le ciel de la nuit"
  ],
  vocabulary: {
    nouns: [
      "feu", "flamme", "soleil", "chaleur", "passion",
      "desir", "nuit", "danse", "rythme", "tambour",
      "fiesta", "volcan", "lave", "braise", "etincelle",
      "coeur", "peau", "corps", "tropique", "plage",
      "ocean", "vague", "lune", "palmier", "carnaval",
      "salsa", "guitare", "clave", "conga", "bongos",
      "sable", "brise", "oasis", "etoile", "horizon",
      "coucher", "aube", "fievre", "sueur", "caresse",
      "murmure", "soupir", "embrasement", "incendie", "torche",
      "bougie", "brasier", "cendre", "fumee", "ardeur",
      "tango", "rumba", "bachata", "merengue", "cumbia",
      "maracas", "trompette", "violon", "piano", "accordeon",
      "mangue", "papaye", "coco", "rhum", "cafe",
      "fleur", "orchidee", "hibiscus", "jasmin", "bougainvillier",
      "hamac", "veranda", "terrasse", "balcon", "patio",
      "carnaval", "masque", "plume", "costume", "cortege",
      "tonnerre", "eclair", "orage", "cyclone", "mousson"
    ],
    verbs: [
      "bruler", "danser", "tourner", "enflammer", "embraser",
      "consumer", "allumer", "attiser", "raviver", "incendier",
      "onduler", "frissonner", "vibrer", "pulser", "battre",
      "transpirer", "fondre", "couler", "exploser", "eructer",
      "murmurer", "caresser", "effleurer", "enlancer", "etreindre",
      "seduire", "enchanter", "ensorceler", "posseder", "enivrer",
      "rugir", "gronder", "trembler", "frissonner", "palpiter",
      "flamboyer", "rougeoyer", "irradier", "rayonner", "scintiller",
      "tourbillonner", "vaciller", "onduler", "serpenter", "fusionner",
      "devorer", "consumer", "embraser", "electriser", "magnifier",
      "tanguer", "chaloper", "se dehancher", "pivoter", "virevolter",
      "claquer", "frapper", "percuter", "marteler", "tambouriner",
      "celebrer", "festoyer", "trinquer", "acclamer", "applaudir",
      "embaumer", "parfumer", "enivrer", "griser", "saouler",
      "flamber", "rougeoyer", "brasiller", "couver", "fumer",
      "suer", "ruisseler", "degouliner", "perler", "suinter",
      "galoper", "bondir", "caracoler", "cabrer", "charger"
    ],
    adjectives: [
      "brulant", "ardent", "enflamme", "incandescent", "volcanique",
      "tropical", "chaud", "torride", "bouillant", "fervent",
      "passionne", "sensuel", "charnel", "sauvage", "intense",
      "fougueux", "electrique", "magnetique", "envoutant", "irresistible",
      "dore", "rouge", "ecarlate", "cramoisi", "vermeil",
      "nocturne", "lunaire", "solaire", "stellaire", "cosmique",
      "profond", "puissant", "vibrant", "palpitant", "frenetique",
      "langoureux", "voluptueux", "enivrant", "capiteux", "exotique",
      "luxuriant", "opulent", "somptueux", "flamboyant", "eblouissant",
      "infernal", "diabolique", "sacre", "primitif", "visceral",
      "equatorial", "caribeen", "insulaire", "maritime", "cotier",
      "luxuriant", "foisonnant", "exuberant", "debordant", "prolifique",
      "endiable", "effrenee", "frenetique", "vertigineux", "tourbillonnant",
      "cuivre", "bronze", "cannelle", "ambre", "caramel",
      "moite", "humide", "suffocant", "etouffant", "accablant",
      "festif", "carnavalesque", "jubilatoire", "exaltant", "triomphal"
    ]
  }
};
