module.exports = {
  themes: [
    "guerre", "enfer", "mort", "destruction", "tenebres",
    "vengeance", "chaos", "puissance", "apocalypse", "fureur",
    "sang", "fer", "flammes", "conquete", "damnation"
  ],
  openers: [
    "Les Flammes De L Enfer Devorent Le Ciel Ce Soir",
    "Du Sang Et Du Fer Nous Forgeons Notre Destinee",
    "L Armee Des Ombres Marche Sur Les Ruines Du Monde",
    "Le Tonnerre Gronde Et La Terre Tremble Sous Nos Pas",
    "Dans Les Cendres Du Monde Ancien Nous Renaissons Plus Forts",
    "La Nuit Eternelle Engloutit Les Derniers Rayons Du Soleil",
    "Les Portes De L Enfer S Ouvrent Dans Un Fracas De Fer",
    "Le Cri De Guerre Dechire Le Silence De L Aube Noire",
    "Les Dieux Sont Tombes Et Nous Marchons Sur Leurs Os",
    "La Lame De Mon Epee Brille Sous La Lune De Sang",
    "Les Corbeaux Tournent Au Dessus Du Champ De Bataille Maudit",
    "La Fureur Des Damnes S Eleve Comme Une Tempete De Feu",
    "Le Monde Brule Et Nous Dansons Dans Les Flammes Eternelles",
    "Les Chaines Se Brisent Et Les Captifs Se Dressent Enfin",
    "Le Dragon S Eveille Et Son Souffle Embrase La Terre",
    "Les Murs De La Forteresse Croulent Sous Les Coups Du Destin",
    "La Mort Chevauche A Travers Les Plaines Desolees Ce Soir",
    "Les Guerriers Se Levent Et Le Sol Tremble Sous Eux",
    "Le Sang Des Vaincus Abreuve La Terre Assoiffee De Vengeance",
    "Les Cieux Se Dechrent Et La Colere Des Dieux Eclate",
    "Dans La Forge Noire Les Armes De La Guerre Naissent",
    "Le Loup Hurle Et Les Tenebres Repondent A Son Appel",
    "Les Armees De La Nuit Deferlent Sur Les Terres Mortelles",
    "Le Trone De Fer Est Forge Dans Le Sang Des Rois",
    "Les Volcans Crachent Leur Rage Sur Le Monde Tremblant De Peur",
    "Le Cavalier Noir Traverse Les Plaines Sans Jamais S Arreter",
    "Les Demons Se Repaissent Des Ames Perdues Dans Les Tenebres",
    "La Foudre Frappe Et Les Tours S Ecroulent Comme Du Verre",
    "Le Marteau De Guerre Resonne Dans La Nuit Sans Fin",
    "Les Flammes Purificatrices Consument Le Monde Corrompu Et Faible",
    "Le Serpent Geant Se Dresse Et Avale Le Soleil Mourant",
    "Les Legions Infernales Marchent Au Son Des Tambours De Guerre",
    "La Tempete De Fer Balaie Les Derniers Espoirs Des Hommes",
    "Le Masque De La Mort Recouvre Le Visage Du Monde",
    "Les Eclairs Dechiren Le Ciel Et Revelent La Fin Proche",
    "Le Sang Coule Comme Un Fleuve Dans Les Rues De Cendres",
    "Les Ames Tourmentees Hurlent Dans Le Vent De La Nuit",
    "La Bete Immonde Se Reveille Et La Terre Saigne Encore",
    "Le Glaive De La Justice Tranche Les Tetes Des Tyrans",
    "Les Cris De Guerre Montent Vers Un Ciel Sans Etoiles",
    "La Citadelle Noire Se Dresse Contre L Horizon De Flammes",
    "Le Pacte De Sang Est Scelle A Jamais Dans Le Feu",
    "Les Vautours Attendent Patiemment La Fin De La Bataille Cruelle",
    "La Rage Des Anciens Coule Dans Nos Veines Ce Soir",
    "Le Cor De Guerre Resonne Et Les Morts Se Relevent",
    "Les Tenebres Avancent Et Rien Ne Peut Les Arreter Desormais",
    "La Couronne De Fer Est Le Prix De La Douleur",
    "Le Rugissement Du Dragon Fait Trembler Les Montagnes Anciennes",
    "Les Barbares Defoncent Les Portes De La Cite Condamnee",
    "La Nuit Des Mille Lames Commence Dans Le Sang Verse"
  ],
  verses: [
    "les flammes devorent les murs de la cite maudite",
    "le sang des guerriers abreuve la terre noire et froide",
    "les chaines se brisent dans un fracas de metal hurle",
    "le vent de la mort souffle sur les plaines desolees",
    "les corbeaux se repaissent des restes du champ de bataille",
    "le fer cogne le fer dans la forge des damnes",
    "les ames perdues errent dans les couloirs de l enfer",
    "la lune de sang eclaire les ruines du monde ancien",
    "le cri du guerrier dechire la nuit comme une lame",
    "les tours s ecroulent sous le poids de la trahison",
    "le feu consume tout ce que les hommes ont bati",
    "les demons rient dans les ombres de la nuit eternelle",
    "la hache du bourreau brille sous la lumiere des torches",
    "les cadavres jonchent le sol de la vallee de cendres",
    "le tonnerre des sabots annonce l arrivee des cavaliers noirs",
    "les murailles tremblent sous les coups des beliers de guerre",
    "le poison coule dans les veines du royaume agonisant",
    "les loups hurlent a la lune comme des ames damnees",
    "le trone est vide et les pretendants versent le sang",
    "les flammes de la vengeance brulent plus fort que tout",
    "le marteau du destin forge les chaines de notre rage",
    "les ombres rampent sur les murs de la forteresse sombre",
    "le vent hurle a travers les gorges de la montagne noire",
    "les guerriers tombent mais leur esprit combat encore sans fin",
    "le dragon crache des flammes sur les armees des mortels",
    "les epees s entrechoquent dans le chaos de la melee sanglante",
    "le ciel se dechire et la pluie de feu commence enfin",
    "les remparts s effondrent comme des chateau de sable fragile",
    "le sang seche sur la lame de l epee vengeresse",
    "les betes de l ombre chassent dans la nuit sans lune",
    "le grondement du volcan annonce la colere de la terre",
    "les traitres payent de leur sang le prix de leur crime",
    "le sol tremble sous la marche des legions infernales",
    "les cris des vaincus resonnent dans les salles de pierre",
    "le froid de la mort saisit les coeurs des plus braves",
    "les vautours planent en cercle au dessus des mourants",
    "le fer rouge marque la chair des esclaves revoltes",
    "les statues des anciens dieux s effritent dans la poussiere",
    "le chaos regne et l ordre ancien n est plus qu un souvenir",
    "les esprits tourmente hantent les ruines du temple profane",
    "le sang versee ne sera jamais oublie ni pardonne",
    "les tenebres s epaississent et la lumiere faiblit sans cesse",
    "le cri de la bete resonne dans les entrailles de la terre",
    "les armures cabossees temoignent de la violence des combats passes",
    "le vent de la destruction emporte les cendres des vaincus",
    "les serpents sifflent dans les crevasses du monde brise",
    "le feu purificateur ne connait ni pitie ni remords",
    "les os blanchis jalonnent le chemin de la conquete cruelle",
    "le bouclier se fend sous les coups repetes de la haine",
    "les cornes de guerre appellent les morts a se battre encore",
    "le metal hurle dans la forge comme une ame en peine",
    "les rats fuient le navire qui sombre dans les flots noirs",
    "le sang des innocents crie vengeance depuis les profondeurs sombres",
    "les flammes lechen les pieds du trone du roi dechu",
    "le glas sonne pour ceux qui ont ose defier la mort",
    "les chaines des prisonniers resonnent dans les geoles obscures",
    "le venin du serpent empoisonne les reves des mortels faibles",
    "les cranes empiles forment le trophee du conquerant sans pitie",
    "le vent glacial transperce les armures des soldats epuises",
    "les ombres des morts dansent dans la lumiere des eclairs",
    "le feu de la rebellion brule dans les coeurs opprimes",
    "les lances se dressent comme une foret de fer acere",
    "le hurlement des damnes resonne dans les grottes profondes et noires",
    "les eaux noires du fleuve charrient les corps des tombes",
    "le traitre meurt par l epee qu il a lui meme forgee",
    "les murs suintent le sang des batailles d autrefois oubliees",
    "le feu sacre consume les idoles du monde ancien corrompu",
    "les aigles de fer planent au dessus de la destruction totale",
    "le grondement de la terre annonce la fin des temps mortels",
    "les guerriers fantomes marchent dans la brume du matin sanglant",
    "le metal en fusion coule comme les larmes des dieux",
    "les cris de rage s elevent au dessus du fracas des armes",
    "le vent transporte l odeur de la poudre et du sang",
    "les murailles de glace se fendent sous le souffle du dragon",
    "le destin se forge dans les flammes de la souffrance pure",
    "les cavaliers de l apocalypse traversent les cieux dechires",
    "le glaive tranche sans distinction entre le juste et le coupable",
    "les entrailles de la terre recrachent leurs morts affames de vengeance",
    "le pacte avec les tenebres est scelle dans le feu noir",
    "les flammes bleues brulent les ponts entre le monde et l enfer",
    "le rugissement du guerrier fait taire le tonnerre lui meme",
    "les ronces de fer envahissent les terres autrefois fertiles",
    "le crrepuscule des dieux illumine le monde de sa fureur",
    "les tambours de guerre battent le rythme de la destruction totale",
    "le spectre de la mort plane sur les derniers survivants terrifies",
    "les eclairs frappent la tour et le monde se fissure",
    "le sang noir coule des blessures du monde agonisant lentement",
    "les loups de fer chassent en meute dans la nuit profonde",
    "le cri de la terre dechire le voile entre les mondes",
    "les flammes montent toujours plus haut dans le ciel sans etoiles",
    "le marteau frappe l enclume et les etincelles sont des etoiles",
    "les morts ne dorment plus dans leurs tombeaux de pierre froide",
    "le vent d acier tranche les nuages comme une lame aiguisee",
    "les hordes sauvages deferlent comme un raz de maree de fureur",
    "le sol est gorge du sang de mille batailles anciennes",
    "les etoiles s eteignent une a une dans le ciel mourant",
    "le fer et le feu sont les seuls maitres de ce monde",
    "les murs de la prison croulent sous la rage des captifs",
    "le dernier souffle du mourant est un cri de defi",
    "les cendres retombent sur un monde qui ne sera plus jamais",
    "le serpent de feu encercle la montagne des damnes pour toujours",
    "les guerriers tombe au combat rejoignent la grande armee des morts",
    "le fracas des armes couvre les prieres des desesperes",
    "les statues de bronze fondent dans la chaleur de l apocalypse",
    "le traitre rampe dans la boue implorant une pitie absente",
    "les portes de la citadelle grincent sous le poids du siege",
    "le vent souffle la cendre des empires tombes en ruines",
    "les chaines du destin lient les vivants et les morts ensemble",
    "le cri du corbeau est le seul chant dans ce desert",
    "les eclats de metal volent comme une pluie meurtriere sans fin",
    "le monde s effondre et nous restons debout dans les decombres",
    "les yeux rouges de la bete percent les tenebres epaisses",
    "le sang rouge marque le seuil du temple de la guerre",
    "les ames hurlantes tourbillonnent dans le vortex de la damnation",
    "le feu du dragon ne laisse que des cendres et du silence",
    "les murs de l enfer sont batis avec les os des damnes",
    "le craquement des os resonne dans le silence de la mort",
    "les vagues noires engloutissent les cotes du monde condamne",
    "le glas resonne pour les royaumes qui ont oublie la guerre",
    "les epees se brisent mais la volonte reste intacte et fiere",
    "le ciel brule d un feu qui ne s eteindra jamais plus",
    "les fantomes des rois errent dans les couloirs du pouvoir vide",
    "le metal en fusion scelle le sort des condamnes a mort",
    "les montagnes s ecroulent sous le poids de la colere divine",
    "le vent de la folie emporte la raison des plus sages",
    "les griffes de la bete laissent des marques sur le monde",
    "le cri de victoire est aussi amer que la defaite subie",
    "les cendres du passe nourrissent les flammes du present brutal",
    "le serpent s enroule autour du trone et etouffe le roi",
    "les morts marchent parmi les vivants sans que personne ne voie",
    "le tonnerre des canons fait trembler les fondations du monde",
    "les corbeaux croassent le requiem des civilisations disparues a jamais",
    "le feu couve sous la cendre et attend son heure fatale",
    "les lames dansent dans la nuit comme des eclairs mortels",
    "le coeur du guerrier bat au rythme des tambours de guerre",
    "les troupeaux de la mort paissent dans les champs de cendres",
    "le venin du pouvoir corrompt les plus nobles des ames",
    "les murs de chair et d os protegent la cite des damnes",
    "le souffle du neant aspire les dernieres lueurs d espoir vain",
    "les machines de guerre avancent et la terre se fissure",
    "le sang verse appelle le sang dans un cycle sans fin",
    "les voix des morts murmurent des maledictions dans le vent glacial",
    "le gouffre s ouvre et les flammes jaillissent des profondeurs noires",
    "les chaines forgees dans la haine ne se brisent qu avec rage",
    "le ciel de plomb ecrase les reves des mortels impuissants",
    "les armees marchent vers leur propre destruction sans le savoir",
    "le metal chante la chanson de la destruction et du chaos",
    "les rats rongent les fondations du monde qui s ecroule lentement",
    "le sang du dragon empoisonne les sources de vie autrefois pures",
    "les hurlements de rage montent de la terre vers le ciel",
    "le feu de l enfer forge les ames les plus dures",
    "les ossements des anciens guerriers craquent sous nos bottes de fer",
    "le vent des limbes emporte les souvenirs des mondes brises",
    "les flammes dansent sur les cadavres des empires dechus et oublies",
    "le marteau du jugement frappe sans distinction ni pitie aucune",
    "les larmes de sang coulent sur les joues de la terre",
    "le dernier soldat debout porte le poids de tous les morts",
    "les racines du mal plongent profondement dans le coeur du monde",
    "le grondement souterrain annonce que la bete s est eveillee enfin",
    "les lames empoisonnees tranchent les liens entre la vie et la mort",
    "le feu eternel brule dans les yeux des condamnes rebelles",
    "les champs de ruines s etendent a perte de vue desormais",
    "le cri des damnes est une symphonie de douleur pure",
    "les eclairs rouges zebrent le ciel noir de l apocalypse",
    "le monde ancien s ecroule et un nouveau nait dans les flammes",
    "les ombres geantes avalent les derniers rayons de lumiere pale",
    "le fer chante quand il tranche la chair des ennemis",
    "les volcans crachent leur fureur sur les terres des hommes",
    "le sol se couvre de givre noir sous le souffle du neant",
    "les combattants epuises refusent de plier malgre les blessures profondes",
    "le tonnerre roule sans fin dans le ciel de l apocalypse",
    "les flammes de la revolte embrasent les quatre coins du monde",
    "le sang des braves nourrit la terre de la resistance eternelle",
    "les fers des prisonniers resonnent comme un hymne de defi",
    "le glas du monde ancien sonne dans la nuit profonde",
    "les aigles noirs planent en silence au dessus du carnage",
    "le cri de la victoire se mele au hurlement des loups",
    "les epees jurees ne retourneront jamais dans leur fourreau de cuir",
    "le pacte de fer lie les guerriers au dela de la mort",
    "les ombres de la guerre s etirent sur les siecles a venir",
    "le metal rugit dans la tempete de la bataille finale",
    "les cendres des heros fertilisent la terre des legendes nouvelles",
    "le vent de la fureur souffle les braises de la rebellion",
    "les mers de sang battent les rivages du monde perdu",
    "le cor retentit et les montagnes repondent avec un grondement sourd",
    "les damnes se dressent et marchent vers la lumiere interdite",
    "le feu de la forge brule plus fort que le soleil",
    "les bannieres noires claquent au vent de la guerre totale",
    "le sang verse aujourd hui fera naitre les roses de demain",
    "les murailles de fer ne cedent pas devant la peur",
    "le cri du metal est la voix de notre colere",
    "les flammes de la liberte brulent dans chaque coeur enchaine",
    "le marteau et l enclume faconnent le destin des guerriers",
    "les ombres s evanouissent quand le feu de la rage s allume",
    "le vent d acier balaie les mensonges des faux prophetes",
    "les chaines tombent et le rugissement des libres secoue la terre",
    "le fer ne rouille pas dans le sang des batailles sacrees",
    "les etoiles meurent mais notre rage brule pour l eternite entiere",
    "le dernier cri du monde est un rugissement de defi absolu",
    "les archers noirs dechochent leurs fleches vers le ciel en flammes",
    "le pont levis s ecrase et les hordes envahissent la cite",
    "les cornes du taureau de fer transpercent les boucliers ennemis",
    "le sang des martyrs nourrit la terre de la resistance fiere",
    "les eclats d obus labourent le sol comme une charrue maudite",
    "le cri du faucon de fer dechire les nuages noirs",
    "les catapultes lancent des pierres en feu sur les remparts fatigues",
    "le venin du scorpion coule dans les veines du monde mourrant",
    "les cavaliers noirs chevauchent les ombres de la nuit sans fin",
    "le belier de guerre defonce les portes de la derniere citadelle",
    "les cris des mourants se melent au sifflement du vent glacial",
    "le masque de fer cache le visage de la verite cruelle",
    "les tours de guet s ecroulent une a une dans la tempete",
    "le goudron bouillant coule sur les assaillants depuis les remparts",
    "les spectres des rois hantent les salles du trone ensanglante",
    "le sol se fissure et les flammes jaillissent des entrailles noires",
    "les catacmbes abritent les secrets des morts oublies depuis longtemps",
    "le fracas des boucliers resonne comme le tonnerre dans la valllee",
    "les chiens de guerre hurlent et tirent sur leurs chaines de fer",
    "le poison lent consume les empires de l interieur vers le neant",
    "les epees rougies par le feu marquent la chair des vaincus",
    "le heaume cabose porte les marques de cent combats acharnes",
    "les fleches sifflent comme des serpents dans l air charge de cendres",
    "le pont des supplices enjambe le gouffre de la damnation eternelle",
    "les tours de flammes eclairent la nuit d une lumiere infernale",
    "le cri de la gargouille glace le sang des plus braves",
    "les murs suintent le poison qui corrompt les fondations du monde",
    "le trone des ombres attend celui qui osera s y asseoir",
    "les tempetes de sable engloutissent les armees dans le desert noir",
    "le sang sur les mains du guerrier ne s efface jamais plus",
    "les volcans forment une chaine de feu autour du monde condamne",
    "le sifflement de la lame annonce la mort du traitre lache",
    "les tombeaux profanes liberent les esprits vengeers de leurs chaines",
    "le sol est jonche de boucliers brises et de lances tordues",
    "les murs de la forteresse saignent sous les coups du destin",
    "le cri du dragon resonne dans les cavernes de la montagne",
    "les armees de squelettes marchent au rythme des tambours de l enfer",
    "le feu gregeois devore les navires dans le port en flammes",
    "les lances des centurions forment un mur de fer implacable",
    "le spectre du roi dechu erre dans les couloirs de pierre",
    "les champs de bataille fument encore longtemps apres le dernier coup",
    "le grondement des chariots de guerre fait fuir les animaux terrifes",
    "les morts empiles forment des collines dans la plaine devastee",
    "le vent de la desolation balaie les cendres des royaumes tombes",
    "les cornes de guerre sonnent et la terre entiere se fige",
    "le sceau de sang ne peut etre brise que par la mort",
    "les survivants errent dans les decombres cherchant les leurs en vain",
    "le metal fondu coule des toits comme des larmes brulantes",
    "les ronces noires envahissent le chateau abandonne par les vivants",
    "le dernier bastion resiste encore mais les murs se fissurent lentement",
    "les herauts de la destruction sonnent la charge une derniere fois",
    "le cri du titan fait s effondrer les colonnes du temple maudit",
    "les lames empoisonnees sifflent dans l air comme des serpents de metal",
    "la terre vomit ses morts et le ciel pleure des larmes de sang",
    "le guerrier aveugle combat par la force de sa rage interieure",
    "les torches eclairent les visages marques par la guerre sans fin",
    "le vent des abimes transporte les maledictions des siecles passes",
    "les mains du forgeron sont noires de suie et de rage contenue",
    "la citadelle de glace craque sous le poids de la fureur ancienne",
    "le grondement des montagnes annonce le reveil de la bete endormie",
    "les corbeaux descendent en spirale sur le champ des derniers vivants",
    "le sang du roi empoisonne coule noir sur les marches du trone",
    "les murs de la prison s ecroulent sous les poings des enchaines",
    "la foudre rouge frappe le sommet de la tour des supplices",
    "le cri du metal dechire le voile entre les mondes des morts",
    "les cavaliers spectraux traversent les plaines dans un silence glacial",
    "le marteau du geant ebranle les fondations du monde des hommes",
    "les epees maudites boivent le sang de ceux qui les touchent",
    "la brume empoisonnee rampe dans les vallees comme un serpent de soufre",
    "le trone de cendres attend le conquérant qui ne connaît pas la peur",
    "les chaines des geants se tendent et le monde craque a chaque maillon",
    "la colere du volcan fait fondre les armures des guerriers orgueilleux",
    "le vent siffle a travers les cranes empiles au bord de la route",
    "les loups d acier hurlent sous une lune de sang et de cendres",
    "la forteresse de fer resiste mais ses portes ploient sous les coups",
    "le dernier soldat leve son epee et le soleil se voile de honte",
    "les flammes vertes brulent les ames sans consumer la chair tremblante",
    "le pont des damnes s ecroule et les condamnes tombent dans le vide",
    "la vengeance est un breuvage amer qui coule dans nos gorges assechees",
    "le cri du phœnix de fer annonce la chute d un empire pourri",
    "les machines infernales broient les os et les espoirs des vaincus",
    "la nuit rouge s abat sur les dernieres terres encore libres",
    "le givre noir recouvre les epees des soldats tombes au combat",
    "les cris des banshees percent la nuit et glacent le sang des vivants",
    "la lave du cratere inonde les villages dans un silence de mort",
    "le masque du bourreau tombe et revele le visage de la trahison",
    "les fleches enflammees dessinent des arcs de feu dans le ciel noir",
    "la terre s ouvre en deux et avale les armees entieres des hommes",
    "le son du cor de guerre fait trembler jusqu aux os des montagnes",
    "les gargoyles de pierre prennent vie et s envolent dans la tempete",
    "la rage du berserk consume tout ce qui se dresse sur son chemin",
    "le trone maudit devore l ame de quiconque ose s y asseoir seul",
    "les flammes noires brulent sans chaleur et geelent l ame des damnes",
    "le hurlement du loup alpha lance la chasse dans la nuit sans lune",
    "la tour de guet s ecroule et les sentinelles tombent dans le vide",
    "le sang des dragons empoisonne les sources et les rivieres du monde",
    "les guerriers zombies marchent sans relache vers les murs de la cite",
    "la faux de la mort moissonne les rangs des armees terrifiees",
    "le metal en fusion scelle les portes de l enfer pour toujours",
    "les eclairs frappent en cadence comme les marteaux de la forge noire",
    "la rage des opprimes eclate comme un volcan trop longtemps contenu",
    "le cri de guerre se transforme en chant funeraire dans la nuit",
    "les murs du donjon suintent la peur de ceux qui y sont morts",
    "la tempete de feu balaie les plaines comme un fleuve de lave",
    "le spectre du general hante le champ de bataille ou il est tombe",
    "les ronces de fer s enroulent autour du trone du tyran dechu",
    "la lame brisee est plus dangereuse qu une lame intacte et neuve",
    "le monde croule et dans les ruines poussent les graines de la revanche",
    "les morts se dressent et leurs yeux brulent d une rage millénaire",
    "la horde avance et le sol tremble sous le poids de mille armures",
    "le chant des forgerons resonne dans les cavernes profondes de la montagne",
    "les chaines de diamant ne resistent pas a la fureur des enchaines",
    "la nuit sans lune est le linceul des empires qui s effondrent",
    "le dernier rempart cede et les tenebres envahissent la terre entiere",
    "les vautours de fer planent au dessus des cites en ruines fumantes",
    "la malediction du roi dechu frappe les generations qui lui succedent",
    "le marteau de l heresie brise les idoles des faux prophetes du monde",
    "les flammes du purgatoire lechent les murs de la cathedrale profanee",
    "le vent hurle les noms des heros oublies dans les gorges profondes",
    "les os des anciens guerriers se levent pour combattre une derniere fois",
    "la riviere de sang traverse la vallee et teinte les pierres de rouge",
    "le cri du metal resonne dans les entrailles de la terre qui gronde",
    "les boucliers brises jonchent le sol comme les ecailles d un dragon mort",
    "la fureur du berserker fait reculer meme les demons les plus feroces",
    "le trone de fer est chaud du sang de ceux qui y sont morts",
    "les ombres des guerriers tombés dansent dans la lueur des eclairs rouges",
    "la terre tremblee sous les pas de l armee des morts vivants",
    "le glaive du destin tranche le fil de la vie des tyrans",
    "les murailles d os et de cendres protegent le coeur noir du monde",
    "la rage du peuple est un raz de maree que rien n arrete",
    "le fer incandescent marque le front des guerriers qui ont jure vengeance",
    "les cendres du sacrifice nourrissent les racines de l arbre de la rage",
    "la nuit eternelle s installe sur les ruines de la civilisation brisee",
    "le monstre des profondeurs fait surface et les oceans se dechrent de peur",
    "les tambours de l apocalypse battent un rythme que seuls les morts entendent",
    "la forteresse de cendres s eleve sur les restes du monde ancien",
    "le hurlement de la meute fait taire les prieres des desesperes",
    "les flammes du chaos consument les archives de l histoire des hommes",
    "le dernier cri du condamne est un defi lance a la mort",
    "les murs de l arene sont taches du sang de mille combats",
    "la rage est une arme que le temps n emousse jamais vraiment",
    "le tonnerre souterrain fait s ecrouler les tunnels du monde souterrain",
    "les epeees croisees forment un pont entre la vie et le neant",
    "la vengeance couve comme un feu sous les cendres du desespoir froid",
    "le cri du guerrier mourant est plus fort que mille trompettes de guerre",
    "les chaines de fer chauffees au rouge marquent la peau des rebelles",
    "la tempete d acier balaie les pretentions des rois de pacotille",
    "le sol se fend et les flammes de l enfer lechent les pieds des vivants",
    "les cornes du demon resonnent dans les cavernes ou les ames se perdent",
    "la derniere bataille fait rage et personne ne sait qui gagnera ce soir",
    "le cri des enchaines fait trembler les barreaux de la prison de fer"
  ],
  bridges: [
    "car le feu de l enfer ne s eteint jamais vraiment",
    "et les morts marchent avec nous vers la bataille finale",
    "mais la vengeance brule plus fort que les flammes infernales",
    "car le chaos est le seul ordre que nous connaissons",
    "et le sang verse crie justice depuis les profondeurs noires",
    "mais les chaines se brisent quand la rage atteint son point",
    "car la mort n est qu une porte vers un combat plus grand",
    "et les tenebres reculeront devant la fureur de nos coeurs",
    "mais le fer ne plie pas sous la main des laches",
    "car nous sommes forges dans les flammes de la souffrance eternelle",
    "et le monde tremblera quand nous marcherons de nouveau ensemble",
    "mais la rage est le seul remede contre la tyrannie",
    "car les guerriers ne meurent pas ils deviennent des legendes",
    "et le tonnerre de notre colere resonnera dans les siecles futurs",
    "mais le pacte de sang ne peut etre rompu jamais",
    "car le metal ne rouille pas dans le feu de combat",
    "et les ombres fuient devant la lumiere de notre fureur",
    "mais la bete s eveille et rien ne peut l arreter maintenant",
    "car le destin se forge dans les flammes pas dans le doute",
    "et les cendres du passe nourrissent le feu de demain",
    "mais les damnes se levent et les tyrans tremblent enfin",
    "car le sang des braves coule pour que les faibles vivent",
    "et le monde brulera avant de renaitre de ses cendres",
    "mais la nuit eternelle finit toujours par rencontrer l aube",
    "car les murs tombent et la verite eclate comme le tonnerre",
    "et nous portons les cicatrices de mille batailles gagnees",
    "mais le feu interieur est plus fort que toutes les tempetes",
    "car la mort n est que le commencement d un combat eternel",
    "et les chaines forgees dans la haine se brisent par la rage",
    "mais le guerrier connait la douleur et la fait sienne",
    "car le metal dans nos veines nous rend plus forts que tout",
    "et les volcans de notre colere finissent par tout emporter",
    "mais la flamme de la revolte ne peut etre etouffee",
    "car nous sommes le tonnerre et l eclair et la tempete",
    "et le monde entendra notre cri jusqu a la fin des temps"
  ],
  choruses: [
    "le feu et le fer forgent notre destinee eternelle",
    "nous marchons dans les flammes et nous n avons pas peur",
    "le sang coule et la terre tremble sous notre colere",
    "les tenebres sont notre royaume et la nuit notre armure",
    "nous sommes les guerriers de l ombre et de la fureur",
    "le metal hurle et nos coeurs battent au rythme du chaos",
    "la mort n est qu un passage vers la gloire eternelle",
    "nous brisons les chaines et le monde s effondre devant nous",
    "le feu de la vengeance brule dans nos veines de fer",
    "les flammes montent et le ciel se dechire au dessus",
    "nous sommes forges dans le feu et trempes dans le sang",
    "le tonnerre gronde et nous repondons avec notre rage",
    "les murs tombent et la fureur du metal prevaut toujours",
    "nous chevauchons la tempete et defions la mort elle meme",
    "le sang des heros coule pour la liberte de tous",
    "les cendres du monde ancien nourrissent notre feu sacre",
    "nous sommes le cri de la terre et la voix du tonnerre",
    "le fer dans nos mains est la justice des opprimes",
    "les flammes de l enfer ne brulent pas les coeurs de fer",
    "nous marchons dans la nuit et la nuit tremble devant nous",
    "le metal est notre priere et le feu notre temple",
    "les chaines se brisent et les damnes se levent enfin",
    "nous portons la rage du monde dans nos poings fermes",
    "le cri de guerre est notre chant de liberte eternelle",
    "les tenebres reculent quand notre fureur s eveille et gronde",
    "nous sommes l orage qui balaie les mensonges des tyrans",
    "le sang verse aujourd hui est la semence de la victoire",
    "les morts combattent avec nous dans la bataille sans fin",
    "nous forgeons notre destin dans les flammes de la resistance",
    "le metal dans nos ames ne rouille pas ne flechit jamais",
    "les flammes de notre rage eclairent le chemin des rebelles",
    "nous sommes la tempete qui detruit et qui purifie tout",
    "le fer et le feu sont les armes de notre liberte",
    "les murs de l oppression croulent sous nos coups de marteau",
    "nous marchons ensemble vers l aube sanglante d un monde nouveau",
    "le rugissement de notre colere fait trembler les dieux eux memes",
    "les epees levees forment une foret de volonte inflexible",
    "nous sommes les enfants du chaos et de la fureur noire",
    "le feu ne s eteint pas dans le coeur des guerriers",
    "les cendres retombent mais notre esprit reste debout et fort",
    "nous portons les armes de nos peres et leur rage sacree",
    "le sang et les larmes forgent les ames les plus dures",
    "les tenebres fuient devant la lueur de nos epees levees",
    "nous sommes la rage incarnee et le monde nous appartient",
    "le tonnerre de nos pas fait trembler les fondations du monde",
    "les flammes eternelles brulent dans les yeux des insoumis",
    "nous sommes le metal qui ne plie pas ne rompt jamais",
    "le cri des opprimes est notre hymne de bataille sacre",
    "les chaines sont brisees et la liberte coute du sang",
    "nous sommes le feu qui consume le mensonge et la peur",
    "le metal rugit et les montagnes s agenouillent devant notre fureur",
    "nous sommes l acier trempe dans les larmes des generations passees",
    "les flammes du combat eclairent le chemin des guerriers de l ombre",
    "le fer et le sang sont le prix de notre liberte gagnee",
    "nous chevauchons le chaos comme des dieux sur des chevaux de feu",
    "le cri de notre rage est l hymne des peuples asservis",
    "les cendres du tyran fertilisent la terre des hommes libres enfin",
    "nous forgeons la victoire dans les flammes de notre determination feroce",
    "le tonnerre repond a notre appel et le monde s incline devant",
    "les murs de l oppression tombent sous le marteau de notre volonte",
    "nous sommes les loups qui chassent dans la nuit sans fin ni peur",
    "le feu de la rebellion ne peut etre eteint par aucune pluie",
    "les epees levees brillent et notre cri fait trembler les dieux",
    "nous marchons dans le sang et les cendres vers un monde nouveau",
    "le metal dans nos veines est plus dur que le diamant noir",
    "les tambours de guerre resonnent et nos coeurs battent a l unisson",
    "nous brisons les murs du silence avec la force de notre voix",
    "le feu sacre brule dans nos ames et ne s eteindra jamais",
    "les guerriers tombent mais la legende ne meurt jamais dans le feu",
    "nous sommes la foudre qui frappe sans prevenir et sans remords",
    "le sang verse sur le champ de bataille crie victoire et gloire",
    "les chaines brisees sont nos trophees et la rage notre couronne",
    "nous portons le fer et le feu contre les ombres de la nuit",
    "le rugissement de la horde fait craquer les murs de la realite",
    "les flammes de notre colere eclairent le monde dans ses tenebres",
    "nous sommes ne dans le feu et nous mourrons dans la gloire",
    "le metal est notre sang et la fureur notre raison d etre",
    "les damnes se levent et les murs de l enfer tremblent devant nous",
    "nous sommes la tempete de fer qui ne connaît ni peur ni fin",
    "le feu de notre revolte eclaire le monde jusqu a la fin des temps"
  ],
  vocabulary: {
    nouns: [
      "epee", "flamme", "cendre", "sang", "fer",
      "guerre", "mort", "enfer", "chaine", "forteresse",
      "trone", "lame", "tonnerre", "dragon", "ombre",
      "fureur", "vengeance", "chaos", "destruction", "trahison",
      "armure", "bouclier", "hache", "marteau", "lance",
      "corbeau", "loup", "bete", "demon", "spectre",
      "volcan", "foudre", "tempete", "gouffre", "abime",
      "ruine", "cendres", "ossements", "crane", "cicatrice",
      "banniere", "rempart", "siege", "conquete", "massacre",
      "forge", "enclume", "metal", "acier", "damnation",
      "apocalypse", "cataclysme", "carnage", "heresie", "blaspheme",
      "necropole", "cimetiere", "tombeau", "mausolee", "sarcophage",
      "grimoire", "sortilege", "malediction", "prophetie", "oracle",
      "titan", "leviathan", "behemoth", "hydre", "minotaure",
      "citadelle", "donjon", "cachot", "oubliette", "douves",
      "catapulte", "belier", "javelot", "fleche", "carquois",
      "faucille", "poignard", "dague", "sabre", "massue"
    ],
    verbs: [
      "bruler", "detruire", "forger", "combattre", "trancher",
      "rugir", "hurler", "ecraser", "dechirer", "fracasser",
      "envahir", "conquerer", "aneantir", "pulveriser", "ravager",
      "decimer", "plonger", "sombrer", "saigner", "gronder",
      "tonner", "foudroyer", "embraser", "calciner", "broyer",
      "lacerer", "pourfendre", "terrasser", "dominer", "soumettre",
      "enchainer", "briser", "fendre", "percer", "hanter",
      "maudire", "damner", "profaner", "trahir", "venger",
      "renaitre", "defier", "resister", "chevaucher", "assieger",
      "massacrer", "pilonner", "deferler", "ramper", "implorer",
      "decapiter", "eviscerer", "empaler", "ecarteler", "crucifier",
      "incanter", "invoquer", "conjurer", "exorciser", "bannir",
      "pietiner", "ecraser", "aplatir", "laminer", "compresser",
      "calciner", "carboniser", "vitrifier", "incinerer", "desintegrer",
      "engloutir", "devorer", "absorber", "aspirer", "siphonner",
      "corrompre", "gangrener", "contaminer", "infester", "empoisonner",
      "marteler", "pilonner", "mitrailler", "bombarder", "canonner"
    ],
    adjectives: [
      "sombre", "sanglant", "furieux", "infernal", "maudit",
      "brutal", "impitoyable", "feroce", "destructeur", "mortel",
      "noir", "ardent", "terrifiant", "sauvage", "cruel",
      "implacable", "devastateur", "titanesque", "apocalyptique", "demoniaque",
      "glacial", "venimeux", "corrompu", "dechaine", "rageur",
      "sinistre", "lugubre", "funebre", "spectral", "macabre",
      "colossal", "foudroyant", "invincible", "indomptable", "redoutable",
      "inebranlable", "inexorable", "carnassier", "vorace", "tonnant",
      "volcanique", "incandescent", "abyssal", "cataclysmique", "diabolique",
      "vengeur", "souterrain", "dantesque", "herculeen", "titanesque",
      "putride", "pestilentiel", "fetide", "nauseabond", "cadaverique",
      "charognard", "necrotique", "gangrene", "corrompu", "purulent",
      "infame", "abject", "ignoble", "atroce", "abominable",
      "cyclopeen", "gigantesque", "monstrueux", "gargantuesque", "pharaonique",
      "sulfureux", "volcanique", "magmatique", "tellurique", "sismique",
      "desole", "ravage", "devaste", "calcine", "ruine",
      "fracasse", "disloque", "demembre", "mutile", "lacere"
    ]
  }
};
