module.exports = {
  themes: [
    "amour",
    "coeur brise",
    "danse",
    "reves",
    "liberte",
    "jeunesse",
    "nuit",
    "espoir",
    "ete",
    "voyage",
    "celebration",
    "confiance",
    "lumiere",
    "desir"
  ],
  openers: [
    "Ce Soir On Danse Sous Les Etoiles Du Ciel",
    "Mon Coeur Ne Bat Que Pour Toi Seule",
    "Les Lumieres De La Ville Nous Appellent",
    "Je Ferme Les Yeux Et Je Reve De Toi",
    "On A Toute La Nuit Pour S'aimer Encore",
    "Le Monde Est A Nous Ce Soir Mon Amour",
    "Chaque Battement De Coeur Me Rapproche De Toi",
    "Les Etoiles Brillent Pour Nous Ce Soir",
    "Prends Ma Main Et Suis Moi Vers La Lumiere",
    "Je Sens La Musique Qui Monte Dans Mon Ame",
    "Ce Matin Le Soleil A Change Ma Vie",
    "On Etait Jeunes Et Le Monde Etait Grand",
    "Laisse Moi Te Montrer Ce Que L'amour Peut Faire",
    "Sous Le Ciel De Paris Mon Coeur S'envole",
    "Tu Es La Seule Chose Qui Me Fait Vibrer",
    "Quand La Nuit Tombe Je Pense Encore A Toi",
    "On Peut Tout Recommencer Si Tu Le Veux",
    "Les Saisons Passent Mais Mon Amour Reste La",
    "Dis Moi Que Tu Restes Jusqu'au Lever Du Jour",
    "Je Danse Seule Mais Je Reve De Tes Bras",
    "Ouvre Les Yeux Le Monde Est Si Beau",
    "Cette Chanson Est Pour Toi Mon Ange",
    "Les Nuits D'ete Sont Faites Pour S'aimer",
    "Mon Ame Cherche La Tienne Dans La Foule",
    "Ce Soir On Oublie Tout Et On Vit",
    "Tu As Allume Une Flamme Dans Mon Coeur",
    "Le Bonheur Est La Juste Devant Nous",
    "Je Compte Les Jours Jusqu'a Te Revoir",
    "La Vie Est Belle Quand Tu Es Pres De Moi",
    "On Se Retrouve La Ou Tout A Commence",
    "Chaque Seconde Sans Toi Me Semble Eternelle",
    "Tu Es Ma Lumiere Dans L'obscurite Du Monde",
    "Les Mots Me Manquent Pour Dire Ce Que Je Sens",
    "Ce Soir La Musique Parle A Notre Place",
    "Je T'attendais Sans Meme Le Savoir",
    "On Va Danser Jusqu'a Ce Que Le Soleil Se Leve",
    "Ton Sourire Illumine Mes Jours Les Plus Sombres",
    "Je Ferme Les Yeux Et Le Monde Disparait",
    "L'amour Nous Guide Vers Des Lendemains Meilleurs",
    "Reste Avec Moi Jusqu'a La Fin Du Temps",
    "Cette Nuit Nous Appartient A Toi Et Moi",
    "On Est Deux Contre Le Reste Du Monde",
    "Je Reve D'un Monde Ou Tu Es Toujours La",
    "La Melodie De Ton Rire Resonne En Moi",
    "Prends Mon Coeur Il Est A Toi Pour Toujours",
    "On A Brule Si Fort Sous Les Etoiles",
    "Chaque Matin Est Un Nouveau Depart Avec Toi",
    "Tu Es Le Reve Que Je Ne Veux Pas Quitter",
    "Laisse La Musique Nous Porter Plus Loin",
    "Je Suis Prete A Tout Pour Un Soir Avec Toi"
  ],
  verses: [
    "je danse seule dans ma chambre en pensant a toi",
    "la pluie tombe sur les vitres comme mes larmes",
    "on etait si jeunes quand tout a commence",
    "ton regard a change ma vie pour toujours",
    "je cherche ton ombre dans chaque rue de la ville",
    "les souvenirs de nous deux me hantent la nuit",
    "mon coeur bat si fort quand tu es pres de moi",
    "on a couru sous la pluie en riant comme des fous",
    "chaque chanson a la radio me parle de toi",
    "je ne sais plus ou finit le reve et ou commence la vie",
    "tes mots resonnent encore dans le silence de ma chambre",
    "on a danse toute la nuit sans voir le temps passer",
    "le gout de tes levres reste sur les miennes",
    "je me perds dans la foule en cherchant ton visage",
    "les jours sans toi sont comme un ciel sans etoiles",
    "on se promettait le monde entier sous les lumieres",
    "chaque pas que je fais me rapproche de mon reve",
    "ton absence est une blessure qui ne guerit pas",
    "les nuits sont longues quand on aime en silence",
    "on a grave nos noms sur les murs de la ville",
    "je sens encore ton parfum dans l'air du soir",
    "la musique nous porte vers un autre monde",
    "on etait invincibles sous les lumieres de la fete",
    "tes promesses sont comme des feuilles emportees par le vent",
    "je regarde le ciel et je pense a ce qu'on etait",
    "chaque note de cette chanson raconte notre histoire",
    "on a partage des secrets que personne ne connait",
    "le matin se leve et je suis encore la",
    "ton rire est la plus belle melodie du monde",
    "je me noie dans tes yeux comme dans un ocean",
    "les heures passent mais mon amour ne change pas",
    "on a brule nos peurs dans les flammes de la nuit",
    "chaque battement de coeur murmure ton prenom",
    "je suis perdue sans toi dans cette grande ville",
    "la lumiere du soleil me rappelle ta chaleur",
    "on etait deux etoiles perdues dans le meme ciel",
    "tes mains sur les miennes c'etait tout ce dont j'avais besoin",
    "je danse avec ton souvenir comme seul partenaire",
    "le monde tourne mais je reste immobile sans toi",
    "on a dessine notre avenir sur des serviettes de bar",
    "chaque larme qui tombe porte un morceau de nous",
    "je garde tes messages comme des tresors precieux",
    "la nuit nous revelait ce que le jour cachait",
    "on se retrouvait toujours au meme carrefour",
    "tes yeux sont des miroirs ou je me reconnais",
    "je chante pour oublier que tu n'es plus la",
    "le silence entre nous dit plus que mille mots",
    "on a couru apres le bonheur sans jamais s'arreter",
    "chaque coucher de soleil me rappelle notre ete",
    "je porte ton amour comme un bijou invisible",
    "la distance entre nous est un ocean de regrets",
    "on dansait sur les toits comme si rien ne comptait",
    "tes baisers avaient le gout du miel et des larmes",
    "je me reveille chaque nuit en cherchant ta main",
    "le vent emporte mes paroles vers toi ce soir",
    "on a vecu cent vies dans un seul regard",
    "chaque refrain me ramene a cette nuit la",
    "je dessine ton visage dans la buee des fenetres",
    "les etoiles sont temoins de ce qu'on a vecu",
    "on a ri si fort que le monde s'est arrete",
    "tes lettres d'amour dorment sous mon oreiller",
    "je marche dans tes pas pour ne pas te perdre",
    "la mer nous separait mais nos coeurs se touchaient",
    "on est nes pour se trouver dans cette vie la",
    "chaque matin sans toi est un combat de plus",
    "je reve de toi meme quand je suis eveillee",
    "le temps s'arrete quand nos levres se frolent",
    "on a ecrit notre histoire dans la poussiere des etoiles",
    "tes silences me parlaient plus fort que tes mots",
    "je ferme les yeux et tu apparais devant moi",
    "la piste de danse est notre seul territoire",
    "on a fait des promesses qu'on savait impossibles",
    "chaque saison me rappelle un chapitre de nous",
    "je t'ai aime comme on aime une premiere fois",
    "le dernier train est parti sans nous ce soir",
    "on se cherchait dans la foule sans se trouver",
    "tes caresses etaient douces comme un soir de mai",
    "je compte les etoiles en attendant ton retour",
    "la ville s'endort mais mon coeur reste eveille",
    "on a partage un reve qui n'avait pas de fin",
    "chaque jour est une page blanche sans ton amour",
    "je me souviens de chaque mot que tu m'as dit",
    "le ciel est gris mais mon coeur garde ta lumiere",
    "on etait le feu et la glace reunis",
    "tes regards me disaient tout sans prononcer un mot",
    "je vis au rythme de cette chanson inachevee",
    "la nuit porte conseil mais elle porte aussi ton nom",
    "on a vole des instants au temps qui passait",
    "chaque rue de cette ville porte notre empreinte",
    "je t'ecris des mots que tu ne liras jamais",
    "le bonheur etait la dans le creux de ta main",
    "on a danse sous la pluie sans parapluie ni peur",
    "tes sourires etaient des soleils dans ma tempete",
    "je garde notre chanson dans un coin de mon ame",
    "la melodie de la nuit berce mes pensees de toi",
    "on a vieilli d'un siecle en une seule nuit",
    "chaque photo de nous est un tresor de papier",
    "je t'ai cherche dans chaque visage de cette foule",
    "le monde est vaste mais mon coeur est petit sans toi",
    "on a marche pieds nus sur le sable chaud",
    "tes doigts dans mes cheveux c'etait mon paradis",
    "je me balance au rythme de nos souvenirs perdus",
    "la lune eclaire le chemin que tu as pris",
    "on a mis notre amour dans une bouteille a la mer",
    "chaque instant avec toi valait mille eternites",
    "je t'ai dit adieu mais mon coeur dit encore bonjour",
    "le matin est froid sans ta voix pour me reveiller",
    "on s'aimait comme dans les films en noir et blanc",
    "tes pas dans la neige etaient ma seule direction",
    "je respire ton souvenir comme un parfum ancien",
    "la ville brille de mille feux qui me rappellent tes yeux",
    "on a traverse l'hiver accroches l'un a l'autre",
    "chaque mot de cette chanson est ne de toi",
    "je danse encore meme quand la musique s'arrete",
    "le silence de la nuit me crie ton absence",
    "on etait des inconnus qui se sont reconnus",
    "tes rires me poursuivent comme des melodies perdues",
    "je navigue sur un ocean de souvenirs avec toi",
    "la chaleur de tes bras me manque ce soir",
    "on a ecrit des chansons sur les murs de notre chambre",
    "chaque etoile filante porte un de mes voeux pour toi",
    "je suis le refrain que tu fredonnais le matin",
    "le temps a passe mais rien n'a vraiment change",
    "on se retrouvait sous le lampadaire a minuit",
    "tes levres murmurent des promesses dans mes reves",
    "je survis a chaque jour en attendant demain",
    "la route est longue mais je sais que tu es au bout",
    "on a pleure ensemble et c'etait notre force",
    "chaque matin je me leve avec ton prenom sur les levres",
    "je ne regrette rien de ce qu'on a partage ensemble",
    "le monde peut trembler mon amour tient bon",
    "on a construit des chateaux dans les nuages roses",
    "tes regards etaient des promesses silencieuses et belles",
    "je vole vers toi comme un papillon vers la lumiere",
    "la nuit est jeune et nos coeurs sont affames",
    "on a tout quitte pour vivre un instant de plus",
    "chaque respiration sans toi est un effort de plus",
    "je me perds dans la danse pour te retrouver",
    "le cafe du matin a le gout de ton absence",
    "on a fait le tour du monde en restant chez nous",
    "tes yeux sont la seule boussole dont j'ai besoin",
    "je tourne en rond dans cette ville sans toi",
    "la musique monte et mon coeur suit le tempo",
    "on a grave notre amour dans l'ecorce des arbres",
    "chaque feu rouge me donne le temps de penser a toi",
    "je suis la chanson que tu as oublie de chanter",
    "le printemps revient mais toi tu ne reviens pas",
    "on s'est aimes comme si demain n'existait pas",
    "tes mots sont des fleches qui touchent toujours leur cible",
    "je porte un masque qui sourit mais mon coeur pleure",
    "la pluie sur mon visage cache mes larmes de toi",
    "on a bu le soleil comme du champagne dore",
    "chaque note de piano me raconte notre premier baiser",
    "je marche sous les etoiles en cherchant notre constellation",
    "le monde s'ecroule mais ta voix me tient debout",
    "on a laisse nos coeurs ouverts a tous les vents",
    "tes photos sur mon mur sont ma galerie secrete",
    "je respire a peine quand tu es si loin de moi",
    "la danse est finie mais le rythme reste en moi",
    "on a vecu l'impossible pendant quelques heures magiques",
    "chaque vague de l'ocean me rappelle tes humeurs",
    "je t'ai donne mon coeur sans mode d'emploi",
    "le miroir me renvoie ton reflet a cote du mien",
    "on etait la preuve que l'amour existe vraiment",
    "tes chansons preferees sont devenues les miennes aussi",
    "je suis une ile perdue dans un ocean sans toi",
    "la nuit tombe et mes pensees s'envolent vers toi",
    "on a joue avec le feu et on s'est brules",
    "chaque anniversaire me rappelle ce qu'on a perdu",
    "je vis dans un film dont tu es la star absente",
    "le soleil se couche sur nos reves inacheves",
    "on a tout donne sans rien garder pour nous",
    "tes pas dans le couloir etaient ma plus belle musique",
    "je me raccroche a l'espoir comme a une bouee",
    "la vie continue mais mon coeur reste en pause",
    "on a ete la lumiere dans l'obscurite de l'autre",
    "chaque sourire que je donne cache un souvenir de toi",
    "je ne peux pas dormir sans ta voix dans ma tete",
    "le train s'en va mais je reste sur le quai",
    "on a ouvert nos ailes sans savoir voler ensemble",
    "tes mains tremblaient quand tu m'as dit au revoir",
    "je suis un puzzle dont tu es la piece manquante",
    "la fete est belle mais il manque quelqu'un ce soir",
    "on a mele nos rires aux bruits de la ville",
    "chaque regard que je croise me fait penser au tien",
    "je tourne les pages de notre album sans fin",
    "le bonheur est fragile comme une bulle de savon",
    "on a cru que l'amour suffisait a tout guerir",
    "tes bras etaient mon refuge quand le monde faisait peur",
    "je suis la derniere page d'un livre que tu as ferme",
    "la route est belle quand on sait ou elle mene",
    "on a perdu le fil mais pas le souvenir",
    "chaque grain de sable me rappelle nos etes passes",
    "je m'endors avec ton nom comme derniere priere",
    "le ciel est immense mais mon monde etait toi",
    "on a couru si vite que le bonheur nous a rattrapes",
    "tes larmes sur ma joue etaient plus chaudes que le soleil",
    "je vis chaque jour comme si c'etait notre dernier",
    "la chanson est finie mais je l'ecoute encore en boucle",
    "on a tout promis sur des etoiles filantes",
    "chaque seconde avec toi vaut une annee sans toi",
    "je suis la flamme qui brule encore pour toi",
    "le monde dort mais mon amour veille sur toi",
    "on a fait de notre histoire la plus belle des chansons",
    "tes sourires sont des rayons de soleil apres la pluie",
    "je ne demande rien qu'un dernier regard de toi",
    "la lumiere du matin me rappelle que tu existais",
    "on a tisse notre amour fil apres fil",
    "chaque brise du soir me porte un peu de toi",
    "je suis la voix qui t'appelle dans le noir",
    "le silence est doux quand il porte ton souvenir",
    "on a construit un monde rien qu'a nous deux",
    "tes mots d'amour sont graves dans ma memoire",
    "je danse avec mon ombre en revant de la tienne",
    "la vie est une chanson et tu en es le refrain",
    "on a tout vecu comme si c'etait un miracle",
    "chaque etoile me rappelle la lumiere dans tes yeux",
    "je garde ton secret comme un tresor dans mon coeur",
    "le vent du soir souffle des mots d'amour pour toi",
    "on a plante des graines d'espoir dans un jardin secret",
    "tes reves et les miens se croisaient dans la nuit",
    "je suis le silence entre deux notes de musique",
    "la pluie dessine ton visage sur ma fenetre",
    "on a ete heureux meme sans le savoir",
    "chaque lever de soleil est un nouveau chapitre sans toi",
    "je cherche encore le chemin qui mene a ton coeur",
    "le ciel se teinte de rose quand je pense a nous deux",
    "on a partage un silence qui disait tout sans parler",
    "tes pas dans la neige formaient un chemin vers mon coeur",
    "je me reveille et ton ombre danse encore sur les murs",
    "la radio joue notre chanson et tout me revient d'un coup",
    "on avait le monde entre nos mains et on l'a laisse filer",
    "chaque flocon de neige me rappelle la douceur de tes mots",
    "je vis au ralenti depuis que tu as quitte ma vie",
    "les lumieres de la fete clignotent mais mon coeur reste eteint",
    "on se regardait comme si personne d'autre n'existait autour",
    "tes levres murmurent encore dans le silence de mes nuits",
    "je tourne dans cette ville comme une boussole sans nord",
    "la douceur de ta voix me manque plus que tout au monde",
    "on a bu les dernieres gouttes de l'ete ensemble toi et moi",
    "chaque rue que je prends me ramene toujours vers toi",
    "je sens ton absence comme une ombre qui me suit partout",
    "les jours se replient sur eux-memes sans ta presence ici",
    "on a danse sous un ciel qui ne nous appartenait pas",
    "tes doigts sur le piano jouaient la melodie de notre histoire",
    "je me noie dans le bruit pour oublier ton silence a toi",
    "la lune me regarde et je lui raconte tout de nous",
    "on a couru apres les nuages en riant comme des enfants",
    "chaque lever de lune me rappelle ta lumiere disparue",
    "je porte ton souvenir comme une echarpe autour de mon cou",
    "les horloges tournent mais le temps s'est arrete dans mon coeur",
    "on a laisse nos rires dans les ruelles de cette vieille ville",
    "tes yeux brillaient plus fort que toutes les vitrines de noel",
    "je chante tes mots quand personne ne m'ecoute le soir",
    "la mer a pris nos traces de pas sur le sable mouille",
    "on a construit des reves sur des serments de minuit",
    "chaque goutte de pluie porte un souvenir de toi en elle",
    "je regarde les couples danser et je pense a ce qu'on etait",
    "les feuilles tombent comme les pages de notre histoire d'amour",
    "on a tout appris ensemble sauf a se dire adieu ce soir",
    "tes mains tremblaient quand tu m'as touche pour la premiere fois",
    "je suis le fantome de nos souvenirs dans cette maison vide",
    "la neige recouvre la ville mais pas mes souvenirs de toi",
    "on a ecrit nos prenoms sur les bancs de ce vieux parc",
    "chaque parfum de fleur me rappelle le jardin de ton sourire",
    "je danse dans la pluie pour laver la douleur de ton depart",
    "les oiseaux chantent le matin mais ta voix me manque plus",
    "on a voyage si loin sans jamais quitter cette petite chambre",
    "tes rires resonnent encore dans le hall de notre immeuble",
    "je ferme les rideaux et je revois ton visage dans le noir",
    "la guitare pleure les mots que ma bouche ne peut pas dire",
    "on a veille toute la nuit a regarder les etoiles tomber",
    "chaque battement de mon coeur est une lettre que je t'envoie",
    "je suis le dernier a croire que tu reviendras un jour",
    "les saisons changent mais ton visage reste le meme en moi",
    "on a seme des promesses dans un champ de lune pleine",
    "tes baisers goutaient les cerises et les larmes de la joie",
    "je vis entre les lignes de cette chanson que tu fredonnais",
    "la ville dort et je suis le seul a penser a nous",
    "on a partage le dernier cafe avant que tout ne change",
    "chaque coucher de soleil peint ton portrait dans le ciel orange",
    "je ne sais plus danser quand la musique ne parle pas de toi",
    "les mots que je n'ai pas dits pesent plus que ceux que j'ai dit",
    "on a couru si loin que le monde semblait petit sans toi",
    "tes traces sur le miroir embue sont tout ce qui me reste",
    "je survis dans un monde ou chaque chanson me rappelle ton nom",
    "la maree emporte nos souvenirs et les ramene chaque matin",
    "on etait si differents que ca ne pouvait qu'etre de l'amour",
    "chaque etoile que je vois me rappelle une nuit avec toi",
    "je respire le vide que tu as laisse dans cette piece froide",
    "les photos jaunissent mais les emotions restent vives en couleur",
    "on a bati notre univers sur un sourire et un peut-etre",
    "tes silences etaient des poemes que seul mon coeur pouvait lire",
    "je me balance sur la balancoire ou on se retrouvait enfants",
    "la pluie dessine des arabesques sur la vitre de ma solitude",
    "on a partage un parapluie et un secret sous l'orage fort",
    "chaque matin le reveil sonne mais c'est ta voix que j'attends",
    "je vis dans une chanson triste dont tu es le dernier couplet",
    "les bougies fondent et l'ombre de ton absence grandit sur les murs",
    "on avait tout le temps du monde mais on a manque de courage",
    "tes lettres parfumees dorment dans un tiroir que je n'ouvre plus",
    "je marche dans les flaques et chacune reflete ton sourire perdu",
    "la nuit me vole les heures et les remplace par des souvenirs",
    "on a danse avec le vent sur ce toit au dessus du monde",
    "chaque refrain de cette chanson est un battement de ton coeur",
    "je vis dans l'echo de ta voix qui s'eloigne chaque jour",
    "les rues mouillees brillent comme tes yeux quand tu pleurais de joie",
    "on a grave des coeurs dans les arbres qui grandissent encore",
    "tes mains sur mon visage c'etait la carte de ma vie",
    "je suis un souvenir qui refuse de s'effacer de ce lieu",
    "la musique s'arrete et ton silence prend toute la place en moi",
    "on a brule si vite que les cendres sont encore chaudes",
    "chaque fois que je ferme les yeux tu es la devant moi",
    "je tourne les pages d'un livre dont tu as ecrit la fin",
    "les papillons dans mon ventre sont devenus des oiseaux en cage",
    "on a tout risque pour un instant qui vaut plus qu'une vie",
    "tes regards du matin etaient le soleil de ma journee entiere",
    "je collectionne les levers de soleil en attendant ton retour",
    "la fenetre ouverte laisse entrer le vent et tes souvenirs aussi",
    "on etait le feu et l'eau mais ensemble on etait la vapeur",
    "chaque note de cette melodie me rappelle le gout de tes levres",
    "je danse avec le vide que tu as laisse entre mes bras",
    "les heures s'egrennent comme des perles d'un collier qui se defait",
    "on a ri jusqu'aux larmes et pleure jusqu'au rire ensemble ce soir",
    "tes pas dans le couloir c'etait le rythme de ma vie entiere",
    "je suis la chanson inachevee que tu as commence a ecrire",
    "la brume du matin enveloppe les restes de notre nuit d'amour",
    "on a cueilli des etoiles et on les a mises dans nos poches",
    "chaque baiser que tu m'as donne brule encore sur mes levres ce soir",
    "je me perds dans les vieux quartiers ou on se promenait ensemble",
    "les dimanches sans toi sont des pages blanches sans histoire dedans",
    "on a danse sur la musique du vent dans les champs verts",
    "tes empreintes sur mon coeur ne partiront jamais au lavage",
    "je vis entre deux mondes celui avec toi et celui sans toi",
    "la chaleur de l'ete me rappelle la douceur de tes mains douces",
    "on a partage mille couchers de soleil mais aucun lever ensemble",
    "chaque larme que je verse pour toi nourrit un jardin secret",
    "je suis le gardien de nos souvenirs dans cette ville qui change",
    "les miroirs ne refletent plus mon sourire depuis que tu es partie",
    "on a jete des pieces dans la fontaine pour un voeu de nous",
    "tes rires dans la foule etaient la seule melodie que j'entendais",
    "je me reveille en sueur apres avoir reve de toi encore",
    "la route vers ton coeur est la seule que je veux prendre",
    "on a construit un pont entre nos deux solitudes immenses",
    "chaque geste que je fais porte l'empreinte de ce qu'on vivait",
    "je vis au rythme d'un coeur qui ne bat que pour toi",
    "les fenetres de notre chambre gardent les traces de nos souffles",
    "on a perdu le temps a chercher ce qu'on avait deja",
    "tes chansons fredonnees sous la douche me manquent plus que tout",
    "je nage dans un ocean de souvenirs sans trouver la rive",
    "la vie est un bal masque et ton visage est le seul vrai",
    "on a tout promis sans rien ecrire et tout s'est envole",
    "chaque nuage dans le ciel prend la forme de ton visage",
    "je vis dans le refrain d'une chanson que tu as oubliee",
    "les ponts de cette ville relient mes souvenirs a tes promesses",
    "on a laisse notre jeunesse sur ce banc face a la mer",
    "tes yeux couleur de miel fondaient mes hivers les plus froids",
    "je suis le dernier passager d'un train qui menait vers toi",
    "la danse est finie et les lumieres s'eteignent une par une",
    "on avait un langage secret que meme le silence comprenait",
    "chaque bouffee d'air frais me rappelle le parfum de tes cheveux",
    "je vis dans le creux de ta main meme si tu l'as fermee",
    "les matins d'hiver sont plus froids sans ta chaleur a mes cotes",
    "on a eu le courage de s'aimer mais pas celui de rester",
    "tes promesses etaient des papillons qui se sont envoles trop vite",
    "je tiens un fil invisible qui me relie encore a ton coeur",
    "la vie sans toi est un film muet en noir et blanc",
    "on a plante notre amour dans un sol trop fragile pour lui",
    "chaque soupir que je pousse traverse la ville pour te trouver",
    "je suis la moitie d'un duo dont l'autre voix s'est tue",
    "les lampadaires s'allument et je pense a nos promenades du soir",
    "on a mis nos secrets dans une boite que j'ai perdu la cle",
    "tes caresses sur mon front chassaient les cauchemars de mes nuits",
    "je dessine des coeurs sur la buee en pensant a ton visage"
  ],
  bridges: [
    "et si on recommencait tout depuis le debut",
    "les murs tombent quand on ose aimer vraiment",
    "entre le reve et la realite je te choisis",
    "peut-etre que demain sera notre jour enfin",
    "les secondes deviennent des heures quand tu pars",
    "je ne savais pas que l'amour pouvait bruler comme ca",
    "au fond de moi une voix me dit de rester",
    "on n'a qu'une vie pour aimer sans compter",
    "les mots s'envolent mais les sentiments restent graves",
    "quelque part entre hier et demain il y a nous",
    "la verite est simple on ne peut pas vivre sans aimer",
    "chaque fin est le debut de quelque chose de nouveau",
    "le coeur sait des choses que la raison ignore",
    "dans le miroir de tes yeux je vois mon avenir",
    "les cicatrices de l'amour sont des medailles de courage",
    "on traverse les tempetes pour meriter le soleil",
    "peut-etre qu'un jour tu comprendras ce que je ressens",
    "le temps ne guerit rien il nous apprend a porter",
    "entre deux battements de coeur il y a ton nom",
    "la musique s'arrete mais la danse continue en moi",
    "on a ete si pres du bonheur sans le toucher",
    "les murs de ma chambre connaissent tous mes secrets",
    "quelque chose me dit que ce n'est pas la fin",
    "le monde peut changer mais mon amour reste le meme",
    "au croisement de nos chemins il y avait un signe",
    "la nuit la plus sombre precede toujours l'aube",
    "je ne sais plus si je reve ou si je vis",
    "entre tes bras le monde entier disparaissait",
    "les etoiles se sont alignees pour nous reunir",
    "peut-etre que l'amour est la seule verite qui reste",
    "on a tout donne et il nous reste l'essentiel",
    "le silence entre nous parle plus fort que les cris",
    "quelque part dans la nuit nos ames se retrouvent",
    "la vie est courte mais l'amour est eternel",
    "au bout du tunnel il y a toujours la lumiere"
  ],
  choruses: [
    "danse avec moi sous les lumieres de la nuit",
    "mon coeur est a toi pour toujours et a jamais",
    "on va briller plus fort que toutes les etoiles",
    "tu es tout ce que j'ai toujours voulu avoir",
    "cette nuit est la notre ne la laisse pas partir",
    "je t'aime comme la mer aime le rivage",
    "on danse on vit on reve ensemble ce soir",
    "ton amour est la seule chose dont j'ai besoin",
    "les etoiles sont la pour nous guider ce soir",
    "je suis a toi tu es a moi pour toujours",
    "on va chanter jusqu'a ce que le soleil se leve",
    "mon coeur bat au rythme de ton prenom",
    "tu illumines ma vie comme un millier d'etoiles",
    "cette chanson est notre histoire ecrite en musique",
    "danse encore danse toujours danse avec moi",
    "tu es ma lumiere dans la nuit la plus sombre",
    "on va voler plus haut que tous les nuages",
    "je respire pour toi je vis pour toi ce soir",
    "les nuits sont belles quand on les partage ensemble",
    "mon ame et la tienne ne font plus qu'une seule",
    "tu es le reve dont je ne veux pas me reveiller",
    "on est nes pour briller sous les memes etoiles",
    "chaque battement de coeur te dit je t'aime",
    "la vie est une fete quand tu es a mes cotes",
    "danse sous la pluie danse sous le soleil",
    "tu es la melodie que mon coeur chante toujours",
    "on va ecrire notre histoire dans les etoiles",
    "je t'attendrai meme si ca prend mille ans",
    "les mots sont faibles pour dire ce que je ressens",
    "ton sourire est le remede a toutes mes peines",
    "on est plus forts ensemble que seuls dans la nuit",
    "je te donnerais le monde si je le pouvais",
    "cette nuit on oublie tout et on danse encore",
    "tu es ma raison de croire en l'amour",
    "on va danser comme si demain n'existait pas",
    "mon coeur t'appelle a travers les ombres de la nuit",
    "tu es le soleil qui eclaire mes jours sombres",
    "on va rever ensemble jusqu'au bout du monde",
    "je suis perdue sans toi retrouve moi ce soir",
    "les etoiles nous montrent le chemin de l'amour",
    "tu es tout mon univers dans un seul regard",
    "on va briller on va danser on va vivre",
    "je t'aime plus que les mots ne peuvent le dire",
    "cette musique est le langage de notre amour",
    "danse avec moi une derniere fois ce soir",
    "tu es la promesse que demain sera beau",
    "on va traverser les oceans pour etre ensemble",
    "mon coeur et le tien battent a l'unisson",
    "tu es la plus belle chanson de ma vie",
    "on va aimer comme si c'etait la premiere fois",
    "tu es la seule etoile qui brille dans mon ciel sombre",
    "on danse sur les toits et le monde est a nos pieds",
    "mon coeur chante ton nom a chaque lever de soleil nouveau",
    "tu es le souffle qui donne vie a mes jours les plus gris",
    "on va s'envoler plus loin que les oiseaux migrateurs",
    "je brule d'amour pour toi et rien ne peut m'eteindre",
    "tu es la danse que mon corps connait par coeur depuis toujours",
    "on est la lumiere qui perce a travers les nuages sombres",
    "mon ame danse avec la tienne sous la lune de nos reves",
    "tu es le refrain qui tourne en boucle dans ma tete",
    "on va courir jusqu'au bout du monde main dans la main",
    "je vis pour toi je danse pour toi je chante pour toi",
    "tu es la flamme qui rechauffe mon hiver sans fin ce soir",
    "on va rever si fort que les etoiles vont nous entendre",
    "mon coeur est une boussole qui pointe toujours vers toi seule",
    "tu es le miracle que j'attendais sans le savoir avant",
    "on va briller ensemble comme deux soleils dans la meme nuit",
    "je t'aime a en perdre le souffle et la raison ensemble",
    "tu es la musique que j'entends meme dans le silence total",
    "on va danser sous les etoiles jusqu'a ce qu'elles s'eteignent",
    "mon coeur est un ocean et ton amour est ma maree",
    "tu es la seule raison pour laquelle je crois au destin",
    "on va tout recommencer comme au premier jour de notre amour",
    "je donnerais tout ce que j'ai pour un instant de plus",
    "tu es ma premiere pensee le matin et la derniere le soir",
    "on est deux ames qui dansent sur la meme melodie eternelle",
    "mon amour pour toi est plus grand que tous les mots du monde",
    "tu es le soleil apres la tempete qui eclaire ma route",
    "on va ecrire la plus belle chanson que l'amour ait jamais connue"
  ],
  vocabulary: {
    nouns: [
      "coeur",
      "etoile",
      "lumiere",
      "nuit",
      "reve",
      "danse",
      "amour",
      "soleil",
      "larme",
      "chanson",
      "ciel",
      "lune",
      "vie",
      "sourire",
      "ame",
      "baiser",
      "regard",
      "espoir",
      "silence",
      "melodie",
      "desir",
      "flamme",
      "promesse",
      "secret",
      "matin",
      "soir",
      "ocean",
      "vent",
      "saison",
      "voyage",
      "fete",
      "bonheur",
      "souvenir",
      "paradis",
      "miroir",
      "refrain",
      "brise",
      "caresse",
      "ombre",
      "chaleur",
      "diamant",
      "jardin",
      "plage",
      "pluie",
      "battement",
      "horizon",
      "frisson",
      "murmure",
      "eternite",
      "aurore",
      "musique",
      "refrain",
      "ritournelle",
      "tempo",
      "vibration",
      "emotion",
      "euphorie",
      "ivresse",
      "tendresse",
      "nostalgie",
      "jeunesse",
      "liberte",
      "destin",
      "confiance",
      "lumignon",
      "constellation",
      "galaxie",
      "papillon",
      "prisme",
      "arc-en-ciel",
      "bulle",
      "eclat",
      "tresor",
      "bijou",
      "couronne",
      "aile"
    ],
    verbs: [
      "danser",
      "rever",
      "aimer",
      "briller",
      "chanter",
      "voler",
      "embrasser",
      "respirer",
      "sourire",
      "courir",
      "tourner",
      "tomber",
      "vibrer",
      "bruler",
      "pleure",
      "murmurer",
      "caresser",
      "illuminer",
      "esperer",
      "promettre",
      "croire",
      "oublier",
      "retrouver",
      "ecouter",
      "sentir",
      "tenir",
      "attendre",
      "chercher",
      "appeler",
      "toucher",
      "effleurer",
      "bercer",
      "enlacer",
      "fredonner",
      "scintiller",
      "flotter",
      "eclater",
      "rayonner",
      "trembler",
      "exister",
      "disparaitre",
      "revenir",
      "pleurer",
      "graver",
      "tisser",
      "envoler",
      "souffler",
      "battre",
      "manquer",
      "ressentir",
      "adorer",
      "celebrer",
      "enchanter",
      "emerveiller",
      "fasciner",
      "captiver",
      "etreindre",
      "enlacer",
      "embrasser",
      "savourer",
      "virevolter",
      "tourbillonner",
      "s'envoler",
      "s'eveiller",
      "irradier",
      "eclabousser",
      "chatoyer",
      "palpiter",
      "frissonner",
      "chavirer",
      "fondre",
      "etinceler",
      "rayonner",
      "emporter",
      "transporter",
      "emerger",
      "eclore",
      "renaitre",
      "oser"
    ],
    adjectives: [
      "beau",
      "doux",
      "tendre",
      "lumineux",
      "eternel",
      "fragile",
      "ardent",
      "magique",
      "brillant",
      "infini",
      "libre",
      "perdu",
      "secret",
      "vivant",
      "celeste",
      "profond",
      "intense",
      "sincere",
      "sauvage",
      "immense",
      "dore",
      "precieux",
      "ephemere",
      "sublime",
      "invisible",
      "solitaire",
      "radieux",
      "pur",
      "leger",
      "nocturne",
      "brulant",
      "sensuel",
      "merveilleux",
      "splendide",
      "romantique",
      "nostalgique",
      "paisible",
      "passionnel",
      "melodieux",
      "envoutant",
      "silencieux",
      "electrique",
      "chaud",
      "mysterieux",
      "inoubliable",
      "timide",
      "fougueux",
      "melancolique",
      "rayonnant",
      "enchante",
      "feerique",
      "eclatant",
      "scintillant",
      "chatoyant",
      "eblouissant",
      "irresistible",
      "magnifique",
      "splendide",
      "captivant",
      "envivrant",
      "celeste",
      "exquis",
      "divin",
      "palpitant",
      "bouleversant",
      "saisissant",
      "etincelant",
      "flamboyant",
      "cosmique",
      "stellaire",
      "aerien",
      "poignant",
      "attendrissant",
      "gracieux",
      "veloute",
      "cristallin",
      "translucide",
      "opalescent",
      "iridescent"
    ]
  }
};
