module.exports = {
  themes: [
    "desir",
    "seduction",
    "passion",
    "nuit",
    "intimite",
    "amour",
    "sensualite",
    "douceur",
    "toucher",
    "flamme",
    "confession",
    "tension",
    "abandon",
    "velours"
  ],
  openers: [
    "Ce Soir La Lune Eclaire Ton Visage Si Beau",
    "Tes Yeux Brillent Comme Des Etoiles Dans La Nuit Chaude",
    "Je Sens Ton Souffle Chaud Contre Ma Peau Ce Soir",
    "La Musique Joue Et Nos Corps Se Rapprochent Lentement",
    "Tu As Allume Une Flamme Que Rien Ne Peut Eteindre",
    "Sous Les Lumieres Tamisees Je Ne Vois Que Toi Seule",
    "Ton Parfum Me Suit Partout Comme Une Douce Obsession",
    "La Nuit Nous Appartient Et Le Monde S'efface Autour",
    "Tes Levres Murmurent Des Mots Que Mon Coeur Connait Deja",
    "Je T'attendais Sans Le Savoir Depuis Toujours Mon Ange",
    "Chaque Nuit Sans Toi Est Un Desir Qui Me Consume",
    "Tu Danses Et Le Monde S'arrete Pour Te Regarder Bouger",
    "Laisse-moi Te Montrer Ce Que Les Mots Ne Disent Pas",
    "Nos Regards Se Croisent Et Tout Le Reste Disparait Soudain",
    "Ce Soir Je Veux Etre Le Seul Dans Ton Univers",
    "Ton Rire Est La Plus Belle Melodie De Ma Vie",
    "Les Draps De Soie Gardent Encore Ton Parfum Envoutant",
    "Quand Tu Me Touches Le Temps S'arrete Un Instant Divin",
    "Je Suis Perdu Dans La Profondeur De Tes Yeux Sombres",
    "La Ville Dort Mais Nos Coeurs Battent Plus Fort Ce Soir",
    "Tu Es La Chanson Que Je Chante En Silence Chaque Nuit",
    "Sous La Pluie Nos Silhouettes Se Confondent En Une Seule",
    "Je Grave Ton Nom Sur Chaque Battement De Mon Coeur",
    "Les Etoiles Sont Jalouses De La Lumiere De Tes Yeux",
    "Ce Soir On Ecrit Une Histoire Que Personne Ne Lira",
    "Tes Mains Sur Ma Peau Font Naitre Un Feu Nouveau",
    "La Nuit S'ouvre Comme Une Fleur Quand Tu Es La",
    "Je Brule D'un Desir Que Seul Ton Regard Peut Apaiser",
    "Nos Ombres Dansent Sur Le Mur Dans La Lueur Des Bougies",
    "Tu Es Le Secret Que Je Garde Au Fond De Moi",
    "Le Silence Entre Nous Dit Plus Que Mille Chansons D'amour",
    "Ce Soir Je Traverse La Ville Pour Te Retrouver Enfin",
    "Ton Corps Est Un Poeme Que Je Lis A Voix Basse",
    "La Chaleur De Ta Peau Fait Fondre Toutes Mes Barrieres",
    "Je Suis L'ocean Et Tu Es La Maree Qui M'attire",
    "Chaque Seconde Loin De Toi Est Une Eternite Qui Brule",
    "Tu M'as Ensorcele Avec Un Seul Regard Dans La Penombre",
    "Les Neons De La Ville Eclairent Notre Danse Secrete",
    "Mon Coeur Te Reconnait Avant Meme Que Mes Yeux Te Voient",
    "Je Veux Etre La Voix Qui Te Murmure Chaque Nuit",
    "Nos Levres Se Trouvent Dans L'obscurite Comme Par Magie",
    "Le Monde Est Bruyant Mais Ton Silence Me Suffit Ce Soir",
    "Tu Es L'encre Et Je Suis La Page De Cette Histoire",
    "La Nuit Tombe Et Mon Desir Pour Toi S'eveille Encore",
    "Tes Doigts Tracent Des Chemins De Feu Sur Mon Ame",
    "Je Suis A Toi Comme La Nuit Appartient Aux Etoiles",
    "Ton Ombre Me Manque Quand Le Soleil Se Leve Seul",
    "La Douceur De Ta Voix Est Mon Refuge Dans La Nuit",
    "On Se Retrouve La Ou Les Mots Ne Servent Plus A Rien",
    "Ce Soir Le Monde N'existe Plus Il N'y A Que Nous Deux"
  ],
  verses: [
    "tes yeux sont un piege ou je veux me perdre sans fin",
    "ta peau a le gout d'un reve dont on ne veut pas se reveiller",
    "le velours de ta voix me fait trembler dans la penombre douce",
    "je compte les heures qui me separent de tes bras accueillants",
    "ton parfum est grave dans ma memoire comme une brulure ancienne",
    "la nuit tombe et mon desir monte comme la maree haute",
    "tes levres dessinent des promesses que je veux voir tenues toujours",
    "le silence entre nous vibre comme une corde de guitare tendue",
    "je me noie dans la douceur de ton regard profond ce soir",
    "ton rire eclate comme du champagne dans la nuit qui brille",
    "les draps froissees gardent la carte de notre nuit ensemble ici",
    "je t'ecris des chansons que seul ton corps peut comprendre vraiment",
    "la flamme entre nous ne faiblit jamais meme quand tout s'eteint",
    "tes doigts sur ma peau ecrivent un poeme de feu doux",
    "la chaleur de tes bras est le seul foyer que je veux",
    "tu es la melodie qui joue en boucle dans ma tete",
    "je ferme les yeux et ton visage apparait comme une vision",
    "nos corps se parlent dans un langage que personne d'autre ne connait",
    "le battement de ton coeur est le tempo de ma vie entiere",
    "la lueur des bougies danse sur ta peau comme de l'or",
    "je suis accro a ton sourire comme a une douce drogue",
    "tu bouges comme une vague et je suis ton rivage fidele",
    "la nuit nous enveloppe comme un drap de soie noire douce",
    "tes mains sont la seule adresse ou mon coeur veut habiter",
    "je brule lentement dans le feu de ton regard intense ce soir",
    "ta voix coule sur moi comme du miel dans l'obscurite chaude",
    "le monde peut attendre quand tu es dans mes bras ici",
    "je trace des constellations sur ta peau avec mes levres brulantes",
    "ton absence est un vide que rien d'autre ne peut combler jamais",
    "la musique monte et nos ames se melent dans la nuit longue",
    "je te cherche dans chaque visage dans chaque rue de la ville",
    "tes yeux sont la promesse d'un monde que je veux explorer",
    "le rouge de tes levres est la couleur de mon desir fou",
    "on danse joue contre joue et le monde tourne autour de nous",
    "ta peau brule sous mes doigts comme un secret bien garde",
    "je suis l'ombre qui te suit quand la lune se leve seule",
    "ton souffle sur ma nuque fait naitre des frissons dans tout mon corps",
    "la distance entre nous n'est qu'un pretexte pour se retrouver mieux",
    "je t'attends comme on attend l'aube apres une nuit trop longue",
    "tes courbes sont les collines d'un paysage que je veux parcourir",
    "le gout de tes baisers me reste sur les levres chaque matin",
    "nos ombres entrelacees sur le mur racontent notre histoire la nuit",
    "tu es la seule flamme dans la nuit froide de ma vie",
    "la soie de tes cheveux glisse entre mes doigts comme de l'eau",
    "je voudrais arreter le temps pour rester dans cet instant sacre",
    "ton corps est un temple ou je viens prier chaque nuit sombre",
    "la lune est temoin de tout ce qu'on se dit sans mots",
    "je porte ton amour comme un bijou secret contre mon coeur",
    "tes yeux me disent des choses que ta bouche ne dira jamais",
    "la chaleur de cette nuit colle a ma peau comme ton souvenir",
    "je suis ivre de toi et je ne veux pas dessaouler jamais",
    "tes murmures sont des sortileges qui m'enchainent a ton univers doux",
    "le battement sourd de la basse fait vibrer mon desir pour toi",
    "nos doigts entrelaces sont la preuve que nous sommes faits l'un pour l'autre",
    "ta silhouette dans la lumiere est un tableau que je ne peux oublier",
    "je me perds dans les ruelles de ton coeur comme un voyageur amoureux",
    "le satin de ta voix adoucit toutes les blessures de mon ame",
    "tes yeux sont deux lacs sombres ou je plonge sans crainte aucune",
    "la nuit nous couvre d'un voile et personne ne nous trouve ici",
    "je danse avec ton ombre quand tu n'es pas pres de moi",
    "ton nom est un murmure que je repete comme une priere nocturne",
    "la fievre de ton regard fait monter la temperature de la piece",
    "nos corps sont deux aimants que rien ne peut separer longtemps",
    "le parfum de ta nuque est mon paradis sur cette terre triste",
    "je voudrais fondre dans la douceur de tes bras chaque nuit ici",
    "tes pas sur le parquet resonnent comme un rythme dans mon coeur",
    "la penombre est notre alliee quand les mots deviennent insuffisants",
    "je suis le gardien de tes secrets et le temoin de ta beaute",
    "ton rire illumine la piece comme un feu de joie nocturne",
    "les heures passent comme des minutes quand je suis avec toi enfin",
    "ta danse est une conversation que mon corps comprend parfaitement bien",
    "le grain de ta peau est la plus belle texture du monde",
    "je te retrouve chaque nuit dans les reves que je fais seul",
    "nos regards sont des ponts qui traversent le bruit de la foule",
    "le bleu profond de la nuit a la couleur de ton regard",
    "tes mots sont des caresses qui touchent les endroits invisibles de moi",
    "la fumee de la cigarette dessine ta silhouette dans l'air du soir",
    "je suis ancre a ton sourire comme un navire dans le port",
    "ta presence efface tout le chaos du monde qui tourne autour",
    "le frisson de ta peau contre la mienne est electrique et doux",
    "je te cherche dans la foule mais tu es deja dans mon coeur",
    "les neons clignotent et ton visage apparait dans chaque lumiere vive",
    "ton absence creuse un vide dans la nuit que rien ne remplit",
    "la sueur sur ta peau brille comme des perles sous la lune",
    "je suis tombe amoureux de ta facon de murmurer mon prenom",
    "nos coeurs battent ensemble comme une seule percussion dans la nuit",
    "la douceur de tes gestes desarme toutes mes defenses fragiles",
    "tu es le feu que je cherchais dans le froid de mes nuits",
    "je suis jealoux du vent qui touche ta peau avant moi",
    "ton corps ondule comme une flamme que je ne peux pas saisir",
    "les murs de cette chambre connaissent nos secrets les plus profonds",
    "la pluie tombe dehors mais ici il fait chaud dans tes bras",
    "je t'ai trouvee dans la foule comme une etoile dans la nuit",
    "tes yeux fermes sont la preuve que tu me fais confiance entierement",
    "le rythme de ton coeur est la basse de ma chanson preferee",
    "nos levres se retrouvent comme deux rivieres qui se jettent dans la mer",
    "la nuit avance et je ne veux pas que le matin vienne",
    "ton nom est ecrit a l'encre invisible sur toute ma peau brulante",
    "je suis prisonnier volontaire de la cage doree de tes bras",
    "le miroir reflete nos deux silhouettes comme un tableau de maitre ancien",
    "ta voix dans le noir est la plus belle musique du monde",
    "je grave chaque instant avec toi dans le marbre de ma memoire",
    "les battements sourds de mon coeur trahissent tout ce que je ressens",
    "tu es la reponse a une question que je n'avais jamais posee",
    "la caresse de tes mots me fait fermer les yeux de plaisir",
    "nos deux souffles se melent dans la nuit comme un seul murmure",
    "je m'endors avec ton image et je me reveille avec ton parfum",
    "le velours de la nuit est doux comme ta peau sous mes doigts",
    "tu es mon addiction la plus douce et la plus dangereuse aussi",
    "la courbe de ton cou est un paysage que je ne me lasse pas d'admirer",
    "je suis a genoux devant la beaute simple de ton sourire",
    "nos corps se connaissent par coeur comme deux danseurs parfaitement accordes",
    "le gout de ton baiser est un souvenir que ma bouche garde",
    "la lumiere sur ta peau cree des ombres que je veux explorer",
    "je respire ton nom comme on respire l'air apres une plongee profonde",
    "tes mains sur mon visage effacent les traces du monde exterieur",
    "la passion entre nous brule comme un incendie que rien n'arrete",
    "je suis l'echo de ta voix dans la nuit silencieuse et chaude",
    "ton corps contre le mien est la seule frontiere que j'accepte",
    "le desir monte en moi comme une maree que rien ne retient",
    "tes yeux me captivent comme la flamme captive le papillon nocturne",
    "la douceur de cet instant suspend le vol impitoyable du temps",
    "nos peaux se frolent et le monde entier se met a vibrer",
    "je suis sous le charme de chaque mot que tu prononces doucement",
    "la nuit est jeune et nous avons encore tant a nous dire",
    "ton ombre est la compagnie que je prefere dans la solitude douce",
    "le feu dans tes yeux allume une constellation dans mon ame noire",
    "je voudrais graver cette nuit dans l'eternite de notre histoire commune",
    "ta peau est la page sur laquelle j'ecris mon plus beau poeme",
    "nos regards se croisent dans la foule et tout le bruit s'eteint",
    "le rythme de ta respiration est la berceuse de mes nuits agitees",
    "tu es la seule personne qui fait trembler le sol sous mes pieds",
    "la lune eclaire ton visage et je tombe amoureux encore une fois",
    "je suis le silence et tu es la musique qui me complete",
    "tes bras sont le refuge ou je me cache du monde entier",
    "la chaleur entre nous pourrait faire fondre les etoiles dans le ciel",
    "je me consume pour toi comme une bougie dans la nuit longue",
    "ton sourire dans le noir est un phare qui me guide toujours",
    "nos doigts se cherchent dans l'obscurite comme deux aveugles qui se trouvent",
    "le souffle de ta voix fait vibrer chaque fibre de mon etre",
    "je suis tombe si loin dans tes yeux que je ne remonterai jamais",
    "la passion que tu allumes ne connait ni repos ni saison",
    "tes murmures a mon oreille sont des incendies que je ne veux pas eteindre",
    "nos corps enroules sont les deux moities d'un meme cercle parfait",
    "le desir est un ocean et tu es mon seul rivage",
    "ta presence emplit la piece comme un parfum qu'on ne peut ignorer",
    "je suis hypnotise par la danse lente de tes hanches gracieuses",
    "les secondes s'etirent quand ta main effleure la mienne timidement",
    "ton regard traverse mon armure et atteint mon coeur directement",
    "la nuit sans toi est un ciel sans etoiles sans lumiere aucune",
    "je porte les traces de tes baisers comme des tatouages invisibles sacres",
    "le tempo de cette nuit est dicte par nos deux coeurs reunis",
    "tu es la fievre douce dont je ne veux jamais guerir",
    "nos ames se touchent dans un espace ou les mots n'existent plus",
    "la douceur de ta peau est un voyage dont je ne reviens pas",
    "je suis enchaine a ton amour et je jette la clef au loin",
    "tes yeux mi-clos sont la plus belle invitation que je connaisse",
    "le son de ton prenom sur mes levres est une melodie parfaite",
    "nos deux solitudes se sont trouvees dans le miroir de la nuit",
    "la braise de ton regard rougeoie dans l'obscurite de ma chambre",
    "je veux etre le dernier nom que tes levres prononcent chaque soir",
    "ton corps est la geographie d'un pays que je veux connaitre par coeur",
    "les heures de la nuit sont des diamants que je garde precieusement",
    "ta respiration est le rythme sur lequel je construis mes reves fous",
    "je suis l'ombre de ton desir et la lumiere de ton matin",
    "nos silences sont plus eloquents que toutes les declarations du monde entier",
    "la tension entre nous est un fil tendu pret a vibrer fort",
    "tes doigts parcourent ma peau comme un musicien joue son instrument prefere",
    "le parfum de cette nuit restera grave dans ma memoire eternellement",
    "je suis perdu dans le labyrinthe de tes bras sans vouloir sortir",
    "ton souffle est la brise tiede qui caresse mon coeur solitaire",
    "la profondeur de tes yeux contient un univers que je veux habiter",
    "nos levres se separent et le manque commence deja immediatement",
    "je suis fou de chaque syllabe que ta bouche laisse echapper",
    "le clair de lune sur ta peau cree un tableau impressionniste",
    "tu es la raison pour laquelle je crois encore a la magie",
    "nos deux corps racontent une histoire que les mots ne savent dire",
    "la douceur de ta main dans la mienne est une guerison profonde",
    "je voudrais boire chaque seconde passee avec toi jusqu'a la derniere goutte",
    "ton absence est une plaie que seul ton retour peut guerir vite",
    "le frisson qui me traverse quand tu me regardes est une promesse",
    "nos coeurs se sont choisis avant que nos yeux ne se rencontrent",
    "la nuit porte nos secrets sur ses ailes de velours noir doux",
    "je suis le gardien de la flamme que tu as allumee en moi",
    "tes baisers sont des mots dans une langue que seul mon corps parle",
    "le rythme de nos deux vies s'accorde comme une harmonie parfaite",
    "ton visage est la premiere chose que je veux voir chaque matin",
    "je m'abandonne a la douceur de cet instant sans regarder l'heure",
    "nos ames entrelacees defient le temps et l'espace qui nous separent",
    "le satin de tes draps garde l'empreinte de nos deux corps meles",
    "je suis le gardien de tes nuits et le voleur de tes soupirs",
    "la danse de tes hanches est un langage que mon corps dechiffre seul",
    "tes cheveux sur l'oreiller dessinent la carte de nos nuits partagees",
    "je voudrais etre le miroir qui te regarde quand tu ne le sais pas",
    "nos souffles se melent dans l'air chaud de cette chambre close la nuit",
    "la douceur de ta nuque sous mes levres est un continent a explorer",
    "je suis le prisonnier heureux de la cage doree de ton amour",
    "tes cils fermes projettent des ombres sur tes joues quand tu dors paisible",
    "la chaleur monte entre nous comme un orage d'ete qui ne creve pas",
    "je suis accro au son de ta voix quand tu murmures mon nom",
    "nos silhouettes dans le miroir forment une oeuvre d'art que personne ne signera",
    "le gout de sel sur ta peau me rappelle que tu es reelle ici",
    "je voudrais figer cet instant dans l'ambre de mon souvenir pour toujours",
    "ta silhouette se decoupe dans la lumiere et je retiens mon souffle emerveille",
    "le froissement des draps est la bande son de nos nuits blanches ensemble",
    "je compte les battements de ton coeur et chacun me dit que tu m'aimes",
    "la courbe de ton dos est un horizon que mes mains parcourent sans fin",
    "tes mots coulent sur ma peau comme une pluie chaude de promesses douces",
    "le noir de la chambre est un ecrin pour le diamant de ta presence",
    "je suis l'instrument et tu es la musicienne qui tire les bonnes notes",
    "nos levres se quittent et le vide qui suit est un gouffre profond",
    "la douceur de tes paupieres fermees est un paysage de serenite pure",
    "je suis le rivage et tu es la vague qui revient toujours vers moi",
    "ton rire dans le noir est un feu d'artifice que seul je peux voir",
    "le contact de ta peau sur la mienne declenche un incendie silencieux",
    "je te porte dans mes pensees comme un bijou cache sous ma chemise",
    "la temperature monte quand nos regards se croisent a travers la piece pleine",
    "tes doigts dans mes cheveux tissent des reves que je ne veux pas couper",
    "je suis l'ecluse et tu es le fleuve qui deborde quand tu m'embrasses",
    "nos deux respirations synchronisees sont la plus belle melodie que je connaisse",
    "le parfum de ta peau est une drogue dont je suis dependant",
    "la lumiere tamisee fait de ta peau un paysage de velours dore",
    "je voudrais vivre dans le creux de ta main pour l'eternite entiere",
    "nos corps se devinent dans le noir comme deux aveugles qui se reconnaissent",
    "le son de ta voix basse est un tremblement de terre dans ma poitrine",
    "tes yeux sont des phares et je suis le navire perdu dans ta nuit",
    "la courbe de tes hanches est une route que je veux suivre sans fin",
    "je suis le papier et tu es l'encre qui donne un sens a ma vie",
    "nos doigts entremeles forment un noeud que rien au monde ne peut defaire",
    "le battement sourd de la musique accompagne le rythme de nos deux corps",
    "ta bouche est une promesse que chaque baiser tient et renouvelle sans cesse",
    "je suis l'echo fidele de chaque soupir que tu laisses echapper la nuit",
    "la douceur de cet instant est un diamant que je garde en secret sacre",
    "nos ombres se superposent sur le mur et ne forment qu'une seule forme",
    "le desir qui monte en moi est un volcan que tu seule peux calmer",
    "tes mains sont des cartes qui me guident vers un tresor cache en toi",
    "la nuit avance et je refuse de laisser le matin nous separer encore",
    "je suis le silence entre deux notes et tu es la melodie qui vibre",
    "nos coeurs battent a contretemps et c'est ca qui rend notre rythme unique",
    "le gout de tes levres est un voyage dont je ne reviens jamais intact",
    "tes yeux mi-clos sont des portes vers un monde ou je veux entrer",
    "la pression de ta main sur la mienne dit tout ce qu'il faut savoir",
    "je suis le gardien de chaque moment passe dans la chaleur de tes bras",
    "nos peaux se reconnaissent dans le noir comme deux vieux amis retrouves",
    "le murmure de ta respiration est mon oxygene dans cette nuit profonde",
    "tes baisers laissent des traces brulantes que le matin ne peut pas effacer",
    "la douceur de ton souffle sur ma joue est le paradis sur terre",
    "je suis enchaine a la beaute de cet instant comme a un sortilege",
    "nos deux vies se tissent dans le noir fil apres fil pour toujours",
    "le velours de ta voix dans le noir me fait chavirer de desir",
    "ton regard me transperce comme une fleche de velours dans la nuit chaude",
    "la danse de tes cils projette des ombres sur ma peau frissonnante",
    "je dessine ton prenom sur le miroir embue de cette salle de bain",
    "le groove de cette nuit coule dans mes veines comme du miel sombre",
    "ta silhouette se balance dans la lumiere rouge du club ferme ce soir",
    "je suis le gardien de chaque frisson que tu me donnes sans mots",
    "nos respirations s'accordent dans le silence epais de cette chambre close",
    "le tissu de ta robe glisse comme une confession entre mes doigts nerveux",
    "je suis hypnotise par la facon dont la lumiere frappe ta clavicule",
    "ton ombre sur le drap est la plus belle carte du monde connu",
    "la basse resonne dans ma poitrine au meme rythme que ton coeur",
    "je voudrais traduire en notes chaque courbe de ton corps endormi",
    "nos peaux se retrouvent dans le noir comme deux vieilles melodies familieres",
    "le reflet de la bougie dans tes yeux cree un univers parallele",
    "je suis accro au timbre grave de ta voix quand tu chuchotes",
    "ta main sur ma nuque declenche un orage electrique sous ma peau",
    "la sueur perle sur ta tempe comme une rosee de passion nocturne",
    "je compte les grains de beaute sur ton epaule comme des etoiles secretes",
    "le velours de minuit n'est rien compare a la douceur de ta peau",
    "nos jambes entrelacees sous le drap forment un noeud que l'aube defait pas",
    "ta respiration lente est un metronome pour les battements de mon coeur agite",
    "le parfum de vanille dans tes cheveux me ramene a des nuits anciennes",
    "je voudrais enregistrer le son de ton rire et le jouer en boucle",
    "nos ombres projetees par les phares qui passent dansent sur le plafond blanc",
    "la chaleur de ta paume contre ma joue efface le bruit du monde",
    "ton sourire en coin est un piege dans lequel je tombe chaque fois",
    "la lune filtre a travers les stores et decoupe ta peau en lumiere",
    "je voudrais fondre dans le creux de ton epaule et y rester eternellement",
    "nos levres se frolent et l'univers retient son souffle un instant sacre",
    "le gout sale de ta peau apres la danse est une addiction nouvelle",
    "je suis l'ombre portee de ton corps quand la lumiere est douce ici",
    "la tension dans l'air entre nous pourrait faire eclater les ampoules electriques",
    "je suis jaloux de l'oreiller qui recueille tes reves chaque nuit sans moi",
    "nos doigts entremeles sont la seule priere que je connais par coeur ce soir",
    "le mouvement de tes hanches est une conversation que mon corps comprend bien",
    "ta voix a travers le telephone est un velours qui me couvre la nuit",
    "je voudrais cartographier chaque centimetre de ta peau avec mes levres brulantes",
    "la fumee de l'encens dessine des spirales autour de nos corps enlaces ici",
    "je suis le gardien jaloux de chaque soupir que tu laisses echapper ce soir",
    "nos deux souffles dans le noir creent un brouillard ou je veux vivre seul",
    "le contact de ta cheville contre la mienne sous la table est electrique",
    "ta facon de te mordre la levre inferieure me fait perdre la raison",
    "je suis le fleuve et tu es le lit ou je coule sans arret",
    "la courbe de ta hanche est un paysage que je photographie mentalement chaque nuit",
    "nos corps synchronises sont une machine parfaite de desir et de tendresse pure",
    "le bruissement de tes draps quand tu te retournes est ma symphonie nocturne",
    "je porte ton odeur sur ma peau comme un tatouage ephemere et doux",
    "ta main dans mes cheveux est la seule therapie dont j'ai besoin ce soir",
    "la nuit nous appartient et le reste du monde peut bien attendre demain matin",
    "je suis un ocean de desir et tu es la maree qui me commande",
    "ton rire grave dans le noir est un feu de joie pour mon ame",
    "nos corps se devinent a travers les vetements comme a travers un voile fin",
    "le son de la pluie dehors est la bande son de notre intimite secrete",
    "je suis enchaine au rythme de tes hanches comme a une melodie fatale",
    "ta peau brune sous le clair de lune est un poeme que je recite seul",
    "la douceur de tes bras autour de moi est la seule cage que j'accepte bien",
    "je voudrais suspendre le temps a la seconde ou tes levres touchent les miennes",
    "nos regards se croisent par dessus la foule et tout le reste s'eteint lentement",
    "le parfum de ton cou quand je m'approche est un vertige delicieux nouveau",
    "je suis le papillon et ton regard est la flamme irresistible nocturne",
    "ta facon de prononcer mon nom transforme un mot en caresse pure et douce",
    "la texture de ta voix est du satin sur une plaie ouverte de mon ame",
    "je voudrais boire tes mots comme un vin que je savoure lentement ici",
    "nos silences charges de desir sont plus bruyants que n'importe quelle musique forte",
    "le battement de ton pouls sous mes doigts est un tambour sacre nocturne",
    "ta silhouette dans l'embrasure de la porte coupe mon souffle chaque fois encore",
    "je suis le gardien de tes insomnies et le voleur de tes matins doux",
    "nos corps emboites sont deux pieces d'un puzzle que le destin a dessine ensemble",
    "le frisson qui court sur ta peau quand je te touche est ma recompense",
    "ta nuque penchee sous la lumiere est un paysage de soie et d'ambre dore",
    "je voudrais etre le premier visage que tu vois quand tu ouvres les yeux",
    "nos mains se cherchent sous la table comme des voyageurs dans la nuit froide",
    "le murmure de ton prenom sur mes levres est une incantation puissante et douce",
    "ta peau sous mes paumes est une terre promise que je ne quitte plus jamais",
    "je suis le reflet dans tes yeux quand la lumiere est parfaite ce soir",
    "la courbe de ton sourire est l'arc de triomphe de ma journee entiere longue",
    "nos nuits ensemble sont des joyaux que je range dans un coffre secret precieux",
    "le gout de ton baiser du matin est meilleur que tout le cafe du monde",
    "ta main sur mon torse au milieu de la nuit me dit tout va bien",
    "je suis accro a la facon dont tu fermes les yeux quand je chante pour toi",
    "la chaleur de ta joue contre mon epaule est un medicament pour l'ame blessée",
    "nos pas resonnent ensemble sur le trottoir mouille comme un rythme parfait bien accorde",
    "le son de ta cle dans la serrure est la plus belle melodie du soir",
    "ta facon de rire quand tu es nerveuse me fait fondre a chaque fois encore",
    "je voudrais capturer l'odeur de ta peau apres la pluie dans un flacon secret",
    "nos corps enlaces forment une ile au milieu de l'ocean de la nuit noire",
    "le contact de tes pieds froids contre les miens sous les draps me reveille",
    "ta voix endormie qui murmure mon nom est la preuve que tu reves de moi",
    "je suis le gardien silencieux de chaque seconde passee dans ta lumiere chaude",
    "la douceur de tes pouces sur mes tempes efface le monde exterieur bruyant",
    "nos deux ombres projetees par le lampadaire ne forment qu'une seule silhouette enlacee",
    "le battement de tes cils sur ma joue est un papillon de velours doux",
    "ta peau est une partition et mes doigts jouent la plus belle sonate nocturne",
    "je suis perdu dans le dedale de tes bras et je n'appelle pas au secours",
    "la brulure douce de ton regard me consume comme un feu lent et bon",
    "nos bouches se retrouvent comme deux affluents qui se jettent dans le meme fleuve",
    "le tissu de ta chemise garde la chaleur de mon etreinte du matin rose",
    "ta facon de danser seule devant le miroir est un spectacle prive divin",
    "je voudrais etre le dernier son que tu entends avant de t'endormir paisible",
    "nos corps se reconnaissent meme dans l'obscurite la plus totale et profonde ici",
    "le souffle tiede de ta respiration dans mon cou est un baume sacre doux",
    "ta main qui remonte lentement le long de mon bras declenche un tremblement profond",
    "la profondeur de ton regard contient des promesses que je veux tenir toujours fidele",
    "nos langues se trouvent et le monde perd toute sa gravite un instant magique",
    "le rythme de nos deux corps est une musique que personne d'autre n'entend ce soir",
    "ta peau mouillee par la pluie brille comme une promesse sous les neons rouges",
    "je suis le verse et tu es le refrain de cette chanson sans fin douce",
    "la facon dont tu te blottis contre moi me fait croire en l'eternite pure",
    "nos regards se verrouillent et un courant passe entre nous comme un eclair doux",
    "le gout de ta peau est le souvenir que je garde quand tu es loin de moi",
    "ta respiration profonde contre mon oreille est le son le plus intime que je connais",
    "je voudrais photographier cet instant ou tes yeux me disent tout sans mots inutiles",
    "nos mains entrelacees sont une promesse plus forte que tous les serments du monde",
    "le poids de ta tete sur mon epaule est le fardeau le plus doux qui soit",
    "ta facon de me regarder a travers tes cils est une arme fatale redoutable",
    "la douceur de ta peau endormie est un continent que je parcours en reve chaque nuit",
    "nos souffles meles dans le noir tissent un voile autour de notre monde secret",
    "le contact de tes levres sur mon front est un sacrement nocturne que j'adore",
    "ta peau porte encore les traces de mes doigts comme une carte invisible gravee",
    "la lumiere dans tes yeux quand tu me vois est mon soleil quotidien fidele",
    "nos corps imbriques sont un chef-d'oeuvre que meme le temps ne peut detruire jamais",
    "le murmure de ton souffle endormi est la plus belle berceuse du monde entier",
    "ta main qui se pose sur la mienne sous la table est un serment sacre",
    "je voudrais que chaque nuit soit un chapitre de notre histoire sans fin ecrite",
    "nos levres se separent et le fil invisible qui les relie ne se rompt jamais",
    "le parfum que tu laisses sur mon oreiller est un fantome bienveillant la nuit",
    "ta silhouette qui s'eloigne dans la rue est un poignard dans mon coeur blesse",
    "la pression de tes doigts sur mon poignet accelere tout mon sang brulant vif",
    "nos deux corps sous le drap sont un paysage de collines et de vallees douces",
    "le son de ta voix dans l'escalier me fait battre le coeur plus vite encore",
    "ta facon de te pencher vers moi quand tu parles me fait tout oublier",
    "je suis enchaine a ton souvenir et les chaines sont faites de soie pure douce",
    "la trace de ton rouge a levres sur ma peau est un trophee precieux sacre",
    "nos regards s'accrochent dans le miroir et le reflet dit la verite nue",
    "le grain de ta peau sous la lumiere tamisee est un univers a explorer seul",
    "ta bouche entreouverte dans le sommeil est un appel auquel je resiste a peine",
    "nos corps fatigues par la danse s'ecroulent ensemble comme deux tours de sable fin",
    "le tremblement de ta main quand tu me touches pour la premiere fois ce soir",
    "ta peau qui rosit sous mes baisers est la plus belle reponse du monde entier",
    "je suis le voyageur et ton corps est le pays que je ne quitte plus jamais",
    "la meche de cheveux collee a ta joue humide est un trait de pinceau dore",
    "nos nuits sont des chapitres que je relis sans me lasser jamais de toi",
    "le frolement de ta hanche contre la mienne quand on marche cote a cote doucement",
    "ta voix rauque du matin est la plus belle melodie que je connaisse ici",
    "je suis le refuge ou tu viens quand le monde est trop bruyant dehors",
    "la lumiere du petit matin sur ton visage est un tableau de maitre sacre ici",
    "nos mains qui se trouvent dans le noir sont deux oiseaux qui se reconnaissent",
    "le battement sourd de la musique dehors rythme nos corps enlaces ici dedans toujours",
    "ta peau parfumee au jasmin est un jardin secret ou je me perds volontiers",
    "je suis le dernier mot de ta journee et le premier de ta nuit belle",
    "le creux de ton epaule est l'endroit le plus sur du monde pour moi",
    "nos silhouettes se decoupent dans la lumiere de l'aube comme un tableau vivant",
    "ta cheville fine que j'effleure du bout des doigts me fait perdre la raison",
    "le rythme lent de ta demarche est une musique que mes yeux dansent seuls",
    "nos deux corps dans le reflet de la fenetre forment un seul dessin parfait",
    "la facon dont tu detaches tes cheveux est un rideau qui se leve",
    "je voudrais etre la chanson que tu fredonnes sous la douche chaque matin",
    "tes levres sur ma tempe sont un bapteme que je recois chaque soir",
    "le craquement du lit quand tu te tournes vers moi est ma musique",
    "nos peaux ont la meme temperature comme si nous partagions le meme sang"
  ],
  bridges: [
    "et dans le silence de la nuit je t'entends encore murmurer",
    "on a traverse la tempete et l'amour nous a tenus ensemble",
    "si tu pars emporte mon coeur je n'en ai plus besoin sans toi",
    "les heures sans toi sont des siecles que je ne supporte plus",
    "entre tes bras j'ai trouve un monde que je ne connaissais pas",
    "le temps s'arrete quand nos regards se croisent dans la penombre",
    "je ne savais pas ce qu'etait le desir avant de te connaitre",
    "tu m'as montre que l'amour peut etre doux et brulant a la fois",
    "sans toi la nuit n'est qu'un vide sans etoiles ni chaleur aucune",
    "je donnerais tout ce que j'ai pour un seul de tes regards",
    "nos deux vies se sont croisees au moment parfait du destin",
    "le monde peut bruler dehors ici il n'y a que ta peau",
    "chaque nuit sans toi me rappelle combien tu me manques fort",
    "je suis tombe et je ne veux pas me relever de cet amour",
    "ton amour m'a change comme la lune change la maree profonde",
    "les mots sont trop petits pour contenir tout ce que tu me fais",
    "avant toi je marchais dans le noir sans savoir qu'il manquait la lumiere",
    "je ne cherche plus rien car j'ai tout trouve dans tes yeux",
    "nos corps se souviennent de chaque nuit meme quand l'esprit oublie",
    "tu es la seule verite dans un monde fait de mensonges doux",
    "la distance ne fait que renforcer la flamme qui brule en moi",
    "je t'ai attendue toute ma vie sans savoir ton visage encore",
    "nos silences sont les conversations les plus profondes que j'ai eues",
    "le monde tourne mais toi et moi restons immobiles dans l'amour",
    "je ne peux pas respirer sans penser a toi c'est une certitude",
    "tu as touche une partie de moi que personne n'avait trouvee avant",
    "les nuits sont faites pour nous deux et le jour n'est qu'un intermede",
    "je brule d'un feu que seule ta presence peut apaiser doucement",
    "on a ecrit notre histoire a l'encre de la passion eternelle",
    "tu es gravee dans mon ame comme un tatouage indelebile et beau",
    "sans ta voix la musique n'est que du bruit dans le vide",
    "je suis perdu dans un reve dont tu es la seule sortie",
    "chaque battement de mon coeur prononce ton nom dans le silence noir",
    "tu m'as donne des ailes dans une nuit ou je rampais seul",
    "l'amour que je ressens depasse tout ce que les mots peuvent dire"
  ],
  choruses: [
    "je ne peux pas vivre sans toi dans cette nuit sans fin",
    "ton amour est la seule chose qui me garde en vie ce soir",
    "je suis a toi corps et ame dans cette nuit qui brule",
    "nos deux coeurs battent comme un seul dans l'obscurite douce",
    "je veux te sentir pres de moi jusqu'au lever du jour",
    "tu es tout ce que je desire dans cette vie passagere",
    "la nuit est a nous et personne ne peut nous la prendre",
    "je brule pour toi comme une flamme eternelle dans le noir",
    "ton corps ton ame ton souffle sont ma raison de vivre",
    "je me perds en toi et je ne veux plus me retrouver",
    "nos levres se retrouvent et le monde reprend enfin son sens",
    "je suis tombe amoureux et je ne veux jamais me relever",
    "ta peau contre la mienne est la seule verite que je connais",
    "je te veux ce soir demain et pour toutes les nuits restantes",
    "tu fais battre mon coeur comme personne ne l'a fait avant toi",
    "la passion entre nous est un feu que rien ne peut eteindre",
    "je suis enchante par toi chaque seconde de chaque nuit noire",
    "nos corps dansent ensemble sur un rythme que nous seuls entendons",
    "je donnerais le monde entier pour une seule nuit avec toi",
    "ton amour coule en moi comme un fleuve qui ne tarit jamais",
    "je te cherchais dans chaque visage et tu etais la depuis toujours",
    "la douceur de tes baisers est un paradis sur cette terre",
    "je suis accro a toi et je n'ai aucune envie de guerir",
    "nos ames se sont trouvees dans le noir de cette nuit belle",
    "tu es la musique et je suis la danse de ton coeur",
    "je veux graver cette nuit dans l'eternite de mon souvenir",
    "tes yeux sont mon ciel et ta peau est mon horizon",
    "je suis le feu et tu es la flamme qui me consume",
    "nos deux vies entrelacees forment un poeme que j'ecris chaque nuit",
    "je ne connais pas de plus beau voyage que celui vers toi",
    "ton amour me rend vivant comme rien d'autre au monde ne peut",
    "je suis perdu dans tes yeux et je n'ai pas besoin de carte",
    "la chaleur de ton amour fait fondre toutes les nuits froides",
    "je te porte dans mon coeur comme un secret precieux et doux",
    "nos corps se comprennent dans une langue au dela des mots simples",
    "tu es le desir que je n'oserai jamais avouer tout haut",
    "je suis fou de toi et cette folie est ma plus belle vertu",
    "la nuit brule quand tu es la et gele quand tu pars loin",
    "je te veux dans chaque chanson chaque reve chaque battement de coeur",
    "nos silhouettes enlacees sont la plus belle oeuvre d'art au monde",
    "je ne respire vraiment que lorsque tu es pres de moi ici",
    "ton amour est un ocean dans lequel je veux me noyer lentement",
    "je suis le gardien de nos nuits et le temoin de notre feu",
    "tu es inscrite dans mon ame a l'encre de la passion pure",
    "nos deux coeurs ne font qu'un quand la musique joue pour nous",
    "je te desire comme la terre desire la pluie apres l'ete sec",
    "ta presence est un cadeau que je deballe chaque nuit avec soin",
    "je suis ton ombre et tu es ma lumiere dans le noir",
    "nos levres ecrivent des histoires que les livres ne racontent jamais",
    "je brule d'amour pour toi et cette flamme ne s'eteindra jamais",
    "ton corps est mon royaume et je suis le roi de tes nuits sombres",
    "nos levres se parlent dans une langue que le monde ne comprend pas",
    "je suis perdu dans ton parfum et je ne cherche pas la sortie",
    "la nuit est notre temple et nos corps sont la priere sacree",
    "je te veux comme la terre veut la pluie apres un long ete sec",
    "nos ames se touchent et le ciel tout entier tremble pour nous deux",
    "je suis le feu qui brule dans tes veines chaque nuit sans fin",
    "ton amour est un rythme que mon coeur ne peut pas oublier jamais",
    "la chaleur entre nous fait fondre le temps et l'espace ce soir",
    "je te porte dans chaque chanson chaque souffle chaque reve que je fais seul",
    "nos corps sont deux flammes qui ne font qu'un seul feu dans le noir",
    "je suis a genoux devant la beaute de cet amour qui me consume entier",
    "ton regard est la seule lumiere dont j'ai besoin dans cette nuit sombre",
    "la passion qui nous lie est plus forte que tout ce qui nous separe",
    "je te desire comme on desire l'air quand on ne peut plus respirer seul",
    "nos deux coeurs ensemble sont une melodie que le monde devrait entendre enfin",
    "je suis ton esclave volontaire et la liberte est dans tes bras doux",
    "la douceur de ta peau est un poeme que je recite chaque nuit seul",
    "je brule je fonds je vis uniquement quand tu es pres de moi ici",
    "ton amour est le seul remede a la fievre qui me devore lentement",
    "nos nuits ensemble valent toutes les richesses de tous les royaumes du monde entier",
    "je suis le gardien de ton coeur et le temoin de ta beaute pure",
    "la nuit sans toi est un desert et ton retour est l'oasis benie",
    "je te cherchais dans chaque reve et tu etais la plus belle realite",
    "nos corps ensemble ecrivent un poeme que les mots seuls ne peuvent dire",
    "je suis l'echo de ton desir et tu es la voix de mon coeur",
    "la fievre de ton amour est la seule maladie dont je veux souffrir",
    "je te veux dans chaque nuit chaque aube chaque crepuscule de ma vie",
    "nos ames entrelacees sont la preuve que l'amour est eternel et sacre",
    "tu es le feu et la douceur reunis dans un seul regard brulant"
  ],
  vocabulary: {
    nouns: [
      "desir", "passion", "flamme", "caresse", "soie",
      "velours", "murmure", "frisson", "baiser", "etreinte",
      "nuit", "lune", "bougie", "ombre", "peau",
      "souffle", "levres", "parfum", "drap", "chaleur",
      "silence", "secret", "fievre", "tentation", "ivresse",
      "abandon", "braise", "eclat", "mystere", "obsession",
      "langueur", "soupir", "nuque", "eclipse", "maree",
      "penombre", "nectar", "mirage", "ondulation", "vertige",
      "promesse", "confidence", "empreinte", "fremissement", "rythme",
      "magnetisme", "envoutement", "sortilege", "ambroisie", "incandescence",
      "seduction", "volupte", "douceur", "tendresse", "intimite",
      "confession", "aveu", "supplique", "devotion", "adoration",
      "enivrement", "euphorie", "extase", "ravissement", "felicite",
      "sensualite", "charme", "attraction", "fascination", "tentation",
      "reflet", "miroir", "diamant", "perle", "satin",
      "dentelle", "soiree", "alcove", "boudoir", "cocon"
    ],
    verbs: [
      "desirer", "bruler", "caresser", "enlacer", "murmurer",
      "effleurer", "embrasser", "seduire", "envouter", "consumer",
      "trembler", "fondre", "fremir", "onduler", "captiver",
      "charmer", "magnetiser", "soupirer", "languir", "implorer",
      "devorer", "adorer", "etreindre", "enchainer", "hypnotiser",
      "fasciner", "embraser", "attirer", "convoiter", "idolatrer",
      "succomber", "defaillir", "supplier", "rougir", "haleter",
      "graver", "noyer", "consumer", "enivrer", "electriser",
      "ensorceler", "fusionner", "s'abandonner", "chavirer", "frissonner",
      "vibrer", "pulser", "irradier", "emouvoir", "bouleverser",
      "savourer", "deguster", "gouter", "palper", "frotter",
      "bercer", "dorloter", "choyer", "cajolier", "cherir",
      "enflammer", "attiser", "raviver", "allumer", "embraser",
      "transporter", "subjuguer", "envahir", "inonder", "submerger",
      "apprivoiser", "conquerer", "capturer", "emprisonner", "posseder",
      "susurrer", "chuchoter", "confesser", "avouer", "reveler"
    ],
    adjectives: [
      "brulant", "sensuel", "doux", "envoutant", "ardent",
      "charnel", "langoureux", "intense", "voluptueux", "magnetique",
      "irresistible", "envivrant", "captivant", "suave", "soyeux",
      "nocturne", "sombre", "profond", "secret", "intime",
      "electrique", "fievreux", "incandescent", "troublant", "sublime",
      "vibrant", "torride", "ensorcelant", "enveloppant", "fascinant",
      "tendre", "passionne", "delicat", "sauvage", "mysterieux",
      "interdit", "ephemere", "eternel", "fragile", "fatal",
      "exquis", "divin", "celeste", "sulfureux", "veloute",
      "obscur", "insatiable", "fougueux", "lumineux", "inoubliable",
      "soyeux", "satine", "nacre", "opalin", "crepusculaire",
      "suave", "onctueux", "moelleux", "veloute", "somptueux",
      "langoureux", "lascif", "indolent", "nonchalant", "alangui",
      "fievreux", "fielleux", "capiteux", "entetant", "grisant",
      "hypnotique", "hallucinant", "vertigineux", "abyssal", "insondable",
      "addictif", "obsessionnel", "imperieux", "irrepressible", "irresistible"
    ]
  }
};
