module.exports = {
  themes: [
    "rebellion",
    "liberte",
    "route",
    "passion",
    "nuit",
    "feu",
    "revolte",
    "rage",
    "chaos",
    "survie",
    "tonnerre",
    "sauvage",
    "orage",
    "destin"
  ],
  openers: [
    "Ce Soir On Met Le Feu A Tout Ce Qu'ils Ont Construit",
    "La Route Est Longue Mais Mon Moteur Ne S'arrete Pas",
    "Je Hurle Dans La Nuit Comme Un Loup Sans Meute",
    "Les Guitares Crient Ce Que Ma Voix Ne Peut Dire",
    "On A Brule Nos Chaines Et On Est Enfin Libres",
    "Le Tonnerre Gronde Et Nous On Danse Dessous",
    "Je Suis Ne Pour Courir Et Pas Pour Obeir",
    "Les Flammes Montent Plus Haut Que Les Murs Qu'ils Ont Batis",
    "Ce Soir La Scene Est A Nous Et Rien D'autre Ne Compte",
    "Je Roule A Fond Sur L'autoroute Du Destin",
    "Les Amplis Hurlent Et Mon Coeur Bat La Mesure",
    "On Ne Demande Pas La Permission De Vivre Libre",
    "Le Ciel Est En Feu Et Nous Sommes Les Flammes",
    "Je Suis Le Bruit Que Fait Le Silence Quand Il Explose",
    "Les Regles Sont Faites Pour Etre Brisees Ce Soir",
    "On Roulait Vers Le Soleil Sans Jamais Regarder En Arriere",
    "Le Monde Peut Bruler Mais On Reste Debout",
    "Je Chante Avec La Rage De Ceux Qui N'ont Plus Rien",
    "Les Etoiles Tombent Et On Les Attrape Au Vol",
    "Ce Soir On Ecrit Notre Legende Avec Du Feu",
    "La Revolte Commence La Ou Le Silence S'arrete",
    "Je Suis La Tempete Que Personne N'a Vu Venir",
    "Les Murs Tremblent Quand On Monte Le Son A Fond",
    "On A Le Sang Chaud Et Le Coeur Indomptable",
    "Le Vent Hurle Mon Nom Sur Les Routes Desertes",
    "Je Me Tiens Debout Face Au Monde Et Je Refuse De Plier",
    "Les Nuits Sont Faites Pour Bruler Et Non Pour Dormir",
    "On A Casse Toutes Les Regles Et On Recommence",
    "Le Feu Dans Mes Veines Me Pousse Toujours Plus Loin",
    "Je Suis Le Cri De Ceux Que Le Monde A Oublies",
    "Les Guitares Pleurent Ce Soir Pour Les Ames Perdues",
    "On Avance Dans La Tempete Les Yeux Grands Ouverts",
    "Le Chaos Est Notre Terrain De Jeu Ce Soir",
    "Je Brule Comme Une Etoile Qui Refuse De S'eteindre",
    "Les Routes Sont Nos Veines Et L'essence Est Notre Sang",
    "On N'a Peur De Rien Quand On N'a Plus Rien A Perdre",
    "Le Rock Coule Dans Nos Veines Depuis La Premiere Note",
    "Je Suis La Foudre Qui Frappe Sans Prevenir Personne",
    "Les Amplis Sont A Fond Et Le Monde Peut Trembler",
    "On Est Les Enfants Du Tonnerre Et De La Nuit",
    "Le Ciel Se Dechire Et Nous On Traverse L'orage",
    "Je Vis Chaque Nuit Comme Si C'etait La Derniere",
    "Les Flammes Dansent Et Nous On Danse Avec Elles",
    "On A Brise Les Miroirs Pour Ne Plus Voir Leurs Regles",
    "Le Moteur Rugit Et La Route S'ouvre Devant Nous",
    "Je Suis Le Feu Que La Pluie Ne Peut Pas Eteindre",
    "Les Murs De Cette Ville Ne Nous Retiendront Plus Jamais",
    "On Chevauche La Foudre Comme Des Cavaliers De L'orage",
    "Le Monde S'ecroule Et Nous On Monte Le Volume",
    "Je Suis Le Dernier Debout Quand Tout S'effondre Autour"
  ],
  verses: [
    "les guitares crient dans la nuit comme des loups affames",
    "on roule a fond sur des routes sans destination fixe",
    "le feu dans mon ventre ne s'eteindra jamais ce soir",
    "j'ai brise les chaines qui me retenaient au sol",
    "la nuit est notre royaume et le bruit notre couronne",
    "on a peint les murs de la ville avec nos cris",
    "le tonnerre gronde dans mes veines a chaque battement",
    "je me suis releve des cendres plus fort qu'avant",
    "les routes desertes sont les seules qui menent quelque part",
    "on a brule nos passeports pour vivre sans frontiere",
    "le vent hurle notre nom a travers les plaines vides",
    "j'ai la gorge en feu et les mains sur le micro",
    "les amplis crachent la rage qu'on ne peut plus contenir",
    "on a danse sur les ruines de ce qu'ils appellent normal",
    "le monde est un orage et je suis la foudre",
    "j'ai les yeux grand ouverts dans un monde qui dort",
    "les etoiles filantes sont les larmes du ciel rebelle",
    "on a jure de ne jamais baisser le volume",
    "le sang dans mes veines est fait de riffs electriques",
    "j'ai couru plus vite que mes demons cette nuit la",
    "les murs de la ville portent les cicatrices de notre passage",
    "on a tourne le dos au confort pour choisir la route",
    "le feu consume tout mais il eclaire le chemin aussi",
    "j'ai hurle dans le vide jusqu'a ce qu'il me reponde",
    "les nuits blanches sont les seules qui ont de la couleur",
    "on a chevauche la tempete sans selle ni frein",
    "le ciel se dechire et la pluie lave nos peches",
    "j'ai les mains en sang d'avoir gratte ces cordes toute la nuit",
    "les phares de la voiture percent le brouillard epais",
    "on a fait trembler les murs avec nos riffs sauvages",
    "le chaos est plus honnete que leur ordre parfait",
    "j'ai bu la nuit jusqu'a la derniere goutte d'obscurite",
    "les flammes dansent dans mes yeux quand la musique monte",
    "on a grave nos noms dans l'ecorce des routes infinies",
    "le moteur rugit comme un animal qui veut sa liberte",
    "j'ai mis le feu a tous les ponts derriere moi",
    "les cicatrices sur mes mains racontent des histoires de cordes",
    "on a defie le tonnerre et il a recule devant nous",
    "le bitume fond sous la chaleur de notre passage",
    "j'ai danse avec le diable sur un riff de guitare",
    "les murs de cette prison ne tiennent plus debout maintenant",
    "on a transforme le bruit en musique et la rage en art",
    "le vent emporte nos cris vers des oreilles affamees",
    "j'ai les poumons en feu d'avoir chante si fort",
    "les etincelles volent de mes doigts sur les cordes",
    "on a roule toute la nuit sans savoir ou on allait",
    "le silence est un ennemi que le rock ecrase toujours",
    "j'ai trouve ma liberte au bout d'une route sans fin",
    "les oiseaux de nuit chantent notre hymne rebelle ensemble",
    "on a crie si fort que les vitres ont explose",
    "le feu de notre rage eclaire les nuits les plus sombres",
    "j'ai perdu la voix mais pas la raison de hurler",
    "les phares eclairent la route comme des yeux de loup",
    "on a laisse nos empreintes sur chaque scene du pays",
    "le monde tournait sans nous alors on a cree le notre",
    "j'ai les os qui vibrent au rythme de la basse",
    "les orages sont nos applaudissements et la pluie nos larmes",
    "on a fait de chaque concert un champ de bataille sonore",
    "le rock coule dans mon sang comme un fleuve en crue",
    "j'ai traverse le desert des conventions sans eau ni regret",
    "les cordes de ma guitare sont les barreaux que j'ai tordus",
    "on a brise le moule qu'ils avaient fabrique pour nous",
    "le feu sacre brule dans le coeur de chaque rebelle",
    "j'ai le souffle court mais la flamme ne faiblit pas",
    "les neons de la salle clignotent comme des signaux de detresse",
    "on a ecrit nos lois sur des serviettes de bar tachees",
    "le volcan gronde sous nos pieds et nous on danse dessus",
    "j'ai les cheveux trempes de sueur et de rock sauvage",
    "les decibels montent et la raison descend dans les abimes",
    "on a fait saigner les amplis jusqu'a la derniere note",
    "le monde est un ring et la musique est notre combat",
    "j'ai le coeur qui cogne comme une grosse caisse dechainee",
    "les routes sombres sont les plus belles quand on y roule vite",
    "on a hurle notre verite dans des salles combles",
    "le sang et la sueur coulent sur le manche de ma guitare",
    "j'ai vu l'aube se lever depuis le toit du monde",
    "les murs de cette ville ne sont pas assez hauts pour nous",
    "on a fait de la nuit notre terrain de jeu eternel",
    "le feu purificateur brule tout sauf notre esprit libre",
    "j'ai les veines qui pulsent au rythme des riffs electriques",
    "les etoiles explosent quand nos guitares attaquent le ciel",
    "on a traverse la nuit comme des fantomes de feu",
    "le chaos est notre musique et le desordre notre harmonie",
    "j'ai la rage des volcans et la patience des montagnes",
    "les mots sortent de ma bouche comme des eclats de verre",
    "on a brule les bateaux pour ne jamais pouvoir revenir",
    "le vent de la liberte souffle sur nos visages marques",
    "j'ai gratte ces cordes jusqu'au sang et ca valait chaque goutte",
    "les nuits de concert sont les seuls moments ou je vis vraiment",
    "on a crie notre colere au visage du monde endormi",
    "le feu de la scene est le seul qui me rechauffe",
    "j'ai roule sans fin sur des routes qui ne menaient nulle part",
    "les amplis grondent comme le tonnerre avant la tempete finale",
    "on a peint le monde en noir et rouge de nos flammes",
    "le rock est la priere de ceux qui ne croient en rien",
    "j'ai les mains tremblantes de rage et de passion melee",
    "les murs de la scene sont les seuls murs que j'accepte",
    "on a fait vibrer la terre sous les coups de notre basse",
    "le ciel est notre toit et la route est notre maison",
    "j'ai le feu qui monte quand le premier accord resonne",
    "les yeux fermes je sens la musique envahir chaque cellule",
    "on a tourne le dos au monde et on a trouve le notre",
    "le sol tremble sous nos bottes quand on marche en cadence",
    "j'ai la gorge rauque d'avoir hurle contre le vent",
    "les flammes lechen le ciel comme des langues de rebelle",
    "on a forge notre legende dans le feu des concerts",
    "le bruit est notre oxygene et le silence notre ennemi",
    "j'ai survecu a la nuit maintenant je possede le jour",
    "les etincelles de la scene brulent plus fort que le soleil",
    "on a ecrase le silence sous le poids de nos accords",
    "le feu ne s'eteint pas quand on y jette sa rage",
    "j'ai la peau marquee par le vent des routes infinies",
    "les guitares pleurent des larmes de metal fondu ce soir",
    "on a fait de notre douleur la plus belle des melodies",
    "le tonnerre est notre batteur et la foudre notre guitariste",
    "j'ai les pieds sur terre mais la tete dans les flammes",
    "les murs de conformite s'ecroulent sous nos accords brutaux",
    "on a danse sur les cendres d'un monde qu'on a refuse",
    "le vent mugit dans les amplis comme une bete sauvage",
    "j'ai le sang chaud de ceux qui ne se rendent jamais",
    "les phares decoupent la nuit en tranches de lumiere crue",
    "on a joue si fort que les etoiles se sont rapprochees",
    "le rock est ma religion et la scene est mon temple",
    "j'ai la rage des tempetes et le calme de l'oeil du cyclone",
    "les vibrations de la basse me traversent comme un seisme",
    "on a fait de chaque route un pelerinage vers la liberte",
    "le feu devore tout ce qui est faux autour de nous",
    "j'ai hurle dans le micro jusqu'a ce que le monde m'entende",
    "les accords sauvages resonnent dans la nuit sans limites",
    "on a refuse de marcher dans le rang qu'ils ont trace",
    "le ciel nocturne est notre toile et les etoiles nos notes",
    "j'ai le coeur en flammes et l'ame en liberte totale",
    "les routes de nuit sont des rivieres de bitume fondu",
    "on a fait trembler les fondations de leur monde parfait",
    "le moteur gronde et les guitares repondent en echo",
    "j'ai la fureur des orages dans chaque note que je joue",
    "les murs vibrent sous la puissance de notre son sauvage",
    "on a chevauche le chaos comme on chevauche la foudre",
    "le feu de la rebellion brule dans nos yeux ce soir",
    "j'ai roule sur la crete des montagnes avec le vent",
    "les cordes vibrent comme des nerfs tendus a l'extreme",
    "on a fait de la nuit un brasier de sons electriques",
    "le monde peut sombrer nous on reste debout dans les flammes",
    "j'ai les mains calleuses de ceux qui jouent sans pitie",
    "les lumieres de la scene sont les seules que je suis",
    "on a traverse le feu et on en est sortis plus forts",
    "le volume monte et les murs de la raison s'effondrent",
    "j'ai la voix des volants qui rugissent dans la tempete",
    "les nuits sans fin sont notre terrain de chasse sonore",
    "on a plante notre drapeau sur les ruines du silence",
    "le rock ne meurt jamais il brule eternellement en nous",
    "j'ai la fievre des nuits ou tout est encore possible",
    "les accords montent en spirale comme un feu qui devore",
    "on a fait de chaque cri un hymne a la liberte",
    "le bruit est notre bouclier contre un monde trop silencieux",
    "j'ai la force des tempetes qui ne connaissent pas la peur",
    "les flammes de nos concerts eclairent les nuits du monde",
    "on a ecrit notre verite avec des riffs de guitare",
    "le ciel se fissure sous la puissance de notre musique",
    "j'ai danse avec les ombres jusqu'a ce que l'aube arrive",
    "les routes infinies sont les seules promesses que je crois",
    "on a fait de notre rage une symphonie electrique",
    "le feu dans mes yeux reflete le brasier de la scene",
    "j'ai les poumons remplis du souffle de la rebellion",
    "les murs tombent un par un sous nos accords sauvages",
    "on est les loups de la nuit et le rock est notre cri",
    "le tonnerre applaudit quand nos guitares fendent le ciel",
    "j'ai fait de chaque route une chanson et de chaque nuit un concert",
    "les cordes saignent mais la musique ne s'arrete jamais",
    "on a incendie le silence avec nos voix rauques",
    "le feu sacre du rock ne s'eteindra que quand nous tomberons",
    "j'ai traverse mille nuits pour trouver cette seule note parfaite",
    "les amplis grondent leur dernier avertissement au monde endormi",
    "on est les survivants d'un monde qui voulait notre silence",
    "le cuir de mes bottes craque sur le sol de la scene brulante",
    "j'ai la rage des volcans qui n'ont jamais connu le repos",
    "les riffs sauvages dechirent le silence comme des griffes de loup",
    "on a brule les regles et danse sur les cendres fumantes",
    "le feu dans mon ame ne connait pas le mot extinction",
    "j'ai conduit toute la nuit avec les guitares comme seul passager",
    "les murs de cette salle vibrent comme les parois d'un volcan",
    "on a fait saigner la nuit jusqu'a ce qu'elle crie grace",
    "le vent de la revolte souffle dans les cordes de ma guitare",
    "j'ai le souffle rauque des loups qui hurlent a la lune rouge",
    "les etincelles de ma guitare mettent le feu au ciel noir",
    "on a transforme la douleur en decibels et le chagrin en accords",
    "le bitume fond sous nos pas quand on marche vers la scene",
    "j'ai le coeur qui bat comme une grosse caisse lancee a fond",
    "les flammes de la rebellion lechen le plafond de cette salle",
    "on a roule vers nulle part et on a trouve notre paradis",
    "le tonnerre de nos amplis fait trembler les fondations du monde",
    "j'ai des eclairs dans les mains quand je touche ces cordes",
    "les routes sans fin sont les seules promesses que la vie m'a tenues",
    "on a casse le moule et reconstruit un monde a notre image",
    "le silence n'a jamais eu sa place dans le temple de nos concerts",
    "j'ai le gout du sang et de l'acier sur les levres ce soir",
    "les phares percent la nuit comme nos guitares percent le silence",
    "on a danse avec les fantomes de tous les rebelles d'avant nous",
    "le feu de cette nuit brulera dans nos memoires pour toujours",
    "j'ai traverse des oceans de bruit pour trouver ma propre note",
    "les murs s'ecroulent un par un sous le poids de nos accords",
    "on a fait de chaque larme un accord mineur qui dechire l'ame",
    "le ciel tremble quand je monte le volume au dessus de tout",
    "j'ai les mains en feu et le coeur en eruption ce soir",
    "les neons clignotent au rythme de notre rage electrique sur scene",
    "on a tourne le dos au confort pour embrasser la tempete sauvage",
    "le rock est le cri de ceux qui refusent de ramper sur le sol",
    "j'ai la peau brulee par le soleil des routes sans ombre",
    "les cordes de ma guitare saignent les mots que je ne peux pas dire",
    "on a fait de chaque nuit un combat contre le silence oppressant",
    "le vent hurle dans les amplis comme l'ame d'un rebelle mort",
    "j'ai le regard des faucons qui chassent dans la tempete noire",
    "les flammes montent et la foule suit le mouvement vers le haut",
    "on a ecrit notre manifeste avec des riffs au lieu de mots",
    "le sol brule sous nos semelles mais on ne s'arrete pas non",
    "j'ai les veines qui vibrent comme les cordes d'une basse dechainee",
    "les orages sont nos standing ovations et la foudre nos rappels",
    "on a fait de la nuit un brasier que rien ne peut eteindre",
    "le feu ne demande jamais la permission avant de tout consumer",
    "j'ai la fureur des marees qui brisent les digues les plus solides",
    "les guitares hurlent leur douleur dans la nuit sans etoiles ce soir",
    "on a chevauche la nuit comme des cavaliers sans peur ni loi",
    "le rock est mon sang et la scene est mon champ de bataille",
    "j'ai la gorge brulee par les cris de mille nuits de concert",
    "les murs de conformite tombent comme des chateaux de cartes fragiles",
    "on a fait trembler le ciel jusqu'a ce que les etoiles tombent",
    "le son de ma guitare est le cri de ma liberte totale",
    "j'ai le pas des nomades qui ne trouvent jamais le repos",
    "les flammes de nos concerts eclairent un monde trop sombre pour voir",
    "on a bu la nuit comme du whisky brulant dans la gorge",
    "le tonnerre dans nos amplis est la voix de notre generation",
    "j'ai les poumons remplis de fumee de scene et de rebellion pure",
    "les routes s'etendent comme des veines qui portent le sang du rock",
    "on a refuse de murmurer dans un monde qui voulait notre silence",
    "le feu dans mes yeux est le reflet de mille concerts passes",
    "j'ai la force des rivieres qui creusent les montagnes avec le temps",
    "les accords resonnent dans ma cage thoracique comme un second coeur",
    "on a fait du bruit notre priere et du chaos notre sanctuaire",
    "le vent des routes ouvertes est le seul parfum que je porte",
    "j'ai le coeur forge dans le metal des guitares electriques lourdes",
    "les nuits de concert sont les seuls jours feries que je reconnais",
    "on a plante notre drapeau noir sur les ruines de leur monde",
    "le sol vibre sous nos pieds comme un coeur qui bat la chamade",
    "j'ai la voix des tempetes qui ne connaissent pas la fatigue",
    "les flammes de notre musique rechauffent ceux que le monde a geles",
    "on a fait de chaque defaite un nouveau riff plus puissant",
    "le rock ne meurt pas il couve sous les cendres en attendant",
    "j'ai les os trempes de musique et le sang rempli de riffs",
    "les murs les plus epais cedent sous la puissance de notre son",
    "on a conquis la nuit et maintenant on vient chercher le jour",
    "le feu sacre brule dans le coeur de ceux qui jouent trop fort",
    "j'ai la determination des locomotives qui ne quittent jamais les rails",
    "les etincelles de la scene retombent sur nous comme une pluie d'or",
    "on a fait vibrer les os de la terre avec nos basses",
    "le tonnerre se tait quand nos amplis prennent la parole ce soir",
    "j'ai le cri des aigles qui fendent le ciel orageux sans peur",
    "les cordes vibrent et le monde tremble sur ses fondations fragiles",
    "on a fait de notre rage une cathedrale de son et de feu",
    "le bitume des routes s'imprime sur nos semelles comme un tatouage",
    "j'ai la fureur des elements quand le premier accord explose",
    "les neons de la scene sont les seules lumieres de ma vie",
    "on a ecrit nos regles avec du feu sur les murs du monde",
    "le silence est un affront que nos guitares ne tolereront jamais",
    "j'ai le souffle des tornades qui balaient tout sur leur passage",
    "les flammes dansent dans nos yeux comme la promesse d'une nuit sauvage",
    "on a fait de chaque salle un volcan pret a exploser sous nos pieds",
    "le feu de la guitare coule sur mes doigts comme de la lave",
    "j'ai les cicatrices des cordes gravees dans la chair de mes doigts",
    "les amplis sont nos canons et la musique est notre revolution totale",
    "on a refuse de vieillir dans un monde qui veut nous dompter",
    "le sol gronde sous le poids de notre musique dechainee ce soir",
    "j'ai la fievre des nuits sans fin passees a jouer dans l'ombre",
    "les guitares pleurent et rient dans le meme souffle electrique brulant",
    "on a fait trembler les vitres de chaque ville traversee la nuit",
    "le feu ne connait pas la frontiere entre la scene et la foule",
    "j'ai le gout de la liberte sur les levres quand je chante fort",
    "les routes de nuit sont des serpents de lumiere sous nos roues",
    "on a fait de chaque concert une insurrection contre le silence",
    "le vent emporte nos accords vers des oreilles qui ont soif de bruit",
    "j'ai la sueur des batailles et le sourire des victorieux ce soir",
    "les murs de cette salle portent les traces de notre passage sauvage",
    "on a fait du rock notre bouclier contre un monde trop silencieux",
    "le tonnerre est jaloux du bruit que font nos amplis le soir",
    "j'ai les mains pleines d'eclairs quand la musique prend possession de moi",
    "les flammes de notre musique ne s'eteignent pas avec le lever du soleil",
    "on a roule vers l'horizon sans jamais trouver la ligne d'arrivee",
    "le rock coule dans mon sang comme un fleuve qui ne tarit pas",
    "j'ai le regard des loups solitaires qui choisissent la nuit comme alliee",
    "les accords fracassent le silence comme des vagues sur les rochers",
    "on a fait de la nuit notre alliee et du bruit notre arme",
    "le feu dans ma poitrine ne s'eteindra qu'avec mon dernier souffle",
    "j'ai la rage des oceans dechainees quand je monte sur scene",
    "les phares de la camionnette eclairent des routes que personne ne prend",
    "on a fait du chaos notre jardin et du bruit notre fleur",
    "le ciel se fend en deux quand nos guitares attaquent ensemble",
    "j'ai le coeur plus lourd que les basses qui font trembler la salle",
    "les etincelles volent comme des lucioles de feu dans la nuit noire",
    "on a traverse le feu et la glace pour arriver jusqu'a cette scene",
    "le rock est une priere hurlee dans un monde qui a oublie dieu",
    "j'ai les cordes vocales usees par mille nuits de cris sinceres",
    "les murs de beton ne sont rien face a la puissance de nos riffs",
    "on a fait de chaque goutte de sueur une note de musique pure",
    "le feu de la passion brule les chaines de la mediocrite",
    "j'ai la foudre dans les doigts et le tonnerre dans la voix",
    "les routes poussiereuses sont les seules eglises que je frequente",
    "on a joue si fort que les morts ont entendu notre musique",
    "le vent de la liberte souffle dans les cordes comme un ouragan",
    "j'ai le sang bouillant des rebelles qui ne connaitront jamais la paix",
    "les flammes de nos concerts dessinent des fresques sur les murs noirs",
    "on a fait de la nuit un jour et du bruit une caresse",
    "le tonnerre applaudit nos solos comme le ciel salue la foudre",
    "j'ai la voix rouille de ceux qui ont crie dans le desert trop longtemps",
    "les cordes de ma guitare sont les nerfs de mon ame a vif",
    "on a marche sur le feu et nos pieds n'ont pas brule ce soir",
    "le rock est le langage des ames qui refusent de se plier",
    "j'ai le souffle des dragons quand le micro se rapproche de mes levres",
    "les nuits de tempete sont les plus belles pour jouer de la guitare",
    "on a fait resonner les montagnes avec la force de nos accords",
    "le feu purificateur ne brule que ce qui ne merite pas de rester",
    "j'ai les yeux rouges des nuits blanches passees a repeter sans cesse",
    "les amplis crachent leur dernier souffle et on leur en redemande encore",
    "on a fait de chaque ville une legende et de chaque nuit un mythe",
    "le ciel est notre plafond et le monde entier est notre scene ouverte",
    "j'ai la rage silencieuse de ceux qui exploent quand ils touchent les cordes",
    "les flammes dansent sur nos guitares comme des esprits liberes de leurs chaines",
    "on a brise les miroirs pour ne plus voir que le feu devant",
    "le rock est l'echo d'un tonnerre qui ne cesse jamais de gronder",
    "j'ai le coeur qui bat comme un marteau sur une enclume brulante",
    "les routes nocturnes sont des poemes ecrits a la vitesse du son",
    "on a fait de notre liberte un concert sans fin ni frontieres",
    "le feu dans nos veines est la preuve que nous sommes vivants",
    "j'ai la determination des pierres qui resistent a l'erosion du temps",
    "les guitares chantent la colere que les mots ne peuvent pas exprimer",
    "on a fait du rock notre oxygene et du bruit notre raison de vivre",
    "le tonnerre dans nos amplis fait trembler les etoiles dans le ciel",
    "j'ai les mains brulees par les cordes et le coeur en flammes vives",
    "les nuits de concert sont les seuls moments ou le temps s'arrete enfin",
    "on a fait trembler la terre et le ciel nous a repondu"
  ],
  bridges: [
    "le feu ne s'eteint pas il se transforme en lumiere",
    "entre le bruit et le silence il y a notre musique",
    "on ne recule plus maintenant c'est le moment de foncer",
    "les chaines se brisent quand la musique parle assez fort",
    "quelque part entre la rage et la paix il y a nous",
    "le monde nous a dit non et nous on a dit plus fort",
    "entre le premier accord et le dernier il y a une vie",
    "on a tout quitte pour cette route et cette musique",
    "les flammes purifient ce que le silence a corrompu",
    "entre le tonnerre et l'eclair il y a notre chanson",
    "on ne connait pas la peur quand la musique nous porte",
    "le monde s'ecroule mais le rock tient toujours debout",
    "entre la revolte et l'espoir il y a un riff de guitare",
    "on a fait de la douleur un carburant pour notre feu",
    "les murs les plus solides tombent face a notre son",
    "entre la nuit et l'aube il y a notre dernier concert",
    "on refuse de s'eteindre meme quand tout s'effondre autour",
    "le silence est la mort et nous on choisit la vie",
    "entre le chaos et l'ordre il y a le rock qui decide",
    "on a la foudre dans les mains et le tonnerre dans la voix",
    "les cendres d'hier sont le terreau de demain qui brule",
    "entre la chute et le vol il y a une note jouee",
    "on ne meurt jamais tant que la musique resonne encore",
    "le feu de la scene nous eclaire quand le monde s'assombrit",
    "entre la cage et le ciel il y a les ailes du rock",
    "on a fait de chaque blessure un tatouage de notre force",
    "les routes ne finissent jamais quand on refuse de s'arreter",
    "entre la tempete et le calme il y a notre refrain",
    "on a choisi le bruit parce que le silence ment",
    "le monde peut bien bruler nos guitares joueront encore",
    "entre les ruines et la gloire il y a un concert de plus",
    "on ne demande pas pardon pour le bruit qu'on fait",
    "les flammes de la rebellion eclairent le chemin des perdus",
    "entre le premier cri et le dernier accord il y a nous",
    "on est nes dans le feu et on mourra dans la lumiere"
  ],
  choruses: [
    "on met le feu a la nuit et on danse dans les flammes",
    "je suis le tonnerre qui gronde dans le ciel rebelle",
    "on roule vers le soleil sans jamais regarder en arriere",
    "le feu brule dans nos veines et rien ne peut l'eteindre",
    "on est libres on est vivants on est le rock ce soir",
    "je hurle dans la nuit et le monde me repond",
    "les guitares chantent notre rage et notre liberte ensemble",
    "on ne s'arretera jamais tant que le feu brulera",
    "je suis la foudre je suis le feu je suis la nuit",
    "on a brise les chaines maintenant on vole enfin",
    "le rock est notre sang et la scene notre champ de bataille",
    "je brule comme un soleil qui refuse de se coucher",
    "on est les enfants de l'orage et du tonnerre sauvage",
    "le monde peut trembler on ne baissera pas le son",
    "je suis ne pour hurler et pas pour murmurer",
    "on monte le volume jusqu'a faire trembler les etoiles",
    "le feu de la rebellion ne s'eteindra jamais en nous",
    "je roule a fond dans la nuit les yeux grand ouverts",
    "on est la tempete que personne ne peut arreter",
    "le rock est vivant tant que nos coeurs battent encore",
    "je suis le cri de la nuit et l'echo de la route",
    "on brule les regles et on ecrit les notres",
    "le feu consume le mensonge et revele la verite",
    "je vis pour la scene et la scene vit pour moi",
    "on est les loups qui hurlent sous la lune de feu",
    "le tonnerre dans nos amplis fait trembler le monde entier",
    "je suis indestructible quand la musique est avec moi",
    "on a le feu sacre et personne ne peut nous l'enlever",
    "le rock est notre priere et la nuit notre cathedrale",
    "je brule d'une flamme que le temps ne peut pas eteindre",
    "on est les derniers rebelles dans un monde de moutons",
    "le ciel est en feu et nous on alimente les flammes",
    "je suis la voix des routes et le cri des guitares",
    "on ne dort jamais tant que la musique reste vivante",
    "le feu monte toujours plus haut quand on nourrit la flamme",
    "je suis le chaos qui danse au rythme du tonnerre",
    "on est le bruit qui derange le silence confortable",
    "le rock ne meurt pas il renait de chaque cendre",
    "je hurle ma verite et le vent la porte au monde",
    "on est les flammes qui brulent dans la nuit eternelle",
    "le monde ne nous a rien donne on a tout pris",
    "je suis le feu la route et la nuit qui ne finit pas",
    "on a la rage qui brule plus fort que mille soleils",
    "le rock est le seul langage que notre coeur comprend",
    "je vis je brule je chante et je ne regrette rien",
    "on est les survivants d'un monde qui voulait notre silence",
    "le feu dans nos yeux eclaire les routes les plus sombres",
    "je suis la tempete le tonnerre et la foudre reunis",
    "on est nes pour faire du bruit et bousculer le monde",
    "le rock coule dans nos veines comme un fleuve de feu",
    "on brule plus fort que le soleil et rien ne nous arretera",
    "je suis le feu la foudre et la rage d'un monde libre",
    "on est les flammes qui dansent sur les cendres de vos regles",
    "le tonnerre est notre musique et la nuit est notre scene",
    "je hurle vers le ciel et les etoiles tremblent de peur",
    "on ne connait pas le silence on ne connait que le feu",
    "le rock est notre cri de guerre et la scene notre champ",
    "je suis la tempete qui balaie un monde trop calme et mort",
    "on monte le volume et le monde entier se reveille enfin",
    "le feu brule en nous comme un soleil qui ne se couche pas",
    "je suis le dernier rebelle debout dans un monde a genoux",
    "on est le bruit que la nuit fait quand elle se rebelle",
    "le rock est notre sang notre souffle et notre dernier battement",
    "je vis pour la scene je meurs pour la musique chaque soir",
    "on chevauche la foudre et on ne regarde jamais derriere nous",
    "le feu dans nos coeurs brule plus fort que tous les soleils",
    "je suis ne du tonnerre et je mourrai dans un eclair blanc",
    "on est les enfants du chaos et la musique est notre mere",
    "le rock rugit en nous comme un lion dans la cage ouverte",
    "je suis la flamme qui refuse de mourir dans le vent froid",
    "on va bruler cette nuit jusqu'a ce que l'aube prenne feu",
    "le ciel est notre scene et les etoiles sont nos spots brillants",
    "je suis le cri que le silence n'a jamais pu etouffer",
    "on est les volcans qui crachent du feu sur un monde endormi",
    "le rock ne mourra jamais tant que nos coeurs battent encore",
    "je brule de chaque note et je renais de chaque accord joue",
    "on est la revolution le bruit et la fureur du monde libre",
    "le feu sacre du rock brule eternellement dans nos veines chaudes",
    "je suis le tonnerre la tempete et le feu qui ne meurt jamais"
  ],
  vocabulary: {
    nouns: [
      "feu",
      "flamme",
      "tonnerre",
      "foudre",
      "orage",
      "tempete",
      "route",
      "autoroute",
      "moteur",
      "guitare",
      "ampli",
      "scene",
      "cri",
      "hurlement",
      "rage",
      "revolte",
      "rebellion",
      "chaos",
      "ruine",
      "cendres",
      "brasier",
      "volcan",
      "loup",
      "bete",
      "cicatrice",
      "chaine",
      "mur",
      "barricade",
      "drapeau",
      "tatouage",
      "sueur",
      "sang",
      "eclair",
      "etincelle",
      "fumee",
      "poussiere",
      "riff",
      "accord",
      "decibel",
      "frequence",
      "basse",
      "batterie",
      "micro",
      "neon",
      "asphalte",
      "bitume",
      "horizon",
      "abime",
      "sommet",
      "aube",
      "rebellion",
      "liberte",
      "corde",
      "solo",
      "manche",
      "pedal",
      "distorsion",
      "feedback",
      "reverb",
      "cuir",
      "botte",
      "drapeau",
      "tatouage",
      "loup",
      "aigle",
      "dragon",
      "acier",
      "ferraille",
      "barricade",
      "cratere",
      "canyon",
      "caverne",
      "grotte",
      "precipice",
      "falaise",
      "ravine",
      "crevasse",
      "forge"
    ],
    verbs: [
      "bruler",
      "hurler",
      "rugir",
      "exploser",
      "gronder",
      "dechirer",
      "fracasser",
      "incendier",
      "foudroyer",
      "pulveriser",
      "eclater",
      "vibrer",
      "resonner",
      "tonner",
      "enflammer",
      "consumer",
      "ravager",
      "detruire",
      "briser",
      "cracher",
      "chevaucher",
      "foncer",
      "rouler",
      "fuir",
      "traverser",
      "defier",
      "resister",
      "combattre",
      "vaincre",
      "survivre",
      "renaitre",
      "emerger",
      "secouer",
      "trembler",
      "rugir",
      "soulever",
      "arracher",
      "lacerer",
      "embraser",
      "fissurer",
      "ebranler",
      "balayer",
      "envahir",
      "dominer",
      "conquerir",
      "liberer",
      "enchainer",
      "marteler",
      "frapper",
      "electriser",
      "calciner",
      "carboniser",
      "volatiliser",
      "disloquer",
      "desartibuler",
      "ebranler",
      "catapulter",
      "propulser",
      "vrombir",
      "piler",
      "labourer",
      "scarifier",
      "lacerer",
      "cisailler",
      "perforer",
      "transpercer",
      "erafler",
      "caramboler",
      "desintegrer",
      "engloutir",
      "submerger",
      "noyer",
      "calciner",
      "volatiliser",
      "craquer",
      "gronder",
      "mugir",
      "galoper"
    ],
    adjectives: [
      "sauvage",
      "rebelle",
      "indomptable",
      "feroce",
      "brulant",
      "electrique",
      "explosif",
      "furieux",
      "dechaine",
      "volcanique",
      "ardent",
      "incandescent",
      "ravageur",
      "foudroyant",
      "brutal",
      "rauque",
      "sombre",
      "nocturne",
      "infernal",
      "titanesque",
      "monstrueux",
      "colossal",
      "puissant",
      "violent",
      "chaotique",
      "tumultueux",
      "devastateur",
      "implacable",
      "impitoyable",
      "indestructible",
      "invincible",
      "libre",
      "solitaire",
      "errant",
      "nomade",
      "affame",
      "assoiffe",
      "trempe",
      "forge",
      "blinde",
      "massif",
      "lourd",
      "strident",
      "grondant",
      "rugissant",
      "incendiaire",
      "torride",
      "orageux",
      "tempetueux",
      "enrage",
      "tellurique",
      "sismique",
      "cataclysmique",
      "herculeen",
      "vertigineux",
      "abyssal",
      "caverneux",
      "tonique",
      "ravageur",
      "devorant",
      "consumant",
      "assourdissant",
      "fracassant",
      "tonitruant",
      "vrombissant",
      "crepitant",
      "dechaine",
      "dechainent",
      "indomptable",
      "inextinguible",
      "insoumis",
      "frenetique",
      "exalte",
      "possede",
      "demonique",
      "sanglant",
      "venimeux",
      "corrosif",
      "acide"
    ]
  }
};
