/**
 * GenreBankExpansion — MASSIVE phrase library expansion.
 * Adds 14 new genres + expanded phrases for existing genres + new mood modifiers.
 * ~2,000+ new lyric phrases for COMPLETE DOMINATION.
 */

export const GENRE_BANKS_EXPANSION = {

    // =====================================================================
    // NEW GENRE: TRAP
    // =====================================================================
    trap: {
        themes: ['hustle', 'ice', 'flex', 'drip', 'money', 'streets', 'grind', 'sauce', 'bands', 'loyalty', 'betrayal', 'come-up'],
        openers: [
            'pull up in the foreign whip',
            'drip too hard they slip',
            'counting blue faces on the flip',
            'ice on my wrist yeah i grip',
            'straight out the mud i dip',
            'trap phone ringing never skip',
            'money counter going brrrr no trip',
            'diamonds dancing on my lip',
            'young and rich i let it rip',
            'came from nothing now i drip',
            'bad and boujee on the strip',
            'the bag secured i never slip',
            'woke up to a money drip',
            'started from the bottom brick by brick',
            'in the kitchen whipping quick',
        ],
        verses: [
            'counting up the racks all night',
            'foreign car under the streetlight',
            'diamonds hit they shining bright',
            'came from nothing now the future bright',
            'ice around my neck so right',
            'paper chasing in the moonlight',
            'trap house jumping every night',
            'money talks it speaks polite',
            'flexing hard it feels so right',
            'young and rich we own the night',
            'drip too hard they lost they sight',
            'bands on bands we hold it tight',
            'pull up in the phantom white',
            'never fold we stand and fight',
            'ice so cold it bites',
            'foreign whip under neon lights',
            'trap star living legendary heights',
            'counting paper through the midnight',
            'designer everything in sight',
            'the gang is here we reunite',
            'we made it out the darkest night',
            'loyalty is worth more than ice',
            'every sacrifice came with a price',
            'trap or die there is no in between',
            'money green the freshest ever seen',
            'stack it up and keep the paper clean',
            'living life just like a movie scene',
            'young boss building up the whole machine',
            'codeine dreams and cash machines',
            'flexing on them diamonds gleam',
            'bankroll heavy stacking cream',
            'the trap is booming and the money stream',
            'lifestyle looking like a fever dream',
            'drip so hard they want the recipe',
            'trap phone buzzing like a melody',
            'diamonds dancing they remember me',
            'money talking like a remedy',
            'counting blessings and the currency',
            'we dont fold under any pressure',
            'every move a calculated measure',
            'ice so cold they check the weather',
            'trap stars shining now and forever',
            'money bag secured with leather',
            'built the empire altogether',
            'foreign whips and alligator leather',
            'we came up together',
            'trap phone ringing off the handle',
            'living life they cant unscramble',
            'diamonds lit just like a candle',
            'every scandal we can handle',
            'young kings sitting at the table',
            'trap or die you know the label',
            'stacking paper we are able',
            'this lifestyle aint a fable',
            'ice so bright it tells a story',
            'drip so hard they know the glory',
            'every chapter territory',
            'trap kings writing inventory',
            'counting money mandatory',
            'flexing hard its predatory',
            'diamonds dancing legendary',
            'young and rich and visionary',
        ],
        bridges: [
            'from the mud to the penthouse suite',
            'trap dreams pounding with the beat',
            'every loss just made us more complete',
            'the come-up story no repeat',
            'diamonds dancing in the heat',
        ],
        preChorus: [
            'yeah we made it out the trap',
            'money on the counter stack',
            'ice around my neck dont lack',
            'drip too hard they cant react',
        ],
        hooks: [
            'drip drip ice ice thats the life',
            'counting money every night',
            'trap star shining in the light',
            'flexing hard we own the night',
            'racks on racks we never stop',
            'ice on ice we at the top',
            'foreign whip we let it drop',
            'trap house vibes we never flop',
        ],
        choruses: [
            'drip so hard they drown in the wave',
            'diamonds dancing in the shade',
            'counting money getting paid',
            'trap star living unafraid',
            'ice around my neck parade',
            'foreign car on the promenade',
            'money talks the plans we laid',
            'flexing hard the game we played',
            'stacking paper lemonade',
            'diamonds shining like a blade',
            'trap phone ringing serenade',
            'young and rich the upgrade',
            'ice so cold the masquerade',
            'money bags the escapade',
            'drip so heavy retrograde',
            'counting blessings getting paid',
        ],
        vocabulary: {
            nouns: ['ice', 'drip', 'bag', 'racks', 'bands', 'chain', 'whip', 'trap', 'block', 'gang', 'crown', 'throne', 'money', 'cash', 'paper', 'diamond', 'gold', 'platinum', 'foreign', 'sauce', 'flex', 'grind', 'hustle', 'empire', 'kingdom', 'streets', 'fire', 'smoke', 'heat', 'flame', 'wave', 'drip', 'flow', 'vibe', 'energy', 'power', 'respect', 'loyalty', 'legacy', 'legend', 'fortune', 'treasure', 'mansion', 'penthouse', 'rooftop', 'skyline', 'sunset', 'midnight', 'stars', 'moon'],
            verbs: ['stack', 'count', 'flex', 'drip', 'pull', 'slide', 'grind', 'hustle', 'shine', 'glow', 'run', 'own', 'build', 'ride', 'fly', 'rise', 'ball', 'stunt', 'flip', 'whip', 'pour', 'drop', 'roll', 'move', 'push', 'chase', 'claim', 'earn', 'win', 'conquer', 'dominate', 'rule', 'reign', 'lead', 'stand', 'hold', 'grip', 'lock', 'load', 'fire'],
            adjectives: ['icy', 'cold', 'frozen', 'dripping', 'heavy', 'loaded', 'stacked', 'foreign', 'exotic', 'lavish', 'rich', 'golden', 'diamond', 'platinum', 'royal', 'supreme', 'legendary', 'unstoppable', 'untouchable', 'unbreakable', 'fearless', 'ruthless', 'relentless', 'savage', 'blessed', 'chosen', 'real', 'raw', 'fresh', 'clean', 'sharp', 'bright', 'lit', 'fire', 'hot', 'fly', 'slick', 'smooth', 'tough', 'hard'],
        },
        // --- SUPER MASSIVE additional trap verses ---
        versesExtra: [
            'the foreign on the lot we pulled the trigger',
            'counting digits getting bigger and bigger',
            'the ice is dancing figure after figure',
            'the trap is pumping hard we pull the lever',
            'stacking money we are never ever stopping',
            'the diamonds on my wrist they keep on popping',
            'designer from the top down to the bottom',
            'the haters keep on watching but we got em',
            'the phantom rolling silent through the city',
            'the money counter singing like a ditty',
            'the plug is on the phone the bag is pretty',
            'the lifestyle got them feeling full of pity',
            'the chain is hitting heavy on my collar',
            'the trap phone ringing baller after baller',
            'the money coming in a little taller',
            'the lifestyle loud we never getting smaller',
            'the penthouse view is looking rather stunning',
            'the bag is on the way the money running',
            'the ops are watching but we keep on gunning',
            'the trap is booming and the cash is coming',
            'the designer on my back the label showing',
            'the money in the safe it keeps on growing',
            'the ice around my neck the light is glowing',
            'the river of the cash it keeps on flowing',
            'the lambo sitting pretty in the driveway',
            'the money talk is speaking in a big way',
            'the diamonds on my fingers for display',
            'the lifestyle that we live from day to day',
            'the safe is full the money overflowing',
            'the drip is heavy and the wind is blowing',
            'the trap is booming and the seeds are sowing',
            'the empire that we built is always growing',
            'the rollie on my wrist the time is money',
            'the weather in the trap is always sunny',
            'the lifestyle sweet the money dripping honey',
            'the haters mad because we looking funny',
            'the foreign switching lanes on the highway',
            'the money counter going every friday',
            'the ice so cold they call it the ice age',
            'the diamonds bright enough to light the stage',
            'we stack it to the ceiling every page',
            'the money coming in at every gauge',
            'the bag secured inside the diamond cage',
            'the trap is booming at a record wage',
            'we never fold we never break the chain',
            'the money flowing heavy like the rain',
            'the ice is dripping running down the drain',
            'the trap phone buzzing pleasure and the pain',
            'designer on my body domain',
            'the lifestyle that we live is not mundane',
            'the grind is heavy pounding in my brain',
            'the money trees are growing once again',
            'the phantom gliding on the boulevard',
            'the ice is sparkling like a greeting card',
            'the trap is booming shaking every yard',
            'the money coming in we standing guard',
            'we built the empire from the ground up',
            'the diamonds in the crown we found the cup',
            'the money overflowing time to re-up',
            'the trap is booming and we never giving up',
            'the rollie spinning like a helicopter',
            'the money in my pocket getting proper',
            'the ice so cold it makes the haters holler',
            'the trap is booming we are getting hotter',
        ],
    },

    // =====================================================================
    // NEW GENRE: DRILL
    // =====================================================================
    drill: {
        themes: ['streets', 'survival', 'loyalty', 'respect', 'war', 'blocks', 'opps', 'hustle', 'real', 'grind'],
        openers: [
            'sliding through the block at midnight',
            'they know we dont play around here',
            'posted on the corner every night',
            'real ones know the struggle right',
            'the streets are watching every move',
            'smoke in the air and nothing to prove',
            'block is hot they feel the groove',
            'real talk nothing left to lose',
            'the streets remember every bruise',
            'posted up we never move',
            'from the trenches to the booth',
            'every bar is nothing but the truth',
            'street code etched into my youth',
            'drill music speaking uncouth',
            'the block is living breathing proof',
        ],
        verses: [
            'on the block we never sleep',
            'the code we live is running deep',
            'real ones know the streets we keep',
            'loyalty runs through my veins',
            'the struggle left me with these chains',
            'every scar tells the story of the pains',
            'the block is cold but the heart remains',
            'drill beats bumping through the lanes',
            'survival mode in every cell',
            'the streets are watching i can tell',
            'from the bottom to the top we fell',
            'and rose again with tales to tell',
            'the ops are lurking in the dark',
            'but real ones always leave a mark',
            'from the trenches to the park',
            'every night is cold and stark',
            'posted on the block we ride',
            'real ones standing by my side',
            'the streets are where the truth resides',
            'survival is the only guide',
            'drill beats echo through the night',
            'every bar is packed with might',
            'the block is watching shining bright',
            'real talk nothing scripted right',
            'the code is simple ride or die',
            'real ones never question why',
            'the streets are cold beneath the sky',
            'but we stand tall we never lie',
            'from the mud we built the throne',
            'the streets remember every stone',
            'real ones grinding on their own',
            'the struggle made us flesh and bone',
            'drill beats knocking at the door',
            'real ones know what we stand for',
            'the block is hot from floor to floor',
            'survival code to the core',
            'they tried to break us but we stood',
            'real ones always understood',
            'the streets taught us what they could',
            'from the concrete grew the good',
            'the block is silent after dark',
            'but every corner leaves a mark',
            'from the gutter to the arc',
            'real ones know it from the start',
            'posted up and battle ready',
            'grip is firm and aim is steady',
            'drill music hitting heavy',
            'the block is silent but the pressure is deadly',
            'concrete jungle living free',
            'the block is all we came to be',
            'real ones move in secrecy',
            'the code is written for eternity',
            'from the bottom looking up',
            'the struggle filled our bitter cup',
            'real ones never giving up',
            'the block is where we all grew up',
        ],
        bridges: [
            'the streets dont sleep and neither do we',
            'from the trenches to the industry',
            'every bar is autobiography',
            'drill music set the real ones free',
        ],
        preChorus: [
            'posted on the block we ride',
            'real ones never run and hide',
            'the streets are cold outside',
            'drill beats bumping worldwide',
        ],
        hooks: [
            'on the block we stand we never fold',
            'real ones know the story told',
            'drill music made of gold',
            'the streets are cold but we are bold',
        ],
    },

    // =====================================================================
    // NEW GENRE: AFROBEAT
    // =====================================================================
    afrobeat: {
        themes: ['dance', 'joy', 'celebration', 'love', 'culture', 'rhythm', 'sun', 'unity', 'freedom', 'ancestors'],
        openers: [
            'the rhythm calling from the motherland',
            'dancing underneath the african sun',
            'feel the beat and let the music run',
            'from lagos to the world we come as one',
            'the drums are speaking can you understand',
            'joyful dancing with the golden sand',
            'afrobeat is pumping through the land',
            'every body moving to the band',
            'the bass is heavy and the rhythm grand',
            'feel the culture flowing through my hand',
            'the sun is rising on a brand new day',
            'afrobeat will take your blues away',
            'dancing to the rhythm hear me say',
            'the music spreads from naija to the bay',
            'feel alive and let the music play',
        ],
        verses: [
            'the drums are calling everybody move',
            'afrobeat is setting up the groove',
            'dancing in the moonlight nothing left to prove',
            'the rhythm got me feeling smooth',
            'from the continent the music flew',
            'every beat is something fresh and new',
            'the sun is shining and the sky is blue',
            'afrobeat connecting me to you',
            'the bassline heavy and the hi-hats light',
            'dancing to the left and to the right',
            'the party goes from sunset until bright',
            'afrobeat is taking off in flight',
            'feel the culture running through my blood',
            'the rhythm rising like a golden flood',
            'from the soil to the sky above',
            'afrobeat is built on joy and love',
            'the percussion hitting like a wave',
            'dancing free because the music gave',
            'the ancestors are watching from the cave',
            'afrobeat the rhythm of the brave',
            'palm wine flowing and the music loud',
            'the dance floor packed with every crowd',
            'afrobeat is making mama proud',
            'the culture shining like a golden shroud',
            'from accra to the western shore',
            'the rhythm pumping to the core',
            'afrobeat is what we all adore',
            'the dance floor calling for encore',
            'the talking drum is speaking truth',
            'the music heals the wounds of youth',
            'afrobeat is living breathing proof',
            'the rhythm lifting through the roof',
            'the sun is setting on the coast',
            'but afrobeat is vibing most',
            'from east to west from coast to coast',
            'the rhythm turns the world into a host',
            'the guitar licks are dripping sweet',
            'the horns are blaring with the beat',
            'afrobeat will never know defeat',
            'the dance floor living breathing heat',
            'feel the energy from head to toe',
            'the rhythm letting everybody know',
            'afrobeat will steal the whole show',
            'the music making spirits glow',
            'the conga beating like a heart',
            'afrobeat is more than just an art',
            'the rhythm pulling worlds apart',
            'then bringing them together from the start',
        ],
        bridges: [
            'the motherland is calling can you hear',
            'afrobeat will wash away the fear',
            'the drums are beating loud and clear',
            'the rhythm celebrating year by year',
        ],
        hooks: [
            'dance dance to the afrobeat',
            'feel the rhythm feel the heat',
            'everybody moving to the beat',
            'afrobeat is living on the street',
        ],
    },

    // =====================================================================
    // NEW GENRE: REGGAE
    // =====================================================================
    reggae: {
        themes: ['peace', 'love', 'unity', 'freedom', 'resistance', 'nature', 'spirituality', 'justice', 'island', 'roots'],
        openers: [
            'one love one heart let us unite',
            'the sun is shining and the vibes are right',
            'island breeze blowing through the night',
            'roots and culture burning bright',
            'feel the riddim feel the bass tonight',
            'from kingston town to every height',
            'jah bless the morning with the light',
            'the music heals the darkest night',
            'reggae rhythms flowing like a stream',
            'chanting down babylon the dream',
            'island living more than what it seem',
            'the bass is heavy and the horns they gleam',
            'one drop rhythm speaking to the soul',
            'reggae music making broken whole',
            'from the roots we reach the goal',
        ],
        verses: [
            'the bass is heavy and the riddim sweet',
            'reggae music bumping in the street',
            'island vibes from head to feet',
            'one love making life complete',
            'chanting down the walls of hate',
            'reggae rhythms never come too late',
            'every soul deserves a better fate',
            'the music opens up the gate',
            'from the island to the world we spread',
            'the message of the living and the dead',
            'reggae music filling hearts with dread',
            'positive vibrations in our head',
            'the skank is bouncing off the wall',
            'reggae music answering the call',
            'one love standing proud and tall',
            'united we will never fall',
            'the palm trees swaying in the breeze',
            'reggae music putting minds at ease',
            'the ocean blue beneath the trees',
            'island living doing as we please',
            'the bass guitar is holding down the groove',
            'reggae music got us all to move',
            'every heartbeat something left to prove',
            'the rhythm smooth the rhythm smooth',
            'roots and culture running through my veins',
            'the music healing all the pains',
            'breaking free from mental chains',
            'reggae rhythms pouring down like rains',
            'from trenchtown to the mountaintop',
            'the reggae beat will never stop',
            'one drop rhythm every crop',
            'the bassline heavy gonna drop',
            'the organ bubbling in the key',
            'reggae music setting spirits free',
            'the island calling you and me',
            'one love is all we need to be',
            'the skank guitar is clean and bright',
            'reggae music shining in the light',
            'every wrong will turn to right',
            'one love we carry through the night',
            'the ocean waves are calling home',
            'reggae rhythms wherever i may roam',
            'the island spirit in my bone',
            'from the roots the tree has grown',
            'the message clear for all to hear',
            'reggae music conquering the fear',
            'one love one heart one atmosphere',
            'the riddim playing year to year',
        ],
        bridges: [
            'one love uniting every nation',
            'reggae music our foundation',
            'from the roots to the constellation',
            'the riddim is the revelation',
        ],
        hooks: [
            'one love one heart one riddim tonight',
            'feel the bass feel the light',
            'reggae music shining bright',
            'island vibes everything is right',
        ],
    },

    // =====================================================================
    // NEW GENRE: PUNK
    // =====================================================================
    punk: {
        themes: ['rebellion', 'anarchy', 'freedom', 'anger', 'society', 'revolution', 'noise', 'defiance', 'youth', 'chaos'],
        openers: [
            'tear it down and start again',
            'screaming at the world of pain',
            'the system broken we remain',
            'three chords and the truth is plain',
            'no future but the one we claim',
            'anarchy is not a game',
            'burn the rulebook fan the flame',
            'the underground will stake its claim',
            'smash the state and break the chain',
            'punk rock screaming through the rain',
            'the mosh pit calling out my name',
            'society you are to blame',
            'loud and fast and never tame',
            'the underground will rise to fame',
            'safety pins and bleach and flame',
        ],
        verses: [
            'three chords and a lot to say',
            'the system crumbling every day',
            'punk rock living our own way',
            'no rules no gods no one to obey',
            'the underground is where we stay',
            'screaming truth into the fray',
            'burn it down and walk away',
            'the revolution starts today',
            'mohawks raised up to the sky',
            'punk rock anthem do or die',
            'society you live a lie',
            'we question everything and ask you why',
            'the mosh pit is our therapy',
            'three chords is all we need to be',
            'punk rock setting spirits free',
            'anarchy for you and me',
            'the speakers blowing out the wall',
            'punk rock never learned to crawl',
            'we stand for those who always fall',
            'rebellion answering the call',
            'leather jacket safety pin',
            'punk rock fighting from within',
            'the battle never wore us thin',
            'we scream until the new begin',
            'the garage is where it starts',
            'punk rock is the bleeding arts',
            'tearing all the rules apart',
            'three chords burning in the heart',
            'society can keep its throne',
            'punk rock built on blood and bone',
            'we walk the path we walk alone',
            'the underground is where we own',
            'distortion ripping through the air',
            'punk rock and we just dont care',
            'the system never played it fair',
            'rebellion growing everywhere',
            'no sellout no compromise',
            'punk rock never tells the lies',
            'we see right through the thin disguise',
            'the underground will always rise',
        ],
        bridges: [
            'three chords changed the world forever',
            'punk rock dies no never never',
            'the underground stays strong together',
            'rebellion in any weather',
        ],
        hooks: [
            'tear it down tear it down tonight',
            'punk rock burning burning bright',
            'scream it loud with all your might',
            'we are the noise we are the fight',
        ],
    },

    // =====================================================================
    // NEW GENRE: SOUL
    // =====================================================================
    soul: {
        themes: ['love', 'heartache', 'devotion', 'gospel', 'strength', 'truth', 'tenderness', 'passion', 'spirit', 'grace'],
        openers: [
            'my soul is singing out to you',
            'the rhythm of my heart beats true',
            'i gave you everything i knew',
            'these feelings running deep and new',
            'the music in my veins it grew',
            'feel the spirit pushing through',
            'the morning light a golden hue',
            'my love for you forever grew',
            'from deep inside the truth i drew',
            'the soul is speaking nothing new',
            'baby let me sing to you tonight',
            'the feeling in my chest ignites the light',
            'every word i say is from the soul',
            'the music makes the broken whole',
            'the spirit moving beyond control',
        ],
        verses: [
            'singing from the deepest part of me',
            'soul music setting spirits free',
            'the melody - is all i need to be',
            'feel the rhythm running through the key',
            'my heart is open can you see',
            'the notes are flowing like the sea',
            'soul music is the remedy',
            'the truth is in the harmony',
            'the organ playing soft and low',
            'soul music letting feelings flow',
            'the spirit of the afterglow',
            'this love will always grow and grow',
            'the backing vocals lift me high',
            'soul music reaching to the sky',
            'every note a reason why',
            'the feeling never says goodbye',
            'the horns are blowing sweet and clean',
            'the prettiest music ever seen',
            'soul rhythms running evergreen',
            'the deepest feeling in between',
            'my voice is trembling with the truth',
            'soul music speaking to the youth',
            'the spirit echoing in the booth',
            'every note is living proof',
            'the tambourine is keeping time',
            'soul music in the key of mine',
            'the feeling is almost divine',
            'the spirit and the song combine',
            'the bassline walking step by step',
            'soul music is what we accept',
            'the spirit moving with each breath',
            'this love will last beyond the death',
            'the choir singing from the heart',
            'soul music is the finest art',
            'the feeling from the very start',
            'the spirit pulling worlds apart',
            'the groove is deep the pocket tight',
            'soul music burning through the night',
            'every word is shining bright',
            'the feeling in my soul ignites',
            'the melody is heaven sent',
            'soul music is the sentiment',
            'the spirit flowing without relent',
            'every note is what i meant',
            'my heart is overflowing now',
            'soul music showing me just how',
            'the spirit speaking through the vow',
            'the rhythm taking final bow',
        ],
        bridges: [
            'my soul is yours and yours is mine',
            'the music flowing like the wine',
            'every note along the line',
            'soul music standing test of time',
        ],
        hooks: [
            'feel my soul feel my heart tonight',
            'the music shining burning bright',
            'soul to soul we hold on tight',
            'everything is going to be alright',
        ],
    },

    // =====================================================================
    // NEW GENRE: BLUES
    // =====================================================================
    blues: {
        themes: ['sorrow', 'heartbreak', 'whiskey', 'road', 'redemption', 'loss', 'pain', 'longing', 'night', 'crossroads'],
        openers: [
            'woke up this morning feeling blue',
            'the highway stretching cold and true',
            'my baby left me nothing new',
            'the whiskey glass is half way through',
            'the crossroads calling what to do',
            'the delta blues are coming through',
            'another sleepless night i knew',
            'the train is gone the sky turned blue',
            'the rain keeps falling nothing new',
            'my heart is broken tried and true',
            'twelve bars of sorrow deep and wide',
            'the blues is flowing like the tide',
            'my baby gone and my hands are tied',
            'the pain inside i cannot hide',
            'sitting on the porch the sun has died',
        ],
        verses: [
            'the guitar crying in the dark',
            'the blues is leaving every mark',
            'from sunset till the morning lark',
            'my soul is burning like a spark',
            'the whiskey bottle almost dry',
            'the blues will never say goodbye',
            'beneath the cold and heavy sky',
            'a broken man i wonder why',
            'the crossroads calling in the night',
            'the blues is burning burning bright',
            'the devil standing on the right',
            'my soul is heavy in the fight',
            'twelve bars of pain and nothing more',
            'the blues is knocking at my door',
            'my heart is broken to the core',
            'been down this road so many times before',
            'the slide guitar is weeping slow',
            'the blues is all i need to know',
            'the river singing soft and low',
            'the pain inside continues to grow',
            'another night of drinking alone',
            'the blues is cutting to the bone',
            'the jukebox playing monotone',
            'the highway leading me back home',
            'the harmonica is crying out',
            'the blues is what its all about',
            'the pain inside there is no doubt',
            'the whiskey burning in my mouth',
            'the moonshine shining on the porch',
            'the blues is lighting like a torch',
            'my heart is burning and its scorched',
            'the feeling cannot be divorced',
            'the bottleneck is sliding down',
            'the blues is living in this town',
            'my heart is heavy like a crown',
            'the tears are falling dripping down',
            'the delta mud beneath my feet',
            'the blues is playing in the street',
            'the heartache and the summer heat',
            'the twelve bar shuffle on repeat',
        ],
        bridges: [
            'the blues dont care about your name',
            'every broken heart will feel the same',
            'the whiskey burns just like the flame',
            'the crossroads calling stake your claim',
        ],
        hooks: [
            'got the blues got the blues tonight',
            'the whiskey burns the feeling bites',
            'twelve bars of sorrow burning bright',
            'the blues is all i have tonight',
        ],
    },

    // =====================================================================
    // NEW GENRE: ALTERNATIVE
    // =====================================================================
    alternative: {
        themes: ['identity', 'alienation', 'searching', 'meaning', 'outsider', 'change', 'reality', 'chaos', 'wonder', 'truth'],
        openers: [
            'somewhere between the static and the sound',
            'the walls are closing but i hold my ground',
            'everything is upside down',
            'lost inside the signal and the noise',
            'we traded in our future for our toys',
            'the silence screaming in the void',
            'i found myself inside the chaos',
            'between the lines is where we live',
            'reality is relative',
            'the universe is asking if we give',
            'the frequency is changing can you hear',
            'the signals fading year by year',
            'between the static something clear',
            'the answers always disappear',
            'we built a world from nothing here',
        ],
        verses: [
            'the television static fills my brain',
            'alternative to all the pain',
            'the frequency is going insane',
            'between the signal and the rain',
            'we colored outside every line',
            'the ordinary left behind',
            'alternative by our design',
            'the different is our paradigm',
            'the feedback loop is ringing loud',
            'standing separate from the crowd',
            'alternative and standing proud',
            'the signal breaking through the cloud',
            'the vinyl spinning on the floor',
            'alternative to all before',
            'the meaning hidden at the core',
            'we always wanted something more',
            'between the lines of black and white',
            'alternative to wrong and right',
            'the spectrum bending in the light',
            'every shade a different sight',
            'the indie label underground',
            'alternative the sweetest sound',
            'the outsiders have found the ground',
            'the different making waves around',
            'we painted murals on the wall',
            'alternative to standing tall',
            'the beautiful within the small',
            'the meaning found within the fall',
            'the basement shows the sweat the tears',
            'alternative beyond the years',
            'the music conquering the fears',
            'the signal ringing in my ears',
            'we took the road less traveled down',
            'alternative to every crown',
            'the beauty in the broken town',
            'the meaning hiding underground',
            'the distortion is the truth',
            'alternative living in the booth',
            'the signal sending living proof',
            'the frequency beneath the roof',
        ],
        bridges: [
            'we are the signal in the noise',
            'alternative the realest choice',
            'the frequency becomes the voice',
            'the different ones who still rejoice',
        ],
        hooks: [
            'between the static and the sound',
            'alternative the lost is found',
            'the signal breaking through the ground',
            'we built a world from nothing now',
        ],
    },

    // =====================================================================
    // NEW GENRE: GRUNGE
    // =====================================================================
    grunge: {
        themes: ['apathy', 'rage', 'despair', 'authenticity', 'alienation', 'self-destruction', 'rain', 'dirt', 'truth', 'noise'],
        openers: [
            'the rain is falling in seattle grey',
            'the flannel stained with yesterday',
            'another wasted broken day',
            'the feedback screaming come what may',
            'the apathy is here to stay',
            'i dont care what they all say',
            'the noise is all i need today',
            'the dirt beneath the beautiful decay',
            'the amplifier blowing in the rain',
            'the broken strings the broken brain',
            'the beautiful inside the pain',
            'the grunge is flowing through my vein',
        ],
        verses: [
            'the distortion pedal screaming loud',
            'another face inside the crowd',
            'the rain is falling like a shroud',
            'the apathy has me endowed',
            'the flannel torn the jeans are ripped',
            'the basement show the speakers flipped',
            'the feedback loop has got me gripped',
            'the beautiful decay has dripped',
            'i dont pretend to have the answers now',
            'the noise is all i can allow',
            'the rain is beading on my brow',
            'the amplifier taking its final bow',
            'the coffee cold the sky is grey',
            'the grunge is here its here to stay',
            'the beautiful in the decay',
            'another cold november day',
            'the power chords the dropped d string',
            'the grunge is everything',
            'the feedback loop has got its sting',
            'the beautiful and suffering',
            'the basement smells of sweat and smoke',
            'the microphone about to choke',
            'the amplifier almost broke',
            'the grunge is real and thats no joke',
            'the distortion heavy like the sky',
            'the rain is falling wonder why',
            'the grunge is screaming do or die',
            'the beautiful inside the cry',
            'the venue stinks the floor is wet',
            'the grunge is all were going to get',
            'the feedback ringing no regret',
            'the best is yet the best is yet',
        ],
        bridges: [
            'the rain will wash it all away',
            'the grunge is here another day',
            'the beautiful inside decay',
            'the noise the truth the only way',
        ],
        hooks: [
            'the rain is falling falling down',
            'the grunge is king of every town',
            'the noise the truth the underground',
            'the beautiful decay we found',
        ],
    },

    // =====================================================================
    // NEW GENRE: EMO
    // =====================================================================
    emo: {
        themes: ['heartbreak', 'vulnerability', 'tears', 'loneliness', 'overthinking', 'diary', 'darkness', 'confession', 'memory', 'scars'],
        openers: [
            'the pages of my diary are stained',
            'every feeling that i ever contained',
            'the tears i cried could fill a lake',
            'my heart is glass and its about to break',
            'the mascara running down my face',
            'i disappear without a trace',
            'the autumn leaves are falling down',
            'my heart is wearing thorns not crowns',
            'the night is long the pillow stained',
            'every piece of me is drained',
            'the notebook filled with all my pain',
            'the memories are pouring rain',
        ],
        verses: [
            'the black eyeliner running down my cheek',
            'too broken and too scared to speak',
            'the feeling leaving me so weak',
            'another lonely miserable week',
            'the diary pages filled with tears',
            'the overthinking and the fears',
            'the loneliness across the years',
            'the sadness ringing in my ears',
            'my heart is shattered on the floor',
            'the pieces scattered by the door',
            'i dont know what im living for',
            'the emptiness is at my core',
            'the autumn wind is blowing cold',
            'the story of the heart retold',
            'the loneliness is getting old',
            'the feelings that i always hold',
            'the mixtape playing on repeat',
            'the bedroom is my only retreat',
            'the heartbreak and the bitter sweet',
            'the tears are falling at my feet',
            'the hoodie pulled over my head',
            'remembering the things you said',
            'the pillow soaking where i bled',
            'my tears on every word i read',
            'the darkness in my bedroom wall',
            'the feeling of the endless fall',
            'the loneliness the midnight call',
            'the tears that answer when you call',
            'the scars are mapping out my skin',
            'the feelings trapped beneath within',
            'the darkness and the violin',
            'the heartbreak and the discipline',
        ],
        bridges: [
            'the tears will dry i know they will',
            'the heart is broken standing still',
            'the loneliness the bitter pill',
            'but somehow i am breathing still',
        ],
        hooks: [
            'my heart is glass my heart is glass',
            'the tears are falling falling fast',
            'the memories of broken past',
            'this feeling is it going to last',
        ],
    },

    // =====================================================================
    // NEW GENRE: LOFI
    // =====================================================================
    lofi: {
        themes: ['nostalgia', 'rain', 'study', 'coffee', 'midnight', 'calm', 'reflection', 'warmth', 'simplicity', 'gentle'],
        openers: [
            'the vinyl crackle and the rain outside',
            'a cup of coffee by the windowside',
            'the midnight hours slowly glide',
            'the lo-fi beats a gentle guide',
            'the rainy evening soft and warm',
            'the vinyl static is the norm',
            'a quiet shelter from the storm',
            'the lo-fi vibes a gentle form',
            'the streetlamp glowing in the haze',
            'the quiet ending to the days',
            'the record spinning in the haze',
            'a gentle rhythm in the purple haze',
        ],
        verses: [
            'the piano keys are soft and slow',
            'the lo-fi rhythm ebbs and flows',
            'the rainy window gently glows',
            'the midnight calm that everybody knows',
            'the coffee steaming in my hand',
            'the lo-fi beats across the land',
            'the gentle rhythm soft and grand',
            'the warmth of something i understand',
            'the vinyl popping soft and sweet',
            'the lo-fi rhythm on repeat',
            'the rainy evening bittersweet',
            'the gentle warmth beneath my feet',
            'the streetlamp casting amber light',
            'the lo-fi vibes of every night',
            'the world is quiet soft and bright',
            'the gentle calm of pure delight',
            'the jazzy chords the dusty keys',
            'the lo-fi vibes the evening breeze',
            'the rainy window if you please',
            'the gentle rhythm putting minds at ease',
            'the study session late at night',
            'the lo-fi beats are shining bright',
            'the gentle calm the fading light',
            'the world is sleeping everything is right',
            'the sample chopped the beat is warm',
            'the lo-fi vibes a gentle storm',
            'the rainy evening in its form',
            'the midnight hours are reborn',
            'the dusty record spinning round',
            'the lo-fi rhythm is the sound',
            'the gentle calm that i have found',
            'the world is quiet underground',
        ],
        bridges: [
            'the rain keeps falling soft outside',
            'the lo-fi beats a gentle ride',
            'the midnight hours open wide',
            'the peaceful calm of eventide',
        ],
        hooks: [
            'lo-fi vibes and rainy nights',
            'the gentle rhythm burning bright',
            'a cup of coffee and the light',
            'the world is calm the world is right',
        ],
    },

    // =====================================================================
    // NEW GENRE: SYNTHWAVE
    // =====================================================================
    synthwave: {
        themes: ['retro', 'neon', 'night', 'future', 'driving', 'city', 'nostalgia', 'chrome', 'digital', 'sunset'],
        openers: [
            'neon lights are cutting through the dark',
            'the synthesizer leaves its mark',
            'driving fast through sunset boulevard',
            'the digital horizon guarding the heart',
            'the retrowave is pumping hard',
            'chrome reflections on the car',
            'the city lights from near and far',
            'the night is young beneath the stars',
            'the analog the digital combine',
            'the synthwave future by design',
            'the neon grid is glowing fine',
            'the retro future intertwine',
        ],
        verses: [
            'the synthesizer humming in the dark',
            'the neon city leaving every mark',
            'the retrowave igniting every spark',
            'the digital horizon like an arc',
            'the sunset burning chrome and gold',
            'the synthwave story to be told',
            'the future past and dreams of old',
            'the neon city brave and bold',
            'the drum machine is pounding hard',
            'the retrowave the avant-garde',
            'the city lights like playing cards',
            'the digital the boulevard',
            'the arpeggio is climbing high',
            'the synthwave reaching for the sky',
            'the neon lights that never die',
            'the retro future passing by',
            'the reverb echoing in the night',
            'the synthwave burning neon bright',
            'the laser beams of purple light',
            'the retro future in my sight',
            'the chrome reflection on the hood',
            'the synthwave the neighborhood',
            'the digital misunderstood',
            'the neon city dark and good',
            'the bassline pumping through the grid',
            'the synthwave and the pyramid',
            'the retro future that we hid',
            'the neon city what we did',
            'the sunset fading into night',
            'the synthwave the satellite',
            'the neon city burning bright',
            'the digital the fahrenheit',
        ],
        bridges: [
            'the neon grid extends forever more',
            'the synthwave knocking at the door',
            'the retro future we adore',
            'the digital horizon to explore',
        ],
        hooks: [
            'neon lights neon nights we ride',
            'the synthwave burning deep inside',
            'chrome and gold the neon guide',
            'the retro future side by side',
        ],
    },

    // =====================================================================
    // NEW GENRE: PHONK
    // =====================================================================
    phonk: {
        themes: ['drift', 'cowbell', 'bass', 'dark', 'speed', 'memphis', 'underground', 'night', 'aggressive', 'raw'],
        openers: [
            'the cowbell hitting hard tonight',
            'the phonk is heavy burning bright',
            'memphis bass beneath the moonlight',
            'the drift is on the tires ignite',
            'the underground is out of sight',
            'the bass so low it bends the night',
            'the phonk is raw the phonk is right',
            'the memphis sound the darkest light',
            'the cowbell ringing through the speakers',
            'the phonk is built for all the seekers',
            'the bass is shaking all the features',
            'the underground the midnight creatures',
        ],
        verses: [
            'the bass is rumbling through the floor',
            'the phonk is knocking at the door',
            'the drift is what we came here for',
            'the memphis sound forevermore',
            'the cowbell cracking in the mix',
            'the phonk is heavy no more tricks',
            'the underground is getting thick',
            'the bass so heavy gonna hit',
            'the tires screeching down the road',
            'the phonk is heavy in the zone',
            'the memphis classic fully blown',
            'the underground we call it home',
            'the reverb floating in the air',
            'the phonk is dark beyond compare',
            'the bass so low you feel it there',
            'the drift is happening i swear',
            'the 808 is shaking walls',
            'the phonk is echoing through the halls',
            'the memphis spirit never falls',
            'the underground is standing tall',
            'the chopped and screwed the vocals drown',
            'the phonk is king of every town',
            'the bass is rumbling underground',
            'the darkest deepest phonk around',
            'the drift control the wheel is turned',
            'the phonk is raw the lesson learned',
            'the memphis fire always burned',
            'the underground respect is earned',
            'the vinyl crackle on the beat',
            'the phonk is heavy on the street',
            'the bass is shaking every seat',
            'the underground can not be beat',
        ],
        bridges: [
            'the cowbell hits the bass drops low',
            'the phonk is heavy here we go',
            'the memphis vibe is all we know',
            'the underground the afterglow',
        ],
        hooks: [
            'bass bass phonk phonk drift tonight',
            'the memphis sound the darkest light',
            'the cowbell cracking burning bright',
            'the underground we own the night',
        ],
    },

    // =====================================================================
    // NEW GENRE: DANCEHALL
    // =====================================================================
    dancehall: {
        themes: ['party', 'wine', 'dance', 'island', 'vibes', 'riddim', 'fire', 'bashment', 'body', 'energy'],
        openers: [
            'the riddim dropping everybody move',
            'dancehall vibes are in the groove',
            'the bashment energy to prove',
            'wine your body smooth and smooth',
            'the selector pulling up the tune',
            'dancehall nights beneath the moon',
            'the bass is heavy coming soon',
            'the island vibes the afternoon',
            'the speaker boxes shaking ground',
            'dancehall vibes the sweetest sound',
            'the riddim spreading all around',
            'the party going down in town',
        ],
        verses: [
            'the dancehall queen upon the floor',
            'the bashment energy and more',
            'the riddim shaking to the core',
            'wine your body on the dance floor',
            'the selector spinning every track',
            'dancehall vibes and thats a fact',
            'the energy you cant hold back',
            'the riddim heavy on attack',
            'the bass is bumping heavy deep',
            'dancehall vibes the rhythm sweet',
            'the body moving to the beat',
            'the party jumping in the street',
            'the sound system is blazing hot',
            'dancehall vibes are all we got',
            'the riddim never going to stop',
            'the party rising to the top',
            'from kingston to the world we spread',
            'dancehall vibes from what we said',
            'the riddim pounding in your head',
            'the energy is seeing red',
            'the wine is moving side to side',
            'dancehall vibes the island pride',
            'the riddim flowing like the tide',
            'the party energy worldwide',
            'the speaker stack is piled high',
            'dancehall vibes beneath the sky',
            'the bashment energy will fly',
            'the party never saying bye',
            'the air horn blasting through the night',
            'dancehall vibes are burning bright',
            'the riddim heavy left and right',
            'the party going till the light',
        ],
        bridges: [
            'the dancehall vibes will never die',
            'the riddim reaching for the sky',
            'the bashment energy on high',
            'the island party standing by',
        ],
        hooks: [
            'wine wine move your body tonight',
            'dancehall vibes are burning bright',
            'the riddim heavy shining light',
            'the bashment energy ignites',
        ],
    },

    // =====================================================================
    // EXPANDED EXISTING GENRE: POP (additional phrases)
    // =====================================================================
    pop_extra: {
        verses: [
            'polaroid memories fading to gold',
            'the playlist shuffling stories untold',
            'a notification from the heart',
            'the algorithm pulled us apart',
            'screenshot the moment save the day',
            'the highlight reel is on display',
            'main character energy on parade',
            'the voicemail that you never played',
            'sending signals through the atmosphere',
            'the frequency is crystal clear',
            'a satellite - of truth and fear',
            'the orbit bringing you right here',
            'velvet midnight sugar rush',
            'the city sleeping in a hush',
            'the neon fading in a blush',
            'the feeling of the golden crush',
            'electric butterflies at dawn',
            'the curtain rises lights are shining bright',
            'the spotlight chasing what is gone',
            'the show goes on until the break of dawn',
        ],
    },

    // =====================================================================
    // EXPANDED EXISTING GENRE: HIPHOP (additional phrases)
    // =====================================================================
    hiphop_extra: {
        verses: [
            'the mic is breathing heavy bars ignite',
            'the flow is supernatural every night',
            'the punchline landing with the knockout right',
            'the cadence changing switching up the height',
            'lyrical assassin on the prowl',
            'the wordplay heavy with the growl',
            'the metaphors are foul - throw in the towel',
            'the pen is mightier than the howl',
            'the sample flipped the beat is raw',
            'the lyricism without a flaw',
            'the bars are dripping from the jaw',
            'the realest thing you ever saw',
            'the cypher spinning round and round',
            'the dopest rapper in the town',
            'the underground the proving ground',
            'the legacy the lasting sound',
            'from rags to riches pen to pad',
            'the illest verses ever had',
            'the comeback story ironclad',
            'the bars hit harder than a cad',
        ],
    },

    // =====================================================================
    // EXPANDED EXISTING GENRE: ROCK (additional phrases)
    // =====================================================================
    rock_extra: {
        verses: [
            'the amplifier cranked to ten',
            'the stadium is roaring then',
            'the power chord the rush of zen',
            'the rock anthem born again',
            'the encore shaking every wall',
            'the crowd is rising standing tall',
            'the guitar solo answering the call',
            'the rock and roll will never fall',
            'the drum fill crashing like a wave',
            'the mosh pit and the crowd we gave',
            'the rock anthem for the brave',
            'the stage is where we misbehave',
            'the tour bus rolling through the state',
            'the rock and roll will never wait',
            'the sold out show the open gate',
            'the legends never met their fate',
            'the wah pedal crying in the night',
            'the rock anthem burning bright',
            'the lighter held up in the sight',
            'the stadium erupting with delight',
        ],
    },

    // =====================================================================
    // EXPANDED EXISTING GENRE: COUNTRY (additional phrases)
    // =====================================================================
    country_extra: {
        verses: [
            'the tailgate down the bonfire lit',
            'the country road the gravel grit',
            'the boots are muddy i admit',
            'the backroads where the fireflies sit',
            'the two-step on the wooden floor',
            'the country store the general store',
            'the pickup truck forevermore',
            'the southern charm i do adore',
            'the sweet tea sweating in the glass',
            'the tractor moving through the grass',
            'the country mile the mountain pass',
            'the memories of summers past',
            'the fishing line the quiet lake',
            'the country life for goodness sake',
            'the apple pie that mama baked',
            'the memories that we have made',
            'the barn dance under harvest moon',
            'the country radio playing our tune',
            'the crickets singing afternoon',
            'the mason jar and silver spoon',
        ],
    },

    // =====================================================================
    // EXPANDED EXISTING GENRE: RNB (additional phrases)
    // =====================================================================
    rnb_extra: {
        verses: [
            'the candles flickering in the room',
            'the bass is heavy and the roses bloom',
            'the silk sheets underneath the moon',
            'the slow jam playing a perfect tune',
            'your body moving like a wave',
            'the rhythm pulling me to cave',
            'the feeling i have always craved',
            'the love that we have always saved',
            'the falsetto reaching for the high',
            'the slow burn underneath the sky',
            'the chemistry i cant deny',
            'the feeling growing multiply',
            'dim the lights and hold me close',
            'the feeling i adore the most',
            'from coast to coast you are the host',
            'the one i want to love and toast',
            'the groove is deep the bass is round',
            'the smoothest rhythm ever found',
            'the whisper of the sweetest sound',
            'the love is spinning round and round',
        ],
    },

    // =====================================================================
    // EXPANDED EXISTING GENRE: EDM (additional phrases)
    // =====================================================================
    edm_extra: {
        verses: [
            'the build is rising to the peak',
            'the bass drop making speakers freak',
            'the laser cutting through the sleek',
            'the dancefloor shaking every week',
            'the synth is pulsing through the crowd',
            'the festival is screaming loud',
            'the drops are heavy and endowed',
            'the bass is rattling every cloud',
            'the 4 on the floor the kick drum pounds',
            'the sidechain pumping electronic sounds',
            'the festival the proving grounds',
            'the bass is shaking all around',
            'the strobe is flashing on the beat',
            'the dancefloor moving to the heat',
            'the drop is coming bittersweet',
            'the bass is heavy in the street',
            'the rave is going all night long',
            'the electronic siren song',
            'the bass is heavy deep and strong',
            'the dancefloor is where we belong',
        ],
    },
};

// =====================================================================
// EXPANDED MOOD MODIFIERS
// =====================================================================
export const MOOD_MODIFIERS_EXPANSION = {
    nostalgic: {
        intensifiers: ['fondly', 'longingly', 'wistfully', 'distantly'],
        swaps: { 'today': 'yesterday', 'new': 'old', 'forward': 'backward', 'modern': 'vintage' },
        vocabulary: ['memory', 'photograph', 'cassette', 'vintage', 'sepia', 'childhood', 'flashback', 'polaroid'],
    },
    rebellious: {
        intensifiers: ['defiantly', 'boldly', 'fiercely', 'audaciously'],
        swaps: { 'follow': 'lead', 'obey': 'defy', 'quiet': 'loud', 'peace': 'chaos' },
        vocabulary: ['revolution', 'anarchy', 'uprising', 'defiance', 'riot', 'resistance', 'rebel', 'overthrow'],
    },
    mystical: {
        intensifiers: ['ethereally', 'cosmically', 'divinely', 'transcendently'],
        swaps: { 'earth': 'cosmos', 'body': 'spirit', 'sight': 'vision', 'day': 'eternity' },
        vocabulary: ['cosmos', 'oracle', 'enchantment', 'astral', 'celestial', 'ethereal', 'mystic', 'transcendent'],
    },
    confident: {
        intensifiers: ['boldly', 'powerfully', 'triumphantly', 'unstoppably'],
        swaps: { 'maybe': 'definitely', 'try': 'will', 'hope': 'know', 'wish': 'demand' },
        vocabulary: ['crown', 'throne', 'victory', 'champion', 'conquer', 'dominate', 'unstoppable', 'reign'],
    },
    vulnerable: {
        intensifiers: ['tenderly', 'softly', 'gently', 'delicately'],
        swaps: { 'strong': 'fragile', 'armor': 'skin', 'shield': 'heart', 'wall': 'window' },
        vocabulary: ['fragile', 'tender', 'exposed', 'raw', 'open', 'wounded', 'transparent', 'honest'],
    },
    euphoric: {
        intensifiers: ['ecstatically', 'blissfully', 'rapturously', 'exuberantly'],
        swaps: { 'walk': 'fly', 'ground': 'sky', 'whisper': 'scream', 'dim': 'blinding' },
        vocabulary: ['euphoria', 'ecstasy', 'bliss', 'rapture', 'transcendence', 'nirvana', 'paradise', 'heaven'],
    },
    haunting: {
        intensifiers: ['eerily', 'hauntingly', 'spectrally', 'ghostly'],
        swaps: { 'living': 'haunting', 'warm': 'cold', 'light': 'shadow', 'voice': 'whisper' },
        vocabulary: ['ghost', 'phantom', 'specter', 'shadow', 'haunt', 'echo', 'apparition', 'remnant'],
    },
    empowered: {
        intensifiers: ['fiercely', 'unapologetically', 'relentlessly', 'magnificently'],
        swaps: { 'small': 'mighty', 'weak': 'powerful', 'doubt': 'certainty', 'follow': 'lead' },
        vocabulary: ['power', 'strength', 'fearless', 'warrior', 'unstoppable', 'fierce', 'mighty', 'invincible'],
    },
};

/**
 * Merge expansion data into existing genre banks.
 * For existing genres, concatenates array fields (openers, verses, bridges, etc.)
 * For new genres, adds them directly.
 */
export function mergeGenreBanks(existing, expansion) {
    for (const [genre, data] of Object.entries(expansion)) {
        // Handle "_extra" suffix genres (merge into existing)
        const baseGenre = genre.replace(/_extra$/, '');
        if (genre.endsWith('_extra') && existing[baseGenre]) {
            for (const [key, arr] of Object.entries(data)) {
                if (Array.isArray(arr)) {
                    if (Array.isArray(existing[baseGenre][key])) {
                        existing[baseGenre][key].push(...arr);
                    } else {
                        existing[baseGenre][key] = arr;
                    }
                }
            }
        } else if (!existing[genre]) {
            // New genre — add directly
            existing[genre] = data;
        } else {
            // Existing genre — merge arrays
            for (const [key, arr] of Object.entries(data)) {
                if (Array.isArray(arr)) {
                    if (Array.isArray(existing[genre][key])) {
                        existing[genre][key].push(...arr);
                    } else {
                        existing[genre][key] = arr;
                    }
                }
            }
        }
    }
}

/**
 * Merge expansion mood modifiers into existing modifiers.
 */
export function mergeMoodModifiers(existing, expansion) {
    for (const [mood, data] of Object.entries(expansion)) {
        if (!existing[mood]) {
            existing[mood] = data;
        }
    }
}
