/**
 * HookGeneratorExpansion2 — Massive second expansion of hook templates.
 * 400+ universal hooks, 30+ per genre across 29 genres, expanded chorus
 * templates, blocklist, and variation patterns.
 */

// =====================================================================
// UNIVERSAL HOOK TEMPLATES — 420+ new templates
// =====================================================================
export const HOOK_TEMPLATES_EXPANSION2 = [
    // ---- Anthem / Empowerment (80+) ----
    'we the {adjective} ones and we don\'t {verb}',
    'stand on the {noun} and {verb} the world',
    'they can\'t {verb} what we built from {noun}',
    'crown on my {noun} {adjective} in my soul',
    'born in the {noun} raised by the {noun2}',
    'we don\'t break we {verb} through {noun}',
    'louder than the {noun} stronger than the {noun2}',
    'the {adjective} keep winning while they {verb}',
    'this is bigger than the {noun}',
    'they counted us out now we {verb} the {noun}',
    'unstoppable {adjective} {noun} forever',
    'the {noun} chose us and we {verb}',
    'watch us {verb} what they said we couldn\'t {verb2}',
    'kings and queens of the {adjective} {noun}',
    'we write our {noun} in the {noun2}',
    '{adjective} blood runs through the {noun}',
    'every scar is a {noun} every {noun2} is a crown',
    'the throne is {adjective} the {noun} is ours',
    'nothing they {verb} can shake the {noun}',
    'we {verb} mountains we {verb2} oceans',
    'our {noun} echoes through the {noun2}',
    'the fire in my {noun} won\'t {verb}',
    'legends don\'t {verb} they {verb2}',
    'this {adjective} {noun} was meant for us',
    'let them watch us {verb} the {noun}',
    'fearless {adjective} and {adjective2} inside',
    'built from the {noun} shaped by the {noun2}',
    'the anthem plays and we {verb}',
    'no limits just {adjective} {noun}',
    'the {noun} can\'t hold the {adjective}',
    'they whispered but we {verb} the {noun}',
    'rise from the {noun} like {adjective} {noun2}',
    'the world will {verb} our {noun}',
    'we carry the {noun} on our {noun2}',
    'I was born to {verb} the {adjective} {noun}',
    '{adjective} hearts will {verb} the {noun}',
    'we lit the {noun} and watched it {verb}',
    'the ceiling is the {noun} the floor is the {noun2}',
    'they said {verb} but we chose to {verb2}',
    'every {noun} we take is {adjective}',
    'the kingdom of the {adjective} {noun}',
    'no permission just {adjective} {noun}',
    'we didn\'t {verb} we {verb2} harder',
    'forged in {noun} tempered by {noun2}',
    'we are the {noun} they tried to {verb}',
    'this is our {adjective} hour',
    'write your {noun} across the {noun2}',
    'we turn the {noun} into {noun2}',
    'never kneel to the {adjective} {noun}',
    'the {adjective} ones own the {noun}',
    '{verb} your {noun} and take the {noun2}',
    'warriors of the {adjective} {noun}',
    'the empire starts with one {noun}',
    'unbreakable {adjective} and {adjective2}',
    'we {verb} together or not at all',
    'the crown fits the {adjective} ones',
    'built different born {adjective}',
    'the {noun} bends but never breaks',
    'we rewrite the {noun} every {noun2}',
    'on top of the {noun} overlooking the {noun2}',
    'they tried to {verb} the {noun} but we stayed',
    'anthem of the {adjective} {noun}s',
    'the {adjective} never {verb} in silence',
    'our {noun} speaks louder than their {noun2}',
    'we don\'t follow {noun}s we {verb} them',
    'the revolution starts with {adjective} {noun}',
    'immortal {adjective} {noun} in our veins',
    'the {noun} remembers who {verb}s',
    'unshakable {adjective} and {adjective2} always',
    'we {verb} the impossible every {noun}',
    'the underdogs own the {noun} tonight',
    'every {noun} was a battle every {noun2} a win',
    'they thought we\'d {verb} but we {verb2}',
    'champions of the {adjective} {noun}',
    'the {noun} salutes the {adjective}',
    'we {verb} the path they feared to walk',
    'victory tastes like {adjective} {noun}',
    'the roar of the {adjective} {noun}',
    'we own every {noun} every {noun2}',
    'destiny {verb}s the {adjective} {noun}',
    'the {adjective} ones always {verb}',

    // ---- Heartfelt / Emotional (60+) ----
    'I carry your {noun} in my {noun2}',
    'the {noun} we lost still {verb}s inside',
    'every {noun} I whisper is about {noun2}',
    'the {adjective} truth is I still {verb}',
    'missing you feels like {adjective} {noun}',
    'I see your {noun} in every {noun2}',
    'the silence {verb}s louder than {noun}',
    'pieces of my {noun} scattered in the {noun2}',
    'I left my {noun} where we {verb}',
    'your {adjective} {noun} haunts my {noun2}',
    'I would {verb} a thousand {noun}s for you',
    'the ghost of your {noun} still {verb}s',
    'wrapped in the {noun} of what we were',
    'I still {verb} when I hear your {noun}',
    'half of my {noun} belongs to your {noun2}',
    'the {adjective} ache of losing your {noun}',
    'I wrote your {noun} on every {noun2}',
    'the {noun} knows how much I {verb}',
    'if {noun}s could speak they\'d say your {noun2}',
    'I breathe you in like {adjective} {noun}',
    'the {noun} between us grows more {adjective}',
    'your memory is my {adjective} {noun}',
    'I held the {noun} until it broke',
    'the {adjective} part is letting the {noun} go',
    'every tear is a {noun} I gave to {noun2}',
    'the way you {verb} still moves my {noun}',
    'holding on to {adjective} {noun}s',
    'your {noun} was the map to my {noun2}',
    'the {adjective} {noun} of yesterday',
    'I built a {noun} from your {noun2}',
    'even the {noun} misses your {noun2}',
    'the goodbye was more {adjective} than the {noun}',
    'I ache inside like {adjective} {noun}',
    'you {verb} a {noun} that won\'t {verb2}',
    'the {noun} we had was {adjective} and real',
    'I painted your {noun} on my {noun2}',
    'the {adjective} wound of letting you {verb}',
    'the {noun} still echoes in the {noun2}',
    'if I could {verb} I\'d bring back {noun}',
    'your {adjective} {noun} lives inside my {noun2}',
    'the rain reminds me of your {noun}',
    'I found the {noun} where you left it',
    'the {adjective} distance between {noun} and {noun2}',
    'you were the {adjective} {noun} I ever knew',
    'I still {verb} the way you {verb2}',
    'my {noun} wears your {adjective} {noun2}',
    'the {noun} you gave me never {verb}s',
    'some {noun}s stay {adjective} forever',
    'I trace your {noun} on the {noun2}',
    'the {adjective} melody of your {noun}',
    'you left your {noun} in my {noun2}',
    'I close my eyes and {verb} your {noun}',
    'the {adjective} weight of empty {noun}',
    'your {noun} was my {adjective} anchor',
    'I keep the {noun} like a {adjective} secret',
    'even the {adjective} {noun} reminds me of you',
    'the {noun} of us is {adjective}',
    'I drew your {noun} on every {noun2}',
    'somewhere your {noun} still {verb}s',
    'the {adjective} cost of {noun}',

    // ---- Party / Energy (60+) ----
    'the {noun} goes crazy when we {verb}',
    'everybody lose your {noun} tonight',
    'we came to {verb} we came to {verb2} tonight',
    '{verb} it {verb2} it flip the {noun}',
    'this {adjective} {noun} ain\'t stopping',
    'the speakers {verb} the {noun} {verb}s',
    'it\'s going down in the {adjective} {noun}',
    'all my people {verb} the {noun}',
    'no sleep just {adjective} {noun} all night',
    'the {noun} keeps going the {noun2} keeps flowing',
    'throw your {noun} up {verb} the {noun2}',
    'we running through the {adjective} {noun}',
    'bounce bounce {verb} the {noun}',
    'the venue is {adjective} the crowd is {adjective2}',
    'pop the {noun} and {verb} the {noun2}',
    'we don\'t leave till the {noun} is over',
    'the {noun} shakes when we {verb}',
    'tonight\'s the {noun} we own the {noun2}',
    'level up the {noun} and {verb}',
    'confetti and {adjective} {noun} everywhere',
    '{adjective} energy {adjective2} vibes',
    'the afterparty is in the {noun}',
    'we {verb} so hard the {noun} trembles',
    'last call for the {adjective} {noun}',
    'the {noun} is electric the {noun2} is magnetic',
    'feeling {adjective} feeling {adjective2} tonight',
    'who needs {noun} when you got {noun2}',
    'the {noun} lit up like {adjective} {noun2}',
    'we turn the {noun} to a {noun2}',
    'wild out {verb} the {adjective} {noun}',
    'the DJ drops the {noun} we {verb}',
    'sweat dripping {noun}s hitting the {noun2}',
    'keep the {noun} going all through the {noun2}',
    'dance floor is {adjective} and so are we',
    'we made the {noun} a {adjective} memory',
    '{verb} it out {verb2} it out tonight',
    'the {noun} hits different when it\'s {adjective}',
    'one more {noun} one more {noun2}',
    'the {adjective} crowd goes up',
    'we shut the {noun} down every {noun2}',
    'this is the {adjective} {noun} of our lives',
    'the bass hits my {noun} and I {verb}',
    'nobody leaves until we {verb}',
    'bring the {noun} bring the {noun2} bring the {adjective}',
    'the {noun} pulses through my {noun2}',
    'we got the {adjective} {noun} on lock',
    'the roof is gone and we {verb}',
    'tonight we break every {noun}',
    'throw your hands up {verb} the {noun}',
    'the {noun} drops and we go {adjective}',
    'maximum {noun} maximum {noun2}',
    'we own the {noun} from dusk to {noun2}',
    '{adjective} nights and {adjective2} {noun}s',
    'this is the {noun} that never {verb}s',
    'we {verb} until the {noun} goes out',
    'the whole {noun} is {adjective} tonight',
    'vibes on {noun} energy on {noun2}',
    '{verb} like the {noun} depends on it',
    'the {adjective} {noun} never sleeps',
    'we keep the {noun} alive',

    // ---- Storytelling / Narrative (40+) ----
    'chapter one began with {adjective} {noun}',
    'the night I {verb} everything changed',
    'I walked a thousand {noun}s to find the {noun2}',
    'they told the tale of {adjective} {noun}',
    'the letter said to {verb} the {noun}',
    'once we had the {adjective} {noun}',
    'I crossed the {noun} to find your {noun2}',
    'the {adjective} {noun} of my youth',
    'I remember when the {noun} was {adjective}',
    'the {noun} began where the {noun2} ended',
    'we lost the {noun} somewhere in the {noun2}',
    'the diary reads {adjective} {noun}',
    'a photograph of {adjective} {noun}',
    'the {noun} was written in the {noun2}',
    'I found a {noun} behind the {noun2}',
    'the last page said to {verb}',
    'the road from {noun} to {noun2}',
    'once there was a {adjective} {noun}',
    'in the story of the {noun} and the {noun2}',
    'the turning point was {adjective} {noun}',
    'we watched the {noun} become the {noun2}',
    'the hero chose to {verb} the {noun}',
    'the villain was the {adjective} {noun}',
    'a scene from the {adjective} {noun}',
    'the ending was more {adjective} than the {noun}',
    'I wrote the {noun} on a {adjective} napkin',
    'the {noun} began to {verb} on the third {noun2}',
    'the prologue to the {adjective} {noun}',
    'they called it the {adjective} {noun}',
    'a flashback to the {adjective} {noun}',
    'the narrator {verb}s through the {noun}',
    'the plot twist was {adjective} {noun}',
    'from the first {noun} to the final {noun2}',
    'the {noun} unfolded like a {adjective} {noun2}',
    'we lived inside the {adjective} {noun}',
    'the credits roll on {adjective} {noun}',
    'the sequel starts with {noun} and {noun2}',
    'I played the {noun} they gave me',
    'the backstory is {adjective} {noun}',
    'fate {verb}s the {adjective} {noun}',

    // ---- Defiant / Bold (50+) ----
    'you want the {noun} come and {verb} it',
    'I don\'t bow to {adjective} {noun}',
    'the {noun} is mine don\'t {verb} it',
    'I {verb} the odds every single {noun}',
    'talk is {adjective} I {verb} the {noun}',
    'they threw the {noun} I threw it back',
    'I stand alone on {adjective} {noun}',
    'the {noun} feared what I would {verb}',
    'I chose {noun} over {noun2}',
    'no apologies for the {adjective} {noun}',
    'my {noun} hits harder than your {noun2}',
    'built on {noun} not on {noun2}',
    'I {verb} the system and the {noun}',
    'the underdog {verb}s the {noun}',
    'they called me {adjective} I called it {noun}',
    'I {verb} when they told me to {verb2}',
    'too {adjective} to {verb} too {adjective2} to fail',
    'the cage is open and I {verb}',
    'I turned the {noun} into my {noun2}',
    'no surrender just {adjective} {noun}',
    'I walk through {noun} like it\'s {noun2}',
    'they whispered {verb} I shouted {verb2}',
    'I took the {noun} they said was {adjective}',
    'the rebel in my {noun} won\'t {verb}',
    'I cut the {noun} and found the {noun2}',
    'nobody owns the {adjective} {noun} but me',
    'the {noun} they feared is what I {verb}',
    'I stare the {noun} down and never {verb}',
    'my {adjective} {noun} scares the {noun2}',
    'I {verb} walls I {verb2} chains',
    'no mercy for the {adjective} {noun}',
    'they built the {noun} to stop me I {verb} it',
    'the odds said {verb} I said {verb2}',
    'savage {adjective} and {adjective2} through the {noun}',
    'I ate the {noun} and asked for {noun2}',
    'nothing in the {noun} can {verb} me',
    'I rewrote the {noun} in my {noun2}',
    'the villain is the {adjective} {noun}',
    'I turned their {noun} into my {noun2}',
    'they\'ll remember how I {verb} the {noun}',
    'untouchable {adjective} and {adjective2}',
    'I own the {noun} they tried to {verb}',
    'the problem is I don\'t {verb}',
    'I threw the {noun} at the {noun2}',
    'run from the {adjective} {noun} if you can',
    'the {noun} trembles when I {verb}',
    'I chose {adjective} they chose {adjective2}',
    'the game changed when I {verb} the {noun}',
    'I don\'t negotiate with {adjective} {noun}',
    'they begged me to {verb} I chose to {verb2}',

    // ---- Minimalist / Punchy (30+) ----
    '{adjective} and free that\'s how we {verb}',
    'just {verb} the {noun} and breathe',
    'pure {noun} nothing else',
    'one {noun} one {noun2} one chance',
    'all gas no {noun} tonight',
    '{verb} first ask later',
    'the {noun} speaks for itself',
    '{adjective} moves only tonight',
    'straight {noun} no chaser',
    'the real ones {verb}',
    'less {noun} more {noun2}',
    '{verb} hard stay {adjective}',
    'cold {noun} hot {noun2}',
    '{adjective} {noun} period',
    'nothing but {noun} tonight',
    'raw {adjective} {noun} energy',
    'say less {verb} more',
    '{noun} over everything',
    'the {adjective} way or no way',
    '{verb} silent hit {adjective}',
    'zero {noun} maximum {noun2}',
    'all {adjective} all {noun} all day',
    'bet on the {adjective} {noun}',
    '{noun} check {noun2} check {verb} check',
    'the formula is {adjective} {noun}',
    'different {noun} same {adjective} energy',
    'we move in {adjective} silence',
    '{verb} now or never {verb2}',
    'the answer is always {noun}',
    'keep the {noun} keep the {noun2}',

    // ---- Mystery / Dark (40+) ----
    'the {noun} watches from the {noun2}',
    'I {verb} in places they can\'t see',
    'the {adjective} fog hides the {noun}',
    'mirrors show the {adjective} {noun}',
    'echoes of a {adjective} {noun}',
    'the clock stops at {adjective} {noun}',
    'ghosts of {noun} haunt the {noun2}',
    'the {noun} bleeds {adjective} {noun2}',
    'I found the {noun} in the darkest {noun2}',
    'I see right through the {adjective} {noun}',
    'the {adjective} truth lives in the {noun}',
    'something {adjective} stirs in the {noun}',
    'the shadow of my {noun} {verb}s',
    'the moon reveals the {adjective} {noun}',
    'I {verb} through the maze of {noun}',
    'the silence screams a {adjective} {noun}',
    'the raven knows the {adjective} {noun}',
    'I {verb} with the ghosts of {noun}',
    'the {adjective} {noun} pulls me under',
    'secrets written in {adjective} {noun}',
    'the labyrinth of {adjective} {noun}',
    'the {noun} opens at midnight',
    'I hear the {noun} through the {noun2}',
    'the {adjective} reflection in the {noun}',
    'corridors of {adjective} {noun}',
    'the phantom of the {adjective} {noun}',
    'the darkness has a {adjective} {noun}',
    'I {verb} where the {noun} ends',
    'the curse of the {adjective} {noun}',
    'buried beneath the {adjective} {noun}',
    'the {noun} speaks in riddles of {noun2}',
    'the cryptic {noun} of {adjective} {noun2}',
    'I traced the {noun} through the {noun2}',
    'the vault holds the {adjective} {noun}',
    'the {adjective} {noun} bleeds at dawn',
    'I wander through the {adjective} {noun}',
    'the omen of the {adjective} {noun}',
    'the {noun} was never what it {verb}',
    'the {adjective} tide swallows the {noun}',
    'the mask reveals the {adjective} {noun}',

    // ---- Romantic (40+) ----
    'you and me beneath the {adjective} {noun}',
    'I {verb} every inch of your {noun}',
    'the taste of your {adjective} {noun}',
    'pull me closer to the {noun}',
    'your {noun} is the only {noun2} I need',
    'I get lost inside your {adjective} {noun}',
    'the way your {noun} {verb}s my {noun2}',
    'tangled up in {adjective} {noun}',
    'your {adjective} {noun} is my favorite view',
    'I {verb} the way you say my {noun}',
    'one touch and the {noun} goes {adjective}',
    'our {noun} writes its own {noun2}',
    'slow dancing in the {adjective} {noun}',
    'the spark between our {noun}s',
    'you {verb} me better than the {noun}',
    'I breathe your {noun} like {adjective} air',
    'the gravity of your {adjective} {noun}',
    'you are the {adjective} {noun} in my sky',
    'I orbit around your {noun}',
    'magnetic {adjective} {noun} between us',
    'your whisper {verb}s my {noun}',
    'intertwined like {adjective} {noun}',
    'the heat of your {adjective} {noun}',
    'you color my {noun} in {adjective} shades',
    'our heartbeats sync like {adjective} {noun}',
    'I crave the {noun} of your {noun2}',
    'you {verb} the {adjective} in me',
    'stolen moments in {adjective} {noun}',
    'every kiss is a {adjective} {noun}',
    'the {noun} you gave me glows {adjective}',
    'I fall for your {adjective} {noun} every time',
    'you make the {noun} feel like {noun2}',
    'our love is a {adjective} {noun}',
    'I {verb} you like the {noun} needs {noun2}',
    'the universe put your {noun} next to mine',
    'your {adjective} {noun} is my compass',
    'we write our {noun} in {adjective} ink',
    'your {noun} tastes like {adjective} {noun2}',
    'I drown in your {adjective} {noun}',
    'the only {noun} is you and me',

    // ---- Inspirational (40+) ----
    'the sunrise waits for the {adjective} {noun}',
    'every step is closer to the {noun}',
    'the mountain bows to those who {verb}',
    'seeds of {noun} grow into {noun2}',
    'the sky opens for the {adjective}',
    'we are the {noun} we\'ve been waiting for',
    'keep the {noun} alive inside your {noun2}',
    'the {adjective} dawn follows the {noun}',
    'I planted {noun} and harvested {noun2}',
    'the road ahead is paved with {noun}',
    'even the {adjective} {noun} can {verb}',
    'the compass points toward {adjective} {noun}',
    'we turn our {noun} into {noun2}',
    'the {adjective} {noun} begins with one step',
    'wings grow from the {adjective} {noun}',
    'the lighthouse guides the {adjective} {noun}',
    'the first {noun} is always {adjective}',
    'bloom where the {noun} meets the {noun2}',
    'the horizon holds the {adjective} {noun}',
    'break the ceiling touch the {noun}',
    'the bridge between {noun} and {noun2}',
    'we plant {adjective} {noun} in the {noun2}',
    'every {noun} deserves a {adjective} ending',
    'the river finds the {noun} eventually',
    'open doors where there were {noun}s',
    'the ladder starts at {adjective} {noun}',
    'shine through the {adjective} {noun}',
    'the phoenix {verb}s from {adjective} {noun}',
    'tomorrow\'s {noun} starts with today\'s {noun2}',
    'the map inside your {noun} leads to {noun2}',
    'we climb the {noun} one {noun2} at a time',
    'the anchor lifts the {adjective} {noun} rises',
    'from {noun} to {noun2} we never stop',
    'every wall is a door to {noun}',
    'the {adjective} flame that never dies',
    'we are the {noun} in someone\'s {noun2}',
    'the storm creates the {adjective} {noun}',
    'the best {noun} starts after the {noun2}',
    'there is {noun} on the other side of {noun2}',
    'believe in the {adjective} {noun} within',

    // ---- Social Media / Modern Culture (30+) ----
    'went viral with the {adjective} {noun}',
    'double tap the {adjective} {noun}',
    'the comments say {adjective} {noun}',
    'live streaming {adjective} {noun} tonight',
    'the timeline shows {adjective} {noun}',
    'influencer of {adjective} {noun}',
    'the DM reads {adjective} {noun}',
    'ratio the {noun} with {adjective} {noun2}',
    'the feed is full of {adjective} {noun}',
    'clout chasing {adjective} {noun}',
    'the algorithm chose {adjective} {noun}',
    'content king of {adjective} {noun}',
    'the notification {verb}s {adjective}',
    'cancel culture can\'t {verb} the {noun}',
    'the hashtag is {adjective} {noun}',
    'swiped right on {adjective} {noun}',
    'the story expires but {noun} stays',
    'retweet the {adjective} {noun}',
    'the followers feel the {adjective} {noun}',
    'subscriber to {adjective} {noun}',
    'the trend is {adjective} tonight',
    'unfiltered {adjective} {noun} only',
    'the creator {verb}s the {noun}',
    'going live with {adjective} {noun}',
    'the meme became {adjective} {noun}',
    'verified {adjective} {noun} status',
    'streaming {noun} on every {noun2}',
    'the playlist hit {adjective} {noun}',
    'share the {adjective} {noun} worldwide',
    'the reel shows {adjective} truth',

    // ---- Cinematic / Epic (30+) ----
    'the credits roll on {adjective} {noun}',
    'orchestral {adjective} {noun} rising',
    'the score builds to {adjective} {noun}',
    'wide angle {adjective} {noun} shot',
    'the montage of {adjective} {noun}',
    'slow motion {adjective} {noun}',
    'the trailer drops {adjective} {noun}',
    'blockbuster {adjective} {noun} moment',
    'the scene cuts to {adjective} {noun}',
    'the director calls {adjective} {noun}',
    'cinematic {adjective} {noun} vibes',
    'the franchise of {adjective} {noun}',
    'zoom in on the {adjective} {noun}',
    'the climax hits {adjective} {noun}',
    'fade to {adjective} {noun}',
    'the soundtrack plays {adjective} {noun}',
    'box office {adjective} {noun}',
    'the sequel to {adjective} {noun}',
    'red carpet {adjective} {noun}',
    'the premiere of {adjective} {noun}',
    'IMAX {adjective} {noun} experience',
    'the stunt defies {adjective} {noun}',
    'the set design is {adjective}',
    'award winning {adjective} {noun}',
    'the dialogue is {adjective} gold',
    'standing ovation for {adjective} {noun}',
    'the close up reveals {adjective} {noun}',
    'silver screen {adjective} {noun}',
    'the spotlight hits {adjective} {noun}',
    'curtain call for {adjective} {noun}',

    // ---- Gaming / Digital (30+) ----
    'level up the {adjective} {noun}',
    'the boss drops {adjective} {noun}',
    'respawn with {adjective} {noun}',
    'the loot is {adjective} tonight',
    'GG on the {adjective} {noun}',
    'the combo breaks the {noun}',
    'clutch play {adjective} {noun}',
    'the lobby is {adjective}',
    'headshot through the {adjective} {noun}',
    'the spawn point is {adjective}',
    'ranked up to {adjective} {noun}',
    'the inventory holds {adjective} {noun}',
    'speed run through {adjective} {noun}',
    'the quest rewards {adjective} {noun}',
    'game over for {adjective} {noun}',
    'the meta shifted to {adjective} {noun}',
    'achievement unlocked {adjective} {noun}',
    'the raid begins at {adjective} {noun}',
    'legendary {adjective} {noun} drop',
    'the arena calls for {adjective} {noun}',
    'pro gamer {adjective} {noun} moves',
    'the stream goes {adjective}',
    'pixel perfect {adjective} {noun}',
    'the checkpoint saves {adjective} {noun}',
    'no scope through the {adjective} {noun}',
    'the guild chants {adjective} {noun}',
    'OP {adjective} {noun} build',
    'the leaderboard shows {adjective} {noun}',
    'new game plus {adjective} {noun}',
    'the highlight reel is {adjective}',

    // ---- Fashion / Aesthetic (20+) ----
    'dripped out in {adjective} {noun}',
    'the fit is {adjective} tonight',
    'runway ready {adjective} {noun}',
    'the threads are {adjective} and clean',
    'designer {noun} and {adjective} vibes',
    'the look is {adjective} perfection',
    'haute couture {adjective} {noun}',
    'the silhouette speaks {adjective}',
    'vintage {adjective} {noun} energy',
    'the palette is {adjective} tonight',
    'tailored to {adjective} {noun}',
    'the accessories match {adjective} {noun}',
    'streetwear {adjective} {noun} culture',
    'the fabric feels {adjective}',
    'monochrome {adjective} {noun}',
    'the collection drops {adjective} {noun}',
    'couture and {adjective} {noun}',
    'the mirror shows {adjective} art',
    'closet full of {adjective} {noun}',
    'the style is {adjective} and bold',

    // ---- Cosmic / Space (20+) ----
    'orbit the {adjective} {noun}',
    'the galaxy holds the {adjective} {noun}',
    'stardust and {adjective} {noun}',
    'the nebula paints {adjective} {noun}',
    'light years from {adjective} {noun}',
    'the cosmos calls the {adjective}',
    'zero gravity {adjective} {noun}',
    'the constellation maps {adjective} {noun}',
    'solar powered {adjective} {noun}',
    'the comet trails {adjective} {noun}',
    'interstellar {adjective} {noun} voyage',
    'the event horizon of {adjective} {noun}',
    'supernova {adjective} {noun} burst',
    'the space station orbits {adjective} {noun}',
    'dark matter and {adjective} {noun}',
    'the black hole swallows {adjective} {noun}',
    'lunar {adjective} {noun} energy',
    'the atmosphere glows {adjective}',
    'asteroid belt of {adjective} {noun}',
    'the universe expands with {adjective} {noun}',

    // ---- Nostalgia / Throwback (20+) ----
    'remember the {adjective} {noun} days',
    'throwback to the {adjective} {noun}',
    'we used to {verb} the {adjective} {noun}',
    'the old days had {adjective} {noun}',
    'rewind to the {adjective} {noun}',
    'those {adjective} {noun} summers',
    'back when the {noun} was {adjective}',
    'the mixtape plays {adjective} {noun}',
    'I miss the {adjective} {noun}',
    'vintage {adjective} {noun} energy',
    'the photograph shows {adjective} {noun}',
    'we were young and {adjective} then',
    'the memory of {adjective} {noun}',
    'once upon the {adjective} {noun}',
    'the good old {adjective} {noun}',
    'classic {adjective} {noun} feeling',
];

// =====================================================================
// GENRE-SPECIFIC HOOK TEMPLATES — 30+ per genre, 29 genres
// =====================================================================
export const GENRE_HOOK_TEMPLATES_EXPANSION2 = {
    pop: [
        'this is our {adjective} anthem tonight',
        'you make my {noun} go {adjective}',
        'I can\'t get enough of the {noun}',
        'we shine like {adjective} {noun}s',
        'call me {adjective} call me {adjective2}',
        'viral {noun} and {adjective} vibes',
        'screenshot this {adjective} {noun}',
        'the algorithm loves our {noun}',
        'trending in the {adjective} {noun}',
        'we breaking the {noun} tonight',
        'hit replay on the {adjective} {noun}',
        'the hook is {adjective} and so am I',
        'main character {noun} energy',
        'slay the {noun} own the {noun2}',
        'giving {adjective} giving {adjective2}',
        'it\'s giving {adjective} {noun}',
        'the era of {adjective} {noun}',
        'zero skips - {adjective} {noun} on repeat',
        'we on repeat like {adjective} {noun}',
        'the summer of {adjective} {noun}',
        'catchy {adjective} and {adjective2} always',
        'stuck in my head like {adjective} {noun}',
        'platinum {noun} and {adjective} vibes',
        'I got that {adjective} {noun} feeling',
        'a million {noun}s can\'t {verb} this',
        'spotlight on the {adjective} {noun}',
        'pop the {noun} like confetti',
        'daydream in {adjective} {noun}',
        'bubblegum {noun} and {adjective} {noun2}',
        'the radio plays our {adjective} {noun}',
        'candy coated {adjective} {noun}',
    ],
    hiphop: [
        'real ones {verb} the {noun}',
        'from the bottom now we {verb} the {noun}',
        'count the {noun} then {verb} the {noun2}',
        'been about the {noun} since day one',
        'run the {noun} like I own the {noun2}',
        'facts I {verb} harder than the {noun}',
        'the bars are {adjective} the flow is {adjective2}',
        'came up from the {noun} to the {noun2}',
        'the game is {adjective} and so am I',
        'whole squad {verb} the {adjective} {noun}',
        'no handouts just {adjective} {noun}',
        'flipping {noun} into {noun2}',
        'the culture {verb}s through my {noun}',
        'I put the {noun} on the map',
        'self made {adjective} {noun} energy',
        'I spit {noun} they spit {noun2}',
        'the pen is {adjective} the pad is {adjective2}',
        'legacy built on {adjective} {noun}',
        'the cipher never stops it {verb}s',
        'headphones on world off {verb} the {noun}',
        'every verse is a {adjective} {noun}',
        'flow state {adjective} and {adjective2}',
        'they bit the style I {verb} the {noun}',
        'the booth is where I {verb}',
        'mixtape {noun} album {noun2}',
        'lyrical {adjective} {noun} champion',
        'I {verb} the mic and own the {noun}',
        'sixteen bars of {adjective} {noun}',
        'the block knows my {adjective} {noun}',
        'wordplay {adjective} and {adjective2}',
        'ghostwriter couldn\'t {verb} this {noun}',
    ],
    rock: [
        'the guitar screams {adjective} {noun}',
        'amplified {adjective} {noun} tonight',
        'we mosh through the {adjective} {noun}',
        'turn the amp to {adjective} {noun}',
        'we bleed {noun} we breathe {noun2}',
        'the pit is {adjective} and alive',
        'fist in the air {verb} the {noun}',
        'power chord and {adjective} {noun}',
        'we shatter the {noun} with {noun2}',
        'the distortion feeds my {noun}',
        'stage dive into {adjective} {noun}',
        'the setlist is {adjective} tonight',
        'feedback and {adjective} {noun}',
        'the encore starts with {adjective} {noun}',
        'we burn the {noun} to the {noun2}',
        'raw and {adjective} through the {noun}',
        'the riff echoes through {adjective} {noun}',
        'bass drops through the {adjective} {noun}',
        'we rage against the {adjective} {noun}',
        'sweat and {noun} on the {noun2}',
        'the crowd surfs on {adjective} {noun}',
        'one band one {noun} one {adjective} sound',
        'headbang to the {adjective} {noun}',
        'the breakdown hits like {adjective} {noun}',
        'plugged in and {adjective} forever',
        'the anthem of the {adjective} misfits',
        'we {verb} until the strings break',
        'the {adjective} solo of a lifetime',
        'stadium {noun} arena {noun2}',
        'reverb and {adjective} {noun} forever',
        'we write the {noun} they sing the {noun2}',
    ],
    rnb: [
        'your body is a {adjective} {noun}',
        'dim the {noun} and come to {noun2}',
        'I {verb} you in the {adjective} glow',
        'satin {noun} and {adjective} {noun2}',
        'the groove is {adjective} between us',
        'I {verb} every curve of your {noun}',
        'midnight {noun} and {adjective} conversations',
        'your vibration matches my {noun}',
        'the bassline {verb}s like your {noun}',
        'candle lit {noun} and {adjective} wine',
        'your aura is {adjective} {noun}',
        'I {verb} you in slow motion',
        'velvet {noun} and {adjective} kisses',
        'the tempo of your {adjective} {noun}',
        'you harmonize with my {noun}',
        'sensual {adjective} {noun} energy',
        'your frequency is {adjective}',
        'I write {noun}s about your {noun2}',
        'the chemistry is {adjective} and real',
        'pillow talk about {adjective} {noun}',
        'your silhouette in {adjective} {noun}',
        'the rhythm of our {adjective} {noun}',
        'honey {noun} and {adjective} {noun2}',
        'I {verb} you with every {noun}',
        'the afterglow of {adjective} {noun}',
        'you make the {noun} feel {adjective}',
        'body language says {adjective} {noun}',
        'electric {noun} between our {noun2}s',
        'the way you move is {adjective}',
        'soul tie {adjective} and {adjective2}',
        'the vibe is {adjective} keep it {adjective2}',
    ],
    edm: [
        'the drop is {adjective} feel the {noun}',
        'synth wave through the {adjective} {noun}',
        'we rave until the {noun} rises',
        'the kick drum {verb}s the {noun}',
        'neon {noun} and {adjective} lights',
        'the buildup is {adjective} the drop is {adjective2}',
        'we lose ourselves in {adjective} {noun}',
        'festival of {adjective} {noun}',
        'the waveform paints the {noun}',
        'hands up for the {adjective} {noun}',
        'we ride the frequency of {noun}',
        'the crowd becomes the {adjective} {noun}',
        'euphoria in {adjective} doses',
        'the breakdown and the {adjective} {noun}',
        'laser cut through {adjective} {noun}',
        'the anthem drops at {adjective} {noun}',
        'arpeggio of {adjective} {noun}',
        'we dance on {adjective} frequencies',
        'the filter sweeps the {noun}',
        'countdown to the {adjective} {noun}',
        'megawatt {adjective} {noun} energy',
        'the oscillator hums {adjective} {noun}',
        'peak time {adjective} {noun}',
        'the festival lights up the {noun}',
        'sub bass through the {adjective} {noun}',
        'ecstatic {adjective} {noun} release',
        'the tempo rises the {noun} {verb}s',
        'unity in {adjective} {noun}',
        'the {adjective} wave carries us',
        'decibels of {adjective} {noun}',
        'the pulse of {adjective} midnight',
    ],
    jazz: [
        'the saxophone {verb}s the {adjective} {noun}',
        'cool {noun} on a {adjective} evening',
        'the swing of {adjective} {noun}',
        'blue notes and {adjective} {noun}',
        'the club is {adjective} tonight',
        'a solo through the {adjective} {noun}',
        'smoke and {adjective} {noun} in the air',
        'the improv takes us to {noun}',
        'scatting through the {adjective} {noun}',
        'the standard of {adjective} {noun}',
        'walking bass and {adjective} {noun}',
        'velvet {noun} and golden {noun2}',
        'the changes flow like {adjective} {noun}',
        'midnight set of {adjective} {noun}',
        'the quartet plays the {adjective} {noun}',
        'brushes on the {noun} like {adjective} rain',
        'the bridge resolves to {adjective} {noun}',
        'a fifth of {noun} and {adjective} keys',
        'the gig is {adjective} the crowd is {adjective2}',
        'improvisation of {adjective} {noun}',
        'the turnaround hits {adjective} {noun}',
        'bebop {noun} and {adjective} energy',
        'the vamp goes {adjective} all night',
        'cool as the {adjective} {noun}',
        'the horn section {verb}s {adjective}',
        'cocktail {noun} and {adjective} tones',
        'the groove is {adjective} the pocket is deep',
        'after hours {adjective} {noun}',
        'pentatonic {adjective} {noun}',
        'the ivory {verb}s a {adjective} {noun}',
    ],
    reggae: [
        'one {noun} one {noun2} one love',
        'the riddim {verb}s the {adjective} {noun}',
        'feel the {noun} in the {adjective} breeze',
        'irie {adjective} {noun} vibes',
        'the island holds the {adjective} {noun}',
        'roots and {adjective} {noun} forever',
        'the dub echoes through {noun}',
        'steppin with the {adjective} {noun}',
        'the skank is {adjective} tonight',
        'bless up with {adjective} {noun}',
        'the sound system {verb}s the {noun}',
        'sunshine and {adjective} {noun}',
        'the yard is {adjective} the vibe is {adjective2}',
        'bass heavy {adjective} {noun}',
        'positive {noun} and {adjective} energy',
        'the message in the {adjective} {noun}',
        'unity through {adjective} {noun}',
        'the toaster rides the {noun}',
        'uptown {noun} downtown {noun2}',
        'jah knows the {adjective} {noun}',
        'the offbeat drives the {noun}',
        'tropical {adjective} {noun} session',
        'the bubble {verb}s the {noun}',
        'conscious {adjective} {noun} always',
        'rockers and {adjective} {noun}',
        'the selector plays the {adjective} {noun}',
        'cool runnings and {adjective} {noun}',
        'the {adjective} herb and the {noun}',
        'skanking to the {adjective} {noun}',
        'the dancehall is {adjective} tonight',
    ],
    latin: [
        'the rhythm of {adjective} {noun}',
        'fuego in the {adjective} {noun}',
        'sabor and {adjective} {noun}',
        'the clave {verb}s the {noun}',
        'baila with the {adjective} {noun}',
        'caliente {adjective} {noun} tonight',
        'the timbales {verb} the {noun}',
        'fiesta of {adjective} {noun}',
        'the congas call the {adjective} {noun}',
        'passion in every {adjective} {noun}',
        'dale {verb} the {adjective} {noun}',
        'the salsa {verb}s through {noun}',
        'tropical {noun} and {adjective} heat',
        'the merengue {verb}s the {noun}',
        'corazon and {adjective} {noun}',
        'the reggaeton bumps the {noun}',
        'azucar and {adjective} {noun}',
        'the dembow rides the {noun}',
        'mi {adjective} {noun} para siempre',
        'the cumbia {verb}s the {noun}',
        'sonido and {adjective} {noun}',
        'the guaguanco of {adjective} {noun}',
        'perreo and {adjective} vibes',
        'the bongo drums {verb} {adjective}',
        'candela in the {adjective} {noun}',
        'the mambo {verb}s through {noun}',
        'rico {adjective} and {adjective2}',
        'the pachanga of {adjective} {noun}',
        'vamos {verb} the {noun}',
        'the brass {verb}s {adjective} {noun}',
    ],
    country: [
        'pick up truck and {adjective} {noun}',
        'the barn dance {verb}s all {noun}',
        'sweet as {adjective} {noun} on a hot day',
        'front porch and {adjective} {noun}',
        'the twang of {adjective} {noun}',
        'whiskey {noun} and {adjective} truth',
        'the tractor rolls through {adjective} {noun}',
        'line dancing to {adjective} {noun}',
        'the honky tonk is {adjective} tonight',
        'fishing with the {adjective} {noun}',
        'country {noun} city {noun2}',
        'the fiddle plays {adjective} {noun}',
        'the bonfire crackles {adjective} {noun}',
        'saddle up and {verb} the {noun}',
        'gravel road and {adjective} {noun}',
        'the hayride through {adjective} {noun}',
        'two step and {adjective} {noun}',
        'the county fair and {adjective} {noun}',
        'moonshine and {adjective} {noun}',
        'the rodeo of {adjective} {noun}',
        'blue jeans and {adjective} {noun}',
        'the farmhouse holds the {adjective} {noun}',
        'steel guitar and {adjective} {noun}',
        'the creek bed and {adjective} {noun}',
        'hay bales and {adjective} {noun}',
        'the sunset on {adjective} {noun}',
        'tailgate love and {adjective} {noun}',
        'the backyard is our {adjective} {noun}',
        'lemonade and {adjective} {noun}',
        'red dirt and {adjective} {noun}',
        'the campfire tells a {adjective} {noun}',
    ],
    metal: [
        'the riff descends to {adjective} {noun}',
        'blast beats through the {adjective} {noun}',
        'we forge the {noun} in {adjective} fire',
        'the growl of {adjective} {noun}',
        'double bass {verb}s the {noun}',
        'the pit opens for {adjective} {noun}',
        'wrath of the {adjective} {noun}',
        'the shred is {adjective} the tone is {adjective2}',
        'horns up for the {adjective} {noun}',
        'the breakdown splits the {noun}',
        'thunder and {adjective} {noun}',
        'we forge our {noun} in the {noun2}',
        'the fury of {adjective} {noun}',
        'iron {noun} and {adjective} will',
        'the wall of {adjective} {noun}',
        'decimation of the {adjective} {noun}',
        'the anthem of {adjective} destruction',
        'mosh into the {adjective} {noun}',
        'hellfire and {adjective} {noun}',
        'we crush the {noun} beneath {noun2}',
        'the hammer falls on {adjective} {noun}',
        'savage {noun} and {adjective} chaos',
        'the abyss holds the {adjective} {noun}',
        'relentless {adjective} {noun} attack',
        'the throne of {adjective} {noun}',
        'war paint and {adjective} {noun}',
        'galloping {noun} and {adjective} speed',
        'the venom of {adjective} {noun}',
        'death grip on the {adjective} {noun}',
        'the avalanche of {adjective} {noun}',
    ],
    punk: [
        'three chords and the {adjective} {noun}',
        'anarchy in the {adjective} {noun}',
        'we spit on the {adjective} {noun}',
        'the zine reads {adjective} {noun}',
        'DIY {noun} and {adjective} attitude',
        'no rules just {adjective} {noun}',
        'the basement show is {adjective}',
        'we break the {noun} and {verb} the rest',
        'safety pins and {adjective} {noun}',
        'the flyer said {adjective} {noun}',
        'fast loud and {adjective} always',
        'the scene is {adjective} tonight',
        'circle pit of {adjective} {noun}',
        'one two three four {verb} the {noun}',
        'the mohawk and the {adjective} {noun}',
        'anti {adjective} pro {adjective2}',
        'the garage shakes with {adjective} {noun}',
        'we don\'t sell out we {verb} the {noun}',
        'skate or {verb} the {noun}',
        'the manifesto of {adjective} {noun}',
        'power chords and {adjective} truth',
        'the underground is {adjective}',
        'we tear the {noun} apart',
        'raw and {adjective} from the start',
        'the label can\'t {verb} the {noun}',
        'spray paint and {adjective} {noun}',
        'the movement starts with {adjective} {noun}',
        'vans and {adjective} {noun} forever',
        'the pit is our {adjective} {noun}',
        'we play it {adjective} we play it loud',
    ],
    trap: [
        'the ice is on the {noun}',
        'foreign {noun} and {adjective} drip',
        'count the {noun} stack the {noun2}',
        'skrrt through the {adjective} {noun}',
        'the plug is {adjective} the {noun} is ready',
        'lean back and {verb} the {noun}',
        'the bag talks {adjective} {noun}',
        'we pull up {adjective} and {adjective2}',
        'the chain swings {adjective} {noun}',
        'finesse the {noun} finesse the {noun2}',
        'trap house {adjective} {noun}',
        'the 808 {verb}s the {noun}',
        'bussin {adjective} like the {noun}',
        'drip report {adjective} {noun}',
        'the whip is {adjective} the fit is {adjective2}',
        'slide through the {adjective} {noun}',
        'no lacking on the {adjective} {noun}',
        'the safe holds {adjective} {noun}',
        'double cup and {adjective} {noun}',
        'the perc hits the {noun}',
        'racks on the {noun} bands in the {noun2}',
        'the trap never {verb}s',
        'whole lotta {adjective} {noun}',
        'the work puts in {adjective} {noun}',
        'dripping sauce on {adjective} {noun}',
        'swerving through the {adjective} {noun}',
        'money talks {adjective} {noun}',
        'the flex is {adjective} tonight',
        'wrist game {adjective} {noun}',
        'the pack is {adjective} the route is {adjective2}',
    ],
    drill: [
        'the opp block is {adjective}',
        'spin through the {adjective} {noun}',
        'no face no {noun} no {noun2}',
        'the drill is {adjective} tonight',
        'slide with the {adjective} {noun}',
        'the score is {adjective} the {noun} is set',
        'on the corner with the {adjective} {noun}',
        'the mask is {adjective} the {noun} is loaded',
        'we don\'t talk we {verb} the {noun}',
        'the strip is {adjective} and alive',
        'no snitching just {adjective} {noun}',
        'the bally and the {adjective} {noun}',
        'active on the {adjective} {noun}',
        'the opps can\'t {verb} the {noun}',
        'field tested {adjective} {noun}',
        'the block report is {adjective}',
        'riding through the {adjective} {noun}',
        'no mercy in the {adjective} {noun}',
        'the driller {verb}s the {noun}',
        'point and {verb} the {adjective} {noun}',
        'the pattern is {adjective} {noun}',
        'cold nights and {adjective} {noun}',
        'the lineup {verb}s the {noun}',
        'certi {adjective} {noun} energy',
        'the ends are {adjective} tonight',
        'crash the {noun} exit the {noun2}',
        'the mash is {adjective} the {noun} speaks',
        'no remorse just {adjective} {noun}',
        'the getaway is {adjective}',
        'smoke and {adjective} {noun} everywhere',
    ],
    lofi: [
        'rainy {noun} and {adjective} thoughts',
        'the tape hiss of {adjective} {noun}',
        'coffee and {adjective} {noun} mornings',
        'vinyl crackle and {adjective} {noun}',
        'the window shows {adjective} {noun}',
        'study session {adjective} and calm',
        'lazy {noun} on a {adjective} afternoon',
        'the beat is {adjective} and mellow',
        'nostalgia in {adjective} {noun}',
        'the sample chops the {adjective} {noun}',
        'warm {noun} and {adjective} blankets',
        'the sunset paints {adjective} {noun}',
        'dreaming of {adjective} {noun}',
        'the city sleeps in {adjective} {noun}',
        'soft {noun} and {adjective} horizons',
        'the record spins a {adjective} {noun}',
        'amber {noun} and {adjective} tones',
        'the bookshelf holds {adjective} {noun}',
        'slow morning {adjective} {noun}',
        'the tea steams {adjective} {noun}',
        'dusty {noun} and {adjective} memories',
        'the cat naps on {adjective} {noun}',
        'golden hour {adjective} {noun}',
        'faded {noun} and {adjective} warmth',
        'the sketch pad shows {adjective} {noun}',
        'late night {adjective} {noun} sessions',
        'the jazz sample meets {adjective} {noun}',
        'peaceful {adjective} {noun} energy',
        'the playlist is {adjective} tonight',
        'drifting through {adjective} {noun}',
    ],
    indie: [
        'the thrift store holds the {adjective} {noun}',
        'polaroid of {adjective} {noun}',
        'we wander through the {adjective} {noun}',
        'the bedroom tapes of {adjective} {noun}',
        'twee {noun} and {adjective} feelings',
        'the gallery shows {adjective} {noun}',
        'cassette deck and {adjective} {noun}',
        'the zine explains the {adjective} {noun}',
        'obscure {noun} and {adjective} beauty',
        'the basement holds {adjective} {noun}',
        'misfit {noun} and {adjective} hearts',
        'the setlist is all {adjective} {noun}',
        'handmade {noun} and {adjective} vibes',
        'the b-side is {adjective} gold',
        'alternative {adjective} {noun} energy',
        'the band van and the {adjective} {noun}',
        'underground {noun} of {adjective} sound',
        'the blog post about {adjective} {noun}',
        'ironic {noun} and {adjective} charm',
        'the opener plays {adjective} {noun}',
        'DIY {adjective} {noun} sessions',
        'the house show is {adjective}',
        'reverb drenched {adjective} {noun}',
        'the chorus pedal and {adjective} {noun}',
        'lo-fi {noun} and {adjective} dreams',
        'the matinee of {adjective} {noun}',
        'bookstore {noun} and {adjective} coffee',
        'the rooftop session is {adjective}',
        'quirky {adjective} {noun} forever',
        'the EP drops {adjective} {noun}',
    ],
    folk: [
        'the banjo picks the {adjective} {noun}',
        'fireside {noun} and {adjective} tales',
        'the timber frame holds {adjective} {noun}',
        'handwritten {noun} on {adjective} paper',
        'the meadow sings a {adjective} {noun}',
        'the fiddle weeps for {adjective} {noun}',
        'harvest moon and {adjective} {noun}',
        'the well runs {adjective} and deep',
        'the quilted {noun} of {adjective} memories',
        'wandering through {adjective} {noun}',
        'the trail leads to {adjective} {noun}',
        'the almanac of {adjective} {noun}',
        'the mill turns for {adjective} {noun}',
        'the orchard bears the {adjective} {noun}',
        'weathered {noun} and {adjective} stories',
        'the homestead and the {adjective} {noun}',
        'cobblestone and {adjective} {noun}',
        'the chapel bell rings {adjective}',
        'lantern light and {adjective} {noun}',
        'the holler echoes {adjective} {noun}',
        'handpicked {noun} and {adjective} grace',
        'the ferry crosses {adjective} {noun}',
        'the loom weaves {adjective} {noun}',
        'woodland {noun} and {adjective} silence',
        'the tavern tells a {adjective} tale',
        'parchment {noun} and {adjective} ink',
        'the caravan of {adjective} {noun}',
        'the cottage holds our {adjective} {noun}',
        'rustic {adjective} {noun} forever',
        'the creek bed tells {adjective} stories',
    ],
    blues: [
        'twelve bars of {adjective} {noun}',
        'the delta {verb}s the {adjective} {noun}',
        'woke up this morning {adjective} as {noun}',
        'the slide guitar cries {adjective} {noun}',
        'crossroads of {adjective} {noun}',
        'the juke joint {verb}s {adjective}',
        'three chords of {adjective} truth',
        'my baby left me {adjective} {noun}',
        'the bottleneck slides through {noun}',
        'lowdown {adjective} {noun} blues',
        'the harp wails {adjective} {noun}',
        'dust and {adjective} {noun} on the road',
        'the turnaround is {adjective}',
        'walking bass of {adjective} {noun}',
        'ain\'t nothing but a {adjective} {noun}',
        'the shuffle {verb}s the {noun}',
        'bourbon and {adjective} {noun}',
        'the porch swing and {adjective} {noun}',
        'midnight blues and {adjective} {noun}',
        'the pickup truck of {adjective} sorrow',
        'slow burn {adjective} {noun}',
        'the harmonica tells {adjective} stories',
        'red eye and {adjective} {noun}',
        'the string bends to {adjective} {noun}',
        'gutbucket {adjective} {noun} soul',
        'the levee breaks on {adjective} {noun}',
        'swamp {noun} and {adjective} grooves',
        'the roadhouse is {adjective} tonight',
        'washboard and {adjective} {noun}',
        'the blue note rings {adjective}',
    ],
    gospel: [
        'the spirit {verb}s the {adjective} {noun}',
        'hallelujah for the {adjective} {noun}',
        'grace upon {adjective} {noun}',
        'the choir lifts the {adjective} {noun}',
        'testify about the {adjective} {noun}',
        'the altar holds our {adjective} {noun}',
        'heaven meets the {adjective} {noun}',
        'the blessing of {adjective} {noun}',
        'we praise through {adjective} {noun}',
        'the sermon speaks of {adjective} {noun}',
        'glory in the {adjective} {noun}',
        'the congregation {verb}s {adjective}',
        'surrender to the {adjective} {noun}',
        'the revival {verb}s the {noun}',
        'anointed with {adjective} {noun}',
        'the promise of {adjective} {noun}',
        'we worship in the {adjective} {noun}',
        'the hymn of {adjective} {noun}',
        'salvation through {adjective} {noun}',
        'the testimony of {adjective} {noun}',
        'we clap for the {adjective} {noun}',
        'the tabernacle {verb}s with {noun}',
        'holy {adjective} {noun} forever',
        'the offering is {adjective} {noun}',
        'the deacon sings {adjective} {noun}',
        'we lift our {noun} in {adjective} praise',
        'the covenant of {adjective} {noun}',
        'breakthrough in the {adjective} {noun}',
        'the jordan flows with {adjective} {noun}',
        'we shout for the {adjective} {noun}',
    ],
    kpop: [
        'the comeback is {adjective} tonight',
        'bias wrecking with {adjective} {noun}',
        'the choreography {verb}s the {noun}',
        'visual {adjective} {noun} energy',
        'the fan chant goes {adjective}',
        'debut stage {adjective} and {adjective2}',
        'the concept is {adjective} {noun}',
        'aegyo and {adjective} {noun}',
        'the lightstick glows {adjective}',
        'maknae power {adjective} {noun}',
        'the bridge hits {adjective} {noun}',
        'center stage {adjective} and flawless',
        'the photocards show {adjective} {noun}',
        'all-kill with {adjective} {noun}',
        'the mv drops {adjective} {noun}',
        'leader line {adjective} {noun}',
        'the pre-chorus builds {adjective}',
        'fanchant and {adjective} {noun}',
        'the title track is {adjective}',
        'ending fairy {adjective} and {adjective2}',
        'the dance break {verb}s {adjective}',
        'selca and {adjective} {noun}',
        'the encore stage is {adjective}',
        'music show {adjective} {noun} win',
        'the b-side is {adjective} perfection',
        'daesang energy {adjective} {noun}',
        'the vlive is {adjective} tonight',
        'comeback trailer {adjective} {noun}',
        'the unit slays {adjective} {noun}',
        'idol {adjective} {noun} forever',
    ],
    anime: [
        'the opening theme is {adjective} {noun}',
        'power up with {adjective} {noun}',
        'the final form is {adjective}',
        'nakama and {adjective} {noun}',
        'the tournament arc of {adjective} {noun}',
        'sakura and {adjective} {noun}',
        'the boss fight {verb}s {adjective}',
        'protagonist {adjective} {noun} energy',
        'the flashback shows {adjective} {noun}',
        'training arc {adjective} and {adjective2}',
        'the rival {verb}s the {adjective} {noun}',
        'isekai {adjective} {noun} adventure',
        'the ending credits show {adjective} {noun}',
        'kawaii {adjective} {noun} vibes',
        'the transformation is {adjective}',
        'slice of {adjective} {noun} life',
        'the sensei speaks {adjective} {noun}',
        'mecha and {adjective} {noun}',
        'the quest for {adjective} {noun}',
        'shounen {adjective} {noun} spirit',
        'the guild holds the {adjective} {noun}',
        'level up the {adjective} {noun}',
        'the dungeon hides {adjective} {noun}',
        'chibi {noun} and {adjective} charm',
        'the legendary {adjective} {noun}',
        'spirit bomb of {adjective} {noun}',
        'the chosen one {verb}s the {noun}',
        'bento box {adjective} {noun} vibes',
        'the festival episode is {adjective}',
        'ultimate {adjective} {noun} attack',
    ],
    afrobeat: [
        'the highlife {verb}s the {adjective} {noun}',
        'jollof and {adjective} {noun}',
        'the groove is {adjective} and heavy',
        'Afro {noun} and {adjective} power',
        'the talking drum speaks {adjective}',
        'wahala and {adjective} {noun}',
        'the shaku shaku is {adjective}',
        'owambe {adjective} {noun} vibes',
        'the Afro groove is {adjective}',
        'azonto through the {adjective} {noun}',
        'the horn section {verb}s {adjective}',
        'zanku and {adjective} {noun}',
        'the polyrhythm {verb}s {noun}',
        'pepper soup and {adjective} {noun}',
        'the keyboard riff is {adjective}',
        'naija {adjective} {noun} energy',
        'the palm wine flows {adjective}',
        'gbedu and {adjective} {noun}',
        'the festival is {adjective} tonight',
        'Afro soul {adjective} {noun}',
        'the baseline {verb}s {adjective}',
        'amapiano meets {adjective} {noun}',
        'the percussion is {adjective} fire',
        'jiggy {adjective} {noun} vibes',
        'the brass blows {adjective} {noun}',
        'dashiki and {adjective} {noun}',
        'the call and response is {adjective}',
        'calabash and {adjective} {noun}',
        'the ancestral {noun} {verb}s {adjective}',
        'we dance the {adjective} {noun}',
    ],
    funk: [
        'the groove locks in {adjective} {noun}',
        'slap bass and {adjective} {noun}',
        'we get funky with the {noun}',
        'the one hits and we {verb}',
        'chicken scratch and {adjective} {noun}',
        'the pocket is {adjective} and deep',
        'clavinet and {adjective} {noun}',
        'the horn stab {verb}s {adjective}',
        'bootsy and the {adjective} {noun}',
        'wah pedal through the {noun}',
        'the breakdown is {adjective} nasty',
        'we funk the {noun} up tonight',
        'syncopated {adjective} {noun}',
        'the brass section is {adjective}',
        'parliament of {adjective} {noun}',
        'tight pocket {adjective} groove',
        'the bridge is {adjective} and funky',
        'the stank face on {adjective} {noun}',
        'low end {adjective} {noun} theory',
        'the worm and the {adjective} {noun}',
        'chromatic {adjective} {noun} lines',
        'the vamp is {adjective} and sticky',
        'headnod {adjective} {noun}',
        'the chop {verb}s the {noun}',
        'polyrhythmic {adjective} {noun}',
        'nine to the bar {adjective} {noun}',
        'the turnaround is {adjective} fresh',
        'fuzz bass and {adjective} {noun}',
        'the clinic of {adjective} groove',
        'we lay the {adjective} {noun} down',
    ],
    house: [
        'four on the floor {adjective} {noun}',
        'the warehouse {verb}s {adjective}',
        'deep in the {adjective} {noun}',
        'the hi-hat rides {adjective} {noun}',
        'jack your body to the {noun}',
        'the organ stab hits {adjective}',
        'filtered {adjective} {noun} rising',
        'the disco sample loops {adjective}',
        'underground {noun} {adjective} vibes',
        'the diva sings {adjective} {noun}',
        'soulful {adjective} {noun} session',
        'the tribal beat {verb}s {noun}',
        'acid line through {adjective} {noun}',
        'the after hours are {adjective}',
        'classic {adjective} {noun} energy',
        'the piano chord lifts {adjective}',
        'Chicago {noun} and {adjective} soul',
        'the groove is {adjective} all night',
        'vocal chop {adjective} {noun}',
        'the snare rolls {adjective}',
        'garage {adjective} {noun} vibes',
        'the sub bass {verb}s {adjective}',
        'peak hour {adjective} {noun}',
        'the mix is {adjective} and seamless',
        'balearic {adjective} {noun}',
        'the terrace plays {adjective} {noun}',
        'disco infused {adjective} {noun}',
        'the kick drum is {adjective}',
        'afro house {adjective} {noun}',
        'the breakdown builds {adjective}',
    ],
    techno: [
        'the machine {verb}s {adjective} {noun}',
        'industrial {adjective} {noun} pulse',
        'the loop is {adjective} and relentless',
        'warehouse rave {adjective} {noun}',
        'the modular speaks {adjective}',
        'dark room {adjective} {noun}',
        'the sequence runs {adjective}',
        'hypnotic {adjective} {noun} trance',
        'the kick is {adjective} and punishing',
        'Berlin {noun} {adjective} nights',
        'the reverb trails {adjective} {noun}',
        'minimal {adjective} {noun} perfection',
        'the strobe hits {adjective}',
        'acid wash {adjective} {noun}',
        'the generator powers {adjective} {noun}',
        'funktional {adjective} {noun}',
        'the dancefloor is {adjective}',
        'pounding {adjective} {noun} all night',
        'the 303 squeals {adjective}',
        'hard {adjective} {noun} energy',
        'the silo echoes {adjective} {noun}',
        'tunnelvision {adjective} {noun}',
        'the polyrhythm is {adjective}',
        'stripped down {adjective} {noun}',
        'the afterparty is {adjective}',
        'driving {adjective} {noun} forever',
        'the clap echoes {adjective}',
        'analog {adjective} {noun} warmth',
        'the system is {adjective}',
        'sonic {adjective} {noun} architecture',
    ],
    dnb: [
        'the breaks hit {adjective} {noun}',
        'amen break {adjective} and chopped',
        'jungle {noun} {adjective} vibes',
        'the reese bass {verb}s {noun}',
        'step up in the {adjective} {noun}',
        'liquid {adjective} {noun} flowing',
        'the roller is {adjective} tonight',
        'neurofunk {adjective} {noun}',
        'the halftime drops {adjective}',
        'two step and {adjective} {noun}',
        'the MC rides the {noun}',
        'tearout {adjective} {noun} energy',
        'the amens chop {adjective}',
        'hospital {adjective} {noun} vibes',
        'the bass face is {adjective}',
        'jump up {adjective} {noun}',
        'the sub {verb}s {adjective}',
        'minimal {adjective} {noun} rollers',
        'the snare rush is {adjective}',
        'dancefloor {adjective} {noun}',
        'the intro builds {adjective}',
        'heavyweight {adjective} {noun}',
        'the double drop is {adjective}',
        'atmospheric {adjective} {noun}',
        'the vocal cuts {adjective}',
        'selecta spin the {adjective} {noun}',
        'the session is {adjective}',
        'ragga {adjective} {noun} jungle',
        'the rave alarm hits {adjective}',
        'massive {adjective} {noun} sound',
    ],
    dubstep: [
        'the wobble {verb}s {adjective} {noun}',
        'filthy {adjective} {noun} bass',
        'the drop is {adjective} tonight',
        'wub wub {adjective} {noun}',
        'the riddim is {adjective}',
        'earthquake {adjective} {noun}',
        'the growl bass {verb}s {noun}',
        'headbanger {adjective} {noun}',
        'the halfstep grooves {adjective}',
        'tearout {adjective} {noun} madness',
        'the midrange is {adjective}',
        'speaker shattering {adjective} {noun}',
        'the filth is {adjective} and heavy',
        'wobble house {adjective} {noun}',
        'the brostep hits {adjective}',
        'deep {adjective} {noun} meditation',
        'the future bass {verb}s {adjective}',
        'robotic {adjective} {noun} sounds',
        'the neuro bass is {adjective}',
        'skrillex-level {adjective} {noun}',
        'the laser bass cuts {adjective}',
        'mechanical {adjective} {noun}',
        'the siren calls {adjective}',
        'modulated {adjective} {noun}',
        'the snare is {adjective} and sharp',
        'dub plates {adjective} {noun}',
        'the frequency is {adjective}',
        'subatomic {adjective} {noun}',
        'the LFO sweeps {adjective}',
        'devastating {adjective} {noun} drop',
    ],
    synthwave: [
        'neon {noun} and {adjective} chrome',
        'the retrowave {verb}s {adjective}',
        'midnight {adjective} {noun} drive',
        'the grid unfolds {adjective} {noun}',
        'outrun {adjective} {noun} sunset',
        'cyberpunk {adjective} {noun} nights',
        'the arpeggiator plays {adjective}',
        'chrome {noun} on {adjective} horizon',
        'the VHS tracks {adjective} {noun}',
        'laser grid and {adjective} {noun}',
        'the synth pad glows {adjective}',
        'retrograde {adjective} {noun}',
        'the freeway is {adjective} tonight',
        'digital {adjective} {noun} sunset',
        'the palm trees line {adjective} {noun}',
        'cassette dreams of {adjective} {noun}',
        'the dashboard reads {adjective}',
        'electric {adjective} {noun} highway',
        'the scanner reveals {adjective} {noun}',
        'turbo {adjective} {noun} energy',
        'the sunset fades {adjective}',
        'analog {adjective} {noun} future',
        'the cityscape glows {adjective}',
        'retro {adjective} {noun} forever',
        'the sequencer plays {adjective}',
        'nightcrawler {adjective} {noun}',
        'the horizon burns {adjective}',
        'chromatic {adjective} {noun} dreams',
        'the tape deck is {adjective}',
        'future nostalgia {adjective} {noun}',
    ],
    vaporwave: [
        'aesthetic {adjective} {noun} forever',
        'the mall echoes {adjective} {noun}',
        'slowed down {adjective} {noun}',
        'marble {noun} and {adjective} columns',
        'the plaza holds {adjective} {noun}',
        'late night {adjective} {noun} shopping',
        'the elevator plays {adjective} {noun}',
        'pastel {adjective} {noun} dreams',
        'the fountain drips {adjective}',
        'corporate {adjective} {noun}',
        'the lobby music is {adjective}',
        'tropical {adjective} {noun} resort',
        'the screensaver shows {adjective} {noun}',
        'smooth {adjective} {noun} jazz fusion',
        'the ad break plays {adjective}',
        'sunset {adjective} {noun} boulevard',
        'the hologram is {adjective}',
        'consumer {adjective} {noun}',
        'the dial-up sings {adjective}',
        'nostalgic {adjective} {noun}',
        'the windows chime {adjective}',
        'virtual {adjective} {noun} paradise',
        'the broadcast is {adjective}',
        'floral {adjective} {noun} shoppe',
        'the statue watches {adjective}',
        'macintosh plus {adjective} {noun}',
        'the sunset loops {adjective}',
        'digital {adjective} {noun} paradise',
        'the pool shimmers {adjective}',
        'remembered {adjective} {noun} dreams',
    ],
    phonk: [
        'cowbell and {adjective} {noun}',
        'the Memphis tape {verb}s {noun}',
        'drifting through {adjective} {noun}',
        'the trunk rattles {adjective}',
        'phonk {adjective} {noun} energy',
        'the sample chops {adjective}',
        'bass boosted {adjective} {noun}',
        'the horror sample {verb}s {noun}',
        'slide in the {adjective} {noun}',
        'the 808 slides {adjective}',
        'gym pump {adjective} {noun}',
        'the vocal sample is {adjective}',
        'dark {adjective} {noun} phonk',
        'the drift hits {adjective}',
        'underground {adjective} {noun} vibes',
        'the breakdown is {adjective}',
        'cowbell anthem {adjective} {noun}',
        'the reverb swallows {adjective} {noun}',
        'sigma {adjective} {noun} grindset',
        'the chopped vocal {verb}s {noun}',
        'lo-fi {adjective} {noun} grit',
        'the subs rattle {adjective}',
        'midnight {adjective} {noun} cruise',
        'the distortion adds {adjective} {noun}',
        'ghostly {adjective} {noun}',
        'the bass cannon is {adjective}',
        'graveyard {adjective} {noun} shift',
        'the tape deck warps {adjective}',
        'raw {adjective} {noun} phonk',
        'the ride cymbal ticks {adjective}',
    ],
    // Additional genre expansions for broader coverage
    ambient: [
        'the drone expands {adjective} {noun}',
        'floating through {adjective} {noun}',
        'the texture is {adjective} and wide',
        'reverb ocean of {adjective} {noun}',
        'ethereal {adjective} {noun} layers',
        'the pad swells {adjective}',
        'infinite {adjective} {noun} space',
        'the shimmer of {adjective} {noun}',
        'dissolving into {adjective} {noun}',
        'the frequency hums {adjective}',
        'weightless {adjective} {noun} drift',
        'the atmosphere holds {adjective} {noun}',
        'glacial {adjective} {noun} movement',
        'the overtones ring {adjective}',
        'suspended in {adjective} {noun}',
        'the wash of {adjective} {noun}',
        'breathe the {adjective} {noun} in',
        'the horizon dissolves {adjective}',
        'crystalline {adjective} {noun}',
        'the space between {adjective} {noun}',
        'zero point {adjective} {noun}',
        'the stillness speaks {adjective}',
        'cascading {adjective} {noun}',
        'the expanse is {adjective}',
        'translucent {adjective} {noun}',
        'the echo fades {adjective}',
        'prismatic {adjective} {noun}',
        'the void fills with {adjective} {noun}',
        'serene {adjective} {noun} currents',
        'the light refracts {adjective}',
    ],
    soul: [
        'the soul {verb}s through the {noun}',
        'deep inside the {adjective} {noun}',
        'the organ plays {adjective} {noun}',
        'testify about {adjective} {noun}',
        'the groove is {adjective} and true',
        'Motown {noun} and {adjective} vibes',
        'the bridge lifts {adjective} {noun}',
        'raw emotion {adjective} and real',
        'the falsetto hits {adjective}',
        'soulful {adjective} {noun} confession',
        'the backing vocals sing {adjective}',
        'heartfelt {adjective} {noun} delivered',
        'the rhythm section is {adjective}',
        'conviction in {adjective} {noun}',
        'the verse confesses {adjective} {noun}',
        'vinyl soul {adjective} {noun}',
        'the brass accompanies {adjective} {noun}',
        'electric {adjective} {noun} piano',
        'the audience feels {adjective}',
        'church raised {adjective} {noun}',
        'the adlib speaks {adjective}',
        'melisma through {adjective} {noun}',
        'the arrangement is {adjective}',
        'classic soul {adjective} {noun}',
        'the hook resolves {adjective}',
        'powerful {adjective} {noun} delivery',
        'the session {verb}s {adjective}',
        'satin {adjective} {noun} smooth',
        'the vibrato {verb}s {adjective}',
        'timeless {adjective} {noun} music',
    ],
    disco: [
        'the mirror ball spins {adjective} {noun}',
        'boogie down with {adjective} {noun}',
        'the bassline walks {adjective}',
        'hustle through the {adjective} {noun}',
        'the strings swell {adjective} {noun}',
        'get on the floor {verb} {adjective}',
        'the groove is {adjective} tonight',
        'four on the floor {adjective} {noun}',
        'Saturday night {adjective} {noun}',
        'the diva belts {adjective} {noun}',
        'glitter and {adjective} {noun}',
        'the horn section blasts {adjective}',
        'funky {adjective} {noun} rhythm',
        'the DJ spins {adjective} {noun}',
        'platform shoes and {adjective} {noun}',
        'the light show is {adjective}',
        'dancing queen of {adjective} {noun}',
        'the orchestra hits {adjective}',
        'bell bottoms and {adjective} {noun}',
        'the conga line {verb}s {adjective}',
        'roller disco {adjective} {noun}',
        'the clap track {verb}s {adjective}',
        'neon lights and {adjective} {noun}',
        'the hi-hat sizzles {adjective}',
        'polyester {adjective} {noun}',
        'the chorus lifts {adjective}',
        'dance marathon {adjective} {noun}',
        'the breakdown grooves {adjective}',
        'midnight {adjective} {noun} fever',
        'the encore is {adjective}',
    ],
    classical: [
        'the symphony {verb}s {adjective} {noun}',
        'allegro through {adjective} {noun}',
        'the concerto speaks {adjective}',
        'fortissimo {adjective} {noun}',
        'the movement resolves {adjective}',
        'crescendo of {adjective} {noun}',
        'the opus is {adjective} and grand',
        'virtuoso {adjective} {noun}',
        'the coda brings {adjective} {noun}',
        'pianissimo {adjective} {noun}',
        'the overture begins {adjective}',
        'chamber {adjective} {noun} music',
        'the fugue weaves {adjective} {noun}',
        'sonata of {adjective} {noun}',
        'the cadenza is {adjective}',
        'orchestral {adjective} {noun} power',
        'the encore demands {adjective}',
        'maestro of {adjective} {noun}',
        'the vibrato speaks {adjective}',
        'adagio {adjective} {noun}',
        'the staccato hits {adjective}',
        'legato through {adjective} {noun}',
        'the aria soars {adjective}',
        'baroque {adjective} {noun}',
        'the prelude opens {adjective}',
        'nocturne of {adjective} {noun}',
        'the ensemble plays {adjective}',
        'romantic era {adjective} {noun}',
        'the finale is {adjective}',
        'symphonic {adjective} {noun} triumph',
    ],
};

// =====================================================================
// CHORUS NOUN TEMPLATES — 50+ new
// =====================================================================
export const CHORUS_NOUN_TEMPLATES_EXPANSION2 = [
    'we command the {rhyme}',
    'the world revolves around the {rhyme}',
    'I became the {rhyme}',
    'nothing survives without the {rhyme}',
    'the key unlocks the {rhyme}',
    'we navigate through the {rhyme}',
    'they bowed before the {rhyme}',
    'the summit reveals the {rhyme}',
    'I traded everything for the {rhyme}',
    'the monument stands for the {rhyme}',
    'we sculpted the {rhyme}',
    'the blueprint shows the {rhyme}',
    'I discovered the {rhyme}',
    'the compass leads to {rhyme}',
    'we harvested the {rhyme}',
    'the kingdom crumbles without the {rhyme}',
    'I surrendered to the {rhyme}',
    'the prophecy speaks of {rhyme}',
    'we awakened the {rhyme}',
    'the archive holds the {rhyme}',
    'I memorized every {rhyme}',
    'the signal points to {rhyme}',
    'we engineered the {rhyme}',
    'the equation solves for {rhyme}',
    'I invested in the {rhyme}',
    'the mirror reflects the {rhyme}',
    'we protected the {rhyme}',
    'the current flows toward {rhyme}',
    'I demolished the {rhyme}',
    'the foundation rests on {rhyme}',
    'we resurrected the {rhyme}',
    'the signature reads {rhyme}',
    'I fashioned a new {rhyme}',
    'the gallery displays the {rhyme}',
    'we decoded the {rhyme}',
    'the telescope reveals the {rhyme}',
    'I guarded the {rhyme}',
    'the recipe calls for {rhyme}',
    'we manufactured the {rhyme}',
    'the headline reads {rhyme}',
    'I embraced the {rhyme}',
    'the satellite orbits the {rhyme}',
    'we amplified the {rhyme}',
    'the mosaic paints the {rhyme}',
    'I channeled the {rhyme}',
    'the revolution needs the {rhyme}',
    'we inherited the {rhyme}',
    'the vessel carries the {rhyme}',
    'I unlocked the {rhyme}',
    'the network connects the {rhyme}',
    'we broadcast the {rhyme}',
    'the summit crowns the {rhyme}',
    'I worshipped every {rhyme}',
    'the battlefield reveals the {rhyme}',
    'we transformed into {rhyme}',
    'the thunderstorm becomes the {rhyme}',
    'I sacrificed the {rhyme}',
    'the dynasty owns the {rhyme}',
    'we orchestrated the {rhyme}',
    'the masterpiece is called the {rhyme}',
    'I fortified the {rhyme}',
    'the expedition found the {rhyme}',
    'we dominated every {rhyme}',
    'the civilization built on {rhyme}',
    'I illuminated the {rhyme}',
    'the architecture frames the {rhyme}',
    'we celebrated every {rhyme}',
    'the frequency matches the {rhyme}',
    'I liberated the {rhyme}',
    'the mechanism drives the {rhyme}',
    'we gravitated toward the {rhyme}',
];

// =====================================================================
// CHORUS ADJECTIVE TEMPLATES — 30+ new
// =====================================================================
export const CHORUS_ADJ_TEMPLATES_EXPANSION2 = [
    'the moment is {rhyme}',
    'we keep it {rhyme} forever more',
    'the rhythm feels {rhyme}',
    'together we stay {rhyme}',
    'the future looks {rhyme}',
    'our bond is {rhyme} and true',
    'the path ahead is {rhyme}',
    'we burn so {rhyme} tonight',
    'the truth is {rhyme} and clear',
    'I feel {rhyme} when you\'re near',
    'the dream is {rhyme} and real',
    'we rise so {rhyme} above',
    'the sound is {rhyme} and pure',
    'I stay {rhyme} no matter what',
    'the crowd goes {rhyme} for us',
    'we made it {rhyme} tonight',
    'the vibe is {rhyme} and right',
    'I keep it {rhyme} inside',
    'the energy stays {rhyme}',
    'we feel {rhyme} together',
    'the morning looks {rhyme}',
    'I stand {rhyme} and proud',
    'the anthem sounds {rhyme}',
    'we grow {rhyme} every day',
    'the landscape is {rhyme}',
    'I breathe {rhyme} air',
    'the melody rings {rhyme}',
    'we dance so {rhyme}',
    'the legacy is {rhyme}',
    'I found my {rhyme} truth',
    'the horizon glows {rhyme}',
    'we stay so {rhyme} and free',
    'the sunrise looks {rhyme}',
    'I breathe it all so {rhyme}',
    'the scenery is {rhyme}',
    'we keep the flame {rhyme}',
    'the chorus sounds so {rhyme}',
    'I run so {rhyme} and wild',
    'the view from here is {rhyme}',
    'we celebrate the {rhyme}',
    'the empire stands {rhyme}',
    'I glow so {rhyme} tonight',
];

// =====================================================================
// CHORUS VERB TEMPLATES — 30+ new
// =====================================================================
export const CHORUS_VERB_TEMPLATES_EXPANSION2 = [
    'I finally learned to {rhyme}',
    'we refuse to {rhyme} for them',
    'the world needs us to {rhyme}',
    'I promised I would {rhyme}',
    'together we can {rhyme}',
    'they never thought we\'d {rhyme}',
    'I wake up just to {rhyme}',
    'we live and breathe and {rhyme}',
    'the mission is to {rhyme}',
    'I dare you to {rhyme}',
    'the calling is to {rhyme}',
    'we trained ourselves to {rhyme}',
    'I swore that I would {rhyme}',
    'the protocol is {rhyme}',
    'we vowed to always {rhyme}',
    'I couldn\'t help but {rhyme}',
    'the anthem tells you {rhyme}',
    'we have the will to {rhyme}',
    'I destined myself to {rhyme}',
    'the crowd begins to {rhyme}',
    'we choose to {rhyme} again',
    'I taught myself to {rhyme}',
    'the moment calls to {rhyme}',
    'we gather here to {rhyme}',
    'I continue just to {rhyme}',
    'the rhythm tells me {rhyme}',
    'we rally here to {rhyme}',
    'I sacrifice to {rhyme}',
    'the compass says to {rhyme}',
    'we decided we would {rhyme}',
    'I exist to {rhyme}',
    'the universe wants me to {rhyme}',
    'we hustled hard to {rhyme}',
    'I manifested the power to {rhyme}',
    'the struggle taught me to {rhyme}',
    'we overcame just to {rhyme}',
    'I earned the right to {rhyme}',
    'the journey forced me to {rhyme}',
    'we committed fully to {rhyme}',
    'I never stopped trying to {rhyme}',
    'the fire demands we {rhyme}',
];

// =====================================================================
// HOOK VOCAB BLOCKLIST — 100+ new words
// =====================================================================
export const HOOK_VOCAB_BLOCKLIST_EXPANSION2 = [
    // Medical / clinical
    'aneurysm', 'catheter', 'dialysis', 'gangrene', 'psoriasis',
    'hemorrhage', 'abscess', 'varicose', 'tendonitis', 'arthritis',
    'bronchitis', 'laryngitis', 'sinusitis', 'dermatitis', 'gingivitis',
    'meningitis', 'hepatitis', 'peritonitis', 'bursitis', 'colitis',
    // Office / mundane
    'invoice', 'receipt', 'memo', 'cubicle', 'briefcase',
    'filing', 'ledger', 'audit', 'compliance', 'directive',
    'quota', 'metrics', 'synergy', 'benchmark', 'deliverable',
    'stakeholder', 'onboarding', 'downsizing', 'outsourcing', 'offshoring',
    // Technical / jargon
    'firmware', 'motherboard', 'ethernet', 'defragment', 'reboot',
    'pixel', 'bitmap', 'hexadecimal', 'boolean', 'integer',
    'subroutine', 'executable', 'debugging', 'compile', 'runtime',
    'constructor', 'destructor', 'polymorphism', 'abstraction', 'instantiate',
    // Kitchen / household
    'dishrag', 'sponge', 'detergent', 'bleach', 'dustpan',
    'clothespin', 'hamper', 'dustbin', 'mildew', 'grout',
    'baseboard', 'drywall', 'shingle', 'gutter', 'downspout',
    'insulation', 'subflooring', 'caulking', 'weatherstrip', 'gasket',
    // Automotive parts
    'crankshaft', 'camshaft', 'flywheel', 'differential', 'exhaust',
    'catalytic', 'converter', 'timing', 'caliper', 'bushing',
    'strut', 'axle', 'linkage', 'solenoid', 'actuator',
    'thermocouple', 'voltmeter', 'ammeter', 'barometer', 'manometer',
    // Biology / science
    'flagellum', 'nucleotide', 'polypeptide', 'prokaryote', 'eukaryote',
    'chloroplast', 'endoplasm', 'telomere', 'centromere', 'organelle',
    // Legal / bureaucratic
    'deposition', 'affidavit', 'injunction', 'misdemeanor', 'felony',
    'arraignment', 'extradition', 'probation', 'parole', 'indictment',
    // Plumbing / trades
    'wrench', 'washer', 'flange', 'nipple', 'coupling',
    'reducer', 'elbow', 'tee', 'valve', 'sealant',
    // Food / cooking
    'spatula', 'whisk', 'ladle', 'saucepan', 'skillet',
    'casserole', 'ramekin', 'mandoline', 'zester', 'colander',
    'marinade', 'consomme', 'roux', 'béchamel', 'mirepoix',
    // Textiles / sewing
    'bobbin', 'thimble', 'darning', 'serger', 'selvage',
    'eyelet', 'grommet', 'interfacing', 'batting', 'notions',
    // Dental
    'incisor', 'molar', 'bicuspid', 'periodontal', 'gingivae',
    'enamel', 'dentin', 'canine', 'premolar', 'mandible',
    // Accounting
    'receivable', 'payable', 'accrual', 'ledger', 'fiduciary',
    'amortization', 'depreciation', 'capitalization', 'encumbrance', 'disbursement',
];

// =====================================================================
// VARIATION PATTERNS — 20+ new
// =====================================================================
export const VARIATION_PATTERNS_EXPANSION2 = [
    { type: 'prefix', additions: ['yo', 'ayo', 'woah', 'ooh', 'uh huh'] },
    { type: 'prefix', additions: ['sing it', 'say it', 'shout it', 'feel it', 'believe it'] },
    { type: 'prefix', additions: ['alright', 'okay', 'here we go', 'this is it', 'one time'] },
    { type: 'prefix', additions: ['you know', 'for real', 'no doubt', 'trust me', 'on my soul'] },
    { type: 'intensifier', additions: ['just', 'even', 'barely', 'nearly', 'almost'] },
    { type: 'intensifier', additions: ['way more', 'much more', 'far too', 'so much', 'way too'] },
    { type: 'intensifier', additions: ['straight up', 'dead', 'literally', 'actually', 'honestly'] },
    { type: 'intensifier', additions: ['low key', 'high key', 'no lie', 'on god', 'facts'] },
    { type: 'repetition', additions: ['let\'s go', 'that\'s it', 'say what', 'you feel me', 'ya heard'] },
    { type: 'repetition', additions: ['on repeat', 'all day long', 'no stopping', 'keep going', 'don\'t stop'] },
    { type: 'repetition', additions: ['turn up', 'pull up', 'run it', 'hit it', 'spin it'] },
    { type: 'repetition', additions: ['we lit', 'we up', 'we on', 'we here', 'we set'] },
    { type: 'prefix', additions: ['ladies and gentlemen', 'attention', 'welcome to', 'introducing', 'presenting'] },
    { type: 'prefix', additions: ['last time', 'first time', 'every time', 'this time', 'next time'] },
    { type: 'suffix', additions: ['yeah yeah', 'oh oh', 'na na', 'la la', 'hey hey'] },
    { type: 'suffix', additions: ['you know it', 'we own it', 'we got it', 'believe it', 'receive it'] },
    { type: 'suffix', additions: ['one more time', 'say it again', 'louder now', 'scream it', 'mean it'] },
    { type: 'suffix', additions: ['for life', 'til I die', 'no debate', 'no cap', 'on sight'] },
    { type: 'prefix', additions: ['no cap', 'big facts', 'real talk', 'straight up', 'on everything'] },
    { type: 'repetition', additions: ['worldwide', 'certified', 'amplified', 'electrified', 'verified'] },
    { type: 'intensifier', additions: ['too real', 'too live', 'too raw', 'too clean', 'too mean'] },
    { type: 'suffix', additions: ['all night long', 'from the start', 'to the end', 'without a doubt', 'in the zone'] },
    { type: 'prefix', additions: ['wait', 'hold up', 'check it', 'watch this', 'get ready'] },
    { type: 'prefix', additions: ['three two one', 'ready set', 'count it down', 'here it comes', 'and we go'] },
    { type: 'suffix', additions: ['can you feel it', 'say it loud', 'hands up now', 'here we are', 'this is us'] },
    { type: 'suffix', additions: ['ride or die', 'now or never', 'sink or swim', 'do or die', 'win or lose'] },
    { type: 'intensifier', additions: ['super', 'ultra', 'mega', 'hyper', 'extra'] },
    { type: 'intensifier', additions: ['no cap', 'on me', 'for sure', 'bet that', 'hundred percent'] },
    { type: 'repetition', additions: ['come alive', 'take flight', 'stand tall', 'break free', 'hold tight'] },
    { type: 'repetition', additions: ['once more', 'round two', 'part two', 'the sequel', 'reloaded'] },
];

// =====================================================================
// MERGE FUNCTIONS
// =====================================================================

/**
 * Merge hook template expansions into existing arrays (deduped by lowercase).
 */
export function mergeHookTemplates2(existing, expansion) {
    const set = new Set(existing.map(t => t.toLowerCase()));
    for (const t of expansion) {
        if (!set.has(t.toLowerCase())) existing.push(t);
    }
}

/**
 * Merge genre-specific hook templates.
 */
export function mergeGenreHookTemplates2(existing, expansion) {
    for (const [genre, templates] of Object.entries(expansion)) {
        if (Array.isArray(existing[genre])) {
            const set = new Set(existing[genre].map(t => t.toLowerCase()));
            for (const t of templates) {
                if (!set.has(t.toLowerCase())) existing[genre].push(t);
            }
        } else {
            existing[genre] = templates;
        }
    }
}

/**
 * Merge chorus templates (deduped by lowercase).
 */
export function mergeChorusTemplates2(existing, expansion) {
    const set = new Set(existing.map(t => t.toLowerCase()));
    for (const t of expansion) {
        if (!set.has(t.toLowerCase())) existing.push(t);
    }
}

/**
 * Merge blocklist words into existing Set.
 */
export function mergeBlocklist2(existing, expansion) {
    for (const word of expansion) existing.add(word.toLowerCase());
}
