/**
 * HookGeneratorExpansion3 — 300+ new hook templates, genre-specific hooks,
 * chorus templates, and variation patterns. Third expansion wave.
 */

// =====================================================================
// UNIVERSAL HOOK TEMPLATES — 150+ new templates
// =====================================================================
export const HOOK_TEMPLATES_EXPANSION3 = [
    // ---- Velocity / Momentum ----
    'we move too fast for the {noun}',
    'the {noun} can\'t keep up with us',
    'accelerate through the {adjective} {noun}',
    'we outrun every {adjective} {noun}',
    'the speed of {adjective} {noun}',
    'faster than the {noun} can {verb}',
    'momentum builds inside the {noun}',
    'we {verb} at the speed of {noun}',
    'no brakes on the {adjective} {noun}',
    'racing through the {noun} and {noun2}',
    'turbo charged {adjective} {noun} energy',
    'the velocity of our {noun}',
    'we sprint through {adjective} {noun}',
    'breakneck {noun} and {adjective} speed',
    'overdrive through the {adjective} {noun}',

    // ---- Gravity / Weight ----
    'heavy is the {adjective} {noun}',
    'the weight of the {noun} on my {noun2}',
    'gravity pulls us toward the {noun}',
    'I carry the {noun} on both {noun2}s',
    'the pressure builds inside the {noun}',
    'anchored to the {adjective} {noun}',
    'the {noun} weighs more than the {noun2}',
    'sinking into {adjective} {noun}',
    'the burden of the {adjective} {noun}',
    'weighted down by {noun} and {noun2}',
    'the {adjective} load we {verb} together',
    'bearing the {noun} without the {noun2}',

    // ---- Electricity / Charge ----
    'electric {noun} through my {noun2}',
    'the voltage of your {adjective} {noun}',
    'we spark like {adjective} {noun}',
    'current running through the {noun}',
    'the charge between the {noun} and {noun2}',
    'wired to the {adjective} {noun}',
    'short circuit in the {adjective} {noun}',
    'the frequency of {adjective} {noun}',
    'plugged into the {adjective} {noun}',
    'the static builds before the {noun}',
    'high voltage {adjective} {noun}',
    'lightning strikes the {adjective} {noun}',

    // ---- Construction / Building ----
    'we build the {noun} from the {noun2} up',
    'lay the {noun} pour the {noun2}',
    'the foundation of the {adjective} {noun}',
    'brick by brick we {verb} the {noun}',
    'construct the {adjective} {noun} tonight',
    'the architecture of the {noun}',
    'scaffolding around the {adjective} {noun}',
    'we raise the {noun} above the {noun2}',
    'the blueprint of our {adjective} {noun}',
    'building {noun} from {adjective} {noun2}',

    // ---- Color / Vivid ----
    'painted in {adjective} {noun}',
    'the color of the {adjective} {noun}',
    'golden {noun} and {adjective} {noun2}',
    'we bleed {adjective} {noun} tonight',
    'a canvas full of {adjective} {noun}',
    'the palette of our {noun}',
    'chromatic {adjective} {noun} falling',
    'neon {noun} against {adjective} {noun2}',
    'the shade of {adjective} {noun}',
    'tinted with {adjective} {noun}',

    // ---- Echo / Reverb ----
    'the echo of the {adjective} {noun}',
    'your {noun} reverberates through {noun2}',
    'the {noun} echoes back to me',
    'I hear the {noun} in every {noun2}',
    'the resonance of {adjective} {noun}',
    'bouncing off the {adjective} {noun}',
    'the sound of {adjective} {noun} returns',
    'reverb inside the {adjective} {noun}',

    // ---- Addiction / Obsession ----
    'I\'m hooked on the {adjective} {noun}',
    'addicted to the {noun} and the {noun2}',
    'can\'t quit the {adjective} {noun}',
    'one hit of {adjective} {noun} and I\'m gone',
    'obsessed with the {adjective} {noun}',
    'I crave the {noun} like {adjective} {noun2}',
    'the {noun} keeps pulling me back',
    'I need another dose of {noun}',
    'hopelessly drawn to the {noun}',
    'withdrawal from the {adjective} {noun}',

    // ---- Arithmetic / Calculation ----
    'the math don\'t lie on {adjective} {noun}',
    'I counted every {noun} and {noun2}',
    'the numbers add up to {adjective} {noun}',
    'multiply the {noun} by the {noun2}',
    'the equation of {adjective} {noun}',

    // ---- Territory / Ownership ----
    'this is our {adjective} territory',
    'I claimed the {noun} for the {noun2}',
    'the {noun} belongs to the {adjective}',
    'we planted our {noun} in the {noun2}',
    'this land of {adjective} {noun}',
    'the domain of {adjective} {noun}',
    'staking claim on the {adjective} {noun}',
    'the empire of {noun} and {noun2}',

    // ---- Transformation / Metamorphosis ----
    'I became the {adjective} {noun}',
    'the {noun} transforms into {noun2}',
    'watch me {verb} into the {noun}',
    'metamorphosis of {adjective} {noun}',
    'evolving past the {adjective} {noun}',
    'I shed the {noun} and found the {noun2}',
    'the {adjective} {noun} I was meant to be',
    'transforming {noun} into {noun2}',

    // ---- Contrast / Duality ----
    '{adjective} on the outside {adjective2} within',
    'the {noun} and the {noun2} collide',
    'sweet and {adjective} like the {noun}',
    'light and {adjective} in the same {noun}',
    'half {noun} half {noun2} all {adjective}',
    'the beauty and the {adjective} {noun}',
    'chaos and {adjective} {noun} together',
    'bitter {noun} and {adjective} {noun2}',

    // ---- Time / Temporal ----
    'the clock strikes {adjective} {noun}',
    'frozen in the {adjective} {noun}',
    'the moment the {noun} stood still',
    'we {verb} until the end of {noun}',
    'chasing the {noun} through the {noun2}',
    'the seconds drip like {adjective} {noun}',
    'timeless {adjective} {noun} forever',
    'the hourglass empties {adjective} {noun}',

    // ---- Prophecy / Destiny ----
    'it was written in the {noun}',
    'the stars aligned for {adjective} {noun}',
    'destiny calls the {adjective} {noun}',
    'prophecy of the {adjective} {noun}',
    'I was chosen for the {noun}',
    'the oracle speaks of {adjective} {noun}',
    'foretold inside the {adjective} {noun}',
    'the fate of {adjective} {noun}',

    // ---- Competition / Victory ----
    'we play to {verb} every {noun}',
    'the trophy goes to {adjective} {noun}',
    'champion of the {adjective} {noun}',
    'we conquered every {noun} and {noun2}',
    'the scoreboard reads {adjective} {noun}',
    'first place in {adjective} {noun}',
    'we won the {noun} we won the {noun2}',
    'the victory lap of {adjective} {noun}',

    // ---- Signal / Beacon ----
    'the signal fires up the {noun}',
    'broadcast the {adjective} {noun} worldwide',
    'the beacon of {adjective} {noun}',
    'we transmit {adjective} {noun} on every {noun2}',
    'the antenna catches {adjective} {noun}',
    'amplify the {noun} amplify the {noun2}',
    'the wavelength of {adjective} {noun}',
];

// =====================================================================
// GENRE-SPECIFIC HOOK TEMPLATES — 10+ per genre, 33 genres = 330+ total
// =====================================================================
export const GENRE_HOOK_TEMPLATES_EXPANSION3 = {
    pop: [
        'bop to the {adjective} {noun} tonight',
        'the playlist of our {adjective} {noun}',
        'instant classic {adjective} {noun}',
        'the bridge is {adjective} the chorus is {adjective2}',
        'I press repeat on {adjective} {noun}',
        'the melody sticks like {adjective} {noun}',
        'chart topping {adjective} {noun} moment',
        'we break the internet with {noun}',
        'ear candy {adjective} and {adjective2}',
        'the drop is {adjective} the pre-chorus is {adjective2}',
        'we shimmer like {adjective} {noun}',
        'this {adjective} {noun} hits different tonight',
    ],
    hiphop: [
        'the grind don\'t stop the {noun} don\'t quit',
        'I wrote my {noun} in the {noun2}',
        'bars loaded {adjective} {noun} ready',
        'the studio is {adjective} the booth is {adjective2}',
        'punchline {noun} after {adjective} {noun2}',
        'I flipped the {noun} and made it {adjective}',
        'the verse hits harder than the {noun}',
        'we stack {noun}s like we stack {noun2}s',
        'the beat knocks {adjective} through the {noun}',
        'spitting {adjective} {noun} every session',
        'I bodied every {noun} on the {noun2}',
        'the hook is {adjective} the beat is {adjective2}',
    ],
    rock: [
        'crank the volume past the {noun}',
        'the Marshall stack roars {adjective} {noun}',
        'we thrash through the {adjective} {noun}',
        'the drum fill shakes the {noun}',
        'a wall of {adjective} {noun} sound',
        'we shred the {noun} to the {noun2}',
        'the riff owns the {adjective} {noun}',
        'slam the {noun} against the {noun2}',
        'we {verb} with every {adjective} note',
        'the breakdown is {adjective} tonight',
        'cranked to eleven {adjective} {noun}',
        'the verse explodes into {adjective} {noun}',
    ],
    rnb: [
        'the groove hits my {noun} just right',
        'I {verb} you in the candlelight of {noun}',
        'smooth {adjective} {noun} and late night {noun2}',
        'the falsetto {verb}s the {adjective} {noun}',
        'our bodies speak in {adjective} {noun}',
        'the afterglow is {adjective} {noun}',
        'I whisper {adjective} {noun} in your ear',
        'the melody wraps around your {noun}',
        'the sheets remember our {adjective} {noun}',
        'I harmonize with your {adjective} {noun}',
        'the R and B of {adjective} {noun}',
        'silk and {adjective} {noun} between us',
    ],
    edm: [
        'the synthesizer {verb}s the {adjective} {noun}',
        'we peak at the {adjective} {noun}',
        'the sidechain pumps {adjective} {noun}',
        'reverb ocean of {adjective} {noun}',
        'the breakdown builds to {adjective} {noun}',
        'drop after drop of {adjective} {noun}',
        'we rave through the {adjective} {noun}',
        'the BPM rises with the {noun}',
        'supersonic {adjective} {noun} waves',
        'the crowd becomes one {adjective} {noun}',
        'bass face when the {noun} drops',
        'the after party is {adjective} {noun}',
    ],
    jazz: [
        'chromatic runs through {adjective} {noun}',
        'the snare brushes paint {adjective} {noun}',
        'a seventh chord of {adjective} {noun}',
        'the upright walks through {adjective} {noun}',
        'late set vibes of {adjective} {noun}',
        'the chart reads {adjective} {noun}',
        'a tritone sub into {adjective} {noun}',
        'the real book of {adjective} {noun}',
        'sipping {noun} under {adjective} spotlights',
        'modal {adjective} {noun} exploration',
        'the rhythm section locks in {adjective}',
        'comping through the {adjective} {noun}',
    ],
    reggae: [
        'the bassline carries {adjective} {noun}',
        'one drop of {adjective} {noun}',
        'the skank guitar hits {adjective} {noun}',
        'we chant for {adjective} {noun}',
        'the roots grow through {adjective} {noun}',
        'island breeze and {adjective} {noun}',
        'the chalice holds {adjective} {noun}',
        'dub plates of {adjective} {noun}',
        'the selector drops {adjective} {noun}',
        'vibes on vibes of {adjective} {noun}',
        'one love one {noun} one {adjective} vibe',
        'the rhythm island of {adjective} {noun}',
    ],
    latin: [
        'the conga speaks {adjective} {noun}',
        'a bolero of {adjective} {noun}',
        'the montuno {verb}s the {noun}',
        'sabrosura and {adjective} {noun}',
        'the charanga plays {adjective} {noun}',
        'ritmo {adjective} {noun} para ti',
        'the bata drums call {adjective} {noun}',
        'reggaeton pulse of {adjective} {noun}',
        'the guiro scratches {adjective} {noun}',
        'musica and {adjective} {noun} forever',
        'el ritmo is {adjective} tonight',
        'la noche and {adjective} {noun}',
    ],
    country: [
        'the flatbed carries {adjective} {noun}',
        'sweet tea porch swing {adjective} {noun}',
        'the honky tonk echoes {adjective} {noun}',
        'a two lane road of {adjective} {noun}',
        'the dobro cries {adjective} {noun}',
        'catfish and {adjective} {noun} evenings',
        'the grain silo holds the {noun}',
        'front yard firefly {adjective} {noun}',
        'the cowboy hat and {adjective} {noun}',
        'small town {adjective} {noun} pride',
        'the dance hall floor and {adjective} {noun}',
        'baptist church and {adjective} {noun}',
    ],
    metal: [
        'the tremolo picks through {adjective} {noun}',
        'we forge the {adjective} {noun} in chaos',
        'down tuned {noun} and {adjective} rage',
        'the circle pit swallows the {noun}',
        'we descend into {adjective} {noun}',
        'the chug breaks through {adjective} {noun}',
        'infernal {adjective} {noun} rising',
        'the throne room of {adjective} {noun}',
        'blood and {adjective} {noun} forever',
        'the siege of {adjective} {noun}',
        'annihilation of the {adjective} {noun}',
        'the cauldron brews {adjective} {noun}',
    ],
    punk: [
        'the squat house rocks {adjective} {noun}',
        'we stagedive into {adjective} {noun}',
        'the demo tape is {adjective} gold',
        'stolen {noun} and {adjective} freedom',
        'the all ages show is {adjective}',
        'we riot for {adjective} {noun}',
        'the sticker says {adjective} {noun}',
        'patches and {adjective} {noun} pride',
        'the house show basement {adjective} {noun}',
        'shout it out {adjective} {noun}',
        'we tear the {adjective} {noun} down',
        'the fanzine prints {adjective} truth',
    ],
    trap: [
        'the hi hat rolls {adjective} {noun}',
        'drip advisory {adjective} {noun}',
        'the block is {adjective} the {noun} is hot',
        'flex on the {adjective} {noun} tonight',
        'designer {noun} and {adjective} taste',
        'the trap shakes with {adjective} {noun}',
        'codeine {noun} and {adjective} dreams',
        'the whip spins {adjective} {noun}',
        'adlibs on the {adjective} {noun}',
        'we ball out {adjective} every {noun}',
        'the pack is {adjective} the price is {adjective2}',
        'foreign everything {adjective} {noun}',
    ],
    drill: [
        'the glide {verb}s the {adjective} {noun}',
        'sliding through the {adjective} blocks',
        'the score settles on {adjective} {noun}',
        'cold {noun} cold {noun2} cold {adjective}',
        'the strip report reads {adjective}',
        'armed with {adjective} {noun} and {noun2}',
        'the drill beat hits {adjective} {noun}',
        'posted up {adjective} on every {noun}',
        'the code is {adjective} the {noun} is silent',
        'no witnesses just {adjective} {noun}',
        'the pavement knows {adjective} {noun}',
        'we slide for {adjective} {noun}',
    ],
    lofi: [
        'the reverb fades into {adjective} {noun}',
        'rain tapping on the {adjective} {noun}',
        'sleepy {noun} and {adjective} afternoons',
        'the cassette holds {adjective} {noun}',
        'warm analog {adjective} {noun}',
        'the pencil sketch of {adjective} {noun}',
        'candle wax and {adjective} {noun}',
        'the typewriter clicks {adjective} {noun}',
        'autumn leaves and {adjective} {noun}',
        'the cat purrs on {adjective} {noun}',
        'paper airplane of {adjective} {noun}',
        'the window fog reveals {adjective} {noun}',
    ],
    indie: [
        'the open mic plays {adjective} {noun}',
        'vintage finds and {adjective} {noun}',
        'the art house shows {adjective} {noun}',
        'bicycle rides through {adjective} {noun}',
        'the journal entry says {adjective}',
        'craft coffee and {adjective} {noun}',
        'the record shop holds {adjective} {noun}',
        'daydream drifting into {adjective} {noun}',
        'the projector shows {adjective} {noun}',
        'we wander through {adjective} {noun} alone',
        'the lyric sheet reads {adjective} {noun}',
        'pawn shop {noun} and {adjective} melody',
    ],
    folk: [
        'the harmonica hums {adjective} {noun}',
        'a front porch ballad of {adjective} {noun}',
        'the dulcimer sings {adjective} {noun}',
        'the storyteller weaves {adjective} {noun}',
        'wool spun from {adjective} {noun}',
        'the windmill turns through {adjective} {noun}',
        'mason jar of {adjective} {noun}',
        'the wagon rolls through {adjective} {noun}',
        'the rocking chair and {adjective} {noun}',
        'kerosene lamp and {adjective} {noun}',
        'the psalm of {adjective} {noun}',
        'the lullaby of {adjective} {noun}',
    ],
    blues: [
        'the bend reaches {adjective} {noun}',
        'I got the {adjective} {noun} blues again',
        'the pickup howls {adjective} {noun}',
        'another {adjective} {noun} on the highway',
        'the shuffle drags through {adjective} {noun}',
        'bent string {noun} and {adjective} tears',
        'the roadside sign reads {adjective} {noun}',
        'whiskey tears and {adjective} {noun}',
        'the honky tonk lights up {adjective} {noun}',
        'broke down on the {adjective} {noun}',
        'the twelve bar truth of {adjective} {noun}',
        'callused hands and {adjective} {noun}',
    ],
    gospel: [
        'the choir lifts {adjective} {noun}',
        'hallelujah for the {adjective} {noun}',
        'the spirit fills the {adjective} {noun}',
        'grace pours like {adjective} {noun}',
        'the congregation sings {adjective} {noun}',
        'testimony of {adjective} {noun}',
        'the pulpit rings with {adjective} {noun}',
        'saved by {adjective} {noun} and love',
        'the hymn of {adjective} {noun}',
        'we praise through {adjective} {noun}',
        'the altar holds the {adjective} {noun}',
        'anointed with {adjective} {noun}',
    ],
    kpop: [
        'the choreography of {adjective} {noun}',
        'visual {noun} and {adjective} stage',
        'the comeback drops {adjective} {noun}',
        'lightstick ocean of {adjective} {noun}',
        'the fanchant goes {adjective} tonight',
        'all kill with {adjective} {noun}',
        'the concept is {adjective} and {adjective2}',
        'bias wrecker {adjective} {noun}',
        'the MV paints {adjective} {noun}',
        'synchronized {adjective} {noun} power',
        'the bridge hits {adjective} {noun}',
        'center stage {adjective} {noun} glow',
    ],
    anime: [
        'the opening plays {adjective} {noun}',
        'power level of {adjective} {noun}',
        'the final form is {adjective} {noun}',
        'transformation into {adjective} {noun}',
        'the backstory reveals {adjective} {noun}',
        'the plot armor of {adjective} {noun}',
        'boss fight in the {adjective} {noun}',
        'the sakura falls on {adjective} {noun}',
        'shonen {adjective} {noun} spirit',
        'the flashback shows {adjective} {noun}',
        'the rival stands in {adjective} {noun}',
        'the protagonist of {adjective} {noun}',
    ],
    afrobeat: [
        'the djembe {verb}s {adjective} {noun}',
        'we dance the {adjective} {noun} tonight',
        'afro rhythm of {adjective} {noun}',
        'the talking drum speaks {adjective} {noun}',
        'palm wine and {adjective} {noun}',
        'the highlife of {adjective} {noun}',
        'dashiki {noun} and {adjective} pride',
        'the shekere shakes {adjective} {noun}',
        'afrobeats pulse of {adjective} {noun}',
        'the village celebrates {adjective} {noun}',
        'the griot sings {adjective} {noun}',
        'jollof and {adjective} {noun} vibes',
    ],
    funk: [
        'the slap bass {verb}s {adjective} {noun}',
        'get down on the {adjective} {noun}',
        'the pocket is {adjective} and deep',
        'stank face {adjective} {noun} groove',
        'the wah pedal cries {adjective} {noun}',
        'we funk our way through {noun}',
        'clavinet and {adjective} {noun}',
        'the horn stab hits {adjective} {noun}',
        'bootsy {adjective} {noun} vibes',
        'syncopation of {adjective} {noun}',
        'the groove don\'t lie it\'s {adjective}',
        'parliament of {adjective} {noun}',
    ],
    house: [
        'the four on the floor {verb}s {adjective}',
        'jackin through the {adjective} {noun}',
        'the organ stab hits {adjective} {noun}',
        'we house our way through {noun}',
        'disco filtered {adjective} {noun}',
        'the diva vocal soars {adjective}',
        'warehouse {noun} and {adjective} energy',
        'the piano loop plays {adjective} {noun}',
        'deep house {adjective} {noun} therapy',
        'the garage brings {adjective} {noun}',
        'we two step through {adjective} {noun}',
        'the club holds {adjective} {noun}',
    ],
    techno: [
        'the kick relentless {adjective} {noun}',
        'industrial {noun} and {adjective} steel',
        'the sequence runs {adjective} {noun}',
        'we lose ourselves in {adjective} {noun}',
        'the modular sends {adjective} signals',
        'hypnotic {adjective} {noun} pattern',
        'the warehouse echoes {adjective} {noun}',
        'analog {noun} and {adjective} voltage',
        'the after hours are {adjective}',
        'machine {noun} and {adjective} rhythm',
        'we merge with the {adjective} {noun}',
        'the circuit bends to {adjective} {noun}',
    ],
    dnb: [
        'the amen break {verb}s {adjective} {noun}',
        'liquid {adjective} {noun} flowing',
        'the reese bass growls {adjective}',
        'jungle {noun} and {adjective} energy',
        'the halftime drops to {adjective} {noun}',
        'we roll through {adjective} {noun}',
        'the MC calls {adjective} {noun}',
        'neurofunk {adjective} {noun} vibes',
        'the dancefloor shakes with {noun}',
        'steppers and {adjective} {noun}',
        'the two step {verb}s {adjective} {noun}',
        'breakbeat of {adjective} {noun}',
    ],
    dubstep: [
        'the wobble {verb}s {adjective} {noun}',
        'filthy {adjective} {noun} energy',
        'the sub bass rattles the {noun}',
        'we headbang through {adjective} {noun}',
        'the riddim hits {adjective} {noun}',
        'robotic {noun} and {adjective} sound',
        'the growl tears through {noun}',
        'bass cannon of {adjective} {noun}',
        'the mosh breaks out at {adjective} {noun}',
        'we wub through {adjective} {noun}',
        'the tearout is {adjective} tonight',
        'laser bass and {adjective} {noun}',
    ],
    synthwave: [
        'the retro pulse of {adjective} {noun}',
        'driving through {adjective} {noun} at night',
        'the grid lights up {adjective} {noun}',
        'chrome {noun} and {adjective} sunset',
        'the cityscape glows {adjective}',
        'we cruise through {adjective} {noun}',
        'analog sunset of {adjective} {noun}',
        'the dashboard reads {adjective} {noun}',
        'neon horizon and {adjective} {noun}',
        'the VHS plays {adjective} {noun}',
        'outrun the {adjective} {noun}',
        'cyber {noun} and {adjective} chrome',
    ],
    vaporwave: [
        'the mall echoes {adjective} {noun}',
        'slowed down {adjective} {noun} forever',
        'the plaza holds {adjective} {noun}',
        'marble columns and {adjective} {noun}',
        'the Windows loads {adjective} {noun}',
        'aesthetic {adjective} {noun} rising',
        'the palm tree sways {adjective}',
        'late capitalism and {adjective} {noun}',
        'the elevator plays {adjective} {noun}',
        'roman bust and {adjective} {noun}',
        'glitched out {adjective} {noun}',
        'the sunset loops {adjective} {noun}',
    ],
    phonk: [
        'the cowbell hits {adjective} {noun}',
        'drift king of {adjective} {noun}',
        'the Memphis tape plays {adjective}',
        'smoke and {adjective} {noun} drifting',
        'the bass vibrates {adjective} {noun}',
        'we slide through {adjective} {noun}',
        'chopped vocals of {adjective} {noun}',
        'the night ride is {adjective}',
        'slowed reverb {adjective} {noun}',
        'the subwoofer rattles {adjective} {noun}',
        'drifting through {adjective} {noun} haze',
        'underground {adjective} {noun} forever',
    ],
    ambient: [
        'the drone carries {adjective} {noun}',
        'suspended in {adjective} {noun}',
        'the texture dissolves into {noun}',
        'we float through {adjective} {noun}',
        'the atmosphere is {adjective} tonight',
        'soundscape of {adjective} {noun}',
        'the shimmer fades to {adjective}',
        'glacial {adjective} {noun} drifting',
        'the pad swells with {adjective} {noun}',
        'ethereal {adjective} {noun} waves',
        'the stillness holds {adjective} {noun}',
        'dissolving into {adjective} {noun}',
    ],
    soul: [
        'the organ testifies {adjective} {noun}',
        'we pour our {noun} into the {noun2}',
        'the vocal runs through {adjective} {noun}',
        'smooth {noun} and {adjective} devotion',
        'the groove holds {adjective} {noun}',
        'we sing from the {adjective} {noun}',
        'Motown {adjective} {noun} feeling',
        'the backing vocals lift {adjective} {noun}',
        'heartfelt {adjective} {noun} inside',
        'the bridge resolves in {adjective} {noun}',
        'church raised {adjective} {noun} always',
        'the ad lib {verb}s {adjective} {noun}',
    ],
    disco: [
        'the mirror ball spins {adjective} {noun}',
        'boogie through the {adjective} {noun}',
        'the string section lifts {adjective} {noun}',
        'we hustle through {adjective} {noun}',
        'the hi hat shimmers {adjective}',
        'glitter and {adjective} {noun} tonight',
        'the bass guitar grooves {adjective} {noun}',
        'roller rink {adjective} {noun} vibes',
        'the floor lights up {adjective} {noun}',
        'we spin through {adjective} {noun}',
        'the DJ booth glows {adjective}',
        'Saturday night {adjective} {noun}',
    ],
    classical: [
        'the overture begins with {adjective} {noun}',
        'a sonata of {adjective} {noun}',
        'the concerto {verb}s {adjective} {noun}',
        'we crescendo into {adjective} {noun}',
        'the movement resolves in {noun}',
        'the strings weep {adjective} {noun}',
        'a fugue of {adjective} {noun}',
        'the coda rings {adjective} {noun}',
        'we waltz through {adjective} {noun}',
        'the prelude to {adjective} {noun}',
        'the oboe sings {adjective} {noun}',
        'a requiem for {adjective} {noun}',
    ],
};

// =====================================================================
// CHORUS NOUN TEMPLATES — 25+ new
// =====================================================================
export const CHORUS_NOUN_TEMPLATES_EXPANSION3 = [
    'we summoned the {rhyme}',
    'the voltage runs through the {rhyme}',
    'I chased the {rhyme} until the dawn',
    'the monument honors the {rhyme}',
    'we fortified the {rhyme}',
    'the radar detects the {rhyme}',
    'I witnessed the {rhyme} with my own eyes',
    'the empire craves the {rhyme}',
    'we ignited every {rhyme}',
    'the tribunal speaks of {rhyme}',
    'I memorized the {rhyme}',
    'the dynasty crumbles at the {rhyme}',
    'we shattered every {rhyme}',
    'the telescope zooms into the {rhyme}',
    'I traded my {rhyme} for the truth',
    'the cathedral holds the {rhyme}',
    'we deciphered the {rhyme}',
    'the archive seals the {rhyme}',
    'I manifested the {rhyme}',
    'the caravan reaches the {rhyme}',
    'we inherited every {rhyme}',
    'the battlefield mourns the {rhyme}',
    'I surrendered my {rhyme}',
    'the algorithm finds the {rhyme}',
    'we calibrated the {rhyme}',
];

// =====================================================================
// CHORUS ADJECTIVE TEMPLATES — 20+ new
// =====================================================================
export const CHORUS_ADJ_TEMPLATES_EXPANSION3 = [
    'the anthem sounds so {rhyme}',
    'we blaze so {rhyme} tonight',
    'the journey feels {rhyme}',
    'I stay forever {rhyme} inside',
    'the legacy remains {rhyme}',
    'we glow {rhyme} from within',
    'the battlefield is {rhyme}',
    'I burn {rhyme} and bold',
    'the skyline looks {rhyme}',
    'we pulse so {rhyme} together',
    'the moment rings {rhyme}',
    'I stand {rhyme} in the storm',
    'the wavelength feels {rhyme}',
    'we soar {rhyme} above',
    'the forecast says {rhyme}',
    'I wake up feeling {rhyme}',
    'the promise stays {rhyme}',
    'we leave it all so {rhyme}',
    'the dynasty stays {rhyme}',
    'I prove them {rhyme} every time',
];

// =====================================================================
// CHORUS VERB TEMPLATES — 20+ new
// =====================================================================
export const CHORUS_VERB_TEMPLATES_EXPANSION3 = [
    'I was destined to {rhyme}',
    'we came alive to {rhyme}',
    'the mission demands we {rhyme}',
    'I climbed the mountain just to {rhyme}',
    'they whispered but I chose to {rhyme}',
    'the crowd erupts when we {rhyme}',
    'I shattered ceilings just to {rhyme}',
    'we crossed the ocean to {rhyme}',
    'the anthem begs us all to {rhyme}',
    'I burned the bridge and learned to {rhyme}',
    'the story ends when we {rhyme}',
    'I found the strength to {rhyme}',
    'we broke the mold to {rhyme}',
    'the universe conspires to {rhyme}',
    'I chase the dawn to {rhyme}',
    'we raise the bar and {rhyme}',
    'the prophecy says we will {rhyme}',
    'I held my ground and chose to {rhyme}',
    'we built the stage to {rhyme}',
    'the legacy demands I {rhyme}',
];

// =====================================================================
// HOOK VOCAB BLOCKLIST — additional words
// =====================================================================
export const HOOK_VOCAB_BLOCKLIST_EXPANSION3 = [
    // Insurance / finance
    'premium', 'deductible', 'copay', 'underwriting', 'actuary',
    'annuity', 'fiduciary', 'amortize', 'lien', 'encumbrance',
    // Plumbing extended
    'ballcock', 'spigot', 'sump', 'septic', 'cesspool',
    'overflow', 'backflow', 'hookup', 'shutoff', 'blowoff',
    // Construction
    'rebar', 'studfinder', 'joist', 'truss', 'fascia',
    'soffit', 'lintel', 'purlin', 'flashing', 'mortar',
    // IT / networking
    'firewall', 'endpoint', 'latency', 'throughput', 'handshake',
    'payload', 'callback', 'webhook', 'namespace', 'singleton',
    // Medical equipment
    'stethoscope', 'tourniquet', 'defibrillator', 'ventilator', 'nebulizer',
    'speculum', 'retractor', 'scalpel', 'forceps', 'clamp',
    // Agriculture
    'fertilizer', 'herbicide', 'pesticide', 'fungicide', 'irrigation',
    'compost', 'silage', 'tilling', 'threshing', 'winnowing',
];

// =====================================================================
// VARIATION PATTERNS — 10+ new
// =====================================================================
export const VARIATION_PATTERNS_EXPANSION3 = [
    { type: 'prefix', additions: ['wake up', 'stand up', 'rise up', 'gear up', 'link up'] },
    { type: 'prefix', additions: ['no doubt', 'no question', 'no debate', 'for certain', 'confirmed'] },
    { type: 'intensifier', additions: ['incredibly', 'undeniably', 'relentlessly', 'unbelievably', 'impossibly'] },
    { type: 'intensifier', additions: ['on point', 'on time', 'on deck', 'on lock', 'on top'] },
    { type: 'repetition', additions: ['we ready', 'we steady', 'we heavy', 'we moving', 'we grooving'] },
    { type: 'repetition', additions: ['to the top', 'to the moon', 'to the sky', 'to the end', 'to the max'] },
    { type: 'suffix', additions: ['no question', 'no exception', 'no hesitation', 'no competition', 'no limitation'] },
    { type: 'suffix', additions: ['and that\'s facts', 'and that\'s real', 'and that\'s it', 'and that\'s us', 'and that\'s life'] },
    { type: 'prefix', additions: ['attention', 'breaking news', 'plot twist', 'headlines', 'update'] },
    { type: 'suffix', additions: ['trust the process', 'built to last', 'made to shine', 'here to stay', 'born to win'] },
];

// =====================================================================
// MERGE FUNCTIONS
// =====================================================================

/**
 * Merge hook template expansions into existing arrays (deduped by lowercase).
 */
export function mergeHookTemplates3(existing, expansion) {
    const set = new Set(existing.map(t => t.toLowerCase()));
    for (const t of expansion) {
        if (!set.has(t.toLowerCase())) existing.push(t);
    }
}

/**
 * Merge genre-specific hook templates.
 */
export function mergeGenreHookTemplates3(existing, expansion) {
    for (const [genre, templates] of Object.entries(expansion)) {
        if (Array.isArray(existing[genre])) {
            const set = new Set(existing[genre].map(t => t.toLowerCase()));
            for (const t of templates) {
                if (!set.has(t.toLowerCase())) existing[genre].push(t);
            }
        } else {
            existing[genre] = templates;
        }
    }
}

/**
 * Merge chorus templates (deduped by lowercase).
 */
export function mergeChorusTemplates3(existing, expansion) {
    const set = new Set(existing.map(t => t.toLowerCase()));
    for (const t of expansion) {
        if (!set.has(t.toLowerCase())) existing.push(t);
    }
}

/**
 * Merge blocklist words into existing Set.
 */
export function mergeBlocklist3(existing, expansion) {
    for (const word of expansion) existing.add(word.toLowerCase());
}
