/**
 * RhymeEngineExpansion — MASSIVE rhyme dictionary expansion.
 * Adds 3,000-4,000 new words across new and expanded rhyme families.
 * COMPLETE AND UTTER DOMINATION of rhyme matching.
 */

// =====================================================================
// NEW RHYME FAMILIES — families that don't exist yet in the base engine
// =====================================================================
export const NEW_RHYME_FAMILIES = {

    // === New consonant-heavy families ===
    'ub': ['club', 'hub', 'pub', 'rub', 'scrub', 'sub', 'stub', 'tub', 'dub', 'grub', 'shrub', 'snub', 'bathtub', 'nightclub', 'doorknob', 'hubbub'],
    'ug': ['bug', 'drug', 'hug', 'plug', 'rug', 'shrug', 'slug', 'snug', 'thug', 'tug', 'mug', 'jug', 'pug', 'dug', 'firebug', 'ladybug', 'bedbug', 'unplug', 'earlug', 'earplug'],
    'um': ['come', 'drum', 'from', 'gum', 'hum', 'numb', 'plum', 'rum', 'some', 'sum', 'thumb', 'overcome', 'outcome', 'become', 'kingdom', 'freedom', 'wisdom', 'boredom', 'random', 'phantom', 'fathom', 'anthem', 'album', 'medium', 'premium', 'stadium', 'podium', 'maximum', 'minimum', 'optimum', 'platinum', 'momentum', 'spectrum', 'quantum', 'tantrum', 'conundrum', 'aquarium', 'gymnasium', 'symposium', 'millennium', 'equilibrium'],
    'ut': ['cut', 'gut', 'hut', 'nut', 'shut', 'strut', 'but', 'coconut', 'shortcut', 'uppercut', 'clearcut', 'peanut', 'walnut', 'chestnut', 'doughnut', 'halibut', 'catapult', 'occult', 'result', 'insult', 'consult', 'adult', 'default', 'assault', 'exult', 'difficult', 'somersault'],
    'ob': ['job', 'mob', 'rob', 'sob', 'throb', 'bob', 'knob', 'prob', 'snob', 'glob', 'hearthrob', 'cornrob', 'doorknob'],
    'og': ['log', 'dog', 'fog', 'blog', 'jog', 'frog', 'smog', 'cog', 'hog', 'catalog', 'dialog', 'monolog', 'analog', 'epilog', 'prolog', 'synagog', 'travellog', 'underdog', 'bulldog', 'hotdog', 'watchdog', 'backlog', 'waterlog'],
    'om': ['bomb', 'calm', 'palm', 'psalm', 'mom', 'prom', 'rom', 'tom', 'atom', 'bottom', 'custom', 'symptom', 'phantom', 'cotton', 'common', 'blossom', 'awesome', 'seldom', 'ransom', 'handsome', 'wholesome', 'troublesome', 'quarrelsome', 'cumbersome', 'loathsome', 'fearsome', 'tiresome', 'worrisome', 'burdensome', 'venturesome'],
    'ab': ['grab', 'stab', 'cab', 'tab', 'lab', 'fab', 'dab', 'jab', 'nab', 'scab', 'prefab', 'taxicab', 'rehab', 'vocab'],
    'ib': ['rib', 'crib', 'bib', 'fib', 'glib', 'nib', 'adlib', 'ad-lib', 'contribute', 'distribute', 'attribute', 'exhibit'],
    'eb': ['web', 'celeb', 'cobweb', 'spiderweb', 'ebb'],

    // === New vowel combinations ===
    'aw2': ['draw', 'raw', 'saw', 'claw', 'flaw', 'jaw', 'law', 'paw', 'straw', 'thaw', 'awe', 'gnaw', 'squaw', 'outlaw', 'in-law', 'coleslaw', 'jigsaw', 'chainsaw', 'seesaw', 'hacksaw', 'withdraw', 'overdraw'],
    'ew': ['new', 'few', 'view', 'knew', 'grew', 'flew', 'drew', 'brew', 'crew', 'clue', 'glue', 'due', 'sue', 'hue', 'cue', 'pursue', 'rescue', 'review', 'renew', 'argue', 'value', 'venue', 'statue', 'virtue', 'revenue', 'continue', 'avenue', 'residue', 'interview', 'overdue', 'breakthrough', 'overview', 'corkscrew', 'misconstrue', 'barbecue', 'subdue'],
    'oo': ['cool', 'fool', 'pool', 'school', 'tool', 'rule', 'cruel', 'jewel', 'fuel', 'stool', 'drool', 'spool', 'moon', 'soon', 'noon', 'tune', 'june', 'dune', 'prune', 'immune', 'fortune', 'commune', 'balloon', 'cartoon', 'platoon', 'bassoon', 'cocoon', 'dragoon', 'festoon', 'harpoon', 'lagoon', 'maroon', 'monsoon', 'pontoon', 'raccoon', 'saloon', 'spoon', 'typhoon', 'honeymoon', 'afternoon', 'tablespoon', 'teaspoon'],
    'air': ['air', 'bare', 'care', 'dare', 'fair', 'hair', 'pair', 'rare', 'share', 'spare', 'square', 'stare', 'swear', 'tear', 'there', 'wear', 'where', 'affair', 'aware', 'compare', 'declare', 'despair', 'impair', 'prepare', 'repair', 'nightmare', 'welfare', 'warfare', 'fanfare', 'elsewhere', 'anywhere', 'everywhere', 'nowhere', 'somewhere', 'underwear', 'millionaire', 'billionaire', 'questionnaire', 'solitaire', 'debonair', 'laissez-faire', 'armchair', 'wheelchair', 'rocking-chair', 'highchair'],
    'ire2': ['tire', 'wire', 'fire', 'hire', 'dire', 'lyre', 'mire', 'sire', 'pyre', 'aspire', 'conspire', 'desire', 'empire', 'expire', 'inspire', 'perspire', 'require', 'retire', 'transpire', 'admire', 'acquire', 'entire', 'inquire', 'campfire', 'crossfire', 'gunfire', 'hellfire', 'wildfire', 'bonfire', 'ceasefire', 'spitfire', 'vampire', 'sapphire', 'umpire'],
    'ure': ['pure', 'sure', 'cure', 'lure', 'tour', 'endure', 'secure', 'mature', 'obscure', 'procure', 'allure', 'demure', 'insure', 'ensure', 'brochure', 'detour', 'contour', 'velour', 'glamour', 'amour', 'devour', 'downpour', 'uproar', 'culture', 'nature', 'future', 'structure', 'picture', 'creature', 'feature', 'mixture', 'texture', 'venture', 'adventure', 'furniture', 'signature', 'temperature', 'literature', 'architecture', 'manufacture', 'departure', 'miniature', 'overture', 'aperture', 'caricature'],
    'oar': ['roar', 'soar', 'board', 'sword', 'toward', 'reward', 'record', 'accord', 'afford', 'discord', 'hoard', 'lord', 'cord', 'ford', 'word', 'absurd', 'unheard', 'overheard', 'occurred', 'preferred', 'referred', 'transferred', 'deterred', 'conferred', 'inferred'],

    // === New multi-syllable families ===
    'ology': ['apology', 'biology', 'ecology', 'mythology', 'psychology', 'technology', 'theology', 'zoology', 'anthology', 'archeology', 'astrology', 'cardiology', 'chronology', 'cosmology', 'dermatology', 'etymology', 'genealogy', 'geology', 'ideology', 'immunology', 'methodology', 'musicology', 'neurology', 'oncology', 'pathology', 'pharmacology', 'physiology', 'radiology', 'sociology', 'terminology', 'toxicology', 'trilogy'],
    'ical': ['critical', 'musical', 'physical', 'political', 'practical', 'radical', 'tropical', 'typical', 'biblical', 'classical', 'clinical', 'comical', 'cynical', 'diabolical', 'dynamical', 'electrical', 'empirical', 'ethical', 'fanatical', 'historical', 'hysterical', 'identical', 'illogical', 'lyrical', 'magical', 'mechanical', 'medical', 'methodical', 'miracle', 'mystical', 'mythical', 'nautical', 'numerical', 'optical', 'oracle', 'paradoxical', 'pharmaceutical', 'philosophical', 'pinnacle', 'piratical', 'poetical', 'satirical', 'skeptical', 'statistical', 'surgical', 'symmetrical', 'tactical', 'technical', 'theatrical', 'topical', 'vertical', 'whimsical'],
    'ular': ['popular', 'regular', 'particular', 'spectacular', 'singular', 'circular', 'cellular', 'molecular', 'muscular', 'secular', 'modular', 'angular', 'annular', 'binocular', 'capsular', 'curricular', 'globular', 'granular', 'irregular', 'jugular', 'lunar', 'modular', 'nuclear', 'ocular', 'peninsular', 'perpendicular', 'polar', 'rectangular', 'scholar', 'solar', 'stellar', 'tabular', 'tubular', 'vascular', 'vehicular', 'vernacular', 'vulgar', 'dollar', 'collar', 'pillar', 'cellar', 'scholar'],
    'ious': ['curious', 'furious', 'glorious', 'previous', 'serious', 'various', 'anxious', 'cautious', 'conscious', 'copious', 'devious', 'dubious', 'envious', 'gracious', 'illustrious', 'industrious', 'ingenious', 'laborious', 'luxurious', 'malicious', 'mysterious', 'notorious', 'obvious', 'oblivious', 'precious', 'rebellious', 'religious', 'spacious', 'studious', 'suspicious', 'tedious', 'victorious', 'ambitious', 'capricious', 'contagious', 'courageous', 'delicious', 'ferocious', 'harmonious', 'imperious', 'infectious', 'judicious', 'litigious', 'melodious', 'nutritious', 'ostentatious', 'outrageous', 'pernicious', 'prodigious', 'sacrilegious', 'superstitious', 'tenacious', 'unconscious', 'vivacious'],
    'ible': ['possible', 'impossible', 'incredible', 'terrible', 'horrible', 'visible', 'invisible', 'flexible', 'accessible', 'admissible', 'compatible', 'combustible', 'convertible', 'defensible', 'digestible', 'divisible', 'edible', 'eligible', 'fallible', 'feasible', 'forcible', 'gullible', 'infallible', 'invincible', 'irresistible', 'legible', 'negligible', 'permissible', 'plausible', 'reversible', 'sensible', 'susceptible', 'tangible', 'bible'],
    'able': ['able', 'cable', 'fable', 'label', 'stable', 'table', 'capable', 'enable', 'disable', 'unable', 'available', 'comfortable', 'considerable', 'desirable', 'durable', 'fashionable', 'favorable', 'formidable', 'honorable', 'inevitable', 'insatiable', 'inseparable', 'knowledgeable', 'manageable', 'memorable', 'miserable', 'notable', 'observable', 'portable', 'profitable', 'questionable', 'reasonable', 'reliable', 'remarkable', 'renewable', 'sustainable', 'tolerable', 'undeniable', 'unmistakable', 'unquestionable', 'unstoppable', 'valuable', 'vulnerable', 'workable'],
    'ment2': ['judgment', 'element', 'moment', 'comment', 'segment', 'cement', 'torment', 'lament', 'ferment', 'garment', 'ailment', 'pigment', 'figment', 'fragment', 'treatment', 'payment', 'statement', 'placement', 'movement', 'improvement', 'equipment', 'government', 'apartment', 'department', 'employment', 'enjoyment', 'amazement', 'excitement', 'announcement', 'arrangement', 'achievement', 'experiment', 'instrument', 'environment', 'development', 'entertainment', 'advertisement', 'establishment', 'encouragement', 'imprisonment'],

    // === Short punchy families ===
    'ust4': ['adjust', 'combust', 'disgust', 'distrust', 'entrust', 'mistrust', 'robust', 'wanderlust', 'bloodlust', 'stardust', 'sawdust', 'pixie-dust', 'gold-dust'],
    'aft': ['craft', 'draft', 'shaft', 'raft', 'aircraft', 'hovercraft', 'witchcraft', 'stagecraft', 'watercraft', 'overdraft', 'handicraft', 'starcraft', 'warcraft'],
    'eft': ['left', 'theft', 'cleft', 'bereft', 'deft', 'heft', 'weft'],
    'ift': ['gift', 'shift', 'drift', 'lift', 'swift', 'rift', 'thrift', 'uplift', 'snowdrift', 'spendthrift', 'airlift', 'facelift', 'forklift', 'shoplifts', 'nightshift', 'dayshift', 'downshift', 'upshift', 'redshift', 'paradigm-shift'],
    'oft': ['soft', 'loft', 'aloft', 'microsoft', 'scoffed', 'coughed'],
    'ulp': ['gulp', 'pulp', 'sculpt'],
    'ump': ['jump', 'bump', 'dump', 'pump', 'lump', 'trump', 'stump', 'plump', 'clump', 'slump', 'hump', 'thump', 'grump'],
    'amp': ['camp', 'damp', 'lamp', 'ramp', 'stamp', 'champ', 'clamp', 'cramp', 'tramp', 'vamp', 'revamp', 'offcamp', 'bootcamp', 'basecamp'],
    'asp': ['grasp', 'clasp', 'gasp', 'rasp', 'unclasp'],
    'ism': ['rhythm', 'prism', 'criticism', 'heroism', 'journalism', 'mechanism', 'metabolism', 'nationalism', 'optimism', 'organism', 'patriotism', 'pessimism', 'pluralism', 'populism', 'realism', 'romanticism', 'skepticism', 'surrealism', 'symbolism', 'terrorism', 'vandalism', 'activism', 'capitalism', 'communism', 'cynicism', 'dynamism', 'egoism', 'escapism', 'extremism', 'idealism', 'individualism', 'liberalism', 'magnetism', 'materialism', 'modernism', 'mysticism'],

    // === Emotional rhyme families ===
    'ope2': ['hope', 'rope', 'scope', 'cope', 'slope', 'dope', 'grope', 'nope', 'pope', 'elope', 'envelope', 'telescope', 'microscope', 'horoscope', 'kaleidoscope', 'stethoscope', 'periscope', 'antelope', 'cantaloupe', 'tightrope', 'downslope', 'gyroscope', 'isotope', 'interlope', 'misanthrope'],
    'ief': ['grief', 'belief', 'relief', 'brief', 'chief', 'thief', 'leaf', 'reef', 'beef', 'disbelief', 'mischief', 'motif', 'masterpiece', 'centerpiece', 'handkerchief'],
    'oom': ['room', 'bloom', 'boom', 'doom', 'gloom', 'groom', 'loom', 'tomb', 'zoom', 'assume', 'consume', 'costume', 'mushroom', 'bathroom', 'bedroom', 'classroom', 'courtroom', 'showroom', 'ballroom', 'boardroom', 'chatroom', 'cloakroom', 'darkroom', 'newsroom', 'stockroom', 'storeroom', 'workroom', 'legroom', 'headroom', 'elbow-room', 'heirloom', 'bridegroom', 'perfume', 'volume', 'resume', 'presume'],
    'aze2': ['blaze', 'craze', 'daze', 'gaze', 'graze', 'haze', 'maze', 'phase', 'praise', 'raise', 'amaze', 'appraise', 'paraphrase', 'rephrase', 'ablaze', 'malaise', 'unfazed', 'stargazer', 'trailblazer'],
    'oze': ['froze', 'chose', 'close', 'nose', 'pose', 'prose', 'rose', 'those', 'compose', 'dispose', 'enclose', 'expose', 'impose', 'oppose', 'propose', 'suppose', 'decompose', 'diagnose', 'predispose', 'transpose', 'overdose', 'grandiose', 'comatose', 'primrose'],
    'ush': ['rush', 'brush', 'crush', 'flush', 'blush', 'gush', 'hush', 'lush', 'mush', 'plush', 'push', 'slush', 'thrush', 'toothbrush', 'paintbrush', 'airbrush', 'hairbrush', 'goldbrush', 'underbrush', 'inrush', 'outrush', 'onrush', 'sugar-rush', 'adrenaline-rush'],
    'ust5': ['must', 'trust', 'just', 'dust', 'bust', 'gust', 'rust', 'crust', 'thrust', 'adjust', 'disgust', 'robust', 'combust', 'wanderlust', 'stardust'],
    'amp2': ['stamp', 'camp', 'damp', 'lamp', 'ramp', 'clamp', 'cramp', 'tramp', 'vamp', 'champ', 'scamp', 'revamp'],
    'etch': ['stretch', 'fetch', 'sketch', 'wretch', 'kvetch', 'outstretch', 'far-fetched'],
    'edge': ['edge', 'hedge', 'ledge', 'pledge', 'wedge', 'sledge', 'allege', 'knowledge', 'acknowledge', 'privilege'],
    'idge': ['bridge', 'ridge', 'fridge', 'midge', 'cartridge', 'porridge', 'partridge', 'cambridge', 'drawbridge', 'footbridge'],

    // === Power/energy families ===
    'olt': ['bolt', 'jolt', 'volt', 'revolt', 'colt', 'dolt', 'molt', 'thunderbolt', 'lightning-bolt', 'deadbolt'],
    'urst': ['burst', 'first', 'thirst', 'worst', 'cursed', 'nursed', 'reversed', 'rehearsed', 'immersed', 'dispersed', 'outburst', 'starburst', 'sunburst', 'cloudburst', 'downburst', 'airburst'],
    'ance': ['dance', 'chance', 'glance', 'lance', 'stance', 'advance', 'enhance', 'finance', 'romance', 'entrance', 'circumstance', 'performance', 'resistance', 'appearance', 'assurance', 'assistance', 'attendance', 'abundance', 'acceptance', 'accordance', 'allegiance', 'alliance', 'allowance', 'ambulance', 'arrogance', 'balance', 'compliance', 'defiance', 'deliverance', 'dependance', 'disturbance', 'dominance', 'elegance', 'endurance', 'fragrance', 'governance', 'grievance', 'guidance', 'ignorance', 'importance', 'independence', 'inheritance', 'instance', 'insurance', 'intolerance', 'perseverance', 'prevalence', 'radiance', 'redundance', 'relevance', 'reliance', 'reluctance', 'remembrance', 'renaissance', 'resonance', 'significance', 'substance', 'surveillance', 'temperance', 'tolerance', 'utterance', 'vengeance', 'vigilance'],
    'ense': ['sense', 'dense', 'fence', 'hence', 'tense', 'defense', 'expense', 'immense', 'intense', 'offense', 'pretense', 'suspense', 'commence', 'condense', 'dispense', 'incense', 'license', 'nonsense', 'recompense', 'self-defense', 'sixth-sense', 'common-sense'],
    'unch': ['bunch', 'crunch', 'hunch', 'lunch', 'munch', 'punch', 'brunch', 'scrunch', 'counterpunch', 'sucker-punch'],
    'unge': ['plunge', 'lunge', 'sponge', 'expunge', 'lounge'],
    'ulse': ['pulse', 'impulse', 'repulse', 'convulse', 'catapulse'],
    'erge': ['merge', 'emerge', 'surge', 'verge', 'converge', 'diverge', 'submerge', 'splurge', 'purge', 'scourge', 'urge', 'resurge'],
    'inge': ['hinge', 'cringe', 'fringe', 'singe', 'tinge', 'binge', 'infringe', 'impinge', 'unhinge', 'syringe'],
    'ulge': ['bulge', 'indulge', 'divulge'],

    // === Nature/atmosphere families ===
    'ust6': ['dust', 'gust', 'must', 'rust', 'trust', 'just', 'bust', 'crust', 'thrust'],
    'awn': ['dawn', 'drawn', 'fawn', 'lawn', 'pawn', 'prawn', 'spawn', 'yawn', 'withdrawn', 'foregone', 'redrawn', 'overdrawn'],
    'usk': ['dusk', 'husk', 'musk', 'rusk', 'tusk', 'busk'],
    'aze3': ['blaze', 'craze', 'daze', 'gaze', 'graze', 'haze', 'maze', 'phase', 'praise', 'raise'],
    'ist': ['fist', 'list', 'mist', 'twist', 'wrist', 'exist', 'assist', 'consist', 'desist', 'enlist', 'insist', 'persist', 'resist', 'subsist', 'artist', 'bassist', 'chemist', 'cyclist', 'dentist', 'florist', 'guitarist', 'herbalist', 'idealist', 'journalist', 'linguist', 'lyricist', 'motorist', 'novelist', 'optimist', 'pessimist', 'pianist', 'pugilist', 'realist', 'scientist', 'socialist', 'soloist', 'specialist', 'strategist', 'stylist', 'terrorist', 'therapist', 'tourist', 'vocalist'],
    'oss': ['boss', 'cross', 'gloss', 'loss', 'moss', 'sauce', 'toss', 'across', 'emboss', 'lacrosse', 'albatross', 'applesauce', 'double-cross'],
    'ust7': ['disgust', 'robust', 'locust', 'august', 'exhaust'],
    'atch2': ['catch', 'match', 'watch', 'patch', 'scratch', 'snatch', 'batch', 'hatch', 'latch', 'thatch', 'attach', 'detach', 'dispatch', 'mismatch', 'rematch', 'eyepatch'],
    'etch2': ['stretch', 'sketch', 'fetch', 'wretch', 'kvetch'],

    // === Abstract/conceptual families ===
    'oom2': ['room', 'bloom', 'boom', 'doom', 'gloom', 'groom', 'loom', 'zoom', 'mushroom', 'ballroom', 'bedroom', 'courtroom', 'classroom', 'bathroom', 'showroom', 'boardroom', 'heirloom', 'bridegroom'],
    'ift2': ['gift', 'shift', 'drift', 'lift', 'swift', 'rift', 'thrift', 'uplift', 'snowdrift'],
    'yst': ['twist', 'fist', 'list', 'mist', 'wrist', 'exist', 'insist', 'persist', 'resist', 'consist', 'analyst', 'catalyst', 'evangelist', 'lyricist', 'pianist', 'vocalist'],
    'ust8': ['just', 'must', 'trust', 'dust', 'rust', 'gust', 'bust', 'crust', 'thrust', 'adjust', 'combust', 'disgust', 'distrust', 'entrust', 'robust', 'wanderlust'],
};

// =====================================================================
// EXPANDED EXISTING FAMILIES — additional words for families that exist
// =====================================================================
export const EXPANDED_RHYME_FAMILIES = {

    // === Expanded A-sounds ===
    'ight': ['oversight', 'copyright', 'playwright', 'birthright', 'downright', 'goodnight', 'streetlight', 'headlight', 'taillight', 'backlight', 'sidelight', 'floodlight', 'torchlight', 'footlight', 'nightlight', 'penlight', 'lamplight', 'gaslight', 'limelight', 'arc-light', 'brake-light', 'green-light', 'traffic-light', 'ultra-light'],
    'ay': ['freeway', 'driveway', 'getaway', 'castaway', 'hideaway', 'giveaway', 'throwaway', 'runaway', 'flyaway', 'stowaway', 'faraway', 'breakaway', 'takeaway', 'walkaway', 'passageway', 'waterway', 'motorway', 'expressway', 'causeway', 'entryway', 'fairway', 'archway', 'gangway', 'hallway', 'midway', 'parkway', 'speedway', 'subway', 'tramway', 'underway', 'airway', 'broadway', 'byway', 'alleyway', 'crossway', 'flyway', 'headway', 'overplay', 'outplay', 'downplay', 'foreplay', 'horseplay', 'swordplay', 'wordplay', 'fair-play', 'foul-play', 'gunplay', 'interplay', 'screenplay', 'role-play', 'child-play'],
    'ain': ['bloodstain', 'eyestrain', 'food-chain', 'supply-chain', 'daisy-chain', 'ball-and-chain', 'brain-drain', 'cross-grain', 'fine-grain', 'whole-grain', 'wood-grain', 'fast-lane', 'slow-lane', 'traffic-lane', 'memory-lane', 'sugar-cane', 'candy-cane', 'walking-cane', 'cellophane', 'windowpane', 'counterpane', 'biplane', 'monoplane', 'seaplane', 'warplane', 'aeroplane', 'aquaplane', 'hydroplane'],
    'ame': ['nickname', 'surname', 'username', 'filename', 'codename', 'last-name', 'first-name', 'pen-name', 'brand-name', 'household-name', 'middle-name', 'maiden-name', 'domain-name', 'stage-name', 'pet-name', 'given-name', 'family-name', 'picture-frame', 'doorframe', 'timeframe', 'mainframe', 'wire-frame', 'airframe', 'framework', 'boardgame', 'ballgame', 'endgame', 'fair-game', 'mind-game', 'war-game', 'blame-game', 'name-game', 'shell-game', 'video-game', 'arcade-game', 'card-game', 'word-game'],
    'ace': ['workplace', 'birthplace', 'fireplace', 'marketplace', 'commonplace', 'hiding-place', 'meeting-place', 'resting-place', 'dwelling-place', 'landing-place', 'parking-place', 'starting-place', 'stopping-place', 'gathering-place', 'air-space', 'cyberspace', 'outer-space', 'head-space', 'living-space', 'breathing-space', 'crawl-space', 'desk-space', 'elbow-space', 'floor-space', 'free-space', 'shelf-space', 'storage-space', 'car-chase', 'goose-chase', 'wild-chase', 'steeplechase', 'paper-chase', 'hot-chase'],
    'ate': ['accommodate', 'accumulate', 'accelerate', 'affiliate', 'aggregate', 'agitate', 'alternate', 'amalgamate', 'ameliorate', 'annihilate', 'approximate', 'arbitrate', 'assassinate', 'calibrate', 'capitulate', 'circulate', 'collaborate', 'commemorate', 'commiserate', 'complicate', 'confiscate', 'congregate', 'consolidate', 'contaminate', 'cooperate', 'coordinate', 'corroborate', 'culminate', 'deactivate', 'decapitate', 'decontaminate', 'degenerate', 'deliberate', 'demonstrate', 'denominate', 'depreciate', 'deteriorate', 'differentiate', 'disseminate', 'dissipate', 'domesticate', 'emancipate', 'enumerate', 'eradicate', 'extrapolate', 'hallucinate', 'inaugurate', 'incapacitate', 'incorporate', 'insinuate', 'interrogate', 'intimidate', 'necessitate', 'procrastinate', 'reciprocate', 'recuperate', 'regenerate', 'rehabilitate', 'retaliate', 'subordinate', 'featherweight', 'lightweight', 'heavyweight', 'flyweight', 'middleweight', 'paperweight', 'deadweight', 'underweight', 'overweight', 'counterweight'],

    // === Expanded E-sounds ===
    'ee': ['guarantee', 'nominee', 'absentee', 'amputee', 'appointee', 'attendee', 'committee', 'conferee', 'deportee', 'detainee', 'divorcee', 'electee', 'endorsee', 'enrollee', 'escapee', 'evacuee', 'examinee', 'franchisee', 'grantee', 'honoree', 'inductee', 'internee', 'interviewee', 'invitee', 'licensee', 'lessee', 'mortgagee', 'nominee', 'payee', 'permittee', 'refugee', 'retiree', 'returnee', 'selectee', 'trainee', 'trustee', 'vendee', 'devotee', 'divorcee', 'employee', 'filigree', 'jubilee', 'licensee', 'pedigree'],
    'eal': ['automobile', 'commonweal', 'banana-peel', 'orange-peel', 'spinning-wheel', 'steering-wheel', 'ferris-wheel', 'cartwheel', 'flywheel', 'pinwheel', 'waterwheel', 'windmill', 'treadmill', 'sex-appeal', 'mass-appeal', 'broad-appeal', 'curb-appeal', 'snob-appeal'],
    'eat': ['buckwheat', 'dead-heat', 'white-heat', 'red-heat', 'preheat', 'reheat', 'overheat', 'superheat', 'box-seat', 'car-seat', 'hot-seat', 'back-seat', 'front-seat', 'love-seat', 'window-seat', 'county-seat', 'mercy-seat', 'ringside-seat', 'dead-meat', 'red-meat', 'white-meat', 'dark-meat', 'ground-meat', 'fresh-meat', 'raw-meat'],
    'eam': ['bloodstream', 'jet-stream', 'mainstream', 'midstream', 'downstream', 'upstream', 'airstream', 'slipstream', 'goldstream', 'crossbeam', 'hornbeam', 'day-dream', 'pipe-dream', 'fever-dream', 'wet-dream', 'broken-dream', 'shattered-dream', 'american-dream', 'ice-cream', 'whipped-cream', 'sour-cream', 'cold-cream', 'vanishing-cream', 'battle-scream'],
    'ear': ['atmosphere', 'biosphere', 'hemisphere', 'ionosphere', 'stratosphere', 'troposphere', 'lithosphere', 'blogosphere', 'ecosphere', 'infosphere', 'technosphere', 'bandolier', 'bombardier', 'brigadier', 'buccaneer', 'cannoneer', 'charioteer', 'financier', 'gondolier', 'grenadier', 'musketeer', 'profiteer', 'racketeeer', 'privateer', 'puppeteer', 'mutineer', 'black-marketeer'],

    // === Expanded I-sounds ===
    'ine': ['assembly-line', 'bottom-line', 'boundary-line', 'finishing-line', 'firing-line', 'goal-line', 'party-line', 'pick-up-line', 'punch-line', 'sight-line', 'starting-line', 'story-line', 'supply-line', 'tree-line', 'waist-line', 'water-line', 'battle-line', 'blood-line', 'bus-line', 'chalk-line', 'clothes-line', 'coast-line', 'contour-line', 'cruise-line', 'date-line', 'dotted-line', 'drop-line', 'foul-line', 'frost-line', 'tag-line', 'picket-line'],
    'ide': ['curbside', 'dockside', 'lakeside', 'poolside', 'ringside', 'roadside', 'trackside', 'waterside', 'wayside', 'backside', 'blindside', 'broadside', 'dark-side', 'downside', 'far-side', 'flip-side', 'north-side', 'south-side', 'east-side', 'west-side', 'right-side', 'wrong-side', 'bright-side', 'wild-side', 'sunny-side'],
    'ire': ['require', 'acquire', 'desire', 'inspire', 'admire', 'retire', 'empire', 'conspire', 'entire', 'enquire', 'perspire', 'transpire', 'rapid-fire', 'surefire', 'ceasefire', 'campfire', 'crossfire', 'friendly-fire', 'gun-fire', 'hell-fire', 'open-fire', 'return-fire', 'cover-fire', 'real-fire'],
    'ive': ['alive', 'arrive', 'contrive', 'deprive', 'derive', 'drive', 'forgive', 'give', 'live', 'revive', 'strive', 'survive', 'thrive', 'archive', 'deep-dive', 'nose-dive', 'sky-dive', 'swan-dive', 'high-five', 'power-drive', 'test-drive', 'hard-drive', 'flash-drive', 'thumb-drive', 'over-drive', 'sex-drive'],
    'ime': ['big-time', 'full-time', 'half-time', 'part-time', 'prime-time', 'real-time', 'show-time', 'war-time', 'peace-time', 'bed-time', 'dinner-time', 'lunch-time', 'supper-time', 'harvest-time', 'closing-time', 'curtain-time', 'drive-time', 'face-time', 'game-time', 'hammer-time', 'play-time', 'screen-time', 'story-time', 'down-time', 'free-time', 'spare-time', 'idle-time', 'kill-time', 'mark-time', 'old-time', 'small-time'],
    'ind': ['color-blind', 'snow-blind', 'like-minded', 'open-minded', 'narrow-minded', 'absent-minded', 'broad-minded', 'civic-minded', 'evil-minded', 'fair-minded', 'feeble-minded', 'high-minded', 'level-minded', 'right-minded', 'simple-minded', 'single-minded', 'small-minded', 'strong-minded', 'tough-minded', 'weak-minded'],

    // === Expanded O-sounds ===
    'ow': ['afterglow', 'archipelago', 'audio', 'bravado', 'buffalo', 'cameo', 'casino', 'commando', 'desperado', 'embargo', 'espresso', 'fiasco', 'gazpacho', 'ghetto', 'grotto', 'gusto', 'incognito', 'innuendo', 'lingo', 'limbo', 'maestro', 'memento', 'mosquito', 'oregano', 'placebo', 'portfolio', 'pseudo', 'rancho', 'ratio', 'risotto', 'scenario', 'sombrero', 'stiletto', 'studio', 'techno', 'tobacco', 'tornado', 'tuxedo', 'veto', 'video', 'virago', 'virtuoso', 'volcano', 'weirdo'],
    'old': ['age-old', 'ice-cold', 'stone-cold', 'blood-cold', 'white-gold', 'black-gold', 'pure-gold', 'liquid-gold', 'solid-gold', 'spun-gold', 'pot-of-gold', 'heart-of-gold', 'good-as-gold', 'twice-told', 'oft-told', 're-told', 'over-sold', 'under-sold', 'hand-rolled', 'rock-and-rolled', 'bankrolled', 'steamrolled', 'logrolled', 'drum-rolled', 'barrel-rolled'],
    'one': ['backbone', 'milestone', 'stepping-stone', 'rolling-stone', 'cobblestone', 'limestone', 'sandstone', 'brownstone', 'grindstone', 'cornerstone', 'foundation-stone', 'hearthstone', 'curbstone', 'flagstone', 'gemstone', 'hailstone', 'lodestone', 'moonstone', 'opalstone', 'rhinestone', 'soapstone', 'touchstone', 'cell-phone', 'smartphone', 'ear-phone', 'head-phone', 'i-phone', 'pay-phone', 'ring-tone', 'dial-tone', 'skin-tone', 'two-tone', 'half-tone', 'mono-tone', 'over-tone', 'under-tone', 'key-stone', 'cap-stone', 'tomb-stone'],
    'ore': ['furthermore', 'evermore', 'forevermore', 'nevermore', 'heretofore', 'theretofore', 'what-for', 'eyesore', 'cold-sore', 'folklore', 'hard-core', 'soft-core', 'inner-core', 'outer-core', 'apple-core', 'rotten-core', 'dance-floor', 'ground-floor', 'top-floor', 'ocean-floor', 'kill-floor', 'shop-floor', 'threshing-floor', 'trap-door', 'back-door', 'front-door', 'side-door', 'screen-door', 'revolving-door', 'sliding-door', 'swinging-door', 'barn-door', 'car-door', 'church-door', 'stage-door', 'cellar-door'],
    'ound': ['background', 'battleground', 'campground', 'fairground', 'foreground', 'playground', 'proving-ground', 'stomping-ground', 'testing-ground', 'training-ground', 'breeding-ground', 'burial-ground', 'common-ground', 'dumping-ground', 'feeding-ground', 'fishing-ground', 'grazing-ground', 'hallowed-ground', 'higher-ground', 'hollow-ground', 'holy-ground', 'home-ground', 'hunting-ground', 'killing-ground', 'middle-ground', 'neutral-ground', 'rising-ground', 'sacred-ground', 'solid-ground', 'stable-ground', 'standing-ground'],

    // === Expanded U-sounds ===
    'ue': ['continue', 'discontinue', 'residue', 'revenue', 'retinue', 'statue', 'virtue', 'tissue', 'issue', 'venue', 'value', 'argue', 'rescue', 'avenue', 'pursue', 'construe', 'misconstrue', 'fondue', 'imbue', 'subdue', 'undue', 'overdue', 'accrue', 'construe'],
    'urn': ['overturn', 'downturn', 'upturn', 'return', 'concern', 'discern', 'nocturne', 'saturn', 'lantern', 'cistern', 'sunburn', 'heartburn', 'windburn', 'rug-burn', 'slow-burn', 'crash-burn', 'slash-burn', 'live-learn', 'hard-earn', 'well-earn'],
    'un': ['undone', 'outdone', 'well-done', 'hard-won', 'hard-run', 'long-run', 'short-run', 'dry-run', 'fun-run', 'hit-run', 'home-run', 'bull-run', 'milk-run', 'test-run', 'trial-run', 'smoking-gun', 'starting-gun', 'top-gun', 'water-gun', 'ray-gun', 'pop-gun', 'stun-gun', 'pellet-gun', 'hired-gun', 'big-gun'],

    // === Expanded complex endings ===
    'ation': ['abbreviation', 'abomination', 'acceleration', 'accommodation', 'accumulation', 'administration', 'affirmation', 'aggravation', 'amplification', 'approximation', 'articulation', 'assassination', 'authorization', 'beautification', 'calculation', 'cancellation', 'certification', 'clarification', 'classification', 'collaboration', 'colonization', 'commemoration', 'commendation', 'compilation', 'complication', 'configuration', 'confirmation', 'confrontation', 'congratulation', 'consideration', 'consolidation', 'consultation', 'contamination', 'coordination', 'corporation', 'customization', 'deforestation', 'delegation', 'demonstration', 'denomination', 'deprivation', 'desolation', 'digitization', 'discrimination', 'documentation', 'elaboration', 'electrification', 'emancipation', 'exaggeration', 'examination', 'exclamation', 'experimentation', 'exploitation', 'falsification', 'fermentation', 'fortification', 'globalization', 'gratification', 'hallucination', 'harmonization', 'humiliation', 'identification', 'illumination', 'implementation', 'improvisation', 'inauguration', 'indignation', 'infatuation', 'initiation', 'inoculation', 'integration', 'interrogation', 'intimation', 'intoxication', 'investigation', 'justification', 'legalization', 'legitimation', 'magnification', 'manifestation', 'maximization', 'memorization', 'minimization', 'modernization', 'modification', 'multiplication', 'normalization', 'notification', 'optimization', 'organization', 'orientation', 'origination', 'pacification', 'personalization', 'polarization', 'privatization', 'purification', 'qualification', 'rationalization', 'realization', 'recommendation', 'reconciliation', 'reconsideration', 'reforestation', 'refrigeration', 'reincarnation', 'relaxation', 'relocation', 'remediation', 'remuneration', 'renovation', 'reorganization', 'reputation', 'resignation', 'restoration', 'reverberation', 'sanctification', 'simplification', 'specification', 'stagnation', 'sterilization', 'stimulation', 'subordination', 'synchronization', 'termination', 'transportation', 'unification', 'urbanization', 'vaccination', 'validation', 'visualization', 'vocalization'],
    'ision': ['precision', 'decision', 'division', 'collision', 'provision', 'revision', 'television', 'supervision', 'incision', 'derision', 'envision', 'circumcision', 'indecision', 'subdivision', 'tunnel-vision', 'double-vision', 'night-vision', 'tunnel-vision', 'x-ray-vision', 'field-of-vision', 'line-of-vision', 'split-decision', 'snap-decision', 'close-decision', 'tough-decision'],
    'ity': ['abnormality', 'accessibility', 'accountability', 'adaptability', 'agility', 'ambiguity', 'animosity', 'antiquity', 'atrocity', 'audacity', 'authenticity', 'availability', 'brutality', 'calamity', 'capability', 'captivity', 'celebrity', 'civility', 'commodity', 'compatibility', 'connectivity', 'credibility', 'culpability', 'dependency', 'desirability', 'durability', 'eccentricity', 'elasticity', 'eligibility', 'enormity', 'extremity', 'familiarity', 'feasibility', 'ferocity', 'flexibility', 'formality', 'frugality', 'functionality', 'generosity', 'hospitality', 'humility', 'legality', 'legitimacy', 'liability', 'longevity', 'luminosity', 'maturity', 'mediocrity', 'mentality', 'minority', 'modernity', 'multiplicity', 'municipality', 'nationality', 'neutrality', 'normality', 'objectivity', 'obscurity', 'peculiarity', 'perplexity', 'plurality', 'polarity', 'posterity', 'productivity', 'profanity', 'profitability', 'proximity', 'publicity', 'punctuality', 'rarity', 'rationality', 'reciprocity', 'reliability', 'respectability', 'responsibility', 'scarcity', 'serenity', 'severity', 'similarity', 'singularity', 'solidarity', 'specialty', 'specificity', 'stability', 'sterility', 'stupidity', 'suitability', 'superiority', 'technicality', 'tenacity', 'tonality', 'totality', 'toxicity', 'tranquility', 'triviality', 'unanimity', 'unpopularity', 'versatility', 'viability', 'virility', 'visibility', 'vitality', 'vivacity', 'vulnerability'],
    'ize': ['alphabetize', 'anesthetize', 'appetize', 'burglarize', 'cauterize', 'centralize', 'civilize', 'colonize', 'computerize', 'conceptualize', 'contextualize', 'criminalize', 'crystallize', 'decentralize', 'democratize', 'destabilize', 'digitize', 'epitomize', 'equalize', 'evangelize', 'externalize', 'familiarize', 'feminize', 'finalize', 'formalize', 'fraternize', 'generalize', 'globalize', 'harmonize', 'homogenize', 'hospitalize', 'humanize', 'hypothesize', 'immortalize', 'immunize', 'individualize', 'industrialize', 'initialize', 'institutionalize', 'internalize', 'ionize', 'legalize', 'liberalize', 'localize', 'marginalize', 'materialize', 'mechanize', 'memorialize', 'merchandise', 'metabolize', 'militarize', 'mineralize', 'modernize', 'monetize', 'moralize', 'nationalize', 'naturalize', 'ostracize', 'pasteurize', 'personalize', 'philosophize', 'plagiarize', 'pluralize', 'politicize', 'polymerize', 'popularize', 'pressurize', 'privatize', 'professionalize', 'proselytize', 'radicalize', 'randomize', 'rationalize', 'revitalize', 'satirize', 'sensitize', 'serialize', 'solemnize', 'sterilize', 'stigmatize', 'subsidize', 'tantalize', 'tranquilize', 'traumatize', 'trivialize', 'tyrannize', 'urbanize', 'verbalize', 'victimize', 'visualize', 'vocalize'],
    'ence': ['allegiance', 'ambiance', 'appliance', 'benevolence', 'beneficence', 'cadence', 'coincidence', 'compliance', 'consequence', 'constituency', 'convergence', 'credence', 'decadence', 'deference', 'defiance', 'deliverance', 'despondence', 'diffidence', 'dissidence', 'divergence', 'eloquence', 'eminence', 'equivalence', 'exigence', 'expedience', 'extravagance', 'flamboyance', 'grievance', 'impermanence', 'impertinence', 'impotence', 'improvidence', 'incandescence', 'incompetence', 'inconvenience', 'indolence', 'inference', 'insolvence', 'jurisprudence', 'malevolence', 'munificence', 'nonchalance', 'nonviolence', 'omnipotence', 'omnipresence', 'omniscience', 'opulence', 'penitence', 'permanence', 'pertinence', 'pestilence', 'pre-eminence', 'prevalence', 'protuberance', 'reticence', 'reverence', 'self-confidence', 'self-reliance', 'self-indulgence', 'sentience', 'somnolence', 'subservience', 'transcendence', 'transference', 'transparency', 'truculence', 'turbulence', 'vehemence'],

    // === Expanded remaining sounds ===
    'ar': ['guitar', 'superstar', 'rock-star', 'pop-star', 'movie-star', 'gold-star', 'five-star', 'all-star', 'north-star', 'rising-star', 'shooting-star', 'falling-star', 'morning-star', 'evening-star', 'shining-star', 'lonely-star', 'distant-star', 'guiding-star', 'wishing-star', 'twinkling-star', 'behind-bars', 'prison-bars', 'gold-bars', 'handle-bars', 'crow-bar', 'mini-bar', 'wet-bar', 'search-bar', 'scroll-bar', 'task-bar', 'tool-bar', 'side-bar', 'snack-bar'],
    'own': ['meltdown', 'breakdown', 'shutdown', 'lockdown', 'crackdown', 'showdown', 'countdown', 'slowdown', 'sundown', 'knockdown', 'rundown', 'lowdown', 'shakedown', 'takedown', 'throwdown', 'touchdown', 'turndown', 'letdown', 'put-down', 'mark-down', 'cut-down', 'cool-down', 'close-down', 'bring-down', 'beat-down', 'back-down', 'wind-down', 'draw-down', 'drawdown', 'face-down', 'hands-down', 'head-down', 'laid-down', 'lock-down', 'stand-down', 'step-down', 'strip-down', 'top-down', 'trickle-down', 'upside-down', 'water-down', 'worn-down'],
    'all': ['free-fall', 'rain-fall', 'snow-fall', 'water-fall', 'wind-fall', 'down-fall', 'night-fall', 'pit-fall', 'foot-fall', 'land-fall', 'short-fall', 'over-all', 'free-for-all', 'above-all', 'after-all', 'cure-all', 'end-all', 'know-all', 'wall-to-wall', 'back-to-wall', 'off-the-wall', 'up-the-wall', 'brick-wall', 'fire-wall', 'sea-wall', 'stone-wall', 'great-wall', 'phone-call', 'wake-up-call', 'curtain-call', 'close-call', 'conference-call', 'judgment-call', 'roll-call', 'trumpet-call'],
    'ack': ['quarterback', 'running-back', 'come-back', 'set-back', 'draw-back', 'cut-back', 'fall-back', 'hold-back', 'push-back', 'pull-back', 'roll-back', 'step-back', 'snap-back', 'bounce-back', 'fight-back', 'blow-back', 'throw-back', 'pay-back', 'buy-back', 'call-back', 'crack-back', 'give-back', 'kick-back', 'knock-back', 'lay-back', 'play-back', 'right-back', 'take-back', 'talk-back', 'turn-back', 'way-back', 'fast-track', 'race-track', 'side-track', 'sound-track', 'wrong-track', 'back-track', 'inside-track', 'railroad-track', 'running-track', 'one-track', 'two-track', 'multi-track'],
    'ing': ['everything', 'anything', 'something', 'nothing', 'plaything', 'something', 'offspring', 'hamstring', 'heartstring', 'shoestring', 'drawstring', 'bowstring', 'g-string', 'puppet-string', 'apron-string', 'bell-ring', 'boxing-ring', 'circus-ring', 'diamond-ring', 'ear-ring', 'engagement-ring', 'fairy-ring', 'key-ring', 'nose-ring', 'signet-ring', 'smoke-ring', 'wedding-ring', 'bird-wing', 'left-wing', 'right-wing', 'chicken-wing', 'angel-wing'],
};

/**
 * Merge expansion data into existing RHYME_FAMILIES.
 * Adds new families and extends existing ones.
 */
export function mergeRhymeFamilies(existing, newFamilies, expandedFamilies) {
    // Add completely new families
    for (const [family, words] of Object.entries(newFamilies)) {
        if (!existing[family]) {
            existing[family] = words;
        } else {
            // Avoid duplicates
            const existingSet = new Set(existing[family].map(w => w.toLowerCase()));
            for (const word of words) {
                if (!existingSet.has(word.toLowerCase())) {
                    existing[family].push(word);
                }
            }
        }
    }

    // Expand existing families
    for (const [family, words] of Object.entries(expandedFamilies)) {
        if (existing[family]) {
            const existingSet = new Set(existing[family].map(w => w.toLowerCase()));
            for (const word of words) {
                if (!existingSet.has(word.toLowerCase())) {
                    existing[family].push(word);
                }
            }
        } else {
            existing[family] = words;
        }
    }
}
